### ISSUE TITLE
How to add media stream to a producer

### ISSUE THREAD

**Issue by eric72** [versatica/mediasoup#1014]
Hi,

I am using NodeJS with mediasoup v3 for creating a sfu server using mediasoup v3.
But i don't understand if what i do is well and how to add the media stream that i get from the front end to the producer.

I would like to know, how to add a media stream to a pipe producer, so every consumer who join the stream can get the media stream and see a livestream or video conference.

Here is my code for creating the pipeProducer on a nodejs back end:
`
async createPipeProducer(userStreamerId: string, mediaStream: MediaStream) {
        const router = await this.createRouterFromWorker(this.worker);

        const transport = await router.createWebRtcTransport(
            {
                webRtcServer : this.server, // Or ListenIps
                // listenIps    : [ { ip: "192.168.0.111", announcedIp: "88.12.10.41" } ],
                enableUdp    : true,
                enableTcp    : true,
                preferUdp    : true
            }
        );

        transport.on("icestatechange", (iceState) => {
            console.log(`ICE state changed to ${iceState}`);
        });

        // Get the supported RTP capabilities
        const rtpCapabilities = router.rtpCapabilities;

        // Create the producer
        const pipeProducer = await transport.produce({
            kind: 'video',
            rtpParameters: rtpCapabilities["video"].codecs.find(codec => codec.mimeType.toLowerCase() === "video/vp8"),
            appData: { type: 'pipe' }
        });

        // Set the media stream as the source of the producer
        const track = mediaStream.getVideoTracks()[0];
        track.onended = () => {
            pipeProducer.pause();
        };

        // It's in this part that i am stuck
        const mediaSender = await pipeProducer.getStats();
        const rtpSenders = mediaSender[0].rtpSenders;
        mediaSender.send(track);

        return pipeProducer;
    }
`

Am i making everything great ? Expect for add a media stream to the producer, so every consumer can join a specific producer's stream.
I can provide more informations if it can help you to help me.
Thanks for your help.

**Comment by nazar-pc** [comment]
GitHub is for bugs, please ask questions on the forum
