### ISSUE TITLE
Mediasoup does not install on Windows

### ISSUE THREAD

**Issue by elplancton** [versatica/mediasoup#1016]
### My environment

- Operating system: Windows 10 (AMD)
- Node version: 18.14.2
- npm version: 9.5.1
- gcc/clang version: 12.1.0 (MinGW)
- mediasoup version: 3.11.11
- mediasoup-client version:
- Python: 3.7
- PIP: 23.0.1

### Issue description
It just won't install, error after installation error.

The only way I found to install mediasoup was to run the commands below in the terminal with administrator permissions

```
git clone https://github.com/versatica/mediasoup.git .\node_modules\mediasoup
cd .\node_modules\mediasoup
pip install --upgrade --target=C:/<project_path>/node_modules/mediasoup/worker/out/pip  meson==1.0.1 ninja==1.11.1 --no-user
npm i
```

**Comment by nazar-pc** [comment]
I see no errors, in the report. Please ask this question with appropriate logs on the forum, GitHub is only for more or less confirmed bugs, which this is not.

**Comment by SannanOfficial** [comment]
Did you ask on the forum? any updates on this? I have the same issue and would love a link to the forum.
