### ISSUE TITLE
IceServer.cpp: uncomment temporal check

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#103]
Uncomment [this check](https://github.com/versatica/mediasoup/blob/v3/worker/src/RTC/IceServer.cpp#L141) once this [patch](https://codereview.webrtc.org/2812173003/diff/1/webrtc/p2p/base/transportcontroller.cc) lands in Chrome stable.

* [Related issue](https://bugs.chromium.org/p/chromium/issues/detail?id=710760)

**Comment by ibc** [comment]
Note: landed in Chrome (still no in stable):

https://bugs.chromium.org/p/chromium/issues/detail?id=710760#c12

**Comment by jmillan** [comment]
Can this issue be closed?

**Comment by ibc** [comment]
No, not yet. Wanna make sure that there aren't old libwebrtc implementations out there behaving that wrong way.

**Comment by jmillan** [comment]
👍

**Comment by ibc** [comment]
Ok, let's close this "issue". A `TODO` has been added in the related code.
