### ISSUE TITLE
debain install mediasoup error

### ISSUE THREAD

**Issue by zw256** [versatica/mediasoup#1030]
mediasoup-demo/server$ npm install
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/zw/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! > mediasoup@3.11.15 postinstall
npm ERR! > node npm-scripts.js postinstall
npm ERR! 
npm ERR! npm-scripts.js [INFO] running task "postinstall"
npm ERR! npm-scripts.js [INFO] buildWorker()
npm ERR! npm-scripts.js [INFO] executeCmd(): make -C worker
npm ERR! make: 进入目录“/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker”
npm ERR! # Updated pip and setuptools are needed for meson.
npm ERR! # `--system` is not present everywhere and is only needed as workaround for
npm ERR! # Debian-specific issue (copied from https://github.com/gluster/gstatus/pull/33),
npm ERR! # fallback to command without `--system` if the first one fails.
npm ERR! /usr/bin/python3 -m pip install --system --target=/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip pip setuptools || \
npm ERR! 	/usr/bin/python3 -m pip install --target=/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip pip setuptools || \
npm ERR! 	echo "Installation failed, likely because PIP is unavailable, if you are on Debian/Ubuntu or derivative please install the python3-pip package"
npm ERR! Collecting pip
npm ERR!   Using cached pip-23.0.1-py3-none-any.whl (2.1 MB)
npm ERR! Collecting setuptools
npm ERR!   Using cached setuptools-67.6.0-py3-none-any.whl (1.1 MB)
npm ERR! Installing collected packages: setuptools, pip
npm ERR! Successfully installed pip-23.0.1 setuptools-67.6.0
npm ERR! # Install `meson` and `ninja` using `pip` into custom location, so we don't
npm ERR! # depend on system-wide installation.
npm ERR! /usr/bin/python3 -m pip install --upgrade --target=/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip  meson==0.61.5 ninja==1.10.2.4
npm ERR! Collecting meson==0.61.5
npm ERR!   Downloading meson-0.61.5-py3-none-any.whl (862 kB)
npm ERR!      ━━━━━━━━━━━━━╸                         307.2/862.5 kB 18.9 kB/s eta 0:00:30
npm ERR! make: 离开目录“/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker”
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
npm ERR!   WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/18/db/3feb3cfa102553b9329d0c887b3c10480381de69abf6e8629f6b32f450df/meson-0.61.5-py3-none-any.whl
npm ERR! ERROR: Exception:
npm ERR! Traceback (most recent call last):
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
npm ERR!     yield
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_vendor/urllib3/response.py", line 561, in read
npm ERR!     data = self._fp_read(amt) if not fp_closed else b""
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_vendor/urllib3/response.py", line 527, in _fp_read
npm ERR!     return self._fp.read(amt) if amt is not None else self._fp.read()
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_vendor/cachecontrol/filewrapper.py", line 90, in read
npm ERR!     data = self.__fp.read(amt)
npm ERR!   File "/usr/lib/python3.9/http/client.py", line 458, in read
npm ERR!     n = self.readinto(b)
npm ERR!   File "/usr/lib/python3.9/http/client.py", line 502, in readinto
npm ERR!     n = self.fp.readinto(b)
npm ERR!   File "/usr/lib/python3.9/socket.py", line 704, in readinto
npm ERR!     return self._sock.recv_into(b)
npm ERR!   File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
npm ERR!     return self.read(nbytes, buffer)
npm ERR!   File "/usr/lib/python3.9/ssl.py", line 1099, in read
npm ERR!     return self._sslobj.read(len, buffer)
npm ERR! socket.timeout: The read operation timed out
npm ERR! 
npm ERR! During handling of the above exception, another exception occurred:
npm ERR! 
npm ERR! Traceback (most recent call last):
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
npm ERR!     status = run_func(*args)
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_internal/cli/req_command.py", line 247, in wrapper
npm ERR!     return func(self, options, args)
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_internal/commands/install.py", line 419, in run
npm ERR!     requirement_set = resolver.resolve(
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
npm ERR!     result = self._result = resolver.resolve(
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
npm ERR!     state = resolution.resolve(requirements, max_rounds=max_rounds)
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
npm ERR!     self._add_to_criteria(self.state.criteria, r, parent=None)
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
npm ERR!     if not criterion.candidates:
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
npm ERR!     return bool(self._sequence)
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
npm ERR!     return any(self)
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
npm ERR!     return (c for c in iterator if id(c) not in self._incompatible_ids)
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
npm ERR!     candidate = func()
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
npm ERR!     self._link_candidate_cache[link] = LinkCandidate(
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
npm ERR!     super().__init__(
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
npm ERR!     self.dist = self._prepare()
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
npm ERR!     dist = self._prepare_distribution()
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
npm ERR!     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
npm ERR!     return self._prepare_linked_requirement(req, parallel_builds)
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_internal/operations/prepare.py", line 536, in _prepare_linked_requirement
npm ERR!     local_file = unpack_url(
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_internal/operations/prepare.py", line 166, in unpack_url
npm ERR!     file = get_http_url(
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_internal/operations/prepare.py", line 107, in get_http_url
npm ERR!     from_path, content_type = download(link, temp_dir.path)
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_internal/network/download.py", line 147, in __call__
npm ERR!     for chunk in chunks:
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
npm ERR!     for chunk in iterable:
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_internal/network/utils.py", line 63, in response_chunks
npm ERR!     for chunk in response.raw.stream(
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_vendor/urllib3/response.py", line 622, in stream
npm ERR!     data = self.read(amt=amt, decode_content=decode_content)
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_vendor/urllib3/response.py", line 587, in read
npm ERR!     raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
npm ERR!   File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
npm ERR!     self.gen.throw(type, value, traceback)
npm ERR!   File "/home/zw/.npm/_cacache/tmp/git-cloneWlTIK4/worker/out/pip/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
npm ERR!     raise ReadTimeoutError(self._pool, None, "Read timed out.")
npm ERR! pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
npm ERR! make: *** [Makefile:101：meson-ninja] 错误 2
npm ERR! npm-scripts.js [ERROR] executeCmd() failed, exiting: Error: Command failed: make -C worker
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /home/zw/.npm/_cacache/tmp/git-cloneWlTIK4
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c -- node npm-scripts.js postinstall
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /home/zw/.npm/_logs/2023-03-23T07_20_07_299Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zw/.npm/_logs/2023-03-23T07_18_49_357Z-debug-0.log

**Comment by ibc** [comment]
Use the forum.

**Comment by RamanSB** [comment]
@zw256 not sure why you have a space in the "node " directory in your path, try remove that space and retrying - not sure if it will resolve the issue, but removing whitespaces certainly helped resolve my issue (See [whitespace issue](https://github.com/versatica/mediasoup/issues/753))

npm ERR! command **/usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js** install --force --cache=/home/zw/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
