### ISSUE TITLE
I am trying to implement a SFU on nodejs, But I get some problems

### ISSUE THREAD

**Issue by lihongming** [versatica/mediasoup#104]
When I call createAnswer() on browser side, the first time is okay, but when a new person join the room. the second person call createAnswer gets the following error.

"Create answer. OperationError: Failed to initialize the answer."

Another things how mediasoup.webrtc.RTCPeerConnection manage the ICE candidates.

**Comment by ibc** [comment]
Please, use the mailing list for questions. I want to keep the issue tracker as clean as possible:

https://mediasoup.org/support/

**Comment by ibc** [comment]
BTW ensure you are properly setting the [usePlanB](https://mediasoup.org/api/#webrtc-RTCPeerConnection-RTCPeerConnectionOptions) flag.
