### ISSUE TITLE
mediasoup-worker crash: free(): invalid pointer

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#1042]
## Bug Report

It's consistently happening in the demo server which is running very latest 3.11.19 version. No idea how to reproduce.

```
2023-03-30T10:06:18.320Z mediasoup:ERROR:Worker (stderr) free(): invalid pointer
2023-03-30T10:06:18.323Z mediasoup:ERROR:Worker worker process died unexpectedly [pid:3465, code:null, signal:SIGABRT]
```

### Your environment

- Operating system: Linux Debian
- gcc/clang version: 6.3.0
- mediasoup version: 3.11.19

**Comment by nazar-pc** [comment]
Attach to the process with gdb, it'll allow you to do backtrace when crash happens

**Comment by ibc** [comment]
> Attach to the process with gdb, it'll allow you to do backtrace when crash happens

Waiting for the crash to happen again (after having enabled coredumps in the demo server) :)

**Comment by vpalmisano** [comment]
I suspect that was caused by this test https://github.com/versatica/mediasoup/issues/1037#issuecomment-1490037979
Probably it happened again right now.

**Comment by ibc** [comment]
```
(gdb)
(gdb) bt full
#0  0x00007f6d294eace1 in raise () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x00007f6d294d4537 in abort () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#2  0x00007f6d2952d768 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#3  0x00007f6d29534a5a in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#4  0x00007f6d29535c14 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#5  0x0000559b97f74942 in RTC::SeqManager<unsigned short, (unsigned char)0>::ClearDropped() ()
No symbol table info available.
#6  0x0000559b97f74a40 in RTC::SeqManager<unsigned short, (unsigned char)0>::Input(unsigned short, unsigned short&) ()
No symbol table info available.
#7  0x0000559b97f8752f in RTC::SvcConsumer::SendRtpPacket(RTC::RtpPacket*, std::shared_ptr<RTC::RtpPacket>&) ()
No symbol table info available.
#8  0x0000559b97f48df4 in RTC::Router::OnTransportProducerRtpPacketReceived(RTC::Transport*, RTC::Producer*, RTC::RtpPacket*) ()
No symbol table info available.
#9  0x0000559b97f371d3 in RTC::Producer::ReceiveRtpPacket(RTC::RtpPacket*) ()
No symbol table info available.
#10 0x0000559b97f89d3f in RTC::Transport::ReceiveRtpPacket(RTC::RtpPacket*) ()
No symbol table info available.
#11 0x0000559b97fb8d2b in RTC::WebRtcTransport::OnRtpDataReceived(RTC::TransportTuple*, unsigned char const*, unsigned long) ()
No symbol table info available.
#12 0x0000559b97faafa8 in RTC::WebRtcServer::OnUdpSocketPacketReceived(RTC::UdpSocket*, unsigned char const*, unsigned long, sockaddr const*) ()
No symbol table info available.
#13 0x0000559b982bb0b1 in uv.udp_recvmmsg ()
No symbol table info available.
#14 0x0000559b982bbd3b in uv.udp_io ()
No symbol table info available.
#15 0x0000559b982bf0bd in uv.io_poll ()
No symbol table info available.
#16 0x0000559b982b291f in uv_run ()
No symbol table info available.
#17 0x0000559b97e92a19 in DepLibUV::RunLoop() ()
No symbol table info available.
#18 0x0000559b97e9ec3f in Worker::Worker(Channel::ChannelSocket*, PayloadChannel::PayloadChannelSocket*) ()
No symbol table info available.
#19 0x0000559b97e9147d in mediasoup_worker_run ()
No symbol table info available.
#20 0x0000559b97e90054 in main ()
No symbol table info available.
```

@jmillan:

`RTC::SeqManager<unsigned short, (unsigned char)0>::ClearDropped() ()` is producing the crash.

**Comment by ibc** [comment]
```c++
	/*
	 * Delete droped inputs greater than maxInput that belong to a previous
	 * cycle.
	 */
	template<typename T, uint8_t N>
	void SeqManager<T, N>::ClearDropped()
	{
		// Cleanup dropped values.
		if (this->dropped.empty())
		{
			return;
		}

		const size_t threshold           = (this->maxInput + MaxValue / 3) & MaxValue;
		const size_t previousDroppedSize = this->dropped.size();
		const auto it1                   = this->dropped.upper_bound(this->maxInput);
		const auto it2                   = this->dropped.lower_bound(threshold);

		// There is no dropped value greater than this->maxInput.
		if (it1 == this->dropped.end())
		{
			return;
		}

		// There is a single value in the range.
		if (it1 == it2)
		{
			this->dropped.erase(it1);
		}
		// There are many values in the range.
		else
		{
			this->dropped.erase(it1, it2);
		}

		// Adapt base.
		this->base = (this->base - (previousDroppedSize - this->dropped.size())) & MaxValue;
	}
```

What about if `it1` and/or `it2` are `std::end` which can be returned by `std::ste::upper_bound()`: https://cplusplus.com/reference/set/set/upper_bound/?

Then the code is calling `std::set::erase(it)` being `it == std::end`, which probably is not good.

**Comment by snnz** [comment]
Can't (this->maxInput + MaxValue / 3) overflow? In this case, (it1, it2) would be an invalid range.

**Comment by jmillan** [comment]
> What about if it1 and/or it2 are std::end which can be returned by std::ste::upper_bound():

If `it1` is `end()`  we leave the method.
`it2` can be `end()` meaning items from `it1` until the end of the container will be erased.

https://en.cppreference.com/w/cpp/container/set/erase

**Comment by jmillan** [comment]
> Can't (this->maxInput + MaxValue / 3) overflow? In this case, (it1, it2) would be an invalid range.

Can you be more specific @snnz?

**Comment by jmillan** [comment]
>>Can't (this->maxInput + MaxValue / 3) overflow? In this case, (it1, it2) would be an invalid range.

> Can you be more specific @snnz?

got it, and correct. This crash happens because `it2` is greater than `it1`.

**Comment by snnz** [comment]
Suppose that` (this->maxInput + MaxValue / 3)` is more than MaxValue. Then `treshhold` will be less than `this->maxInput` and `it2` may turn out to be in front of `it1`.

**Comment by jmillan** [comment]
Working on it.

**Comment by jmillan** [comment]
> Suppose that (this->maxInput + MaxValue / 3) is more than MaxValue

`threshold` is capped to `MaxValue`. I'm trying to come with a specific example in order to write the corresponding failing test. Let me know if you come up with a specific example.

**Comment by snnz** [comment]
No, I haven't an example. Never even used SVC; this is purely theoretical for me.

**Comment by ibc** [comment]
> got it, and correct. This crash happens because `it2` is greater than `it1`.

What? It's obviously expected that it2 is > than it1. Otherwise `this->dropped.erase(it1, it2)` wouldn't make sense.

**Comment by jmillan** [comment]
> What? It's obviously expected that it2 is > than it1. Otherwise this->dropped.erase(it1, it2) wouldn't make sense.

EDIT:It is expected, but the error comes out of `t2` being < `t1`.

**Comment by ibc** [comment]
@jmillan should fuzzer trigger this crash? I'm about to run it now in v3. Just wondering if the fuzzer code should run the controversial code.

**Comment by jmillan** [comment]
No, because it needs explicit dropped sequence numbers. I'm trying to write the proper unit test for this.

**Comment by ibc** [comment]
What about dropping some seq numbers also in fuzzer?

**Comment by jmillan** [comment]
> What about dropping some seq numbers also in fuzzer?

Yes, ok.

**Comment by jmillan** [comment]
Crash happened via fuzzer 🎉
