### ISSUE TITLE
Make `appData` no longer read-only

### ISSUE THREAD

**Issue by alexciarlillo** [versatica/mediasoup#1043]
## Feature Request

https://mediasoup.discourse.group/t/just-curious-why-appdata-is-read-only/5116 

Would be nice to be able to do:

```
consumer.appData = {...consumer.appData, ...someNewAppData}
```

**Comment by nazar-pc** [comment]
Just write this instead:
```javascript
Object.assign(consumer.appData, someNewAppData)
```

**Comment by alexciarlillo** [comment]
> Just write this instead:
> 
> ```js
> Object.assign(consumer.appData, someNewAppData)
> ```

Yeah I am fine with that and am using it as a workaround. My original question in the discourse was just to find out if this was a bad idea or if there was some internal reason it was read-only. ibc said there was not and that I should open an issue 🤷
