### ISSUE TITLE
Observer peer

### ISSUE THREAD

**Issue by skystebnicki** [versatica/mediasoup#105]
Hi, great work on this library. We are considering it now for a pretty hefty project - down the road.

One problem we have is that the majority of our attendees are observers only, with one person (sometimes two) offering media.

Browser-to-browser this is possible because we can simply call peer.createOffer without having to first set the remote SDP of the peer.

However, it looks like there might be an assumption that every peer connecting to the server, it will always do so with an offer. The reason I think that is because peer.createOffer requires that you first call peer.setRemoteDecription with the sdp of the remote peer.

I'll look into the code myself to see if there is a way to fix that, but figured I would let you know.

**Comment by jmillan** [comment]
Hi @skystebnicki,

Please use the mailing list for usage questions.

**Comment by jmillan** [comment]
BTW:

>  it looks like there might be an assumption that every peer connecting to the server, it will always do so with an offer

Consider this offer a 'capabilities' object sent by the remote peer whenever it wants to join a room. It literally indicates mediasoup about the capabilities of this remote peer. You can forget about that SDP afterwards: it is not part of the offer answer.

Once with such capabilities, mediasoup will generate the appropriate SDP offer `peerconnection::createOffer` and send it to the remote peer.

> The reason I think that is because peer.createOffer requires that you first call peer.setRemoteDecription with the sdp of the remote peer.

Not correct.

Please check https://mediasoup.org/api/#webrtc and overall API documentation, and use the mailing list for further info.

There are already similar questions responded in the mailing list.

**Comment by skystebnicki** [comment]
Thanks I'll check the mailing list.
