### ISSUE TITLE
mediasoup client SDK

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#106]
Rather than dealing with SDPs, provide a SDK for connecting clients to a mediasoup room. No signaling protocol included (that's up to the application on top of mediasoup).

The client side Peer SDK will provide full features (including advanced ones such as simulcast/SVC or desktop sharing). The SDK will internally deal with SDPs in Chrome/Firefox and with ORTC API in Edge. The SDK will properly notify the app about changes in the room (such as new participants, audio/video streams, etc).

**Comment by touch0day** [comment]
record is import too

**Comment by ibc** [comment]
@touch0day this issue is about a specific feature, the Peer SDK, not a generic feature request list.
Deleting both comments to leave it clear.

**Comment by ibc** [comment]
This is being done in a separate [mediasoup-client](https://github.com/versatica/mediasoup-client) project.

**Comment by ibc** [comment]
Done.
