### ISSUE TITLE
Holding the same reference for appData in PipedObjects

### ISSUE THREAD

**Issue by balazskreith** [versatica/mediasoup#1060]
I'm not sure if it's a bug or a question of concept for appData.

Here is the issue:

```javascript
const myAppData = {
  text: 'Oh Happy Day!'
}
const sourceRouter = // a simple router on worker 1
const webrtcTransport = sourceRouter.createWebRtcTransport(...);
const mediaProducer = webrtcTransport.produce({
  ...producerOptions,
  appData: myAppData
});

const targetRouter = // another router on worker 2
const { pipeProducer } = await sourceRouter.pipeToRouter({
  producerId: mediaProducer.id,
  router: targetRouter,
  // ...
});

pipeProducer.appData.text = 'Oh Cr*ppy Day!'

console.log(mediaProducer.appData.text);  // It prints "Oh Cr*ppy Day!"

```

My guess is that in https://github.com/versatica/mediasoup/blob/56eda745e2cad34fab00c998b0e47a570d838a2a/node/src/Router.ts#L918, a reference is assigned and not a copy of the original appData, so whatever you change in pipeProducer.appData (or mediaProducer.appData) mutates the same object.

The question is: Is it intentional, so the piped objects' application data must be the same as the original, and I just made an unnecessary issue? Or should every created object have its own appData?

**Comment by ibc** [comment]
`appData` could contain complex non-serializable/clonable objects such as class instances, etc. We cannot clone it.

Yes, `appData` of the original Producer is copied (by reference) into the pipe Producer. You can later do `pipeProducer.appData = NEW_OBJECT` (available in mediasoup >= 3.11.20, see recent PR https://github.com/versatica/mediasoup/pull/1046).
