### ISSUE TITLE
High mediasoup-worker CPU usage with 3.11.22 version

### ISSUE THREAD

**Issue by vpalmisano** [versatica/mediasoup#1067]
## Bug Report
After upgrading to 3.11.22 version, we are experiencing a very high CPU usage when the number of video consumers increases, probably caused by the new rtx buffer implementation.
Here you have a graph of the mediasoup worker CPU usage when running a test with 1 SD producer and 40 consumers:
- at the left: using 3.11.22 version
- at the right: using a custom version (https://github.com/vpalmisano/mediasoup/commits/3-11-13-fork) obtained picking the commits starting from 3.11.13 to 3.11.22 excluding the rtx buffer refactor commits.

![image](https://user-images.githubusercontent.com/283319/232560328-e7cb45b3-7e5f-41cd-9bb3-78af56aaa1b0.png)

**Comment by ibc** [comment]
> probably caused by the new rtx buffer implementation

Why this assumption? It's not a new implementation but an optimization of what was already in there.

**Comment by vpalmisano** [comment]
It seems the only change that could affect the CPU when consumers increase. With HD resolution and 1000 consumers the CPU increase is approximately 4 times. I will try to extract some traces with valgrind.

**Comment by jmillan** [comment]
@vpalmisano, maybe a `git bisect` would help narrowing the exact commit that introduced this.

**Comment by jmillan** [comment]
@vpalmisano, please try with the latest version since there was a performance enhancement here 937bb6c832582d05ebbfa35cc38864894d683391

**Comment by vpalmisano** [comment]
Sorry, there was an error in the ticket description. I'm testing the 3.11.22 version vs 3.11.13.
I'm running the same test with all the tags between .13 to .22

**Comment by vpalmisano** [comment]
The issue happens when switching from 3.11.15 to 3.11.16

**Comment by ibc** [comment]
> The issue happens when switching from 3.11.15 to 3.11.16

![image](https://user-images.githubusercontent.com/16191/232832011-40210c85-6ce6-478d-9b9f-984a38f90eed.jpeg)

@jmillan 🥺

**Comment by jmillan** [comment]
I'll try this tomorrow.

> It seems the only change that could affect the CPU when consumers increase. With HD resolution and 1000 consumers the CPU increase is approximately 4 times. I will try to extract some traces with valgrind.

I guess I'll be able to see the CPU usage difference with any number of consumers, ie: 4, right?. Comparing both versions. Also, are you using Simulcats/SVC? any other details?

**Comment by vpalmisano** [comment]
I'm using VP9/SVC, 1 publisher and 50 consumers.

**Comment by ibc** [comment]
> I'm using VP9/SVC, 1 publisher and 50 consumers.

Just video? Or also OPUS with NACK?

**Comment by vpalmisano** [comment]
Yep, audio with NACK and video.

**Comment by vpalmisano** [comment]
Anyway, testing with audio only streams (with NACK), the CPU usage is quite the same between the old and the latest versions.

**Comment by vpalmisano** [comment]
Video only test, VP9 SVC 1280x720, 1 producer and 50 consumers (left: 3.11.15, right: 3.11.23):
![image](https://user-images.githubusercontent.com/283319/232856428-de26e6ed-d248-43b8-b847-e8c57b36126a.png)

**Comment by vpalmisano** [comment]
Valgrind trace with 3.11.23:
![image](https://user-images.githubusercontent.com/283319/232857947-9c322ff3-7c9b-4221-b7c3-3cfa6d7426b9.png)

[callgrind.out.3504049.gz](https://github.com/versatica/mediasoup/files/11264664/callgrind.out.3504049.gz)

**Comment by ibc** [comment]
@jmillan, seeing Valgrind output, do you think that calling `RemoveOldestByTimestamp()` in the retransmission buffer every time a packet arrives could be the culprit? We did the very same before and it's supposed to be fast since it stops as soon as it finds an entry in the buffer that is recent enough (unless there is a bug in maths there).

**Comment by ibc** [comment]
> do you think that calling `RemoveOldestByTimestamp()` in the retransmission buffer every time a packet arrives could be the culprit? We did the very same before and it's supposed to be fast since it stops as soon as it finds an entry in the buffer that is recent enough (unless there is a bug in maths there).

I've just added `Dump()` at the end of `RemoveOldestByTimestamp()` and it properly clears expected old packets:


https://user-images.githubusercontent.com/16191/232921549-7112f410-f718-4148-aa3f-f20b93ed8ba3.mp4

**Comment by jmillan** [comment]
I'll instrument this during the day. I can't say anything reliable until I do it.

**Comment by vpalmisano** [comment]
It seems to me that the SeqManager::Input method uses a lot of CPU cycles:

![image](https://user-images.githubusercontent.com/283319/233021427-1ac6b603-1b19-4498-96af-e5ecf48e2efc.png)

and it is at the 1st place for self-cpu usage:

![image](https://user-images.githubusercontent.com/283319/233021976-0bca8938-7b93-4eda-8fd0-fe622d78be33.png)

**Comment by jmillan** [comment]
For some reason building with `MEDIASOUP_BUILDTYPE=Debug` does crash on `abseil` dependency when performing this test in mediasoup-demo.

I'm running the demo with `Release` mode and I can see this as well. `RTC::SeqManager::Input()` is taking too much CPU time. My guess is that we are now storing for more time the `dropped` numbers, and we need to execute `lower_bound` and`std::distance` for every incoming packet. The more elements there are in the the `dropped` container the more expensive those methods are...

I'm thinking how could we store less dropped packets.

**Comment by jmillan** [comment]
Sharing here the diff of of SeqManager comparing the previous and current versions: https://github.com/versatica/mediasoup/compare/7ebffcc01bc8c5c0c08220ebf5a0229f66a75b22..d146ee5b45bbf5298d746fccc23091b79d5a53d9#diff-50454e8bc8389ba485ecc1f3cf8b1ba24fda34d8facf202fe9d485bf7d465434

**Comment by jmillan** [comment]
PR is on its way.
