### ISSUE TITLE
mediasoup-worker crashed

### ISSUE THREAD

**Issue by magiczhangx** [versatica/mediasoup#1071]
## Bug Report

Mediasoup-worker crashed.  Attached core file.
### Core file:
[crash.zip](https://github.com/versatica/mediasoup/files/11303177/crash.zip)
[stacktrace.txt](https://github.com/versatica/mediasoup/files/11303195/stacktrace.txt)

### environment

- Operating system: ubuntu:20.04 (Linux 3.10.0-693.2.2.el7.x86_64 1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux)
- Node version: v19.8.1
- npm version: 9.5.1
- gcc/clang version: gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
- mediasoup version: 3.11.24 **with MEDIASOUP_BUILDTYPE=Debug build**
- mediasoup-client version:  mediasoup-client(v3.6.69) , libmediasoupclient(v3.3.0)

#### Scenario:

- peer1 produce camera
- peer2 consume it

#### Possible Position:
```C++
//last_send_time_ms_ is possible null ?
absl::optional<int64_t> AlrDetector::GetApplicationLimitedRegionStartTime(
    int64_t at_time_ms) {
  if (!alr_started_time_ms_ && *last_send_time_ms_) {
    int64_t delta_time_ms = at_time_ms - *last_send_time_ms_;
    // If ALR is stopped and we haven't sent any packets for a while, force start.
    if (delta_time_ms > alr_timeout_) {
      MS_WARN_TAG(bwe, "large delta_time_ms: %ld, forcing alr state change",
        delta_time_ms);
      alr_started_time_ms_.emplace(at_time_ms);
    }
  }
  return alr_started_time_ms_;
}
```

**Comment by magiczhangx** [comment]
no crash on 3.11.21

**Comment by qqpmsc2006** [comment]
The last_send_time_ms_ is empty. The optional object is asserted not empty in debug mode.

**Comment by jmillan** [comment]
> The last_send_time_ms_ is empty. The optional object is asserted not empty in debug mode.

Feel free to submit a PR if you can.

**Comment by qqpmsc2006** [comment]
#1072

**Comment by qqpmsc2006** [comment]
#1072 
As far as I understand, I replaced  *last_send_time_ms_ with last_send_time_ms_.has_value()

**Comment by ibc** [comment]
Fixed in https://github.com/versatica/mediasoup/pull/1072
