### ISSUE TITLE
Inappropriate rtp header padding, which can lead to wasted bandwidth

### ISSUE THREAD

**Issue by buptlsp** [versatica/mediasoup#1073]
## Bug Report
I use wireshark to capture the rtp audio packets and found that the rtp header had strange padding, as shown below:
![image](https://user-images.githubusercontent.com/3291512/235050329-afbedc3d-e1bb-4337-ba54-a6e674860b85.png)
It makes 8 bytes of padding per packet, and according to RFC5285, the one-byte extension header should look like this:
![image](https://user-images.githubusercontent.com/3291512/235050532-1f954ff1-f9da-4b5e-8f2d-0dc1b5ae1f57.png)

mediasoup uses two extension headers：mid and aiuodLevel. in the consumer, both of which are normally 1 byte in length, so only 4 bytes are needed. I changed the code of mediasoup and got the following result, and then all of them run well:
![image](https://user-images.githubusercontent.com/3291512/235051175-29dfa91f-92d7-4080-bf57-9fb35d0071f2.png)

According to wireshark's packet capture, the length of an audio packet is around 150 bytes, each packet has 8 bytes of waste, which basically results in having 5.3% of bandwidth wasted.

the code is because this line of  worker/src/RTC/Producer.cpp :
![image](https://user-images.githubusercontent.com/3291512/235051324-5e3be3bb-d29f-4422-a79e-a41057f70cd4.png)

The code uses MidMaxLength, which has a value of 8. But the actual mid is less than 8. When UpdateMid, it can be memcpy directly. this method makes updateMid easy, but the extra padding will cause the bandwidth to increase. Bandwidth is money. This place may need resize extensions, but it may bring more memory and cpu consumption. Maybe I need to judge the length change to handle it, but this would be a bit too difficult for me. I hope you guys can help me with this, thanks a lot.

**Comment by nazar-pc** [comment]
Don't we intentionally change 1 byte RTP header extensions to 4 bytes intentionally, @ibc?

**Comment by ibc** [comment]
> Don't we intentionally change 1 byte RTP header extensions to 4 bytes intentionally, @ibc?

Can you please specify the question a bit more? do you mean if we change 1 byte to 4 bytes extension type when adding an extra extension in case there is no more slots when using 1 byte style?

**Comment by nazar-pc** [comment]
I thought we converted either into 4 byte extension internally to simplify handling, didn't we?

**Comment by ibc** [comment]
Nope. We keep packet's original extensions type. In fact AFAIR we always create extensions from scratch when routing packets and always use 1 byte style. But we can parse both styles in packets being received by mediasoup.

**Comment by buptlsp** [comment]
@nazar-pc  Yes, I have submit the pr, may you can reivew it first. It's not ready now, I　will resubmit when it is ok
