### ISSUE TITLE
rust/example/echo not work

### ISSUE THREAD

**Issue by ali322** [versatica/mediasoup#1074]
### Your environment

- Operating system: mac os big sur 11.7.4
- rustup toolchain: stable-x86_64-apple-darwin (default)
- rustc version: rustc 1.68.2 (9eb3afe9e 2023-03-27)
- mediasoup version: latest

### Issue description
here is reproduction steps:
1. git clone the whole repository
2. cd `rust/examples` and run `cargo run --example echo`
3. cd `rust/examples-frontend` and run `npm start`
4. open chrome and navigate to localhost:3000, click on the play button of receive preview

got errors in my terminal

```bash
echo: ../../../../../../worker/subprojects/abseil-cpp-20211102.0/absl/types/optional.h:431: absl::lts_20211102::optional<T>::operator*() & [with T = long int]::<lambda()>: Assertion `false && "this->engaged_"' failed.
```

**Comment by nazar-pc** [comment]
Can you do bisecting and figure out when the issue was introduced? It certainly worked before, on Linux at very least.

**Comment by ali322** [comment]
i test again in CentOS Linux release 8.5.2111, got same error when i click play button of receive preview, any suggestions?

**Comment by ali322** [comment]
here is my environment

```bash
stable-x86_64-unknown-linux-gnu (default)
rustc 1.67.0 (fc594f156 2023-01-24)
```

**Comment by nazar-pc** [comment]
Suggestion already provided in previous comment. Find when it regressed or else I'll get to it myself when I have time.

**Comment by bekriebel** [comment]
I attempted a bisect, but am unable to find a working version. The `rust-0.10.0` tag has the same issue as the current version (received A/V doesn't load), `rust-0.9.3` and below either won't compile on the backend side, or don't seem to have a functional frontend.

I'm new to rust and mediasoup, so am not sure what the best steps are for debugging. The build failures on the older tagged versions seem to be coming from the C components (the errors are coming from ninja while compiling c code).

**Comment by bekriebel** [comment]
In my case, this turned out to be a networking issue. I had tested on a remote machine with forward ports as well as a local WSL instance. In both cases, it seems like the ICE candidates being generated by the server were not allowing the connection to the SFU.

For quick testing, I fixed it with this change:

```rust
diff --git a/rust/examples/echo.rs b/rust/examples/echo.rs
index 0a0c688b9..ac76914f7 100644
--- a/rust/examples/echo.rs
+++ b/rust/examples/echo.rs
@@ -181,10 +181,16 @@ impl EchoConnection {
         // We know that for echo example we'll need 2 transports, so we can create both right away.
         // This may not be the case for real-world applications or you may create this at a
         // different time and/or in different order.
-        let transport_options = WebRtcTransportOptions::new(TransportListenIps::new(ListenIp {
-            ip: IpAddr::V4(Ipv4Addr::LOCALHOST),
-            announced_ip: None,
-        }));
+        let transport_options = WebRtcTransportOptions::new(
+            TransportListenIps::new(ListenIp {
+                ip: IpAddr::V4(Ipv4Addr::LOCALHOST),
+                announced_ip: None,
+            })
+            .insert(ListenIp {
+                ip: IpAddr::V4(Ipv4Addr::new(10, 0, 0, 1)),
+                announced_ip: None,
+            }),
+        );
         let producer_transport = router
             .create_webrtc_transport(transport_options.clone())
             .await
```

The `ip: IpAddr::V4(Ipv4Addr::new(10, 0, 0, 1)),` needs to be set to a routable IP address from your test system.

I'm guessing this issue can actually be closed since the examples do seem to work as described if you are truly testing from localhost.

**Comment by nazar-pc** [comment]
Thanks for testing, closing then.

Yes, these are just examples for local testing, not proper production applications. They are designed to be almost as simple as possible to showcase the idea and allow you to get started.
