### ISSUE TITLE
Missing comma in mediasoup webpage, on location transport.produce options > encoding

### ISSUE THREAD

**Issue by Ksj14-kumar** [versatica/mediasoup#1077]
Missing comma for separate encoding options inside> transport.produce<ProducerAppData>(options)
here is the link where a comma is missing <a href="https://mediasoup.org/documentation/v3/mediasoup/api/#Transport">https://mediasoup.org/documentation/v3/mediasoup/api/#Transport</a>

**Comment by nazar-pc** [comment]
There is a website repo, just send PR there: https://github.com/versatica/mediasoup-website

**Comment by Ksj14-kumar** [comment]
Okay, Thanks for this

**Comment by ibc** [comment]
Please @Ksj14-kumar open an issue in the mediasoup-website GitHub project indicating better where the issue is because I cannot see it. Thanks.
