### ISSUE TITLE
When can GPU encoding and decoding be supported？

### ISSUE THREAD

**Issue by zhuya1996** [versatica/mediasoup#1078]
When can GPU encoding and decoding be supported ，thanks

**Comment by nazar-pc** [comment]
Never, mediasoup doesn't encode or decode audio or video

**Comment by zhuya1996** [comment]
> 从不，mediasoup 不对音频或视频进行编码或解码

It only has forwarding function??  thankyou

**Comment by ibc** [comment]
Please use the mediasoup forum for questions and not GitHub.
