### ISSUE TITLE
add getRoom on Server [feature]

### ISSUE THREAD

**Issue by lihongming** [versatica/mediasoup#108]
now we can create a room on server through server.createRoom(options).

I also found for each room, it has a roomID, How about to implement the API getRoom(roomID).

**Comment by lihongming** [comment]
If you think this feature is useful. I can help to implement it.

**Comment by ibc** [comment]
Honestly I prefer to leave the API small and clean, without providing features that can be easily implemented by the Node.js application. For example, within your Node.js application:

```js
// Map of mediasoup Room instances indexed by room.id.
let rooms = new Map();

// Let's server be a mediasoup Server instance.

server.on('newroom', (room) => {
  rooms.set(room.id, room);

  room.on('close', () => {
    rooms.delete(room.id);
  });
});
```

So when you need to retrieve a mediasoup `Room` by `id`,  just do:

```js
rooms.get(id);
```

That's all.
