### ISSUE TITLE
create worker failed  Error: [pid:40, code:2, signal:null]

### ISSUE THREAD

**Issue by duyjack** [versatica/mediasoup#1085]
I run service with mediasoup version 3.11.24.
When server start and create worker, I receive message Error: [pid:40, code:2, signal:null]

I run it on docker. 

Node version: 16
Mediasoup version: 3.11.24

I have read information and follow these step in this blog ( https://mediasoup.org/support/#crashes-in-mediasoup-get-a-core-dump) but it's not works

I don't know what happen.
Can anyone help me solve this problem?

**Comment by ibc** [comment]
Use the mediasoup forum for problems or usage questions, this is not a bug but something wrong in your end.
