### ISSUE TITLE
Remove usage of `node-fetch`

### ISSUE THREAD

**Issue by piranna** [versatica/mediasoup#1095]
Node.js has an implementation of `fetch()` API [since 17.5.0](https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#fetch). Remove usage of `node-fetch` for it, to don't add extra dependencies, it's being used only on `npm-scripts.mjs` file so it's not needed at runtime at all.

**Comment by ibc** [comment]
1. mediasoup is guaranteed to run in Node >= 16: https://github.com/versatica/mediasoup/blob/v3/package.json#L48, so we cannot rely on native `fetch`.
2. `node-fetch` is used in runtime to download the prebuilt mediasoup-worker binary: https://github.com/versatica/mediasoup/blob/v3/npm-scripts.mjs#L83

So we must live with `node-fetch` until we increase require Node version to 18, which will not happen soon.

**Comment by piranna** [comment]
> 2\. `node-fetch` is used in runtime to download the prebuilt mediasoup-worker binary: [`v3`/npm-scripts.mjs#L83](https://github.com/versatica/mediasoup/blob/v3/npm-scripts.mjs?rgh-link-date=2023-05-30T08%3A33%3A24Z#L83)

For me that's install time, not runtime :-) but the Node.js >= 16 is enough reason for me, just only let's keep this topic in mind, Node.js 16 will get EOL in a bit more than three months...

**Comment by ibc** [comment]
Install time is not runtime, right, but node-fetch must be available when installing mediasoup via NPM in production mode so it must be in "dependencies" rather than in "devDependencies".

**Comment by piranna** [comment]
> Install time is not runtime, right, but node-fetch must be available when installing mediasoup via NPM in production mode so it must be in "dependencies" rather than in "devDependencies".

Agree.
