### ISSUE TITLE
Plain Transport Custom RTCP Port

### ISSUE THREAD

**Issue by ezioda004** [versatica/mediasoup#1096]
## Feature Request

When we create PlainTransport with `rtcpMux` `false`, then the transport uses 2 ports. One for RTP and the other for RTCP. While creating we can pass the port to `router.createPlainTransport()`, however, the RTCP port is selected from the worker's port range. I'm requesting an option to pass down a custom RTCP port to  `router.createPlainTransport()`, so the application layer can manage this port. In our app, we're already managing pipe transport ports and with the addition of plain transport, we're only able to manage RTP ports and not RTCP.

**Comment by albyho** [comment]
``` javascript
const transport = await router.createPlainTransport(
  {
    listenIp : "1.2.3.4",
    rtcpMux  : false, // false or unset
    comedia  : false // false or unset
  });
```

``` javascript
// Calling connect() on a PlainTransport created with comedia unset and rtcpMux
// also unset.
await plainTransport.connect(
  {
    ip       : '1.2.3.4',
    port     : 9998,
    rtcpPort : 9999
  });
```

**Comment by ibc** [comment]
PR done here: https://github.com/versatica/mediasoup/pull/1099

However, note that such a PR targets `flatbuffers` branch which has an ongoing PR https://github.com/versatica/mediasoup/pull/1064. So this feature will be in v3 once both PRs are merged.

**Comment by ezioda004** [comment]
This is great, however, I was expecting an option like `rtcpPort` like we have a `port` option in `PlainTransportOptions`. Would it make sense to add this option alongside `rtcpListenInfo`?

**Comment by ibc** [comment]
> This is great, however, I was expecting an option like `rtcpPort` like we have a `port` option in `PlainTransportOptions`. Would it make sense to add this option alongside `rtcpListenInfo`?

Definitely not. [ListenInfo](https://github.com/versatica/mediasoup/pull/1084) is the way to go once `flatbuffers` branch is merged in v3, and `ListenIp` will be deprecated. Some for `port` option in every `router.createXxxTransport()` API.

**Comment by ezioda004** [comment]
> Definitely not. [ListenInfo](https://github.com/versatica/mediasoup/pull/1084) is the way to go once `flatbuffers` branch is merged in v3, and `ListenIp` will be deprecated. Some for `port` option in every `router.createXxxTransport()` API.

Ok, so `listenInfo` and now `rtcpListeninfo` will replace `listenIp`, `port`. Understood.

**Comment by ibc** [comment]
Will not replace because the former options will still be available to not break backwards compatibility, but I don't want to add already deprecated new options.

**Comment by ibc** [comment]
This was done long ago.
