### ISSUE TITLE
no forwarding padding packet

### ISSUE THREAD

**Issue by buptlsp** [versatica/mediasoup#1097]
I use wireshark to capture the rtp packet and found lots of packet like this. 
![image](https://github.com/versatica/mediasoup/assets/3291512/d812b887-7802-4f91-9fc7-867ac6a944ab)

The package only contains padding , no payload. I checked some information, this packet is mainly used to probing the network when pacing. 

I would like to ask a question, is it a good idea to not forward this pure padding packet? If so, I would like to stop forwarding such packets.

**Comment by ibc** [comment]
There is an ongoing PR improving those things. We'll address it when possible.

**Comment by buptlsp** [comment]
OK， thanks!
