### ISSUE TITLE
REMB decreases with increasing of viewer

### ISSUE THREAD

**Issue by huangshan309** [versatica/mediasoup#110]
during the test, i found when there is one viewer for a peer, the status panel of this peer shows "available bitrate 500kbps", which is the max bitrate in the config.js, but the "available bitrate" decreases with increasing of the number of viewers:

viewers    available bitrate
1              500 kbps
2              333 kbps
3              222 kbps
4              167 kbps
5              133 kbps
6              111 kbps
7              95  kbps
8              83 kbps

i'm thinking, maybe the calculating of REMB goes wrong somehow？

**Comment by notedit** [comment]
you should read more code  from that demo.  

https://github.com/versatica/mediasoup-demo/blob/master/server/lib/Room.js#L451

**Comment by huangshan309** [comment]
thank you, got it, so MAX_BITRATE is for the total bandwidth from mediasoup to browser. each peer's max send bitrate is decided by the number of participants in the room, not exact the policy in my mind, but i got it, thank you.
