### ISSUE TITLE
Chrome issues when offer/answer handling is delayed by >1s

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#112]
Reported by Kwindla Kramer in the mailing list:

----

We started seeing consistent "frozen stream" issues in Chrome recently while building an application using mediasoup.

Initially we were using very simple websockets signaling code as we learned the mediasoup APIs. When we switched over to using our "real world" signaling layer, we discovered several reproducible cases of streams freezing in Chrome. We could see in chrome://webrtc-internals that bytes sent per second would briefly drop to 0, and Chrome would usually mark the streams as "muted=true".

We've spent the past couple of days chasing this down and have posted a stripped down test case here: https://github.com/kwindla/mediasoup-offer-delay

It turns out that we can trigger this "frozen stream" Chrome bugginess by simply introducing a consistent delay of ~1s or more in the offer/answer sequence from mediasoup to Chrome.

It took a while to figure this out mostly because we initially assumed we would trace the issue to a bug somewhere in our own signaling code. But we also went down several rabbit holes caused by different permutations of delay between several clients causing Chrome to do different things with the incoming streams, sometimes marking them as muted, sometimes just losing any ability to receive bytes on one stream, sometimes no longer receiving bytes on all incoming streams. Fun and interesting bug!

**Comment by ibc** [comment]
So, the test case listens for `negotiationneeded` fires and it delays sending the SDP offer for ~1 second, and that causes frozen video, right?

* When `onnegotiationneeded` is fired, mediasoup is already sending the new stream to the browser so, most probably, RTP packets arrive before the SDP.
* Theoretically the browser should just ignore them.
* At the time the SDP offer arrives to the browser (1 second later in this case), and since this is a SDP O/A in which a new remote stream exists, the browser is supposed to send a PLI to request a video full frame for the new receiving stream.

So no idea why this is failing (unless Chrome is doing something ugly after receiving unknown RTP packets with an unknown SSRC for ~1 second...).

It would help if you could please repeat the same test with just audio. This is, make a new browser join the room by just sending audio (no video) and delay the SDP re-offer for 1 second (or more) to others. If the other peers in the room do not receive the new audio stream then this is not something related to "frozen video".

**Comment by kwindla** [comment]
In regards to your description above, it's *not* the new stream that freezes. It's the *existing* stream that the first client is already playing back. And it freezes when `createOffer` is called on the mediasoup side, before Chrome is sent the updated SDP.

Here's the sequence:

1. Client A joins the room.
2. Client B joins the room. onnegotiationneeded fires for Client A. We delay sending offer by one second. Offer/answer exchange goes fine and video stream B->A plays fine in Client A. (B-> plays fine, too.)
3. Client C joins the room. onnegotionneeded fires for Client A. We delay for 1s. Then as soon as the mediasoup js code calls `createOffer` on the RTCPeerConnection for Client A, the video stream freezes in Chrome. (Before we send the offer again.)

**Comment by kwindla** [comment]
Ok, I updated the test code to zero in on the `createOffer` call on Client A's peerconnection (on the server side) when Client C joins.

The test server code has a new flag, `--chrome-freeze` that breaks out logic for each individual client's `createOffer()` and sdp send. That block of code is here:

  https://github.com/kwindla/mediasoup-offer-delay/blob/master/soup-server.js#L194

The README is updated, too.

**Comment by ibc** [comment]
Thanks for your work. I'll check this in the next days.

**Comment by ibc** [comment]
Hi, unfortunately I haven't got the time to check this, and I'm about taking some holidays. I'll check it, for sure.

BTW: I know it's difficult to get an older version of Chrome, but me and many others have detected issues in Chrome 58. It behaves much worse that Chrome 57 when it comes to SDP renegotiation stuff (remote videos get frozen for a while and Chrome sends a PLI to request a key frame). This did not happen in Chrome <= 57 at all. May be you can test your issue with Chrome 57 somehow?

**Comment by kwindla** [comment]
Hi, I did check with Chrome 57. I had the same thought as you. But Chrome 57 had the same behavior. I don't think there's any difference between 57 and 58, in terms of this specific issue.

**Comment by ibc** [comment]
Hi @kwindla, really sorry for the delay. I'm terribly busy with some projects those days and cannot check this for now. I will come to this once I get available.

**Comment by ibc** [comment]
Given that mediasoup v2 does no longer transmit SDPs in the wire, the issue reported here can not happen. Closing.
