### ISSUE TITLE
RtpSender.disable() and enable() without renegotiation

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#113]
Currently, the WebRTC API exposed by mediasoup generates an `negotiationneeded` event after calling `disable()` or `enable()` on a `RtpSender`. This is not efficient at all, and it causes issues in libwebrtc ObjC library due the lack of `stream.onremovetrack` event.

So the idea is the following:

```js
rtpSender.disable({ renegotiate: false })
```

Will do this in the next days.

**Comment by jmillan** [comment]
👍
