### ISSUE TITLE
`workerBin` is exposed as a type

### ISSUE THREAD

**Issue by piranna** [versatica/mediasoup#1130]
Due to https://github.com/versatica/mediasoup/pull/1123, now `workerBin` [is exposed as a type](https://github.com/versatica/mediasoup/blob/222ebd2c5d19b36a956aadea02d480f7264a2235/node/src/Worker.ts#L195-L202) in `mediasoup.types`... while being a string instead :-) Not critical, but it was curious to find it :-D

Semi-offtopic: shouldn't `workerBin` be better exposed as a readonly getter on a per-Worker instances? Specially since it's possible to modify `process.env` on runtime, so it's possible to have Workers running different workerBin instances in the same execution of Mediasoup...

**Comment by ibc** [comment]
What does it mean "exported as a type"? It's a string, a real string, and not a type. And it's not exported in types.ts but in index.ts (which imports it from Worker.ts in module loading time).

Regarding the other concern, while it true that the app can modify process.env.MEDIASOUP_WORKER_BIN before creating each Worker, the workerBin constant is computed only once when mediasoup module is loaded/imported/required. So changing the value of that env after loading mediasoup won't have any effect in future Workers. So the behavior is the intended one.

I'm closing this issue because I'm pretty sure that we are exporting a string (rather than a type) and the other concern is "invalid" (current behavior is the intended one).

**Comment by piranna** [comment]
> What does it mean "exported as a type"?

A type, or a class constructor.


> And it's not exported in types.ts but in index.ts (which imports it from Worker.ts in module loading time).

It appeared me inside `mediasoup.types` object, since `types.ts` is [exporting everything from `Worker.ts`](https://github.com/versatica/mediasoup/blob/222ebd2c5d19b36a956aadea02d480f7264a2235/node/src/types.ts#L1), so later `workerBin` string is leaked in the Javascript code after transpiled. That's the "bug" I'm talking about, that leaked string. If you do `console.log(mediasoup.types)`, you'll see the `workerBin` string there.


> the workerBin constant is computed only once when mediasoup module is loaded/imported/required

Good point 👍🏻. In this case, I would have put the value as a static property of the `Worker` class, but it's mostly a matter of preference on the API design.

**Comment by ibc** [comment]
> It appeared me inside mediasoup.types object, since types.ts is exporting everything from Worker.ts, so later workerBin string is leaked in the Javascript code after transpiled. That's the "bug" I'm talking about, that leaked string. If you do console.log(mediasoup.types), you'll see the workerBin string there.

Oh, true. We may have to individually select in types.ts which things to import from Worker .ts instead. But anyway the documentation says that workerBin is directly exported by main module so we are good.



Regarding how to export workerBin, yes, it could be a static member of worker but that's indeed super cosmetic thing. For next mediasoup v4 I'll take into account these topics. Now I prefer to not change things that would introduce breaking changes within v3.

**Comment by piranna** [comment]
> Oh, true. We may have to individually select in types.ts which things to import from Worker .ts instead. But anyway the documentation says that workerBin is directly exported by main module so we are good.

Sure, as I said it's not a critical bug :-)


> Regarding how to export workerBin, yes, it could be a static member of worker but that's indeed super cosmetic thing.

Agree.


> For next mediasoup v4 I'll take into account these topics. Now I prefer to not change things that would introduce breaking changes within v3.

Fair enough. Do you have a public v4 list where we can contribute and discuss, or do you have it just as an internal one by the moment?

**Comment by ibc** [comment]
> Do you have a public v4 list where we can contribute and discuss, or do you have it just as an internal one by the moment?

Will do it after summer and after flatbuffers and other pending efforts are finished in v3.

**Comment by piranna** [comment]
> Will do it after summer and after flatbuffers and other pending efforts are finished in v3.

Awesome :-D Please keep us (me :-P) informed when you plan to do it so we can help ;-)
