### ISSUE TITLE
`Worker.died` field is missing in docs

### ISSUE THREAD

**Issue by piranna** [versatica/mediasoup#1133]
Published docs don't include `Worker.died` field, but it's being checked in the tests (and it's in the code).

**Comment by nazar-pc** [comment]
I'm not sure you're supposed to use it though. There are a few private APIs that are only used by tests to check internal invariants.

**Comment by piranna** [comment]
> I'm not sure you're supposed to use it though. There are a few private APIs that are only used by tests to check internal invariants.

If that's the case, I don't know what bad can do to have a boolean getter flag as public, that's in fact no prefixed with an underscore to mark it as non-public...

**Comment by ibc** [comment]
There is a reason for this getter to exist and be public. I don't remember now but will figure out and will add it on the documentation website next week.

**Comment by ibc** [comment]
Documented.
