### ISSUE TITLE
WebRtcServer `webrtctransporthandled` event is being dispatched before Router `newtransport`

### ISSUE THREAD

**Issue by piranna** [versatica/mediasoup#1137]
At https://github.com/versatica/mediasoup/blob/0b628632bd18f60a30a9742fc0b37eb58c8efd68/node/src/Router.ts#L468-L474 we see that WebRtcServer `webrtctransporthandled` event is being dispatched before Router `newtransport`. What's the reason of that? Wouldn't it make more sense that `newtransport` is being dispatched first, and later `webrtctransporthandled` tell us that this Transport is being handled by the WebRtcServer? If not, in its current order, we are being notified that a Transport we didn't know at all before is being handled by the WebRtcServer instance...

**Comment by ibc** [comment]
Makes sense. PR welcome, otherwise I'll do eventually.

**Comment by piranna** [comment]
PR available at https://github.com/versatica/mediasoup/pull/1138.

**Comment by piranna** [comment]
Thank you :-)
