### ISSUE TITLE
mediasoup installation issue in windows 7

### ISSUE THREAD

**Issue by kul1010** [versatica/mediasoup#116]
$ node server
- process.env.DEBUG: *LOG* *WARN* *ERROR* *mediasoup-worker*
- config.mediasoup.logLevel: debug
- config.mediasoup.logTags: [ 'info', 'rtp', 'rtcp', 'rtx' ]
module.js:487
    throw err;
    ^

Error: Cannot find module 'mediasoup'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\asergis\eg\jssip\mediasoup-demo\server\server.js:1
9:19)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

===========When i again install mediasoup then showing below error===============
pankaj.k@YEN-PC MINGW64 /d/asergis/eg/jssip/mediasoup-demo/server (master)
$ npm i mediasoup

> mediasoup@1.2.5 postinstall D:\asergis\eg\jssip\mediasoup-demo\server\node_modules\mediasoup
> make Release

'make' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mediasoup@1.2.5 postinstall: `make Release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mediasoup@1.2.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pankaj.k\AppData\Roaming\npm-cache\_logs\2017-06-13T07_30_49_050Z-debug.log

**Comment by ibc** [comment]
The README and documentation clearly say that Windows is not supported.

**Comment by kul1010** [comment]
I have installed it on Ubuntu now. But below error when used $ gulp dev

TypeError: Cannot read property 'apply' of undefined
    at /usr/lib/node_modules/gulp/bin/gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

**Comment by ibc** [comment]
First of all: why do you run gulp dev?

**Comment by kul1010** [comment]
for development environment.

**Comment by ibc** [comment]
Run node -v and gulp -v within the mediasoup folder.

**Comment by kul1010** [comment]
node version is 8.0.0 
and gulp
CLI version 1.3.0
Local version 4.0.0-alpha.2

**Comment by ibc** [comment]
> for development environment. And same error for prod and live.

Oh no, there is no `gulp dev` nor `gulp prod` nor `gulp live` in **mediasoup** project, so not sure what exactly you mean. Do you mean the demo project?

**Comment by ibc** [comment]
Anyhow, for now try with Node 6 please. Node 8 comes with npm 5.0.X which has some bugs that also affect me in other projects.

**Comment by kul1010** [comment]
node version is 8.0.0 
and gulp
CLI version 1.3.0
Local version 4.0.0-alpha.2

**Comment by kul1010** [comment]
I have changed version using nvm. But below error when used $ node server.js
pankaj@ubuntu:/var/www/mediasoup-demo/server$ node server.js 
- process.env.DEBUG: *LOG* *WARN* *ERROR* *mediasoup-worker*
- config.mediasoup.logLevel: debug
- config.mediasoup.logTags: [ 'info', 'rtp', 'rtcp', 'rtx' ]
[opening Readline Command Console...]
cmd>   mediasoup-demo-server:LOG protoo WebSocket server running +0ms
  mediasoup:ERROR:Channel received invalid message: Unknown encoding: null +4ms
  mediasoup:ERROR:Channel received invalid message: Unknown encoding: null +7ms
  mediasoup:ERROR:Channel received invalid message: Unknown encoding: null +1ms
  mediasoup:ERROR:Channel received invalid message: Unknown encoding: null +0ms
  mediasoup:ERROR:Channel received invalid message: Unknown encoding: null +0ms
  mediasoup:ERROR:Channel received invalid message: Unknown encoding: null +0ms
  mediasoup:ERROR:Channel received invalid message: Unknown encoding: null +0ms
  mediasoup:ERROR:Channel received invalid message: Unknown encoding: null +1ms
  mediasoup:ERROR:Channel received invalid message: Unknown encoding: null +0ms
  mediasoup:ERROR:Channel received invalid message: Unknown encoding: null +0ms
  mediasoup:ERROR:Channel received invalid message: Unknown encoding: null +0ms
  mediasoup:ERROR:Channel received invalid message: Unknown encoding: null +0ms
  mediasoup:ERROR:Channel received invalid message: Unknown encoding: null +5ms
  mediasoup:ERROR:Channel received invalid message: Unknown encoding: null +1ms

**Comment by kul1010** [comment]
pankaj@ubuntu:/var/www/mediasoup-demo/app$ sudo gulp prod
[sudo] password for pankaj: 
[12:55:47] Using gulpfile /var/www/mediasoup-demo/app/gulpfile.js
[12:55:47] Starting 'prod'...
[12:55:47] Starting 'env:prod'...
[12:55:47] setting "prod" environment
[12:55:47] Finished 'env:prod' after 46 ms
[12:55:47] Starting 'clean'...
[12:55:47] Finished 'clean' after 26 ms
[12:55:47] Starting 'lint'...
[12:55:52] Finished 'lint' after 4.66 s
[12:55:52] Starting 'bundle'...
[12:56:16] Finished 'bundle' after 24 s
[12:56:16] Starting 'html'...
[12:56:16] Finished 'html' after 46 ms
[12:56:16] Starting 'css'...
(node:9136) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
[12:56:18] Finished 'css' after 2.22 s
[12:56:18] Starting 'resources'...
[12:56:18] Finished 'resources' after 147 ms
[12:56:18] Finished 'prod' after 31 s
pankaj@ubuntu:/var/www/mediasoup-demo/app$

**Comment by ibc** [comment]
Dear @kul1010, I'm sorry but this issue tracker is about mediasoup, and not about the mediasoup-demo project.
