### ISSUE TITLE
Add prebuilds for Apple M1

### ISSUE THREAD

**Issue by piranna** [versatica/mediasoup#1167]
## Feature Request

Apple M1 Github workers [are available in beta](https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/).

**Comment by ibc** [comment]
Correct me if I'm wrong but they are not free:

> To try the new Apple silicon macOS larger runner, update the runs-on: key in your GitHub Actions YAML workflow YAML file to target macos-latest-xlarge or macos-13-xlarge. The 12-core macOS larger runner is moving from xlarge to large, and is still available by updating the runs-on: key to macos-latest-large, macos-12-large, or macos-13-large. There is no sign-up required for the beta and the runner is immediately available to all developers, teams, and enterprises.
>
> As part of GitHub’s continued commitment to deliver the best developer experience we are excited to share with you that we will be decreasing the price of our macOS larger runners.

Although it seems contradictory...

**Comment by piranna** [comment]
It seems they are not free because it's considered "large", but you are right, information is not clear, I can't find an answer myself either. I suggest maybe config it, and see if it fails :-)

**Comment by ibc** [comment]
Nope. Confirmed that it's not free. It says that the beta program doesn't require extra sign up. But large runners have never been free so neither this new one.

Closing ticket (sadly).
