### ISSUE TITLE
RtpSender missing associatedRtpReceiver

### ISSUE THREAD

**Issue by wcbear** [versatica/mediasoup#117]
Hi,

I see the issue where when webrtc.RTCPeerConnection is used, associatedRtpReceiver of an RtpSender becomes undefined in the following steps.

1. Create RTCPeerConnection for A, successfully establish the connection.
1-1. Listen 'newrtpsender' for the Peer of the RTCPeerConnection
2. Create RTCPeerConnection for B
2-1. Set B capability, create, set, and send an offer to B
2-2. Set an answer from B.

The listener registered at 1-1 gets called with an RtpSender without associatedRtpReceiver (i.e. RtpReceiver for B)

I have confirmed it with version 1.2.6

Thanks,
wcbear

**Comment by ibc** [comment]
Good catch. Unfortunately I'll be out for 2-3 weeks. I will take a look at my arrival.

**Comment by ibc** [comment]
This will no longer happen in mediasoup v2 (in which we are hardly working).

**Comment by wcbear** [comment]
I see.
Are there more information about v2 overall?

**Comment by wcbear** [comment]
Probably this?
https://github.com/versatica/mediasoup/blob/v2/TODO_V2.md

**Comment by ibc** [comment]
* https://github.com/versatica/mediasoup/tree/v2
* https://github.com/versatica/mediasoup-client
* https://github.com/versatica/mediasoup/milestone/2

**Comment by jmillan** [comment]
Closing since this is not an issue.
