### ISSUE TITLE
npm postinstall fails in Windows: rd /s /q worker\out\msys => The system cannot find the file specified

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#1179]
## Bug Report

This is a recent error happening in Windows CI: https://github.com/versatica/mediasoup/actions/runs/6536142903/job/17747178461?pr=1178

```
npm-scripts [INFO] [postinstall] executeCmd(): rd /s /q worker\out\msys
The system cannot find the file specified.
npm-scripts [ERROR] [postinstall] executeCmd() failed, exiting: Error: Command failed: rd /s /q worker\out\msys
```

Nothing has changed so this is related to Windows. No idea. We need to make it work reliably in all supported Windows versions.

Somehow the issue doesn't make sense. When installing mediasoup on Windows (and forcing it to compile the worker instead of fetching a prebuilt worker), this is the flow:

1. `MEDIASOUP_SKIP_WORKER_PREBUILT_DOWNLOAD=true npm install mediasoup --foreground-scripts` (well, whichever syntax is needed in Windows to set environment variables).
2. The npm 'postinstall' task will run the 'postinstall' section in `npm-scripts.mjs`.
3. It will first fun `buildWorker()`:
  ```ts
  function buildWorker()
  {
	logInfo('buildWorker()');

	if (IS_WINDOWS)
	{
		if (!fs.existsSync('worker/out/msys/bin/make.exe'))
		{
			installMsysMake();
		}

		const msysPath = `${process.cwd()}\\worker\\out\\msys\\bin`;

		if (!process.env.PATH.includes(msysPath))
		{
			process.env.PATH = `${msysPath};${process.env.PATH}`;
		}
	}

	executeCmd(`${MAKE} -C worker`);
  }
  ```
4. Note that if `worker/out/msys/bin/make.exe` doesn't exist then it calls `installMsysMake()` which does this:
  ```ts
  function installMsysMake()
  {
	logInfo('installMsysMake()');

	let res = spawnSync('where', [ 'python3.exe' ]);

	if (res.status !== 0)
	{
		res = spawnSync('where', [ 'python.exe' ]);

		if (res.status !== 0)
		{
			logError('`installMsysMake() | cannot find Python executable');

			exitWithError();
		}
	}

	executeCmd(`${String(res.stdout).trim()} worker\\scripts\\getmake.py`);
  }
  ```
5. So here it ensures that we have `python3.exe` and then runs `worker/scripts/getmake.py` which does this:
  ```py
  import io, hashlib, tarfile, urllib.request

  def get(url, digest):
    data = urllib.request.urlopen(url).read()
    assert hashlib.sha256(data).hexdigest() == digest
    tar = tarfile.open(fileobj=io.BytesIO(data))
    tar.extractall('worker/out/msys')
    tar.close()

  get('https://sourceforge.net/projects/mingw/files/MSYS/Base/msys-core/msys-1.0.19-1/msysCORE-1.0.19-1-msys-1.0.19-bin.tar.xz/download', '8c4157d739a460f85563bc4451e9f1bbd42b13c4f63770d43b9f45a781f07858')
  get('https://sourceforge.net/projects/mingw/files/MSYS/Base/libiconv/libiconv-1.14-1/libiconv-1.14-1-msys-1.0.17-dll-2.tar.lzma/download', '196921e8c232259c8e6a6852b9ee8d9ab2d29a91419f0c8dc27ba6f034231683')
  get('https://sourceforge.net/projects/mingw/files/MSYS/Base/gettext/gettext-0.18.1.1-1/libintl-0.18.1.1-1-msys-1.0.17-dll-8.tar.lzma/download', '29db8c969661c511fbe2a341ab25c993c5f9c555842a75d6ddbcfa70dec16910')
  get('https://sourceforge.net/projects/mingw/files/MSYS/Base/coreutils/coreutils-5.97-3/coreutils-5.97-3-msys-1.0.13-bin.tar.lzma/download', 'f8c7990416ea16a74ac336dcfe0f596bc46b8724b2d58cf8a3509414220b2366')
  get('https://sourceforge.net/projects/mingw/files/MSYS/Base/regex/regex-1.20090805-2/libregex-1.20090805-2-msys-1.0.13-dll-1.tar.lzma/download', '85dd8c1e27a90675c5f867be57ba7ae2bb55dde8cd2d19f284c896be134bd3d1')
  get('https://sourceforge.net/projects/mingw/files/MSYS/Base/termcap/termcap-0.20050421_1-2/libtermcap-0.20050421_1-2-msys-1.0.13-dll-0.tar.lzma/download', '62b58fe0880f0972fcc84a819265989b02439c1c5185870227bd25f870f7adb6')
  get('https://sourceforge.net/projects/mingw/files/MSYS/Base/bash/bash-3.1.23-1/bash-3.1.23-1-msys-1.0.18-bin.tar.xz/download', '38da5419969ab883058a96322bb0f51434dd4e9f71de09cd4f75b96750944533')
  get('https://sourceforge.net/projects/mingw/files/MSYS/Base/make/make-3.81-3/make-3.81-3-msys-1.0.13-bin.tar.lzma/download', '847f0cbbf07135801c8e67bf692d29b1821e816ad828753c997fa869a9b89988')
  ```
6. Here it **clearly** extracts things in `worker/out/msys` folder, notice the `tar.extractall('worker/out/msys')` line.
7. So then `buildWorker()` continues. It adds `${process.cwd()}\\worker\\out\\msys\\bin` to the `PATH` and runs `make` to compile the worker.
8. And then `buildWorker()` completes so `cleanWorkerArtifacts()` is called which does this:
  ```ts
  function cleanWorkerArtifacts()
  {
	logInfo('cleanWorkerArtifacts()');

	// Clean build artifacts except `mediasoup-worker`.
	executeCmd(`${MAKE} clean-build -C worker`);
	// Clean downloaded dependencies.
	executeCmd(`${MAKE} clean-subprojects -C worker`);
	// Clean PIP/Meson/Ninja.
	executeCmd(`${MAKE} clean-pip -C worker`);

	if (IS_WINDOWS)
	{
		executeCmd('rd /s /q worker\\out\\msys');
	}
  }
  ```
9. And somehow the last command `rd /s /q worker\\out\\msys` fails only in some cases (see https://github.com/versatica/mediasoup/issues/1179#issuecomment-1770463999) with this error:
  ```
  npm-scripts [INFO] [postinstall] executeCmd(): rd /s /q worker\out\msys
  The system cannot find the file specified.
  npm-scripts [ERROR] [postinstall] executeCmd() failed, exiting: Error: Command failed: rd /s /q worker\out\msys
  ```
9. How is it possible? Obviously `worker\out\msys` folder DOES exist, it's guaranteed by steps before.

**Comment by ibc** [comment]
Windows ecosystem is pathetic. I've google the above error and there are just tons of posts telling you to reinstall Windows, format HD, etc.

**Comment by ibc** [comment]
@haiyangwu @nazar-pc maybe you know something about this recent error in Windows?

**Comment by nazar-pc** [comment]
Looks like it is a cleanup step after `getmake.py`, maybe `make` was not fixed to a specific version and has changed now?

**Comment by ibc** [comment]
A workaround is to avoid error being thrown in the `cleanWorkerArtifacts()` function as follows:

```ts
executeCmd('rd /s /q worker\\out\\msys', /* exitOnError */ false);
```

So basically we do not clean worker artifacts after building the worker, which IMHO is not that bad.

> Looks like it is a cleanup step after `getmake.py`, maybe `make` was not fixed to a specific version and has changed now?

Absolutely no idea. `getmake.py` clearly run this:

```py
get('https://sourceforge.net/projects/mingw/files/MSYS/Base/make/make-3.81-3/make-3.81-3-msys-1.0.13-bin.tar.lzma/download', '847f0cbbf07135801c8e67bf692d29b1821e816ad828753c997fa869a9b89988')
```

And it does this at the beginning (I have no idea what it is about) which clearly extracts stuff into 'worker/out/msys' folder.

```py
def get(url, digest):
  data = urllib.request.urlopen(url).read()
  assert hashlib.sha256(data).hexdigest() == digest
  tar = tarfile.open(fileobj=io.BytesIO(data))
  tar.extractall('worker/out/msys')
  tar.close()
```

**Comment by ibc** [comment]
@jmillan @nazar-pc are we ok with the temporary solution I suggest in my comment above?

```ts
executeCmd('rd /s /q worker\\out\\msys', /* exitOnError */ false);
```

**Comment by nazar-pc** [comment]
I would prefer to understand why it happens though. Are you able to spin up a Windows VM to see what is actually going on in file system there?

**Comment by ibc** [comment]
Definitely I don't have any (virtual) Windows setup to test :(

**Comment by ibc** [comment]
I have an idea: create a temporal PR that catches that error and then prints the content of the worker/out/msys folder (if it exists, and it should because postinstall installed things in there). Do you know the exact command for that? Is it `dir worker\\out\\msys?`

**Comment by nazar-pc** [comment]
I mean you can install any VM management (like VirtualBox Parallels, VmWare), download official Windows ISO and install it in a VM. Then you will have, that is how I debugged some Windows issues, I don't run Windows daily either.

**Comment by ibc** [comment]
Yes, but I'm super busy with tons of tasks (specially at work) and honestly I cannot deal with virtual machines right now.

**Comment by nazar-pc** [comment]
> I have an idea: create a temporal PR that catches that error and then prints the content of the worker/out/msys folder (if it exists, and it should because postinstall installed things in there). Do you know the exact command for that? Is it `dir worker\\out\\msys?`

If you want to debug it in CI then makes sense to me, but only as a debugging step. Would be great if someone on Windows debugged this though.

**Comment by ibc** [comment]
Asking to a workmate.

**Comment by ibc** [comment]
So the error doesn't happen for a folk using this Windows and Visual Studio versions:

```
Activating VS 17.7.4
C compiler for the host machine: cl (msvc 19.35.32217.1 "Microsoft (R) C/C++ Optimizing Compiler Version 19.35.32217.1 for x64")
C linker for the host machine: link link 14.35.32217.1
C++ compiler for the host machine: cl (msvc 19.35.32217.1 "Microsoft (R) C/C++ Optimizing Compiler Version 19.35.32217.1 for x64")
C++ linker for the host machine: link link 14.35.32217.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
```

**Comment by ArcanisCz** [comment]
Hi! I have tried to install mediasoup on my windows machine, and it works for me. 
```
C:\Users\arcan\git\test>npm i mediasoup

added 21 packages in 6m

6 packages are looking for funding
  run `npm fund` for details
```

- mediasoup@3.12.13
- Microsoft Visual Studio Community 2019 Version 16.11.9
- Windows 11 Home 22H2 22621.2428

msys folder is not present after installation

```
C:\Users\arcan\git\test\node_modules\mediasoup\worker\out>ls
Release/
```
Some output from postinstall
```
The Meson build system
Version: 1.2.1
Source dir: C:\Users\arcan\git\test\node_modules\mediasoup\worker
Build dir: C:\Users\arcan\git\test\node_modules\mediasoup\worker\out\Release\build
Build type: native build
Project name: mediasoup-worker
Project version: undefined
C compiler for the host machine: cl (msvc 19.29.30139 "Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30139 for x64")
C linker for the host machine: link link 14.29.30139.0
C++ compiler for the host machine: cl (msvc 19.29.30139 "Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30139 for x64")
C++ linker for the host machine: link link 14.29.30139.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Downloading openssl source from https://www.openssl.org/source/openssl-3.0.8.tar.gz
Download size: 15151328
Downloading: ..........
Downloading openssl patch from https://wrapdb.mesonbuild.com/v2/openssl_3.0.8-1/get_patch
Download size: 11463052
...
Deleting C:\Users\arcan\git\test\node_modules\mediasoup\worker\subprojects\libsrtp-2.5.0
Deleting C:\Users\arcan\git\test\node_modules\mediasoup\worker\subprojects\packagecache\openssl-3.0.8.tar.gz
Deleting C:\Users\arcan\git\test\node_modules\mediasoup\worker\subprojects\packagecache\openssl_3.0.8-1_patch.zip
Deleting C:\Users\arcan\git\test\node_modules\mediasoup\worker\subprojects\openssl-3.0.8
make: Leaving directory `/c/Users/arcan/git/test/node_modules/mediasoup/worker'
npm-scripts [INFO] [postinstall] executeCmd(): make clean-pip -C worker
make: Entering directory `/c/Users/arcan/git/test/node_modules/mediasoup/worker'
rm -f -rf /c/Users/arcan/git/test/node_modules/mediasoup/worker/out/pip
make: Leaving directory `/c/Users/arcan/git/test/node_modules/mediasoup/worker'
npm-scripts [INFO] [postinstall] executeCmd(): rd /s /q worker\out\msys
npm info run mediasoup@3.12.13 postinstall { code: 0, signal: null }
```
which seems like the folder msys was there and the command deleted it sucesfully. If I execute command after installation, it says error
```
C:\Users\arcan\git\test\node_modules\mediasoup>rd /s /q worker\out\msys
The system cannot find the file specified.
```

which leads me to conclusion that the CI build did not created msys folder. When I create msys folder manually and run the command again, it executes without error and deletes the folder. So the command itself works as expected.

**Comment by ArcanisCz** [comment]
Only differences I see are
- CI mscv `19.35`, my machine `19.29`
- CI using `mingw32-make`, my machine just `make`
- CI pip `23`, my machine pip `21`

my `make`
```
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i686-pc-msys
```

**Comment by ibc** [comment]
Thanks @ArcanisCz, super useful.

**Comment by ArcanisCz** [comment]
If the problem is only a failing command in case folder does not exist, maybe smth like https://stackoverflow.com/questions/14502612/delete-a-directory-and-its-files-using-command-line-but-dont-throw-error-if-it can be usefull?

Or the real underlying problem is that the `msys` folder is not created and should have been there always?

**Comment by ArcanisCz** [comment]
Do you want me to see contents of the folder before deletion on my system?

**Comment by ibc** [comment]
> If the problem is only a failing command in case folder does not exist, maybe smth like https://stackoverflow.com/questions/14502612/delete-a-directory-and-its-files-using-command-line-but-dont-throw-error-if-it can be usefull?

That's basically the solution I suggested before. See  https://github.com/versatica/mediasoup/issues/1179#issuecomment-1768769402

But it's not a nice solution because `worker\out\msys` folder SHOULD exist at that point. I've explained all the flow in the issue description above (updated right now). It's impossible that such a folder doesn't exist at that time when compilation finishes.

> Do you want me to see contents of the folder before deletion on my system?

Yes please. Not sure if you need to checkout mediasoup repo for that.

**Comment by nazar-pc** [comment]
The only possible reason for `worker/out/msys` to not exist is for file extraction to fail, which explains why wrong `make` is used as described above.

**Comment by ArcanisCz** [comment]
The folder is there from basically start of postinstall script (when meson/python initializes) and its there due to postinstall (was not created when I --ignore-scripts)

![image](https://github.com/versatica/mediasoup/assets/8430123/631d8e49-ddc1-4107-9853-7f52f20f5cf4)

**Comment by nazar-pc** [comment]
That is how it should be. If CI fails then in CI downloading/extraction flow is broken for some reason.

**Comment by ArcanisCz** [comment]
In case you want to see full output from my machine:

[fulllog.txt](https://github.com/versatica/mediasoup/files/13041280/fulllog.txt)

Not sure how can I help more now, if you need me to test/try anything please ping me 🙏

**Comment by ibc** [comment]
> The only possible reason for `worker/out/msys` to not exist is for file extraction to fail, which explains why wrong make is used as described above.

Wow, but... if file extraction fails then it means that `getmake.py` script failed, and if it failed it means that `executeCmd(`${String(res.stdout).trim()} worker\\scripts\\getmake.py`)` did throw, and hence `installMsysMake()` did also throw, and hence `buildWorker()` did also throw, and if so the whole script terminates and `cleanWorkerArtifacts()` CANNOT be executed so it cannot fail.

So @nazar-pc, I fail to understand that possible reason. It's not possible.

**Comment by ibc** [comment]
> In case you want to see full output from my machine:
> 
> [fulllog.txt](https://github.com/versatica/mediasoup/files/13041280/fulllog.txt)

Your logs say that everything is fine and the whole thing behaves as expected:
```
npm-scripts [INFO] [postinstall] buildWorker()
npm-scripts [INFO] [postinstall] installMsysMake()
npm-scripts [INFO] [postinstall] executeCmd(): C:\Users\arcan\AppData\Local\Programs\Python\Python38\python.exe worker\scripts\getmake.py
npm-scripts [INFO] [postinstall] executeCmd(): make -C worker

...

npm-scripts [INFO] [postinstall] executeCmd(): rd /s /q worker\out\msys
npm info run mediasoup@3.12.13 postinstall { code: 0, signal: null }
```

 
> Not sure how can I help more now, if you need me to test/try anything please ping me 🙏

Thanks!

**Comment by nazar-pc** [comment]
> So @nazar-pc, I fail to understand that possible reason. It's not possible.

I do not know how/what/where, but it is clear that the files are not there. Or maybe they are extracted into `worker/out/msys`, but it is not `worker/out/msys` that we think it is or something (maybe `pwd` inside of Python script is different, so it extracts files elsewhere, providing an absolute path would fix that particular issue).

**Comment by ibc** [comment]
> Or maybe they are extracted into `worker/out/msys`, but it is not `worker/out/msys` that we think it is or something (maybe `pwd` inside of Python script is different, so it extracts files elsewhere, providing an absolute path would fix that particular issue).

https://github.com/versatica/mediasoup/pull/1187
