### ISSUE TITLE
TS: expect() statements inside event handlers are not taking any effect 

### ISSUE THREAD

**Issue by jmillan** [versatica/mediasoup#1188]
Because mediasoup instances use `EnhancedEventEmitter.safeEmit()` which absorbs any exception occurred in the event handler.

This makes that `expect(1).toBe(2);` in a event handler does not fail and makes the test pass.

Example: https://github.com/versatica/mediasoup/blob/v3/node/src/tests/test-DirectTransport.ts#L154

**Comment by ibc** [comment]
We should **only** use `safeEmit()` in internal listeners and never use it in public events. The app is free to add try/catch into its listeners.

NOTE: Same must be done in mediasoup-client and mediasoup-aiortc-client.

NOTE: Let's do this directly in flatbuffers.

**Comment by jmillan** [comment]
> NOTE: Let's do this directly in flatbuffers.

I have just discovered this issue that has always been there. Can we wait for `flatbuffers` to be moved to `v3` and do it then? 

It will be impossible for anyone to look at the PR otherwise. 

I don't find this being so urgent. We can do it as soon as `flatbuffers` is merged.

**Comment by ibc** [comment]
Ok, I was under the impression that you need this done to verify tests in flatbuffers. If not, let's wait.

**Comment by ibc** [comment]
Hell, why is this failing? https://github.com/versatica/mediasoup/actions/runs/6586227674/job/17894163137?pr=1187

```
error: failed to run custom build command for `mediasoup-sys v0.5.4 (D:\a\mediasoup\mediasoup\worker)`

Caused by:
  process didn't exit successfully: `D:\a\mediasoup\mediasoup\target\debug\build\mediasoup-sys-609a6396dde901ad\build-script-build` (exit code: 101)
  --- stdout
  C:\hostedtoolcache\windows\Python\3.9.13\x64\python3.exe

  --- stderr
  Traceback (most recent call last):
    File "D:\a\mediasoup\mediasoup\worker\scripts\getmake.py", line 27, in <module>
      get('https://sourceforge.net/projects/mingw/files/MSYS/Base/bash/bash-3.1.23-1/bash-3.1.23-1-msys-1.0.18-bin.tar.xz/download', '38da5419969ab883058a96322bb0f51434dd4e9f71de09cd4f75b96750944533')
    File "D:\a\mediasoup\mediasoup\worker\scripts\getmake.py", line 18, in get
      tar.extractall(args.dir)
    File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\tarfile.py", line 2045, in extractall
      self.extract(tarinfo, path, set_attrs=not tarinfo.isdir(),
    File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\tarfile.py", line 2086, in extract
      self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
    File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\tarfile.py", line 2159, in _extract_member
      self.makefile(tarinfo, targetpath)
    File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\tarfile.py", line 2200, in makefile
      with bltn_open(targetpath, "wb") as target:
  PermissionError: [Errno 13] Permission denied: 'D:\\a\\mediasoup\\mediasoup\\worker\\out\\msys\\bin\\bashbug'
  thread 'main' panicked at 'Failed to install MSYS/make', worker\build.rs:107:17
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
Error: The process 'C:\Users\runneradmin\.cargo\bin\cargo.exe' failed with exit code 101
```

**Comment by jmillan** [comment]
> Hell, why is this failing? https://github.com/versatica/mediasoup/actions/runs/6586227674/job/17894163137?pr=1187

Wrong PR.

**Comment by ibc** [comment]
Hell. Deleting.

**Comment by ibc** [comment]
So I cannot reproduce the error. I mean, I've literally make `safeEmit()` behave as `emit()` (no try/catch) and the tests succeed ¯\_(ツ)_/¯

@jmillan what do I need to reproduce the problem? you remember?

**Comment by jmillan** [comment]
> So I cannot reproduce the error. I mean, I've literally make `safeEmit()` behave as `emit()` (no try/catch) and the tests succeed ¯\_(ツ)_/¯
> 
> @jmillan what do I need to reproduce the problem? you remember?

As said in the description, write `expect(1).toBe(2)` in an even handler. The test will pass, and it should not.

**Comment by ibc** [comment]
Well, that's the thing: if I add this in the test file:

```ts
dataConsumer.on('message', (message, ppid) =>
{
  // current code

  expect(1).toBe(2);
});
```

then I see that those listeners are failing due to the new `emittererror` event. The thing is that I do NOT see any other error, meaning that all the other `expect()` are NOT failing!

```
  console.log
    ------ dataConsumer listener error [eventName:message]: Error: expect(received).toBe(expected) // Object.is equality

    Expected: 2
    Received: 1

      at DataConsumer.<anonymous> (node/src/tests/test-DirectTransport.ts:150:11)

        at DataConsumer.<anonymous> (node/src/tests/test-DirectTransport.ts:235:12)

  console.log
    ------ dataConsumer listener error [eventName:message]: Error: expect(received).toBe(expected) // Object.is equality

    Expected: 2
    Received: 1

      at DataConsumer.<anonymous> (node/src/tests/test-DirectTransport.ts:150:11)

 PASS  node/src/tests/test-DirectTransport.ts
  ✓ router.createDirectTransport() succeeds (11 ms)
  ✓ router.createDirectTransport() with wrong arguments rejects with TypeError (26 ms)
  ✓ directTransport.getStats() succeeds (4 ms)
  ✓ directTransport.connect() succeeds (1 ms)
  ✓ dataProducer.send() succeeds (249 ms)
  ✓ dataProducer.send() with subchannels succeeds (5 ms)
  ✓ DirectTransport methods reject if closed (6 ms)
  ✓ DirectTransport emits "routerclose" if Router is closed (2 ms)
  ✓ DirectTransport emits "routerclose" if Worker is closed (2 ms)

Test Suites: 1 passed, 1 total
Tests:       9 passed, 9 total
Snapshots:   0 total
Time:        3.067 s
Ran all test suites matching /tests\/test-DirectTransport.ts/i.
```
