### ISSUE TITLE
How to manage mediasoup objects to disk?

### ISSUE THREAD

**Issue by nswon** [versatica/mediasoup#1209]
Before i ask: I tried writing in mediasoup group but access denied appears.

Are mediasoup objects supposed to be managed in-memory? I want to save them on a disk but I couldn't figure out how.

Is there a way to just subtract the state of the instance and manage it or import objects without creating new ones? Or is there any other way to save to disk?

**Comment by nazar-pc** [comment]
Questions on the forum: https://mediasoup.discourse.group/

**Comment by nswon** [comment]
<img width="1300" alt="스크린샷 2023-11-04 오후 7 42 20" src="https://github.com/versatica/mediasoup/assets/80371249/af81e118-1482-4154-8195-509e1fade19f">

How do I post it? I think I don't have authority

**Comment by jmillan** [comment]
@nswon, I can see you as a normal user. I don't know the reason why you may not be able to post.

<img width="1325" alt="Screenshot 2023-11-15 at 13 17 32" src="https://github.com/versatica/mediasoup/assets/732340/e478711d-f826-4312-9624-ae7058645c1c">
