### ISSUE TITLE
actions-rs/cargo are outdated and unmaintained

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#1215]
We run `actions-rs/cargo@v1` actions in `mediasoup-rust.yaml`. As warned in https://github.com/versatica/mediasoup/actions/runs/6796993961:

> ci (ubuntu-22.04)The following actions uses node12 which is deprecated and will be forced to run on node16: actions-rs/cargo@v1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default
> ci (ubuntu-20.04)The following actions uses node12 which is deprecated and will be forced to run on node16: actions-rs/cargo@v1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

Problem is that [actions-rs/cargo](https://github.com/actions-rs/cargo) CI actions are not maintained... "This repository has been archived by the owner on Oct 13, 2023. It is now read-only.".

So what now?

**Comment by nazar-pc** [comment]
At least it was archived now. We can switch to just running `cargo` with shell, it is not difficult at all.

**Comment by ibc** [comment]
> At least it was archived now. We can switch to just running `cargo` with shell, it is not difficult at all.

But that means that we must install cargo in CI hosts, right?

**Comment by nazar-pc** [comment]
> But that means that we must install cargo in CI hosts, right?

Nope, it is there by default already

**Comment by ibc** [comment]
So should we just remove those actions and run cargo fmt, clippy and test commands instead?

**Comment by nazar-pc** [comment]
Should work, yes

**Comment by ibc** [comment]
Stupid question. Suddenly I don't have `cargo` command anymore...
No idea if it went away after running `brew update` some days ago. Should I (re)install the whole thing with `curl -sSf https://static.rust-lang.org/rustup.sh | sh`?

**Comment by nazar-pc** [comment]
If you installed rustup through brew last time you can do that again, otherwise I would recommend https://rustup.rs/ as the canonical way to install everything necessary

**Comment by ibc** [comment]
I've run `rustup-init` again which is what I installed via Brew long ago. `cargo` available again.
