### ISSUE TITLE
Command failed: make -C worker flatc

### ISSUE THREAD

**Issue by Sansuihe** [versatica/mediasoup#1219]
I failed to execute npm install in your November 15, 2023 version。Here is my error message, I am using the M1 chip of node18 mac。

A fallback URL could be specified using source_fallback_url key in the wrap file

meson.build:198:18: ERROR: Incorrect hash for source:
 4208129b49006089ba1d6710845a45e31c59b0ab6bff9e5788a87f55c5abd602 expected
 4677df57af9322eaad12b351de43c5c120aeca694ca8e77784892ca36529fada actual.

A full log can be found at /Users/Desktop/sansui/webrtc/mediasoup-3/worker/out/Release/build/meson-logs/meson-log.txt
make: *** [setup] Error 1
npm-scripts [ERROR] [prepare] executeCmd() failed, exiting: Error: Command failed: make -C worker flatc
npm ERR! code 1
npm ERR! path /Users/yingxianghe/Desktop/sansui/webrtc/mediasoup-3
npm ERR! command failed
npm ERR! command sh -c node npm-scripts.mjs prepare

I thought it was a problem with my machine and I tried to fix it for a long time, but I found that I had placed a version of your history and they all worked fine。

**Comment by nazar-pc** [comment]
Sometimes happens when GitHub returns garbage instead of zip file, try again and post on the forum next time.
