### ISSUE TITLE
Add full client+server multi-browser integration testing

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#123]
For mediasoup 2.0 (in which we'll have [mediasoup-client](https://github.com/versatica/mediasoup-client) we need a full integration testing environment to test different browsers joining a mediasoup room.

**Comment by ibc** [comment]
Some resources:

* [W3C WebDriver](https://w3c.github.io/webdriver/webdriver-spec.html)
* [Bringing automated testing to Microsoft Edge through WebDriver](https://blogs.windows.com/msedgedev/2015/07/23/bringing-automated-testing-to-microsoft-edge-through-webdriver/)
* [Selenium, Travis-CI and WebRTC ](https://blog.andyet.com/2015/07/28/selenium-travis-webrtc/)

**Comment by fippo** [comment]
add karma to the list of resources. For single-browser tests I found it much more reliable than selenium ;-)

**Comment by ibc** [comment]
Annotated :)

**Comment by lgrahl** [comment]
A bit outdated but still useful: https://github.com/nplab/WebRTC-Data-Channel-Playground

**Comment by ibc** [comment]
Unfortunately there is no DataChannel support in mediasoup yet :(

**Comment by grahamtallen** [comment]
Probably saw this already, but just in case: https://www.cosmosoftware.io/publications/andre2018_Comparative_Study_of_SFUs.pdf

Thank you all for making an incredibly useful library; this has some of the best support and maintenance I've seen in an open-sourced project.

**Comment by ibc** [comment]
Yeah, we have it in the mediasoup website: https://mediasoup.org/documentation/publications/ :)

Thanks a lot.

**Comment by ibc** [comment]
Maybe tomorrow.
