### ISSUE TITLE
Not able to run, getting error as  Unexpected token '??=' in Router.js

### ISSUE THREAD

**Issue by technicalbirdVayuz** [versatica/mediasoup#1232]
I need to update in manually to get this up & running. Using the Meteor project to run this

Not able to run it on Production

Getting issue here,

 if (webRtcServer) {
            enableUdp ??= true;
            enableTcp ??= true;
        }
        else {
            enableUdp ??= true;
            enableTcp ??= false;
        }

**Comment by ibc** [comment]
As documented in the Installation section in the website, Node >= 16 is needed, and Node >= 16 supports the above syntax perfectly. So no issue here. 

Please use the forum if you want to comment something else about your problem (but it's not a bug in mediasoup).
