### ISSUE TITLE
Hown many peer connect in a time 

### ISSUE THREAD

**Issue by gmchaturvedi1** [versatica/mediasoup#124]
Dear Friends,

i am very new to webrtc and serching the correct one. can u please suggest me how many concurrent connection can be handled with this .

Reagrds
gmchaturvedi

> Please, do NOT open an issue if you have problems or questions regarding the use of mediasoup. Use the mediasoup Google Group instead:
> 
> https://groups.google.com/forum/#!forum/mediasoup
> 
> If you have found a bug in the software, or want to propose a new well documented feature or improvement, please delete this text and continue. :)

**Comment by ibc** [comment]
As the text note you ignored above, please use the mailing list for questions.
