### ISSUE TITLE
Inconsistency between fbs and worker

### ISSUE THREAD

**Issue by ybybwdwd** [versatica/mediasoup#1246]
In request.fbs, the `Request.handler_id` is required,
```
table Request {
    id: uint32;
    method: Method;
    handler_id: string (required);
    body: Body;
}
```
but in worker `ChannelRequest::ChannelRequest():110` checks if the field exists
```cpp
// Handler ID is optional.
if (flatbuffers::IsFieldPresent(this->data, FBS::Request::Request::VT_HANDLERID))
{
	this->handlerId = this->data->handlerId()->str();
}
```

**Comment by ibc** [comment]
@jmillan I think we can safely remove that check in `Worker.cpp`, right?

**Comment by jmillan** [comment]
Yep, that check can be removed.

EDIT: I'm quite sure, but needs to be checked.

**Comment by ibc** [comment]
Same applies to `ChannelNotification.cpp`. On it.
