### ISSUE TITLE
Add stream NTP timestamp access to the Node API

### ISSUE THREAD

**Issue by GithubUser8080** [versatica/mediasoup#1248]
## Feature Request

I would like to request, if possible, an API for accessing an RTP stream's wallclock information, for server side inter-stream synchronization.

This could be either 

- A getSenderReport() method in a producer (i am aware that SimulcastConsumer uses this to synchronize between streams of the same producer, this is a similar use case but for streams of different producers).
- A method that just returns a relation of NTP/RTP for a producer, or anything simpler to implement. 

Consumers already have a ProducerRtcpSenderReport event listener so exposing this as a node event too would be great and suffice. Thanks

**Comment by jmillan** [comment]
Something similar to [this](https://github.com/versatica/mediasoup/blob/v3/worker/src/RTC/Producer.cpp#L1598) could be done where the `RecvRtpStream` calls a new `listener->OnRtpStreamRtcpPacket()` method when it receives a Sender Report, which in turn would emit the corresponding `trace` event.

Fill free to make PR.

**Comment by GithubUser8080** [comment]
Thanks, i will try once i familiarize myself with the codebase. In the meantime, would you say that the Date.now() upon receiving 'rtp' consumer event (via DirectTransport) minus the producer roundTripTime would be a decent approximation of the packet wallclock time?

**Comment by jmillan** [comment]
> In the meantime, would you say that the Date.now() upon receiving 'rtp' consumer event (via DirectTransport) minus the producer roundTripTime would be a decent approximation of the packet wallclock time?

I would lie if told you it is. That's something you should try, sorry.

**Comment by jmillan** [comment]
Done.
