### ISSUE TITLE
Worker build fails on Fedora 26 using package manager's `gcc 7` due to inconsistent output of `gcc -dumpversion`

### ISSUE THREAD

**Issue by kaustavdm** [versatica/mediasoup#125]
Using Fedora 26 x86-64, gcc 7.1.1, python 2.7.13, with all dependencies satisfied, I tried installing mediasoup using `npm` by doing `npm install mediasoup --save` and kept hitting this error:

```
 mediasoup@1.2.8 postinstall /home/foo/projectroot/node_modules/mediasoup
> make Release

cd worker && /usr/bin/python2 ./scripts/configure.py -R mediasoup-worker
Traceback (most recent call last):
  File "./scripts/configure.py", line 80, in <module>
    (major, minor), is_clang = compiler_version()
ValueError: need more than 1 value to unpack
make: *** [Makefile:19: Release] Error 1
```

I went looking under the hood. Turns out the error is due to inconsistent output of `cc -dumpversion`.  

I'm neither much acquainted with mediasoup codebase nor am I an expert in `gcc`, but from what I saw (and found), calling `cc -dumpversion` has inconsistent output across some distros and `gcc` versions. This is a [known issue](https://bugzilla.redhat.com/show_bug.cgi?id=1441594) and there is a [workaround](https://stackoverflow.com/questions/45168516/gcc-7-1-1-on-fedora-26-dumpversion-now-only-includes-major-version-by-default). Here is what I get:

```
$ cc -dumpversion
7
$ cc -dumpfullversion
7.1.1
```
As a result, `compiler_version()` in `./worker/scripts/configure.py` returns `((7,), False)` and hence the error.

So, question is, does it make sense to use `cc -dumpfullversion` if `cc`'s `major` is `>= 7`? Will this affect anything internal? I saw a few instances of `-dumpversion` in the code.

Apologies for the rather verbose subject line.

**Comment by kaustavdm** [comment]
FWIW, using `clang` avoids this for me and successfully installs `mediasoup` on same machine. Adding details here for further details (and for my future self)

```
$ export CC=/usr/bin/clang
$ export CXX=/usr/bin/clang++
$ npm install mediasoup --save
```

**Comment by ibc** [comment]
Thanks for the report. Indeed something that must be fixed.

So the problem here is that whether we must use `-dumpversion` or `-dumpfullversion` depends on whether we are using `gcc` or `clang`. The `configure.py` script knows that (we are `gcc` or `clang` before checking the CC version, [here](https://github.com/versatica/mediasoup/blob/master/worker/scripts/configure.py#L39), so some Python code should be added before line 39. Pseudo-code:

```
// Detect whether we are gcc or clang:
is_clang = 'clang' in proc.communicate()[0].split('\n')[0]

// Get the MAYOR version:
proc = subprocess.Popen(CC.split() + ['-dumpversion'], stdout=subprocess.PIPE)
// Here we must be ready to deal with "7", or "5.1.1", etc, so mayor_version must result in
// 7 or 5
mayor_version = proc.communicate()[0].xxxx // TODO: no idea about Python, sorry

// If clang of gcc < 7 use dumpversion:
if (is_clang || (mayor_version < 7) {
  proc = subprocess.Popen(CC.split() + ['-dumpversion'], stdout=subprocess.PIPE)
}
// If clang >= 7 use dumpfullversion:
else {
  proc = subprocess.Popen(CC.split() + ['-dumpfullversion'], stdout=subprocess.PIPE)
}
```

However I don't know Python (the `configure.py` was a contribution of @saghul). If you know Python, may you please send a PR implementing the above code?

**Comment by kaustavdm** [comment]
I'll take a stab at in a day or two :-)

**Comment by ibc** [comment]
Hi @kaustavdm, any news about this?

**Comment by kaustavdm** [comment]
Oops. Sorry got caught up with work and forgot about this. Can anyone else take it up?

**Comment by ibc** [comment]
We don't have Fedora so we will need to wait for Debian to include more modern versions of gcc before we fix it.
