### ISSUE TITLE
500+ receiver server generate sdp offer issue

### ISSUE THREAD

**Issue by touch0day** [versatica/mediasoup#126]
test information:
one sender,500+ receiver 
the issue:
the lasts receivers can't receive media stream, but the receivers have received is ok
chrome console error info
Failed to parse SessionDescription. a=ssrc:2002 msid Failed to get the ssrc attribute value from msid. Expected format <attribute>:<value>.
sdp info
v=0
o=mediasoup  69002535  1  IN  IP4  0.0.0.0
s=-
t=0  0
a=ice-lite
a=fingerprint:sha-256  5E:D5:52:BB:F7:E1:50:FE:65:86:53:E1:2B:3E:D8:16:EC:2A:ED:FE:81:20:DE:A6:49:BB:37:5B:20:31:0F:53
a=msid-semantic:  WMS  *
a=group:BUNDLE  audio-tracks  video-tracks
m=audio  7  RTP/SAVPF  100
c=IN  IP4  127.0.0.1
a=rtpmap:100  opus/48000/2
a=fmtp:100  minptime=10;useinbandfec=1
a=extmap:1  urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=setup:actpass
a=mid:audio-tracks
a=sendrecv
a=ice-ufrag:fyc5zp3mzshws831
a=ice-pwd:gfd6wi83ot6tppcixsubtb98ta72qetv
a=candidate:udpcandidate  1  udp  1078862079  116.62.170.38  15759  typ  host
a=candidate:tcpcandidate  1  tcp  1078862079  116.62.170.38  15646  typ  host  tcptype  passive
a=end-of-candidates
a=ice-options:renomination
a=ssrc:2002  cname:4vfvcngrhu
a=ssrc:2002  msid
a=ssrc:4288191983  cname:vKpysaRWm69mpvvK
a=ssrc:4288191983  msid:OTWeiER5T07ZxBRhtZBGynu02uCBC3dk8Pyp  2bbb2769-3923-4e14-8198-7c9b1343d8da
a=rtcp-mux
a=rtcp-rsize
m=video  7  RTP/SAVPF  123  101
c=IN  IP4  127.0.0.1
a=rtpmap:123  VP8/90000
a=rtpmap:101  rtx/90000
a=fmtp:101  apt=123
a=rtcp-fb:123  ccm  fir
a=rtcp-fb:123  nack
a=rtcp-fb:123  nack  pli
a=rtcp-fb:123  goog-remb
a=extmap:2  urn:ietf:params:rtp-hdrext:toffset
a=extmap:3  http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4  urn:3gpp:video-orientation
a=setup:actpass
a=mid:video-tracks
a=sendrecv
a=ice-ufrag:fyc5zp3mzshws831
a=ice-pwd:gfd6wi83ot6tppcixsubtb98ta72qetv
a=candidate:udpcandidate  1  udp  1078862079  116.62.170.38  15759  typ  host
a=candidate:tcpcandidate  1  tcp  1078862079  116.62.170.38  15646  typ  host  tcptype  passive
a=end-of-candidates
a=ice-options:renomination
a=ssrc:3570052871  cname:vKpysaRWm69mpvvK
a=ssrc:3570052871  msid:OTWeiER5T07ZxBRhtZBGynu02uCBC3dk8Pyp  09bb7989-32e1-4685-b369-7091d0d761d1
a=ssrc:1806549032  cname:vKpysaRWm69mpvvK
a=ssrc:1806549032  msid:OTWeiER5T07ZxBRhtZBGynu02uCBC3dk8Pyp  09bb7989-32e1-4685-b369-7091d0d761d1
a=ssrc-group:FID  3570052871  1806549032
a=rtcp-mux
a=rtcp-rsize

**Comment by ibc** [comment]
In mediasoup v2 the SDPs will be just generated and handled in client side by [mediasoup-client](https://github.com/versatica/mediasoup-client), so this issue should not happen.

**Comment by jmillan** [comment]
@touch0day, out of curiosity, did you get any further in your troubleshooting?

**Comment by ibc** [comment]
This won't be a problem in mediasoup v2 anymore, so let's close this issue.
