### ISSUE TITLE
Windows CI jobs failing due to meson

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#1292]
## Bug Report

https://github.com/versatica/mediasoup/actions/runs/7395922187/job/20120052331?pr=1291

In summary:

```
"C:\hostedtoolcache\windows\Python\3.9.13\x64\python3.exe" -m pip install --upgrade --no-user --target="D:\a\mediasoup\mediasoup\worker/out/pip_meson_ninja"  meson==1.3.0 ninja==1.10.2.4
Collecting meson==1.3.0

  Using cached meson-1.3.0-py3-none-any.whl.metadata (1.8 kB)

Collecting ninja==1.10.2.4

  Using cached ninja-1.10.2.4-py2.py3-none-win_amd64.whl (293 kB)

Using cached meson-1.3.0-py3-none-any.whl (976 kB)

Installing collected packages: ninja, meson

Successfully installed meson-1.3.0 ninja-1.10.2.4

cd D:\a\mediasoup\mediasoup\worker && "D:\a\mediasoup\mediasoup\worker/out/pip_meson_ninja/bin/meson" setup --prefix "D:\a\mediasoup\mediasoup\worker/out/Release" --bindir "" --libdir "" --buildtype release -Db_ndebug=true -Db_pie=true -Db_staticpic=true --vsenv "D:\a\mediasoup\mediasoup\worker/out/Release/build"
Directory already configured.


Just run your build command (e.g. ninja) and Meson will regenerate as necessary.

Run "meson setup --reconfigure to force Meson to regenerate.


If build failures persist, run "meson setup --wipe" to rebuild from scratch

using the same options as passed when configuring the build.


ERROR: Unknown options: "b_pie, b_staticpic"

npm-scripts.mjs [ERROR] [prepare] executeCmd() failed, exiting: Error: Command failed: "python3" -m invoke -r worker flatc
npm ERR! code 1
npm ERR! path D:\a\mediasoup\mediasoup
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node npm-scripts.mjs prepare
```

We may want to happily blame this recent merged PR https://github.com/versatica/mediasoup/pull/1275 but it wouldn't be fair since it did pass all CI jobs and they also passed in more recent PRs and changes in v3 branch. This is something new. New meson version in Windows?

**Comment by nazar-pc** [comment]
Error is quite clear:
> ERROR: Unknown options: "b_pie, b_staticpic"

Just need to find out where it comes from and why it worked before (maybe it was something deprecated that we still used historically)

**Comment by ibc** [comment]
In https://mesonbuild.com/Builtin-options.html#base-options:

> The following options are available. Note that they may not be available on all platforms or with all compilers:
> [...]
> - b_staticpic: Build static libraries as position independent
> - b_pie: Build position-independent executables (since 0.49.0)

I'm pretty sure we need at least one of them to avoid problems with some deps/subprojects.

**Comment by ibc** [comment]
> I'm pretty sure we need at least one of them to avoid problems with some deps/subprojects.

https://github.com/versatica/mediasoup/issues/315

**Comment by ibc** [comment]
I'm gonna try to remove both args and see.
