### ISSUE TITLE
Very low bandwidth in Android Chrome

### ISSUE THREAD

**Issue by thehappycoder** [versatica/mediasoup#133]
To reproduce: Publish video from Android Chrome and from Android firefox from the same device and at the same network / spot.

Result: After 5-10 seconds of video transmission, bandwidth in Chrome will get very low whereas in Firefox it will be 4 times greater.

This doesn't happen in Desktop Chrome.

**Comment by ibc** [comment]
In Android you cannot send video from two tabs or two browsers at the same time. In fact, if the browser tab does not have the focus it stops sending video.

**Comment by thehappycoder** [comment]
@ibc I didn't do it at the same time

**Comment by ibc** [comment]
This cannot depend on mediasoup itself. mediasoup does not limit the sending bitrate of remote senders. However, it uses REMB to send bandwidth estimations to the senders.

Whether a browser decides to decrease its sending bitrate depends on the REMB values received by mediasoup and the number of packetloss reported in RTCP Receiver Report generated by mediasoup.

Said that, I just cannot know why your Android Chrome is sending less than Firefox in same circumstances.

**Comment by thehappycoder** [comment]
This may be due to docker bug. I'll also try disabling REMB. I'll test more and get back to you.

**Comment by thehappycoder** [comment]
After disabling goog-remb, video publisher went nuts. The bandwidth had been increasing to unlimited value and then it started getting lots of nacks and video freezed.

So basically, publishing video from mobile device is not working for me with mediasoup at the moment. I'll create google group thread.

**Comment by ibc** [comment]
We are doing lot of stuff regarding simulcast and many other improvements and refactoring in v2:

https://github.com/versatica/mediasoup/issues/134#issuecomment-328928285

Let's please wait for v2.
