### ISSUE TITLE
Local stream hiccups after flipping camera

### ISSUE THREAD

**Issue by thehappycoder** [versatica/mediasoup#134]
In Google Chrome on Android when user flips camera (say, from front to back), the local stream pauses from time to time a lot. It also seem to be affecting the reception of this stream on the server side.

This does not happen when publishing video from desktop Chrome.

In Firefox I can't even flip the camera for some reason. Looks like it doesn't detect the 2nd camera.

**Comment by ibc** [comment]
We are working on mediasoup v2 which changes absolutely everything.

* https://github.com/versatica/mediasoup/tree/v2
* https://github.com/versatica/mediasoup/milestone/2

Even more, mediasoup v2 comes with a [mediasoup-client](https://github.com/versatica/mediasoup-client) library for browsers that provides a simple, cross-browser and powerful JS API to send and receive media, including the ability to dynamically switch tracks, simulcast, etc.

Said that, I recommend you waiting a bit (a few weeks) for mediasoup v2 as we are not maintaining v2 anymore.

**Comment by thehappycoder** [comment]
Thanks @ibc I'll try it out.

I don't need simulcast though, as it will waste extra traffic. My main use case is publishing video from phone connected to 3g.

**Comment by thehappycoder** [comment]
@ibc Still an issue in v2. I just checked.

**Comment by ibc** [comment]
We don't do extensive tests in mobile browsers. Have you tested other SFUs or media servers in mobile browsers? how do they behave?

**Comment by thehappycoder** [comment]
Yes, Licode, for example, is optimised to run on 3g with significantly
better experience.

**Comment by ibc** [comment]
You can limit REMB for mobile clients, wouldn't that work?

**Comment by thehappycoder** [comment]
I disabled goog-remb by removing it from capabilities. This resulted in
available bandwidth growing indefinitely while stream got stuck at some
point.

I know one person did that in Licode but his stream didn't get stuck.

Is there anything else that can be done as a workaround?

**Comment by ibc** [comment]
I don't know why you disable REMB. What I mean is "limit what REMB reports" so the browser will not send more than that:

* https://mediasoup.org/api/#transport-setMaxBitrate

**Comment by thehappycoder** [comment]
I set max bitrate to 1000 kbps from the start. The problem was that with
this limit on 3g which had about 330 max upload, mediasoup starts on sender
side was showing available bandwidth of around 100kbps.

I also noticed that mediasoup doesn't use b=AS: in sdp whereas Licode does.
