### ISSUE TITLE
set MS_LOG_DEV_LEVEL 3, lead to build errors

### ISSUE THREAD

**Issue by adcen0107** [versatica/mediasoup#1360]
### Your environment
- Operating system: ubuntu22.04
- Node version:v18.19.1
- npm version:10.2.4
- gcc/clang version:gcc version 11.4.0
- mediasoup version: 3.13.24
- mediasoup-client version:

### Issue description
at Logger.hpp set 	#define MS_LOG_DEV_LEVEL 3
then 
cd worker
make
------------------------------
got error, some info below:
  228 |           MS_DEBUG_DEV("arrival_time_ms - first_arrival_time_ms_:%f, smoothed_delay_:%f", kv.first, kv.second);
      |                                                                                              ^~~~~
../../../include/Logger.hpp:298:143: note: in definition of macro ‘MS_DEBUG_DEV’
  298 |                         const int loggerWritten = std::snprintf(Logger::buffer, Logger::BufferSize, "D" _MS_LOG_STR_DESC desc, _MS_LOG_ARG, ##__VA_ARGS__); \
      |                                                                                                                                               ^~~~~~~~~~~
../../../deps/libwebrtc/libwebrtc/modules/congestion_controller/goog_cc/trendline_estimator.cc:228:104: error: ‘struct webrtc::TrendlineEstimator::PacketTiming’ has no member named ‘second’
  228 |           MS_DEBUG_DEV("arrival_time_ms - first_arrival_time_ms_:%f, smoothed_delay_:%f", kv.first, kv.second);
----------------------------------------
trendline_estimator.cc  
source code below:

#if MS_LOG_DEV_LEVEL == 3
        for (auto& kv : delay_hist_) {
          MS_DEBUG_DEV("arrival_time_ms - first_arrival_time_ms_:%f, smoothed_delay_:%f", kv.first, kv.second);
        }
#endif

**Comment by ibc** [comment]
Thanks, fixed.
