### ISSUE TITLE
#define MS_LOG_DEV_LEVEL 3, build error

### ISSUE THREAD

**Issue by adcen0107** [versatica/mediasoup#1361]
Your environment
Operating system: ubuntu22.04
Node version:v18.19.1
npm version:10.2.4
gcc/clang version:gcc version 11.4.0
mediasoup version: 3.13.24
mediasoup-client version:
Issue description
at Logger.hpp set #define MS_LOG_DEV_LEVEL 3
then
cd worker
make
-----------------------------
In file included from ../../../src/RTC/SctpAssociation.cpp:6:
../../../src/RTC/SctpAssociation.cpp: In member function ‘void RTC::SctpAssociation::SendSctpMessage(RTC::DataConsumer*, const uint8_t*, size_t, uint32_t, RTC::SctpAssociation::onQueuedCallback*)’:
../../../src/RTC/SctpAssociation.cpp:463:35: error: expected ‘)’ before ‘sctp’
  463 |                                   sctp,
      |                                   ^~~~
../../../include/Logger.hpp:298:122: note: in definition of macro ‘MS_DEBUG_DEV’
  298 |                         const int loggerWritten = std::snprintf(Logger::buffer, Logger::BufferSize, "D" _MS_LOG_STR_DESC desc, _MS_LOG_ARG, ##__VA_ARGS__); \
      |                                                                                                                          ^~~~
../../../include/Logger.hpp:298:64: note: to match this ‘(’
  298 |                         const int loggerWritten = std::snprintf(Logger::buffer, Logger::BufferSize, "D" _MS_LOG_STR_DESC desc, _MS_LOG_ARG, ##__VA_ARGS__); \
      |                                                                ^
../../../src/RTC/SctpAssociation.cpp:462:33: note: in expansion of macro ‘MS_DEBUG_DEV’
  462 |                                 MS_DEBUG_DEV(

**Comment by ibc** [comment]
Thanks, fixed.
