### ISSUE TITLE
arm64 prebuilt binaries are replacing x64 ones

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#1372]
### Details

- This PR added worker prebuilt binaries for arm64: https://github.com/versatica/mediasoup/pull/1363
- And those prebuilt binaries are being generated, however they generate a name with `x64` rather than `arm64` so they are **replacing** the x64 binaries!!!  
  ![CleanShot-2024-04-09-at-19 06 05@2x](https://github.com/versatica/mediasoup/assets/16191/ee0e966c-9b4f-449e-b07f-145ce40b4c1f)
- See the resulting binaries: https://github.com/versatica/mediasoup/releases

This is the Node code we use to generate the file name of each worker prebuilt binary (in `npm-scripts.mjs`):

```ts
function getWorkerPrebuildTarName() {
	let name = `mediasoup-worker-${PKG.version}-${os.platform()}-${os.arch()}`;

	// In Linux we want to know about kernel version since kernel >= 6 supports
	// io-uring.
	if (os.platform() === 'linux') {
		const kernelMajorVersion = Number(os.release().split('.')[0]);

		name += `-kernel${kernelMajorVersion}`;
	}

	return `${name}.tgz`;
}
```

According to Node docs, [os.arch()](https://nodejs.org/api/os.html#osarch) should return one of these values:

> 'arm', 'arm64', 'ia32', 'loong64', 'mips', 'mipsel', 'ppc', 'ppc64', 'riscv64', 's390', 's390x', and 'x64'

However, in GitHub CI, despite we add `arch: arm64` in the matrix, the machines running the CI action report `os.arch() => 'x64'`.

**Comment by ibc** [comment]
CC @arcinston

**Comment by arcinston** [comment]
https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/

turns out GitHub arm64 runners are in private beta

as soon as they are out in public 
this workflow should work as expected 

I did not know of this before hand and for that I am extremely sorry 

there is no harm currently as the current "arm64" is actually x64 runners
hence should not cause any trouble

**Comment by ibc** [comment]
I see. Thanks for the explanation. Ok, I'll disable them for now: https://github.com/versatica/mediasoup/issues/1372

**Comment by nazar-pc** [comment]
> this workflow should work as expected

I don't think so, `arch` option in the matrix is not used anywhere anyway.

**Comment by ibc** [comment]
Given that there is zero evidence that the syntax will be `arch: arm64` I've finally removed those entries entirely in all matrixes. Will be added back once ARM64 support becomes public in CI.
