### ISSUE TITLE
RtpPacket::SetPayloadLength get wrong payloadLength

### ISSUE THREAD

**Issue by Lynnworld** [versatica/mediasoup#1379]
Hi,
this method padding length to 4 bytes, however it change ```real payloadLength```  and remove padding flags , is that the correct ?
I thing we should check padding length is the same as orig length, if padding happen then set padding flag to true and set padding byte to padding length.

```
void RtpPacket::SetPayloadLength(size_t length)
	{
		MS_TRACE();

		// Pad desired length to 4 bytes.
		length = static_cast<size_t>(Utils::Byte::PadTo4Bytes(static_cast<uint16_t>(length)));

		this->size -= this->payloadLength;
		this->size -= size_t{ this->payloadPadding };
		this->payloadLength  = length;
		this->payloadPadding = 0u;
		this->size += length;

		SetPayloadPaddingFlag(false);
}
```

[https://github.com/versatica/mediasoup/blob/d6373d540751c06b7fb96f0e7e26ad56f50f25bd/worker/src/RTC/RtpPacket.cpp#L653](url)

**Comment by ibc** [comment]
Yes, the API is a bit unfortunate. Improving it here: https://github.com/versatica/mediasoup/pull/1380

**Comment by ibc** [comment]
Finally this is not gonna done that way. All methods in `RtpPacket` will remove padding if present. Rationale in the PR.
