### ISSUE TITLE
Add interface for RTC::Shared, Channel::ChannelNotifier and ChannelMessageRegistrator

### ISSUE THREAD

**Issue by o-u-p** [versatica/mediasoup#1399]
## Feature Request
this will make code more readable and flexible.

**Comment by ibc** [comment]
I don't know what this is about. Please specify much more hopefully with real code snippets.

**Comment by o-u-p** [comment]
for example, we can make "void ChannelNotifier::Emit(const std::string& targetId, FBS::Notification::Event event)" to be an interface, and can define some custom implement to send flatbuffer. that will be more flexible.

**Comment by ibc** [comment]
Please, feel free to write a PR proposal. Honestly we are too busy and won't have time to investigate this.
