### ISSUE TITLE
[Rust] Transport with only audio producer results in server-side transport cc is not created.

### ISSUE THREAD

**Issue by mstyura** [versatica/mediasoup#1400]
## Bug Report

`WebRtcTransport` with only audio producer with enabled transport congestion control results in transport CC is not actually enabled on server side, i.e. `Transport::tccServer` is `nullptr`

### Your environment

- Operating system: -
- Node version: -
- npm version: -
- gcc/clang version: -
- mediasoup version: v3.13.24
- mediasoup-client version: -

#### Steps to reproduce:
1. Run `rust/examples/echo`
2. Edit `rust/examples-frontend/echo/src/index.ts` to disable video and hence video producer
3. Run `rust/examples-frontend/echo`
4. Open echo app in browser `http://localhost:3001/`

#### Actual result:
Bitrate of sent audio is started at high values and drops to minimum allowed by webrtc (16Kb/s).
<img width="309" alt="image" src="https://github.com/versatica/mediasoup/assets/385639/37c25318-98be-40e5-ad1f-8761050d95ae">

#### Expected result:
Bitrate of sent audio is depend on actual network bandwidth available.

**Comment by ibc** [comment]
Please paste the browser side SDP after creating the audio Producer and also the RtpParameters given to transport.produce() in server side.

**Comment by mstyura** [comment]
I've found an issue and will provide MR with fix, this was just a justification issue to link with MR.
