### ISSUE TITLE
Video software encoding Quality Limitation vs hardware encoding

### ISSUE THREAD

**Issue by jeffery30162** [versatica/mediasoup#1405]
Hello, when I use software encoding VP8/VP9 vs Hardware H264, I'm experiencing qualityLimitationReason: Bandwidth limitation.

Both streams have the same everything: resolution, framerate, ProducerOptions, etc. The only difference is one is H264 and the other VP8.
H264 works perfectly, VP8 after a minute or so (seems random) the stream quality is severely reduced with the qualityLimitationReason: "Bandwidth".

Both are running on the same system (7950x | 128gb ram | 6900xt). I've tried on both Electron and Edge browser.

Could this be an issue with the server or client? What could it be? 

Thanks for your time

**Comment by nazar-pc** [comment]
For questions like this please use forum rather than GitHub: https://mediasoup.discourse.group
