### ISSUE TITLE
Ci tests fail consistently in Windows (Node and Rust)

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#1407]
Nothing changed in related source code, it's just that CI tests in Windows (Node and Rust) started failing, so this is probably due to some change/update in the Windows version or its tools in CI hosts.

- Windows Node tests failing: https://github.com/versatica/mediasoup/actions/runs/9445664600/job/26013737283
- Windows Rust tests failing: https://github.com/versatica/mediasoup/actions/runs/9445911963/job/26014463237

**Comment by ibc** [comment]
Good news @nazar-pc! This issue auto-fixed itself.

**Comment by nazar-pc** [comment]
Good news, sure, but do you have an idea why? :joy:

**Comment by ibc** [comment]
> Good news, sure, but do you have an idea why? 😂

We don't know why it broke and we don't know why it auto-fixed itself. So we are good (meaning that it will eventually happen again and we'll have no idea, but that's ok).

**Comment by satoren** [comment]
@ibc 
Since the test code previously contained undefined behavior, it is not surprising that errors occur depending on the randomness and environment. Why not run tests with CI with various sanitizers enabled?

**Comment by ibc** [comment]
> @ibc Since the test code previously contained undefined behavior, it is not surprising that errors occur depending on the randomness and environment. Why not run tests with CI with various sanitizers enabled?

You mean compiling mediasoup-worker with address sanitizer and so on and run Node and Rust tests that way?

**Comment by satoren** [comment]
Yes. 

We can also confirm that the test fails when run with address sanitizer enabled in Node tests.
https://github.com/satoren/mediasoup/actions/runs/9545217751/job/26305515808?pr=2

You can try this by simply setting a few environment variables.
https://github.com/satoren/mediasoup/pull/2/files#diff-8ef8d7b717d737ed620a4153e34a3d1f8240b4544d09ccd7d284b6ebfa594d35R21

**Comment by satoren** [comment]
It seems that sanitizer interferes with SIGNAL, so the error may be due to that.

**Comment by ibc** [comment]
```yamls
asan_option: 'detect_leaks=0' # Disable leak detection because detect memory leaks in flatbuffers tool.
```

Which memory leak issue in flatbuffers?

> It seems that sanitizer interferes with SIGNAL, so the error may be due to that.

Then we should include some `env` in matrix entries using sanitizer to avoid running that test.

**Comment by satoren** [comment]
> Which memory leak issue in flatbuffers?

The `flatc` to be used for the build. This is really noise.
https://github.com/satoren/mediasoup/actions/runs/9540178305/job/26291556482#step:5:1857

**Comment by ibc** [comment]
Related: https://github.com/versatica/mediasoup/pull/1416
