### ISSUE TITLE
libsrtp: wraparound with loss decryption failure

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#1437]
Rationale in the ticket: https://webrtc-review.googlesource.com/c/src/+/358360

Theoretical solution is that the first **output** seq number of each mediasoup `XxxxConsumer` is not 0 or 1 (to avoid that a previous packet arriving later triggers the bug in libsrtp) and it's smaller than 2^15.

**Comment by fippo** [comment]
does your sequence number mapper handle this case "correctly":
* map(5) -> 5
* map(4) -> 4
I always assumed one would not have to bother with 4 in this case since it is too old but...

**Comment by ibc** [comment]
> does your sequence number mapper handle this case "correctly":
> 
> * map(5) -> 5
> 
> * map(4) -> 4
> 
> I always assumed one would not have to bother with 4 in this case since it is too old but...

There are like 10000 tests covering that case and more complex ones in TestSeqManager.cpp.
