### ISSUE TITLE
Implement getRoom(room.id)

### ISSUE THREAD

**Issue by Globik** [versatica/mediasoup#144]
Is there any chance to implement a method such like: server.getRoom(room.id)?
Say I wanna create three or more rooms and don't want to store room instances in a map or set objects.
I see in a module already there is new Set for the room instances.

**Comment by ibc** [comment]
How do you know the `room.id` if you don't store the `room`?

**Comment by Globik** [comment]
In line 65 I see new Set for room instances:
https://github.com/versatica/mediasoup/blob/master/lib/Worker.js

**Comment by ibc** [comment]
`Room` instances are indeed stored in a `Set` within the `Worker.js` file (which represents a mediasoup-worker subprocess there can be many of them). 

I don't want to also keep a map of `Room` instances in the `Server.js` class. Note that, `Server.createRoom()` just returns a `Room` instance generated by a random `Worker`.

It shouldn't be so hard for the Node.js app to keep a map of rooms. In fact, you will need also a map for the "signaling room" (whichever you use), etc. So I don't think `server.getRoomById()` would provide too much help.

BTW we are working on [mediasoup v2](https://github.com/versatica/mediasoup/milestone/2) which  comes with a [mediasoup-client](https://github.com/versatica/mediasoup-client) SDK for client side, so expect LOT of changes (basically you won't need to deal with `RTCPeerConnection` in browser side anymore).

**Comment by Globik** [comment]
Oh, I see, thanx for a clarification.
