### ISSUE TITLE
Stop signing certificates with SHA1

### ISSUE THREAD

**Issue by fippo** [versatica/mediasoup#1447]
[This uses SHA-1](https://github.com/versatica/mediasoup/blob/3604b1e983350c0fa9bc95621530f42e487bdd1f/worker/src/RTC/DtlsTransport.cpp#L418C9-L418C18)
```
ret = X509_sign(DtlsTransport::certificate, DtlsTransport::privateKey, EVP_sha1());
```
to sign the self-signed certificate. SHA-1 is on its way out but this is *not* the usage in SDP that we are tracking [in Chromium](https://issues.webrtc.org/issues/42225856)

Be as cool as ~@lminiero~ @tgabi333, [use EVP_SHA256](https://github.com/meetecho/janus-gateway/blob/bae9c51982835c2d745dbe38a80eb660ac6a07e1/src/dtls.c#L322)

**Comment by CosmosisT** [comment]
There's maybe ECDSA that could be used.

**Comment by ibc** [comment]
Thanks. PR done here: https://github.com/versatica/mediasoup/pull/1450

@CosmosisT, I have no idea about how to use ECDSA to sign a certificate with OpenSSL and IMHO we don't strictly need it.
