### ISSUE TITLE
Error: [pid:5976, code:3221225477, signal:null]

### ISSUE THREAD

**Issue by Sam15b** [versatica/mediasoup#1449]
I am encountering the following error when i createWorker:
error: [pid:5976, code:3221225477, signal:null]    at ChildProcess.<anonymous> (C:\Users\super\Desktop\Media\node_modules\mediasoup\node\lib\Worker.js:149:43)

Steps Taken:
Deleted node_modules and package-lock.json.
Ran npm install and npm rebuild mediasoup.   To reconfigure the setup

But still i getting error

My Environment : Window 10
      Mediasoup Version:  3.14.13

My Code Snippet:
`const createWorker = async () => {
    const worker = await mediasoup.createWorker();

    console.log(`Worker created with pid: ${worker.pid}`);

    if (worker.createWebRtcServer) {
        const webRtcServer = await worker.createWebRtcServer({
            listenInfos: [
                {
                    protocol: 'udp',
                    ip: '127.0.0.1',
                    portRange: { min: 30000, max: 40000 }
                },
                {
                    protocol: 'tcp',
                    ip: '127.0.0.1',
                    portRange: { min: 30000, max: 40000 }
                }
            ]
        });

        console.log(`WebRtcServer created with id: ${webRtcServer.id}`);
    } else {
        console.error("Error");
    }
}

worker = createWorker()`

I am seeking assistance in diagnosing this error and understanding if it is related to Mediasoup’s configuration or a compatibility issue with my development environment. Any guidance or suggestions would be greatly appreciated.

**Comment by nazar-pc** [comment]
We have forum for questions, GitHub is for actual bugs

**Comment by ibc** [comment]
Code `3221225477` in Windows means memory access issue. It's hard to believe that a memory access issue happens by just running that code above so it must be something else. Unfortunately there are no logs or anything that could help diagnosing it so there is nothing actionable in this potential bug report. Sadly we cannot keep open issues in GH for which there is no possible action so I must close it. If you get relevant extra info proving this is a bug in mediasoup please add a comment here.
