### ISSUE TITLE
Mediasoup TypeScript types are not exported

### ISSUE THREAD

**Issue by agoenks29D** [versatica/mediasoup#1451]
- Operating system: Windows 10
- Node version: v18.18.2
- npm version: 9.8.1
- mediasoup version: 3.14.13

I use Visual Studio Code to develop mediasoup using the Nest.js framework

I created a new branch on my local branch when I installed mediasoup at versions 3.14.12 and 3.14.13. The TypeScript types I had created earlier do not respond when I search for the definitions of the types I have imported
![image](https://github.com/user-attachments/assets/694871a9-1fac-4638-b701-ca84c1f32044)

However, when using version 3.14.11, the TypeScript type definitions work normally
![image](https://github.com/user-attachments/assets/4b5ba60e-3c9c-497c-a7ae-45eb1bd56b2f)

This is the Visual Studio Code profile I am using
https://vscode.dev/profile/github/e56672665350186c037749b2776ba04e

For details on the mediasoup code development I'm working on, you can see my repository here
https://github.com/medansoftware/mediasoup-nest.git

**Comment by ibc** [comment]
Please detail the issue rather than pasting a screenshot. I don't know how your text editor behaves and what it is saying there. Please report the problem properly.
