### ISSUE TITLE
DirectTransport consumer not receiving RTP packets in Rust

### ISSUE THREAD

**Issue by sw-vish** [versatica/mediasoup#1454]
### Your environment

- Operating system: Pop!_OS 22.04 LTS
- clang version: 14.0.0
- gcc version: 11.4.0
- mediasoup version: v3 (rust crate version 0.17.1)

### Issue description

The `.on_rtp` callback for a Consumer created from a DirectTransport never gets called.

```rs
let direct_transport = self.router
    .create_direct_transport(DirectTransportOptions::default())
    .await
    .unwrap();

let options = ConsumerOptions::new(self.producer_id, self.rtp_capabilities);

let consumer = direct_transport
    .consume(options)
    .await
    .unwrap();

// "on_rtp" never gets logged
consumer.on_rtp(|_| info!("on_rtp")).detach();

self.consumers.push(consumer);
```
Looking at the source, it looks like the RTP notification has been commented out: https://github.com/versatica/mediasoup/blob/v3/rust/src/router/consumer.rs#L846.

**Comment by ibc** [comment]
@nazar-pc do you know why that notification is commented in the code?

**Comment by nazar-pc** [comment]
I think it was simply forgotten during conversion to flatbuffers, I don't think it was intentional

**Comment by ibc** [comment]
@nazar I give you the honor to uncomment it and become a hero if you wish
