### ISSUE TITLE
example of consuming Webrtc Media in an External Endpoint (PlainTransport)

### ISSUE THREAD

**Issue by hyc242828** [versatica/mediasoup#1471]
## Feature Request

Could you please provide an example of consuming Webrtc Media in an External Endpoint (PlainTransport) for mediasoup-demo?

**Comment by hyc242828** [comment]
like "https://github.com/versatica/mediasoup-demo/tree/v3/broadcasters", for PlainTransport produce

**Comment by ibc** [comment]
This is not what Feature Requests are for. Please use the mediasoup forum for questions.
