### ISSUE TITLE
DOMException: Failed to execute 'structuredClone' on 'Window': #<Object> could not be cloned

### ISSUE THREAD

**Issue by md-golamrabbani** [versatica/mediasoup#1474]
### I'm using vue js 3

Error
![Screenshot_4](https://github.com/user-attachments/assets/c970890c-ca03-42d6-82a1-2e1f44d2af79)

code
![Screenshot_5](https://github.com/user-attachments/assets/e3cb6d27-18e5-4a25-a855-7069b6489510)
![Screenshot_6](https://github.com/user-attachments/assets/2cbefb4f-259e-4e5c-8607-4159f199d77d)

`

<script>
  import RoomClient from "@/services/meeting";

  export default {
    name: "Toolbar",

    data() {
      return {
        isScreenShare: false,
      };
    },

    props: {
      roomControl: {
        type: Object,
        required: true,
      },
    },

    methods: {
      // screen share
      screenShare() {
        this.roomControl.produceScreenShare(RoomClient.MEDIA_TYPE.screen);
      },
`

meeting.js 
`

  async produceScreenShare() {
    const stream = await navigator.mediaDevices.getDisplayMedia({
      video: true,
    });

    const track = stream.getVideoTracks()[0];
    const params = { track };

    const producer = await this.producerTransport.produce({ params });
    this.producers.set(producer.id, producer);

    const elem = document.createElement("video");
    elem.srcObject = stream;
    elem.id = producer.id;
    elem.playsinline = false;
    elem.autoplay = true;
    elem.className = "vid";
    document.getElementById("meetingUserAdd").appendChild(elem);
    this.handleFS(elem.id);

    producer.on("trackended", () => {
      this.closeProducer(MEDIA_TYPE.screen);
    });

    producer.on("transportclose", () => {
      // console.log("Producer transport close");
      elem.srcObject.getTracks().forEach((track) => track.stop());
      elem.parentNode.removeChild(elem);
      this.producers.delete(producer.id);
    });

    producer.on("close", () => {
      // console.log("Closing producer");
      elem.srcObject.getTracks().forEach((track) => track.stop());
      elem.parentNode.removeChild(elem);
      this.producers.delete(producer.id);
    });

    this.producerLabel.set(MEDIA_TYPE.screen, producer.id);
    this.event(EVENTS.startScreen);
  }
`

I'm working on below git repo, just convert it vue.js that's it.
https://github.com/Dirvann/mediasoup-sfu-webrtc-video-rooms/tree/master

Please, give me a solution. 

Thank you

**Comment by nazar-pc** [comment]
Client-side code is unrelated to this repo, you probably wanted https://github.com/versatica/mediasoup-client instead. But I'd recommend to start with the forum first. Also for anything client-side it'd be helpful to know what browser you're using.

**Comment by ibc** [comment]
Please check closed issues in mediasoup-client GH issues and also in the public forum. This non-real-issue has been discussed multiple times already.
