### ISSUE TITLE
Ignore RTCP XR

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#151]
When there is desktop sharing (with Chrome) it seems that there are RTCP Extended Reports somewhere, producing every one second:

```
mediasoup:WARN:mediasoup-worker [id:zeezuiun#1] RTC::RTCP::Packet::Parse() | error parsing UNKNOWN Packet +0ms
mediasoup:WARN:mediasoup-worker [id:zeezuiun#1] RTC::RTCP::Packet::Parse() | unknown RTCP packet type [packetType:207]
```

Could we just ignore them without logging?

**Comment by fippo** [comment]
this is https://bugs.chromium.org/p/webrtc/issues/detail?id=6301 -- no negotiation, unregistered block type, ...

**Comment by jmillan** [comment]
Interesting.., thanks @fippo
