### ISSUE TITLE
Server crash at creation

### ISSUE THREAD

**Issue by Banou26** [versatica/mediasoup#152]
```
const mediasoup = require('mediasoup')
const server = mediasoup.Server()
server.on('close', error => {
  if (error) console.error(error)
})
```
results in 

> ozvc_1  | Mon, 16 Oct 2017 01:34:45 GMT mediasoup mediasoup version 1.2.8
> ozvc_1  | Mon, 16 Oct 2017 01:34:45 GMT mediasoup Server() [options:undefined]
> ozvc_1  | Mon, 16 Oct 2017 01:34:45 GMT mediasoup:Server constructor() [options:undefined]
> ozvc_1  | Mon, 16 Oct 2017 01:34:45 GMT mediasoup:Worker constructor() [id:gyksgjse#1, parameters:"--rtcMinPort=10000 --rtcMaxPort=34999"]
> ozvc_1  | Mon, 16 Oct 2017 01:34:45 GMT mediasoup:Channel constructor()
> ozvc_1  | Mon, 16 Oct 2017 01:34:45 GMT mediasoup:Worker constructor() [id:gyksgjse#2, parameters:"--rtcMinPort=35000 --rtcMaxPort=59997"]
> ozvc_1  | Mon, 16 Oct 2017 01:34:45 GMT mediasoup:Channel constructor()
> ozvc_1  | Mon, 16 Oct 2017 01:34:45 GMT mediasoup:ERROR:Worker child process error [id:gyksgjse#1, error:Error: spawn /ozvc/src/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker ENOENT]
> ozvc_1  | Mon, 16 Oct 2017 01:34:45 GMT mediasoup:ERROR:Worker close() [error:Error: child process error [id:gyksgjse#1, error:Error: spawn /ozvc/src/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker ENOENT]]
> ozvc_1  | Mon, 16 Oct 2017 01:34:45 GMT mediasoup:Channel close()
> ozvc_1  | Mon, 16 Oct 2017 01:34:45 GMT mediasoup:ERROR:Worker child process error [id:gyksgjse#2, error:Error: spawn /ozvc/src/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker ENOENT]
> ozvc_1  | Mon, 16 Oct 2017 01:34:45 GMT mediasoup:ERROR:Worker close() [error:Error: child process error [id:gyksgjse#2, error:Error: spawn /ozvc/src/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker ENOENT]]
> ozvc_1  | Mon, 16 Oct 2017 01:34:45 GMT mediasoup:Channel close()
> ozvc_1  | Mon, 16 Oct 2017 01:34:45 GMT mediasoup:Server latest Worker closed [error:Error: child process error [id:gyksgjse#2, error:Error: spawn /ozvc/src/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker ENOENT]]
> ozvc_1  | Mon, 16 Oct 2017 01:34:45 GMT mediasoup:ERROR:Server close() [error:Error: child process error [id:gyksgjse#2, error:Error: spawn /ozvc/src/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker ENOENT]]
> ozvc_1  | Error: child process error [id:gyksgjse#2, error:Error: spawn /ozvc/src/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker ENOENT]
> ozvc_1  |     at ChildProcess.Worker._child.on (/ozvc/src/server/node_modules/mediasoup/lib/Worker.js:103:15)
> ozvc_1  |     at emitOne (events.js:115:13)
> ozvc_1  |     at ChildProcess.emit (events.js:210:7)
> ozvc_1  |     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
> ozvc_1  |     at onErrorNT (internal/child_process.js:374:16)
> ozvc_1  |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
> ozvc_1  |     at process._tickCallback (internal/process/next_tick.js:180:9)
> ozvc_1  |     at Function.Module.runMain (module.js:667:11)
> ozvc_1  |     at startup (bootstrap_node.js:201:16)
> ozvc_1  |     at bootstrap_node.js:626:3

I'm using mediasoup in docker (i'm on windows)
I tried using the v2 & the experimental branch instead, they don't have this problem but like their branch suggest, it's not ready, ( i tried using server.createRoom and i get the is "not a function" error )

**Comment by Banou26** [comment]
Just saw the v2 example, gonna try making something with that new api even if there's no docs

**Comment by ibc** [comment]
No idea how you installed mediasoup, but this error means that the binary was not found, probably because compilation/building failed:

```
mediasoup:ERROR:Worker child process error [id:gyksgjse#1, error:Error: spawn /ozvc/src/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker ENOENT]
```

Anyhow, please let's move issues/problems to the public mailing list.

**Comment by venkpath** [comment]
@ibc 

Getting below exception while running  npm start at server..

please help me

(node:7436) UnhandledPromiseRejectionWarning: Error: spawn E:\gitclone\mediasoup
-demo\server\node_modules\mediasoup\worker\out\Release\mediasoup-worker ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:7436) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To termina
te the node process on unhandled promise rejection, use the CLI flag `--unhandle
d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio
ns_mode). (rejection id: 1)
(node:7436) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

**Comment by Envek** [comment]
Faced this weird issue too. 

It seems like sometimes mediasoup build artifacts are being removed for some reason. Executing `yarn install` emits `Already up-to-date.`

To fix it install mediasoup again with command like `yarn add mediasoup` and it will rebuild native components. Thanks to @HellSquirrel for figuring this out.

**Comment by ibc** [comment]
This seems to be related to #459. Unfortunately the reporter never provided requested information so hard to help. We don't use `yarn` BTW.

**Comment by thiago-temonitore** [comment]
i'm try run add mediasoup but show this err. Can someone help me ?



error C:\Users\thiago.nicacio\Desktop\server\node_modules\mediasoup: Command failed.
Exit code: 1
Command: node npm-scripts.js postinstall
Arguments:
Directory: C:\Users\thiago.nicacio\Desktop\server\node_modules\mediasoupOutput:
npm-scripts.js [INFO] running task "postinstall"
npm-scripts.js [INFO] executing command: python ./worker/scripts/configure.py --format=msvs -R mediasoup-worker
C:\Users\thiago.nicacio\Desktop\server\node_modules\mediasoup\worker\deps\gyp\pylib\gyp\input.py:1186: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if the_dict_key is 'variables' and variable_name in the_dict:
['--format=msvs', '-R', 'mediasoup-worker', 'C:\\Users\\thiago.nicacio\\Desktop\\server\\node_modules\\mediasoup\\worker\\mediasoup-worker.gyp', '-I', 'C:\\Users\\thiago.nicacio\\Desktop\\server\\node_modules\\mediasoup\\worker\\common.gypi', '--depth=C:\\Users\\thiago.nicacio\\Desktop\\server\\node_modules\\mediasoup\\worker', '-Dhost_arch=x64', '-Dtarget_arch=x64', '-Dopenssl_fips=', '-Dmediasoup_asan=false', '-Dnode_byteorder=little']
Warning: Missing input files:
C:\Users\thiago.nicacio\Desktop\server\node_modules\mediasoup\worker\deps\libwebrtc\libwebrtc\modules\remote_bitrate_estimator\bwe_defines.h    
C:\Users\thiago.nicacio\Desktop\server\node_modules\mediasoup\worker\deps\libuv\libuv\common.gypi
npm-scripts.js [INFO] executing command: MSBuild ./worker/mediasoup-worker.sln /p:Configuration=Release
'MSBuild' n�o � reconhecido como um comando interno
ou externo, um programa oper�vel ou um arquivo em lotes.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by Bessonov** [comment]
I use webpack to package the application and ran into a similar issue. Probably because [__dirname](https://github.com/versatica/mediasoup/blob/6401ff2/node/src/Worker.ts#L220) resolves to the `dist` folder. Setting the environment variable `MEDIASOUP_WORKER_BIN=node_modules/mediasoup/worker/out/Release/mediasoup-worker node` for development helped me.

**Comment by Debzoti** [comment]
this error persists i tried again "pnpm install and update mediasoup" no solution somehow.




pnpm start

> mediasoup-demo-server@3.0.0 start /home/debzoti/coding-files/video-app-demo/mediasoup-demo/server
> DEBUG=${DEBUG:='*mediasoup* *INFO* *WARN* *ERROR*'} INTERACTIVE=${INTERACTIVE:='true'} node server.js

process.env.DEBUG: *mediasoup* *INFO* *WARN* *ERROR*
config.js:
{
  "domain": "localhost",
  "https": {
    "listenIp": "0.0.0.0",
    "listenPort": 4443,
    "tls": {
      "cert": "/home/debzoti/coding-files/video-app-demo/mediasoup-demo/server/certs/fullchain.pem",
      "key": "/home/debzoti/coding-files/video-app-demo/mediasoup-demo/server/certs/privkey.pem"
    }
  },
  "mediasoup": {
    "numWorkers": 8,
    "workerSettings": {
      "logLevel": "warn",
      "logTags": [
        "info",
        "ice",
        "dtls",
        "rtp",
        "srtp",
        "rtcp",
        "rtx",
        "bwe",
        "score",
        "simulcast",
        "svc",
        "sctp"
      ],
      "disableLiburing": false
    },
    "routerOptions": {
      "mediaCodecs": [
        {
          "kind": "audio",
          "mimeType": "audio/opus",
          "clockRate": 48000,
          "channels": 2
        },
        {
          "kind": "video",
          "mimeType": "video/VP8",
          "clockRate": 90000,
          "parameters": {
            "x-google-start-bitrate": 1000
          }
        },
        {
          "kind": "video",
          "mimeType": "video/VP9",
          "clockRate": 90000,
          "parameters": {
            "profile-id": 2,
            "x-google-start-bitrate": 1000
          }
        },
        {
          "kind": "video",
          "mimeType": "video/h264",
          "clockRate": 90000,
          "parameters": {
            "packetization-mode": 1,
            "profile-level-id": "4d0032",
            "level-asymmetry-allowed": 1,
            "x-google-start-bitrate": 1000
          }
        },
        {
          "kind": "video",
          "mimeType": "video/h264",
          "clockRate": 90000,
          "parameters": {
            "packetization-mode": 1,
            "profile-level-id": "42e01f",
            "level-asymmetry-allowed": 1,
            "x-google-start-bitrate": 1000
          }
        }
      ]
    },
    "webRtcServerOptions": {
      "listenInfos": [
        {
          "protocol": "udp",
          "ip": "0.0.0.0",
          "port": 44444
        },
        {
          "protocol": "tcp",
          "ip": "0.0.0.0",
          "port": 44444
        }
      ]
    },
    "webRtcTransportOptions": {
      "listenInfos": [
        {
          "protocol": "udp",
          "ip": "0.0.0.0",
          "portRange": {
            "min": 40000,
            "max": 49999
          }
        },
        {
          "protocol": "tcp",
          "ip": "0.0.0.0",
          "portRange": {
            "min": 40000,
            "max": 49999
          }
        }
      ],
      "initialAvailableOutgoingBitrate": 1000000,
      "minimumAvailableOutgoingBitrate": 600000,
      "maxSctpMessageSize": 262144,
      "maxIncomingBitrate": 1500000
    },
    "plainTransportOptions": {
      "listenInfo": {
        "protocol": "udp",
        "ip": "0.0.0.0",
        "portRange": {
          "min": 40000,
          "max": 49999
        }
      },
      "maxSctpMessageSize": 262144
    }
  }
}
  mediasoup-demo-server:INFO running 8 mediasoup Workers... +0ms
  mediasoup createWorker() +0ms
  mediasoup:Worker constructor() +0ms
  mediasoup:Worker spawning worker process: /home/debzoti/coding-files/video-app-demo/mediasoup-demo/server/node_modules/.pnpm/mediasoup@https+++codeload.github.com+versatica+mediasoup+tar.gz+6e6f2987cb99cf6503c37f5dc2a02f419964a235/node_modules/mediasoup/worker/out/Release/mediasoup-worker --logLevel=warn --logTag=info --logTag=ice --logTag=dtls --logTag=rtp --logTag=srtp --logTag=rtcp --logTag=rtx --logTag=bwe --logTag=score --logTag=simulcast --logTag=svc --logTag=sctp +0ms
  mediasoup:Channel constructor() +0ms
  mediasoup:ERROR:Worker worker process failed [pid:undefined]: spawn /home/debzoti/coding-files/video-app-demo/mediasoup-demo/server/node_modules/.pnpm/mediasoup@https+++codeload.github.com+versatica+mediasoup+tar.gz+6e6f2987cb99cf6503c37f5dc2a02f419964a235/node_modules/mediasoup/worker/out/Release/mediasoup-worker ENOENT undefined +0ms
  mediasoup:Worker close() +10ms
  mediasoup:Channel request() [method:WORKER_CLOSE] +5ms
  mediasoup:ERROR:Channel Producer Channel error: Error: write EPIPE undefined +0ms
node:internal/child_process:285
      const err = new ErrnoException(exitCode, syscall);
                  ^

Error: spawn /home/debzoti/coding-files/video-app-demo/mediasoup-demo/server/node_modules/.pnpm/mediasoup@https+++codeload.github.com+versatica+mediasoup+tar.gz+6e6f2987cb99cf6503c37f5dc2a02f419964a235/node_modules/mediasoup/worker/out/Release/mediasoup-worker ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /home/debzoti/coding-files/video-app-demo/mediasoup-demo/server/node_modules/.pnpm/mediasoup@https+++codeload.github.com+versatica+mediasoup+tar.gz+6e6f2987cb99cf6503c37f5dc2a02f419964a235/node_modules/mediasoup/worker/out/Release/mediasoup-worker',
  path: '/home/debzoti/coding-files/video-app-demo/mediasoup-demo/server/node_modules/.pnpm/mediasoup@https+++codeload.github.com+versatica+mediasoup+tar.gz+6e6f2987cb99cf6503c37f5dc2a02f419964a235/node_modules/mediasoup/worker/out/Release/mediasoup-worker',
  spawnargs: [
    '--logLevel=warn',
    '--logTag=info',
    '--logTag=ice',
    '--logTag=dtls',
    '--logTag=rtp',
    '--logTag=srtp',
    '--logTag=rtcp',
    '--logTag=rtx',
    '--logTag=bwe',
    '--logTag=score',
    '--logTag=simulcast',
    '--logTag=svc',
    '--logTag=sctp'
  ]
}

Node.js v22.18.0
 ELIFECYCLE  Command failed with exit code 1.

**Comment by ibc** [comment]
> I use webpack to package the application and ran into a similar issue. Probably because [__dirname](https://github.com/versatica/mediasoup/blob/6401ff2/node/src/Worker.ts#L220) resolves to the `dist` folder. Setting the environment variable `MEDIASOUP_WORKER_BIN=node_modules/mediasoup/worker/out/Release/mediasoup-worker node` for development helped me.

Could you please report a new issue here in GH (with all the required info and STR) please?

**Comment by Bessonov** [comment]
@ibc 

I can try, but I'm not sure that my use case is in scope. Basically, I'm compiling with `tsc` from `./src` into `./build`, and then using webpack to bundle from `./build` to `./dist/server.mjs`, which is the executed file.

However, due to `__dirname` and a custom path, `mediasoup` expects a specific directory layout - which no longer exists, because everything (including `Worker.ts`, except for resources and binaries, which are now placed in `./dist`) is now bundled into a single file.

In many cases, the bundler can adjust the paths if `require` and similar functions are used. But that's not the case here.

WDYT?

**Comment by ibc** [comment]
I think that your usage is a bit out of the scope of what a Node server side application usually is. I think it's ok that mediasoup relies on `__dirname` to look up for the worker executable. However, if the application mangles the folder structure of the whole source code including dependencies (because it does bundling) then it's the responsibility of the app to workaround the problem it's causing by doing that.

**Comment by ibc** [comment]
Anyway I've created an issue here with STR:

https://github.com/versatica/mediasoup/issues/1601

**Comment by ibc** [comment]
@Bessonov please take a look to this PR that solves the issue: https://github.com/versatica/mediasoup/pull/1603

Comments in that PR, please.
