### ISSUE TITLE
Consumer::Add/RemoveProfile() should do nothing if not enabled

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#157]
When `Consumer::RemoveProfile()` is called, it may fire an "effectiveprofilechange". It should NOT do it if not enabled. Also, and even more important, it should NOT use `this->rtpStream` since it's `nullptr` when the Consumer is disabled (`IsDisabled()`).

NOTE: I don't mean that `Add/RemoveProfile()` should just exit if not enabled. In fact, they must update state (existing profiles, etc) for later when `Enable()` is called.

Other considerations:

* Must recheck whether `Consumer::Disable()` and `Consumer::Enable()` properly updates/resets internal status, RTP probing, etc.

**Comment by jmillan** [comment]
> When Consumer::RemoveProfile() is called, it may fire an "effectiveprofilechange". It should NOT do it if not enabled

Done,

>  it should NOT use this->rtpStream since it's nullptr when the Consumer is disabled (IsDisabled())

It does not. The stream status check timer is reset if probing, which only can happen if the Consumer is enabled.
