### ISSUE TITLE
 failed assertion `payloadOffset < this->payloadLength': payload offset bigger than payload size

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#159]
```
2017-11-09T16:20:22.837Z mediasoup:WARN:mediasoup-worker [id:dnlijfix#1] RTC::RTCP::Sdes::Parse() | not enough space for SDES item, discarded
2017-11-09T16:20:23.102Z mediasoup:WARN:mediasoup-worker [id:dnlijfix#1] RTC::RTCP::Sdes::Parse() | not enough space for SDES item, discarded
2017-11-09T16:20:23.539Z mediasoup:mediasoup-worker [id:dnlijfix#1] RTC::Producer::ReceiveRtpPacket() | key frame received [ssrc:93142492, seq:18331, profile:default]
mediasoup-worker's stderr: ABORT[id:dnlijfix#1] RTC::RtpPacket::ShiftPayload() | failed assertion `payloadOffset < this->payloadLength': payload offset bigger than payload size
2017-11-09T16:20:24.980Z mediasoup:ERROR:Worker child process exited [id:dnlijfix#1, code:null, signal:SIGABRT]
```

**Comment by ibc** [comment]
It happens in VP8.cpp, here:

```c++
// Modify the RtpPacket payload in order to always have two byte pictureId.
if (!payloadDescriptor->hasTwoBytePictureId)
{
	// Shift the RTP payload one byte from the begining of the pictureId field.
	packet->ShiftPayload(2, 1, true /*expand*/);
	// Set the two byte pictureId marker bit.
	data[2] = 0x80;
	// Update the payloadDescriptor.
	payloadDescriptor->hasTwoBytePictureId = true;
}
```

This is probably produced by Edge. AFAIR it sends rare VP8 payloads, without some fields.

So basically the caller must check the payload size before calling `ShiftPayload()`.

**Comment by ibc** [comment]
Opss, no, what it happen (AFAIR) is that Edge does NOT include `PictureId` in VP8 payloads.

**Comment by ibc** [comment]
It happened again in the demo server (which was updated):

```
mediasoup-worker's stderr: ABORT[id:wenesnle#1] RTC::RtpPacket::ShiftPayload() | failed assertion `payloadOffset < this->payloadLength': payload offset bigger than payload size
```

**Comment by ibc** [comment]
Checking `i` is not enough. It may happen that the VP8 payload has `i` but has no `PictureId`:

```c++
if (payloadDescriptor->i)
{
	if (len < ++offset + 1)
		return nullptr;

	byte = data[offset];

	if ((byte >> 7) & 0x01)
	{
		if (len < ++offset + 1)
			return nullptr;

		payloadDescriptor->hasTwoBytePictureId = true;

		payloadDescriptor->pictureId = (byte & 0x7F) << 8;
		payloadDescriptor->pictureId += data[offset];
	}
	else
	{
		payloadDescriptor->pictureId = byte & 0x7F;
	}
}
```

so this check will return true anyway:

```c++
if (payloadDescriptor->i && !payloadDescriptor->hasTwoBytePictureId)
```

**Comment by ibc** [comment]
I've commited a fix: 1528cfe9da28566df02e123e09715a73ec38b216

However, I think there are more vulnerabilities as, `Encode()` checks whether a flag `i` or `l` is set and assumes that, if so, there was `PictureId` field (fixed) and `tl0PictureIndex`. But that's not true so it must be fixed or a malicious packet with `l` but no `tl0PictureIndex` would produce a crash.

**Comment by ibc** [comment]
To clarify, the fact that the original payload has bit flags set (`i`, `l`, `t`, `k`, `y`, etc) does not mean that there is real space for the associated fields, so we need more boolean getters such as `hasTl0PictureIndex`, `hasTlIndex`, `hasKeyIndex`, etc. And check those getters rather than the original (and not reliable) flags in the payload.

**Comment by jmillan** [comment]
Will be fix + tests will be ready tomorrow.

**Comment by jmillan** [comment]
Comment: Whenever returning `nullptr` from `VP8::Parse`, then no `VP8:Encode` is called for such RTP packet.

I'm working on this right now.

**Comment by ibc** [comment]
OK, then the check should also verify whether `this->payloadDescriptor` is set.

**Comment by jmillan** [comment]
If this `this->payloadDescriptor`  is not set `VP8::Encode` will not be called. 

I'm working on it.

**Comment by ibc** [comment]
AFAIU the crash happens when the Producer mangles the packet so before any Encode() call.

**Comment by jmillan** [comment]
Here was the problem to this issue: 725ea8b 

If the `extended` flag is not set then we must ignore the payload descriptor.  This was a hole in the parser.

Some VP8  tests have been added too.

**Comment by jmillan** [comment]
Also, the suggested `hasX` have been implemented. We do not rely on the flags anymore but on the actual data 8ba457ea
