### ISSUE TITLE
Screen Sharing

### ISSUE THREAD

**Issue by gmchaturvedi1** [versatica/mediasoup#161]
Dear Friends ,

can u help us for screen  sharing.

Regards
gmchaturvedi 

> Please, do NOT open an issue if you have problems or questions regarding the use of mediasoup. Use the mediasoup Google Group instead:
> 
> https://groups.google.com/forum/#!forum/mediasoup
> 
> If you have found a bug in the software, or want to propose a new well documented feature or improvement, please delete this text and continue. :)

**Comment by ibc** [comment]
Questions in the public mailing list, please.
