### ISSUE TITLE
Implement multiple producer codecs.

### ISSUE THREAD

**Issue by ethand91** [versatica/mediasoup#166]
Would like to implement the following: 

1. Client joins a room and streams the video stream in two codecs (VP8/H264).
   * Create two separate transports of type 'send' and apply the preferred codec in them.
   * Create two separate producers of type 'video' and apply the same video track to them.
2. Google Chrome Consumer logs into room and plays the VP8 track.
3. iOS Safari 11 Consumer logs into room and plays the H264 track.

**Comment by ibc** [comment]
As told in the mailing list, this is feasible but requires some tuning. Will be eventually added (sooner than later).

However, from the point of view of the producer browser, take into account that having to encode a video stream with two different encodings (VP8 and H264) won't be very CPU friendly. Let's see how it goes.

**Comment by ibc** [comment]
Sorry, this is specific to `mediasoup-client`. There is nothing else to do in `mediasoup` server side to enable this.

Moving the issue to: https://github.com/versatica/mediasoup-client/issues/8
