### ISSUE TITLE
No audio from iOS

### ISSUE THREAD

**Issue by artushin** [versatica/mediasoup#170]
When testing on a iOS device in Safari, it looks like the encoded audio is super low volume. The receiver on desktop Chrome shows values of totalAudioEnergy around 2.2164036295180267e-7. That's compared to a value of about 2.948547124862671 when going from Chrome to Chrome.

I haven't checked that stat when testing iOS Safari to iOS Safari but there's no audio coming through there either.

Can be replicated on demo.mediasoup.org.

**Comment by ibc** [comment]
mediasoup server does not alter the audio, and mediasoup-client does not perform any kind of `getUserMedia` or similar (that's up to the app). So AFAIU this cannot be related to mediasoup at all.

Said that, I've a similar problem when I use the demo web app in my mobile (HTC U11, Android Chrome). The remote hears me in super low volume. However the same happens to me using a specific native Android app, but it does not happen when using audio call in Android Slack or Whatsapp, so honestly no idea.

**Comment by artushin** [comment]
Yeah, it strangely doesn't happen on https://webrtc.github.io/samples/src/content/peerconnection/audio/ when using iOS safari so I figured it must have something to do with the implementation but I can't see anything that mediasoup-demo does that would change the behavior. It might be really useful for debugging if mediasoup-client exposed the RTCPeerConnection instance so that we could call getStats on it when debugging (or just proxy a getStats call).

**Comment by artushin** [comment]
Also, I think the really low mic volume on Android is probably something else. With the totalAudioEnergy I mentioned (I assume) you couldn't possible hear anything at 2.2164036295180267e-7

**Comment by ibc** [comment]
mediasoup-client does not expose the PeerConnection because it also works in ORTC browsers (Edge). Said that, you can get the PeerConnection in the demo as follows:

```js
var pc = window.CLIENT._room.transports[0]._handler._pc;
```

**Comment by ibc** [comment]
Let's close this issue since there is nothing in mediasoup producing that.

**Comment by artushin** [comment]
Np, that's for the input. The issue got resolved after I refactored some of my code related to getUserMedia. I wish I could tell you what exactly was causing it but I made a few changes. One of the significant ones was starting with requesting initial permissions with a {audio: true, video: true} constraint. It doesn't seem like it should affect anything other than combining the permissions prompts, but I have a suspicion it does more than that in iOS.

**Comment by artushin** [comment]
Just for the benefit of anyone else seeing similar issues and ending up on this ticket, I'm also seeing occasional issues with iOS Safari intermittently not sending audio at all. I've been able to narrow this down as a microphone issue (the MediaStreamTrack doesn't produce any sound locally either, even though it plays). This issue seems to be consistently resolved by restarting the Safari app.

**Comment by ibc** [comment]
"Fortunatelly" I don't need to deal with iOS Safari yet :)
Although, at least, I can say that in OSX Safari everything works nice.

**Comment by moppymopperson** [comment]
Thank you both for documenting this
