### ISSUE TITLE
`gulp test:worker` fails (mediasoup-worker-test never ends)

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#176]
It happens in Linux (in Travis and our Linux server):

```
[16:56:59] cd worker && ./out/Release/mediasoup-worker-test --invisibles --use-colour=yes
```

That never ends. It should be due to some infinite bucle in a test, not sure if [here](https://github.com/versatica/mediasoup/commit/fb0a664a7c190723efd2e5d59cf8463922420869#diff-5687bf1313ee24ab70e6227d6d319d02R80) or [here](https://github.com/versatica/mediasoup/commit/fb0a664a7c190723efd2e5d59cf8463922420869#diff-5687bf1313ee24ab70e6227d6d319d02R92).

**Comment by jmillan** [comment]
fixed by e2e4e5501e37
