### ISSUE TITLE
Use "JSON for Modern C++"

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#178]
It's faster than JsonCpp and the API looks great:

https://github.com/nlohmann/json

**Comment by jmillan** [comment]
Looks so nice

**Comment by ibc** [comment]
Already used in https://github.com/ibc/libsdptransform :)

**Comment by Globik** [comment]
In what cases could I use this libsdptransform? Could be on server side in C for communication with mediasoup main.cpp?

**Comment by ibc** [comment]
mediasoup does not use SDP stuff in server side but like-ORTC parameters.

Please, let's discuss in the mailing list. This issue is just a To-do for mediasoup.

**Comment by ibc** [comment]
Done in v3.
