### ISSUE TITLE
Failed to resolve module specifier 'mediasoup-client'

### ISSUE THREAD

**Issue by Yalhu** [versatica/mediasoup#182]
I install mediasoup-client via npm ,with the guide of documentation.
There is an error:Failed to resolve module specifier 'mediasoup-client'. And other module works well.
I did this on win10, and ubuntu 14( node v8+,npm v5+).There is code:
`$ npm install mediasoup-client --save`
```
import mediasoupClient from "mediasoup-client";
```
![node_module](https://user-images.githubusercontent.com/27722787/34819845-d966ce58-f6f9-11e7-916f-fecfb6c5ca17.png)
Please help me what to do,Thanks!

**Comment by ibc** [comment]
Please, use the mediasoup-client GitHub issue tracker.
