### ISSUE TITLE
Firefox not able to receive/send stream encoded in h264

### ISSUE THREAD

**Issue by harris** [versatica/mediasoup#184]
I have tried set up mediasoup 2.0.9 and not able to get firefox to work with h264.  Previously we had mediasoup 1.2 running and it was able to stream with h264 on ff. 

**Repro case:** 
- setup mediasoup-demo from https://github.com/versatica/mediasoup-demo
- use 
`			{
				kind       : 'video',
				name       : 'H264',
				clockRate  : 90000,
				parameters :
				{
					'packetization-mode' : 1
				}
			}
` 
I setup a server running the demo at [here](https://webrtc-v2.hideout.gg:3000).  I am pretty sure there are something wrong with h264 because I was also able to get it up and running with `vp8` and it runs on all browsers including ff. Please let me know I could provide more info to help debug.  Thanks for creating such an awesome project.

**Comment by ibc** [comment]
Check the SDP that Firefox sends and receives. If something is wrong in the H264 negotiation you should see it there.

Anyhow, you are not even providing info about which browsers are sending/receiving H264 in your room. Please use the mailing list unless you have a specific and documented issue/bug to report in mediasoup or mediasoup-client ("something does not work in the demo" is not a valid issue here).
