### ISSUE TITLE
Strange behavior in "low or bad" bandwidth links

### ISSUE THREAD

**Issue by HeriBrito** [versatica/mediasoup#188]
Hi,

following rules from Jose Luis, i put this issue.

When a client connect to server with an "low or very bad" bandwidth link, the server is always (each 2-3 seconds) sending "consumerEffectiveProfileChanged" notification to cliente, jumping to profile "high", "medium" and "low". When client is using "medium/low" profile, the stream is possible, but when the server jump to "high" profile ... the client freeze the stream. I uploaded a STAT trace, calling consumer.enableStats() from client side.

Begin lines with "cliente.js:88" show the "consumerEffectiveProfileChanged" notification, and "clientRoom.js:159" all the DATA RTP. I hope this can help you to find the source of this behavior.

MacBook Air - MacOS 10.12.6
node v7.6.0
npm mediasoup-2.0.11
mediasoup-client-2.0.8 
Disabled "maxBitrate" from config.js in mediasoup-server
The link used it's a IPSec VPN in a 4G link

Regards,
Heri

[traceSTATs.txt](https://github.com/versatica/mediasoup/files/1688891/traceSTATs.txt)

**Comment by ibc** [comment]
Thanks, we'll work on this.

**Comment by jmillan** [comment]
@HeriBrito,

In some point in the log provided there is a transition from `LOW` to `HIGH` profile. Currently this should only happen as a result of explicitly calling `consumer.setPreferredProfile()` with a `HIGH` value.

Are you doing so?

**Comment by HeriBrito** [comment]
Hi @jmillan,

not, consumer.setPreferredProfile() is never called. The only, i have a function where join the audio/video tracks (from both consumer) in a MediaStream object, so it can play in a html5 video.srcObject, and when consult consumer.effectiveProfile (audio or video), always return null.

Regards

**Comment by HeriBrito** [comment]
Hi @jmillan,

is your commit merged into the master branch?

Regards

**Comment by ibc** [comment]
Not yet. The PR is here: https://github.com/versatica/mediasoup/pull/190 but it's not yet merged.

@jmillan we should get a slot to test it and merge.

**Comment by HeriBrito** [comment]
Ok @ibc,

so with this PR merged it's supposed that we can use the SVC VP8 in low bandwidth with Chrome?, because i had read some post in your [mailing list](https://groups.google.com/forum/#!forum/mediasoup) that Chrome not work very well with SVC, it would be better work with firefox to use this utility?

Regards

**Comment by ibc** [comment]
WE must still work on #190. Its purpose is just to improve the simulcast layers handling. It's not related to SVC at all.

**Comment by jmillan** [comment]
I'll test [this](https://github.com/versatica/mediasoup/commit/0a4420a3e4b6cdda64e752b549220279c3bafbd9) old patch so it is added to v2. Is that OK @ibc?

**Comment by ibc** [comment]
Go go

**Comment by jmillan** [comment]
Deployed in https://v2demo.mediasoup.org

So far so good.

**Comment by ibc** [comment]
Is this committed to v2 branch?

**Comment by jmillan** [comment]
Commited in dev branch. Works nicely in the tests I've done.

**Comment by ibc** [comment]
I do not see any related commit in "devel" branch.

BTW: if this works fine, and given than v3 is completely different, I suggest committing this into v2 branch and releasing a new v2 version.

**Comment by jmillan** [comment]
done
