### ISSUE TITLE
Add 'timestamp' filed to events

### ISSUE THREAD

**Issue by jmillan** [versatica/mediasoup#189]
MS events should come with a `timestamp` field as a correlation facility.

**Comment by ibc** [comment]
Yes

**Comment by ibc** [comment]
This is not so easy without an API change. For example, the `Consumer` emits some events such as:

```js
consumer.on('pause', fn(originator, appData))
```

Where to add the `timestamp`?

Even more, if we add (somewhere) a `timestamp` that would be added in the mediasoup JavaScript layer, meaning that it would match the moment in which the event is emitted to the app. If so, why is a `timestamp` needed at all?

**Comment by jmillan** [comment]
Makes sense when it comes to analyse the raw events, not necessarily on the API. But we've seen that it can be achieved when building an events collector but jut adding the timestamp value as a formatting process.
