### ISSUE TITLE
preferTcp not honored

### ISSUE THREAD

**Issue by artushin** [versatica/mediasoup#193]
If a room is created in mediasoup-client with `transportOptions: {preferTcp: true}`, the resulting remote candidate connection is shown in chrome://webrtc-internals/ as UDP. However, setting `transportOptions: {udp: false}` with the same SFU results in a working TCP connection.

**Comment by ibc** [comment]
Thanks a lot. The documentation was ok, but the default values were wrong:

https://github.com/versatica/mediasoup/commit/70d537f7eb060bfeb43d0c56920fd54a4aefdfb1

Fixed in 2.0.14 and published.

**Comment by artushin** [comment]
Same for https://github.com/versatica/mediasoup/blob/dc69b20c058a3be5139ce8718f5276ef04439c1d/worker/include/RTC/Transport.hpp#L62 options?

**Comment by ibc** [comment]
No, that's ok. The documentation, indeed, was wrong. Fixed now: https://mediasoup.org/documentation/mediasoup/api/#WebRtcTransport-MirroringOptions

Thanks.

**Comment by artushin** [comment]
Thanks!
