### ISSUE TITLE
What should I do if I want to record a video conference or record a multiplayer video conference? Do you provide the API interface? If not, where should I change it?

### ISSUE THREAD

**Issue by jaciyu** [versatica/mediasoup#194]
What should I do if I want to record a video conference or record a multiplayer video conference? Do you provide the API interface? If not, where should I change it?

**Comment by jmillan** [comment]
> Please, do NOT open an issue if you have problems or questions regarding the use of mediasoup. Use the mediasoup Google Group instead:
> 
> https://groups.google.com/forum/#!forum/mediasoup
> 
> If you have found a bug in the software, or want to propose a new well documented feature or improvement, please delete this text and continue. :)

**Comment by mahesh-co1** [comment]
@jaciyu Heyy did you find the solution?

**Comment by ibc** [comment]
> @jaciyu Heyy did you find the solution?

Not here, please. There is a support forum.

**Comment by mahesh-co1** [comment]
Didn't get anything there. Why don't you just answer here and attach link to it and close this forever? That will be helpful for many.

**Comment by ibc** [comment]
> Didn't get anything there. Why don't you just answer here and attach link to it and close this forever? That will be helpful for many.

Because we have a forum for support and discussions, and we just want to use GitHub issues for real issues. And because that's our decision no matter what others consider.
