### ISSUE TITLE
Audio and video streams do not leave the browser running on the virtual host

### ISSUE THREAD

**Issue by VShtaba** [versatica/mediasoup#195]
Hi guys,

I tried the demo version of mediasoup.
I like it. You are doing a wonderful service, thank you.

If users use the same browsers for a videoconference, they hear and see each other. It is very good.

But I discovered the problem.
**Audio and video do not leave the browser if it is running in Remote Desktop Session on a remote virtual machine.**

I used the Google Chrome browser - the official build of 64.0.3282.186 version 64 bit on the remote desktop of the Windows 10 Pro virtual machine. Processor Intel Xeon E5-2673 v3 2.40 GHz - 4 cores, 8 GB of RAM, without support for hardware sound. Chrome uses about 10-20% of the processor using WebRTC, and I have about 5 GB of free memory.
 
What could it be? How to fix this?

**Comment by VShtaba** [comment]
& Perhaps you know that:
1. Edge does not send the sound of the microphone and webcam video to another user in the Chrome browser.
2. Edge does not send only the webcam video if the second user uses Edge browser.

**Comment by ibc** [comment]
Hi, I'm sorry but I don't accept issues reharding the demo app, nor this is a forum for asking doubts or usage problems.

Please use the public mailing list.

**Comment by VShtaba** [comment]
Correctly, I understand that you need to write a post here?
https://groups.google.com/forum/#!forum/mediasoup

**Comment by ibc** [comment]
That's a public mailing list, so you write to the mailing list, not just to me. If me or others can help you, we'll do.
