### ISSUE TITLE
No RTCP from createRtpStreamer

### ISSUE THREAD

**Issue by artushin** [versatica/mediasoup#197]
Wireshark shows only RTP packets when sending RTP/RTCP to a port.

I've got the capture file if you want it, just let me know if/where you want me to send it.

**Comment by artushin** [comment]
Too big to attach. You can find it here: https://storage.googleapis.com/artushin-misc/videortp.pcapng

This is the github issue btw 😄

**Comment by ibc** [comment]
Indeed, we are not sending RTCP in `PlainRtpTransport`.

In `WebRtcTransport` constructor we do:

```c++
// Start the RTCP timer.
this->rtcpTimer->Start(static_cast<uint64_t>(RTC::RTCP::MaxVideoIntervalMs / 2));
```

However we don't do that on `PlainRtpTransport`.

**Comment by ibc** [comment]
@artushin can you test in master branch? It should send RTCP now. If so, please confirm so we release a new version. Thanks!

**Comment by artushin** [comment]
LGTM

**Comment by ibc** [comment]
mediasoup 2.0.15 is out.
