### ISSUE TITLE
FR: update turnServers dynamicaly in an existing room in mediasoup-client

### ISSUE THREAD

**Issue by misi** [versatica/mediasoup#201]
I would like to update the ICE server after the room has been created in mediasoup.client,
but unfortunately I didn't find a room function that I could use to update the turnServers.

Would it be possible to add a new function to Room object that updates RoomOptions->turnServers and this way I could restart ICE with the new turnServer?

I get a time limited long term (turn) credential from an API, so this is why I need this feature.

**Comment by ibc** [comment]
Please, move this to the mediasoup-client project ;)

https://github.com/versatica/mediasoup-client

**Comment by misi** [comment]
Sorry.. & Done.
