### ISSUE TITLE
Implement H264 simulcast

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#215]
Chrome is suppose to include H264 simulcast soon (just simulcast, no temporal layers within each simulcast stream), and there are cams that already do H264 simulcast.

We need to add support for it in mediasoup, and the only we need is being able to detect H264 keyframes. We don't even need to investigate how to do that since @lminiero already did it (see [janus_h264_is_keyframe](https://github.com/meetecho/janus-gateway/blob/master/utils.c#L643) in janus).

**Comment by lminiero** [comment]
You're welcome! :smile:

**Comment by ibc** [comment]
FUCK, HE'S READ THIS!

**Comment by ibc** [comment]
Done in 2.2.6

**Comment by ibc** [comment]
Currently it fails when moving the preferred Consumer profile from high to low or medium (it does not fail when moving to high however). As @murillo128 pointed out in Twitter:

> If I have to bet, it is missing SPS/PPS before first IDR nal unit of the Iframe after the switch.

**Comment by ibc** [comment]
Some unverified stuff I've found in a quick search:

* https://stackoverflow.com/questions/1957427/detect-mpeg4-h264-i-frame-idr-in-rtp-stream
* http://e2e.ti.com/support/legacy_forums/embedded/multimedia_software_codecs/f/356/t/73235?How-to-correctly-judge-the-keyframe-of-H-264#

**Comment by ibc** [comment]
**NOTE:** If we modify `H264::Parse()` to always set `payloadDescriptor->isKeyFrame = true;` the video is not frozen when switching profile. Obviously this is a hack that produces a small frozen effect (the time it takes for the PLI to be sent and I-Frames being received, etc).

**Comment by ibc** [comment]
Suggestion by Tim:

> switch when you find nal 7 instead of that other code

**Comment by ibc** [comment]
I've logged `nal` and it's absolutely **never** 7.

**Comment by ibc** [comment]
I don't receive any `nal 7` nor `fragment 7` as a result of a PLI.

@lminiero (who later will sue us for violating the GPL 3):

> as Sergio said it might be in an aggregated NAL, which means in a 24 NAL
> https://github.com/meetecho/janus-gateway/blob/master/postprocessing/pp-h264.c#L283

**Comment by ibc** [comment]
@murillo128 said:

> SPS/PPS should be before each iframe or transmitted out of band in sdp sprop parameter. if not, if first packet containing the sps or pps is dropped, stream would be not decodable at all even if resending iframes

**Comment by ibc** [comment]
Some research. I've added logs to see what happens when a H264 profile change is requested. This is:

```
// This is high stream
RTC::Codecs::H264::Parse() | fragment:28, nal:5, startBit:0, keyFrame:false +7ms
RTC::Codecs::H264::Parse() | fragment:28, nal:5, startBit:0, keyFrame:false +0ms
RTC::Codecs::H264::Parse() | fragment:28, nal:5, startBit:0, keyFrame:false +6ms
RTC::Codecs::H264::Parse() | fragment:28, nal:5, startBit:0, keyFrame:false +5ms
RTC::Codecs::H264::Parse() | fragment:28, nal:5, startBit:0, keyFrame:false +1ms

// Now los stream is requested and PLI is sent immediately
RTC::Consumer::SetPreferredProfile() +5ms
RTC::Consumer::RequestKeyFrame() +0ms

// Those are packets in the meanwhile
RTC::Codecs::H264::Parse() | fragment:28, nal:5, startBit:0, keyFrame:false +1ms
RTC::Codecs::H264::Parse() | fragment:28, nal:5, startBit:0, keyFrame:false +0ms
RTC::Codecs::H264::Parse() | fragment:28, nal:5, startBit:0, keyFrame:false +11ms
RTC::Codecs::H264::Parse() | fragment:28, nal:5, startBit:128, keyFrame:true +1ms
RTC::Codecs::H264::Parse() | fragment:28, nal:5, startBit:0, keyFrame:false +0ms
RTC::Codecs::H264::Parse() | fragment:28, nal:5, startBit:0, keyFrame:false +3ms
RTC::Codecs::H264::Parse() | fragment:28, nal:5, startBit:0, keyFrame:false +7ms
RTC::Codecs::H264::Parse() | fragment:28, nal:5, startBit:0, keyFrame:false +0ms
RTC::Codecs::H264::Parse() | fragment:28, nal:5, startBit:0, keyFrame:false +6ms
RTC::Codecs::H264::Parse() | fragment:28, nal:5, startBit:0, keyFrame:false +6ms
RTC::Codecs::H264::Parse() | fragment:28, nal:5, startBit:0, keyFrame:false +0ms
RTC::Codecs::H264::Parse() | fragment:28, nal:5, startBit:0, keyFrame:false +6ms
RTC::Codecs::H264::Parse() | fragment:24, nal:0, startBit:0, keyFrame:false +549ms
RTC::Codecs::H264::Parse() | fragment:24, nal:0, startBit:0, keyFrame:false +0ms
RTC::Codecs::H264::Parse() | fragment:28, nal:5, startBit:128, keyFrame:true +0ms

// Finally the requested keyframe is received
RTC::Consumer::SendRtpPacket() | key frame received for target profile [profile:low] +0ms

// And here the low stream (yes, frozen due the issue we don't know yet)
RTC::Codecs::H264::Parse() | fragment:28, nal:5, startBit:128, keyFrame:true +1ms
RTC::Codecs::H264::Parse() | fragment:24, nal:0, startBit:0, keyFrame:false +5ms
RTC::Codecs::H264::Parse() | fragment:28, nal:5, startBit:128, keyFrame:true +0ms
RTC::Codecs::H264::Parse() | fragment:28, nal:5, startBit:0, keyFrame:false +0ms
RTC::Codecs::H264::Parse() | fragment:28, nal:5, startBit:0, keyFrame:false +6ms
```

**Comment by ibc** [comment]
And this is the same (by copy&pasting code) but here within `Consumer.cpp`. Specifically within the block `if (this->effectiveProfile != this->targetProfile && profile == this->targetProfile)`:

```
// Here high stream
[...]

// Here medium is requested and PLI sent
RTC::Consumer::SetPreferredProfile() | ----- SetPreferredProfile(medium) ----- +7s
RTC::Consumer::RequestKeyFrame() | ----- RequestKeyFrame() ----- +0ms

// Packets received with profile medium
RTC::Consumer::SendRtpPacket() | fragment:24, nal:0, startBit:0, keyFrame:false +361ms
RTC::Consumer::SendRtpPacket() | fragment:28, nal:5, startBit:128, keyFrame:true +0ms
RTC::Consumer::SendRtpPacket() | key frame received for target profile [profile:medium] +1ms
```

If we take a look to the first packet received with profile medium, it's NOT a keyframe (so it's ignored). Could such a packet be the missing one????

**Comment by ibc** [comment]
So, what if instead of checking `fragment == 5 || MORE_STUFF` we check `fragment == 24 || MORE_STUFF`? I've tested it locally and I "think" it may work, but unfortunately my Safari is tired or something and does not even respond (even high stream is frozen all the time).

**Comment by ibc** [comment]
In fact, according to [RFC 6184](https://tools.ietf.org/html/rfc6184):

> Fragmentation Unit: Used to fragment a single NAL unit over multiple
   RTP packets.  Exists with two versions, FU-A and FU-B, identified
   with the NAL unit type numbers 28 and 29, respectively.  Specified in
   Section 5.8.

I have no idea what `fragment` is, but the spec says nothing about `fragment 5`.

**Comment by jmillan** [comment]
Following you tests @ibc, I've done the following changes on the keyframe detection.

```diff
iff --git a/worker/src/RTC/Codecs/H264.cpp b/worker/src/RTC/Codecs/H264.cpp
index 54883501..11f451ca 100644
--- a/worker/src/RTC/Codecs/H264.cpp
+++ b/worker/src/RTC/Codecs/H264.cpp
@@ -23,7 +23,9 @@ namespace RTC
                        uint8_t nal      = *(data + 1) & 0x1F;
                        uint8_t startBit = *(data + 1) & 0x80;

-                       if (fragment == 5 || ((fragment == 28 || fragment == 29) && nal == 5 && startBit == 128))
+                       if (
+                         fragment == 5 || (fragment == 24 && nal == 0) ||
+                         ((fragment == 28 || fragment == 29) && nal == 5 && startBit == 128))
                                payloadDescriptor->isKeyFrame = true;

                        return payloadDescriptor.release();
```

The profile change is smooth as it can be.

fragment value 24 is refered in  [RFC 6184](https://tools.ietf.org/html/rfc6184) as `STAP-A`( Single-Time Aggregation Packet type A)

**Comment by ibc** [comment]
So let's close this issue.
