### ISSUE TITLE
Server warnings for safari as producer and firefox as consumer

### ISSUE THREAD

**Issue by JSteitz** [versatica/mediasoup#220]
Producer: Safari Audio+Video (no constraints)
Consumer: Firefox

Firefox only receives 1fps and the server log outputs some warnings.
I tested it with other browsers and only Firefox has the problem and produces the warnings.

Additional Info:
I'm using 2 send transports for audio/video with different bitrates.

```
  mediasoup:WARN:mediasoup-worker [id:goswzpjh#4] RTC::Transport::HandleRtcpPacket() | no Producer for received SDES chunk [ssrc:3573841416] +4s
  mediasoup:WARN:mediasoup-worker [id:goswzpjh#4] RTC::Transport::HandleRtcpPacket() | no Producer for received SDES chunk [ssrc:3573841416] +3s
  mediasoup:WARN:mediasoup-worker [id:goswzpjh#4] RTC::Transport::HandleRtcpPacket() | no Producer for received SDES chunk [ssrc:3573841416] +6s
  mediasoup:WARN:mediasoup-worker [id:goswzpjh#4] RTC::Transport::HandleRtcpPacket() | no Producer for received SDES chunk [ssrc:3573841416] +4s
  mediasoup:WARN:mediasoup-worker [id:goswzpjh#4] RTC::Transport::HandleRtcpPacket() | no Producer for received SDES chunk [ssrc:3573841416] +7s
```

**Comment by ibc** [comment]
Those logs have an explanation. They just happen due the nature of WebRTC RtpTransceivers in which tracks "never end" even after stopping a sending track and/or RtpSender.

I've never seen such a 1fps bitrate and you don't provide any info so I cannot manage this as a bug. Please use the mailing list instead.

**Comment by JSteitz** [comment]
Sure I could provide more info, if you tell me what you need.
I don't know where the problem comes from.

Just closing a ticket is just bullshit.
It's not helping anyone.

**Comment by ibc** [comment]
Sorry, this is a bug tracker, not a support forum. We just want to handle here (in GitHub) proven issues and feature wishes.  I cannot help you to get more info about an issue we've never seen and I cannot keep an issue open for that. Please use the mailing list and we (and may be also other users) will try to help.
