### ISSUE TITLE
Missing parameter in transportParameters

### ISSUE THREAD

**Issue by havfo** [versatica/mediasoup#226]
### Your environment

- Operating system: Debian Stretch
- Node version: 8.12.0
- npm version: 6.4.1
- gcc/clang version: gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)
- mediasoup version: 2.4.3

### Issue description
PlainRtpTransport missing parameter.

mediasoup-client expects remotePlainRtpParameters.version, but this is not included in:
https://github.com/versatica/mediasoup/blob/master/lib/Peer.js#L368

**Comment by ibc** [comment]
@jmillan this is true. `mediasoup` does not add `version` field. Do we really need such a `version` field? Wouldn't it be better if we don't set such a `version` field and instead let the client app detect whether `ip` is IPv4 or IPv6?

**Comment by jmillan** [comment]
In fact the client app needs to add such `version` field and provide it to `RemotePlainRtpSdp` SDP handler: `setTransport[Local,Remote]Parameters`.

The app needs to get the `version` out of the `ip` coming from mediasoup.

**Comment by jmillan** [comment]
Example in Node.js:

```js
this.safeEmitAsPromise('@needcreatetransport', transportLocalParameters)
                        .then((transportRemoteParameters) =>
			{
				const { plainRtpParameters } = transportRemoteParameters;

				const version = net.isIP(plainRtpParameters.ip);

				if (!version)
					throw new Error('Invalid IP address in plainRtpParameters');

				plainRtpParameters.version = version;

				// Provide the remote SDP handler with transport remote parameters.
				this._remoteSdp.setTransportRemoteParameters(transportRemoteParameters);
```
