### ISSUE TITLE
Roadmap for mediasoup v3

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#227]
After internal discussions we have decided to start the design of the future `mediasoup` v3. The v2 version has been a great advance and had made possible many scenarios that were impossible in v1 (it introduced `mediasoup-client` which provides a proper and unified API for all the browsers). However we are aware of a big room for improvement in the current v2 design.

## Changes for v3 and their rationale

* `mediasoup` v2 is based on peers. A peer is just a wrapper that holds transports, producers and consumers. However those peers just exist at Node.js level, they do NOT exist at C++ level. Those peers also impose some unnecessary internal design constraints that provide no real benefit. In v3 we'll get rid of "peers". It will be up to the application to manage the concept of peers (if required by the app) or not.

* `mediasoup` v2 depends too much on opaque messages (the [MEDIASOUP_PROTOCOL](https://github.com/versatica/mediasoup-client/blob/master/MEDIASOUP_PROTOCOL.md)) generated by both, `mediasoup-client` and `mediasoup` (server), that must be blindly exchanged between both without the application being aware of what those opaque messages exactly mean. In v3, we'll get rid of those opaque messages and, instead, will provide real JS API calls for both `mediasoup-client` and `mediasoup` to create and manage transports, producers and consumers.

* Make it possible to easily inject external audio/video in `mediasoup` from sources such as `ffmpeg`, `gstreamer`, etc. without requiring `mediasoup-client`. This is **easily** doable in v3. An example using  example using `ffmpeg`: https://github.com/versatica/mediasoup/blob/master/doc/ffmpeg.md

* `mediasoup` v2 can just listen for RTP in a single IPv4 and/or IPv6, making it not possible to run different transports in different IPs (needed in scenarios in which there are external clients but also clients running within backend hosts that may access `mediasoup` using a different IP). In v3, the Node.js app will be responsible of indicating the exact IP or IPs each transport must use.

* `mediasoup` v2 is multi-process. It runs into a single Node.js process and launches N (typically same number as CPU cores) C++ subprocesses: `mediasoup` workers that handle the media layer. Those media workers are single thread (based on `libuv` IO library). However, each room in mediasoup just uses a single worker, which means a single CPU with a single thread. This works very well for some hundreds of participants, but it does not scale well for **broadcasting** scenarios (a few media producers and many many many consumers). `mediasoup` v3 will make broadcasting scenarios possible by allowing a room to use N media worker subprocesses. It will also make it possible to extend a room into N separate hosts running different instances of `mediasoup`.

**Comment by notedit** [comment]
That will be a great change than v2.

**Comment by tkmn0** [comment]
Hi! 
Thanks for good news about mediasoup v3.
I have a question.  How about native mobile client? if "real JS API" supports native client as well, it is good however, if not, should we use react native SDK live mediasoup v2?  
Actually, I'm looking for SFU media server which can handle offer from native mobile clients.

Best regards.

**Comment by ibc** [comment]
> I have a question. How about native mobile client? if "real JS API" supports native client as well, it is good however, if not, should we use react native SDK live mediasoup v2?

There is an open issue for this: https://github.com/versatica/mediasoup-client/issues/6

However, we have not received any contribution. Building a native SDK requires time and expertise. We, the mediasoup developers, can rely on `react-native-webrtc` (even if ugly) for now, but it requires a JS client (in this case `React Native`) which is not the only choice when it comes to build mobile apps. We agree that a proper C++ `mediasoup-client-native` with bindings for Android and iOS would be great, but we need help on this or someone who pay us for coding it.

I wrote [libsdptransform](https://github.com/ibc/libsdptransform), which is a C++ port of the `sdp-transform` JS library (internally used by `mediasoup-client`)  but more pieces are needed to create `mediasoup-client-native`.

**Comment by ibc** [comment]
> mediasoup client using (or almost force to using) your signal server. i agree it make things simple. but i like socket.io as signal server. just personal choice.

This si completely false. We've NEVER recommended using ANY signaling protocol. The documentation clearly says that mediasoup does not mandate any sig protocol, and there is even a Examples section with mediasoup examples using different signaling solutions:

https://mediasoup.org/documentation/examples/


> so,i don't think "improve performence" in V3 is important. to be honest ,who will use nodejs do a heavy job?

No idea. May be Netflix? PayPal? are those good examples of applications running on top of Node that also require a very good performance?

BTW `mediasoup` exposes its API in Node but it manages audio/video in C/C++.

> and,if we talk VC, the biggest problem is bandwidth.before we exceed mediasoup performance limit, the bandwidth or udp package crash the server 99999999 times.

Bandwidth is not a problem if you can run parallel servers. That's one of the features that mediasoup v2 will enable.

> personally, i want mediasoup has more function, can export "stream/rtp" object /data ... etc.but,it is your project, you are the god.

You are welcome to propose those features you wish. Have you requested them before?

**Comment by notedit** [comment]
> This works very well for some hundreds of participants, but it does not scale well for broadcasting scenarios (a few media producers and many many many consumers)

In this case,  how the sender side handle  PLI/FIR ?    If  we have several watcher  has very poor  network, there will  be many  PLI/FIR requests I think.

**Comment by xxxman2008** [comment]
hi, ibc , take easy .

   I read the whole document about mediasoup .  I know mediasoup "NEVER recommended using ANY signaling protocol."  .  But ,in  real life ,if somebody want  his project online ASAP,  it's better to using "Pxxx server".  i forgot the name.   So it 's why i said "force to using"  ..maybe ,i should say " for lazy man".  haha.

  I applaud mediasoup exposes its API in Node but it manages audio/video in C/C++. It's a good design.  In fact, i have test using pure nodejs to proceed "media stream regarding" task.  such as  RTMP /FLV.  You know the result.   That's  why  i say "who will use nodejs do a heavy job".

Have you requested them before?  ---  OK ,  i just told you yesterday ..hahah.    from my post ,you know my english is poor. so , usually , i will not say much.

Regarding the "bandwidth" , it's  a huge topic.  From my experience, in following scenario.
10 people Video conference ,every body publish 1280x720@25/30fps (720p) , 1M bps bitrate,CBR
in SFU mode, One "server side" peer require bandwidth :
1 inbound stream:  1M bps ( let's say ,this number is min require for user experience )
9 outbound stream : 9x1M bps
So, the total bandwidth for  one "server side peer" is  9M bps(out).  10 people should  require 10x9M = 90M bps out . 
For a server have 1G bps Internet line ,   in above scenario,  100 people will consume the whole internat bandwidth. ( In real life ,we also should  consider PPS(package per second) , "real time audio/video" ...etc.  ).  That's  why i say "before we reach the performance bottle.....".    You can not expect distributed design will resolve this problem .
And  in MCU mode , transcode CPU usage is the bottle.  also  not the mediasoup business.
Maybe , netfix server equiped 10G NIC (and direct int ernet link),but i don't think mediasoup cann't handle it.  That's why i say " the performance is not most important task for V3".

Just my opinion , V2 and mediasoup-client is enough for  application development. It's time to make it stable , provide more function/api . for example :
 1 -  Integrate/plugin for "SIP" cooperation( so ,if boss have no internet access ,he can join the meeting via PSTN ).
2 - Integrate OpenCV or  filter function or mixer function , so , the user can do some funny job with rtp stream .

BTW:  i  really really want to say "you do a  good job". sincerely .

**Comment by ibc** [comment]
> > This works very well for some hundreds of participants, but it does not scale well for broadcasting scenarios (a few media producers and many many many consumers)
> 
> In this case, how the producer side handle PLI/FIR ? If we have several consumers has very poor network, there will be many PLI/FIR requests I think.

Currently the `Producer.cpp` class in mediasoup server already limits the number of PLI/FIR sent to the client. Basically, no more than 1 PLI/FIR per second is sent. If another PLI/FIR is requested in the meanwhile, it's delayed.

Said that, there is a simple rule here: just the encoder can process a PLI/FIR and generate the corresponding keyframe. So, when in a SFU scenario, that is the remote client.

**Comment by xxxman2008** [comment]
> What we (also) want to promote in mediasoup v3 is the ability to create server-side media producers that inject streams into a `mediasoup` instance. Those producers may run in the same or in different server. And we'll try to make it easier to develop those producers in any language.
> 
That's ok .  Do you mean  anyone using mediasoup can  take streams  out , do some job ,and then put it back??  or ,  insert/replace  streams into "server side peer"  ?

Anyway ,these ideas is great. So,  the filter/mixer/CV/AI  can be true. up to application developer.

**Comment by ibc** [comment]
> Do you mean anyone using mediasoup can take streams out , do some job ,and then put it back?? or , insert/replace streams into "server side peer" ?

It's not mediasoup the entity who will do such as "job". The picture would be as follows:

* Browser A sends video to mediasoup.
* mediasoup forwards that video stream to another node via sig+RTP (that node is a `consumer`).
   * Such a node may run in same or different host.
* Such a node processes the video, converts it, etc, and sends it back to mediasoup via a new `producer`.
* mediasoup forwards that new video to browser B and browser C.

**Comment by Flamenco** [comment]
Just piping in my 2 cents here, but I would like to add some thoughts to the V3 horizon.

I started using Mediasoup because I wanted to broadcast from a browser.  I had 3 choices for architecture:  mesh, peer-to-peer downstream distribution, and server based.  Because I also wanted to record all streams on the server, Mediasoup was the best choice.  I really liked it's simple and universal API on the client, and ability to run without installing a separate server daemon.  Furthermore,  the node wrapper around a C-based core installs seamlessly.  If I had any other use-case, I would not have gone with Mediasoup.

I am happy to see that the 'broadcast' use case is high on the priorities!  What I do not understand is the discussion around the limiting factor when broadcasting.  It seems to me that the focus should be on running multiple instances of MediaSoup on multiple networks to scale horizontally.  No matter how much we refactor and/or streamline the API, the biggest issue when it comes to broadcasting will always be performance on production systems.

So I would like to see a system to easily create, configure, and monitor a network Mediasoup servers that provides load-balancing and fault tolerance.

**Comment by Flamenco** [comment]
Hello @ibc.  Thank you for responding.  I did read bullet #4.  My issue is that my bandwidth, not my CPU, is the limiting factor.  Once my application has a certain number of (publishers x subscribers), I will need to run on another physical network.  On my LAN, I have 8 servers, each with 12 CPUs and 100 GB RAM.  No matter how much you optimize your code, my WAN network is the limiting factor.

> The API refactor has a different motivation

That's my concern.  I was hoping we could consider all the options before you start your journey. 

> mediasoup v3 will allow that and also horizontal scaling via separate servers

I don't see this 'horizontal scaling' in the original post or anywhere else for that matter..  If that's the case, great!

**Comment by ibc** [comment]
We cannot do magic to increase WAN network bandwidth. However streaming servers do exist. I assume they solve the network issue somehow.

**Comment by ibc** [comment]
I hope this will help people here understand the motivation for the new broadcasting design in v3:

https://github.com/versatica/mediasoup/blob/master/doc/Charts.md

**Comment by ibc** [comment]
@notedit, please take a look to the issue description, I've updated it with info about "PLIs every two seconds".

**Comment by ibc** [comment]
For all those interested in how the v3 API will look like, here a test unit that makes use of all the API in **mediasoup-client v3**:

https://github.com/versatica/mediasoup-client/blob/v3/__test__/test.js?ts=2

**Comment by yarekc** [comment]
please don't make a protoo/reactjs gas factory for demo.
Provide some simple : pubsihStream(streamid) and playStream(streamid) function that will fit 99% of all developers needs !

**Comment by ibc** [comment]
There are already N mediasoup example apps running vanilla JS. Please don't reopen such a request here again.

**Comment by ibc** [comment]
> I am asking for 2 functions that will make it even easier to be used.

[This](https://github.com/versatica/mediasoup-client/blob/v3/__test__/test.js?ts=3) is the API in `mediasoup-client` v3.

> When using flashphoner, antmedia, red5pro or wowza people handle 3 functions:
> publish, play, record

You can use them if you are fine with the API they expose. `mediasoup` will be as low level API as possible to allow any kind of scenario (meetings, broadcasting, etc).

**Comment by ibc** [comment]
> When using flashphoner, antmedia, red5pro or wowza people handle 3 functions:
> publish, play, record

In mediasoup-client v3:

```js
// Send a track.
const audioProducer = await sendTransport.send({ track });

// Receive a track.
const audioConsumer = await recvTransport.receive({	producerId });

// Play the received track into an HTML <audio> element.
audioElem.srcObject = new MediaStream([ audioConsumer.track ]);
```

And, of course, communicate those actions (when appropriate) to the server to call `mediasoup` server API methods on the corresponding entity (Transport, Producer, etc).

**Comment by yarekc** [comment]
**that's brilliant**. If could could embed that into you demo, that would be perfect.
Ex: how to get the producerId in the recvTransport or set it on sendTransport.
Thanks again.

**Comment by yarekc** [comment]
Thanks IBC,

Do you have an idea when v3 will be online ?
Do you plan to create this Faq: 
- How do I publish a stream ?
- How do I play a stream ?
- How do I record a stream ?
(and promise I will stop harassing you)
Regards

**Comment by ibc** [comment]
Well, you talk like if mediasoup V2 documentation did not explain how to publish a stream, doesn't it?

Anyway, mediasoup does not manage streams (MediaStream instances) but tracks (MediaStreamTrack instances). Hope that's not a problem.

**Comment by ibc** [comment]
For those who would like to know how to use `ffmpeg` in mediasoup v3 to send (for example) and audio file, take a look to [this](https://github.com/versatica/mediasoup-client/blob/v3/doc/ffmpeg.md).

**Comment by mpbikc** [comment]
And how long we shourl wait for v3 version? I see, you have started. But when we will see first release - it is 1 month, or may be half year?
As for me I wanted to migrate from kurento to mediasoup but faced with 2 big problems. I think most of developers will face with them(yarekc, me - are examples):

1) I read all mailing lists, all documentation, but couldn't find good way to record video.
I created RtpStreamer( via
`room.createRtpStreamer(producer, {.....`
And then I tryed to use ffmpeg, like

> v=0
> o=mediasoup 7199daf55e496b370e36cd1d25b1ef5b9dff6858 0 IN IP4 127.0.0.1
> s=7199daf55e496b370e36cd1d25b1ef5b9dff6858
> c=IN IP4 127.0.0.1
> t=0 0
> m=video 20000 RTP/AVP 101
> a=rtpmap:101 H264/90000
> a=sendrecv
> 

`ffmpeg -protocol_whitelist "file,rtp,udp" -vcodec h264 -re -i video_sdp -vcodec copy video_out.mp4`

And the same for opsus video, but audio and video were not synchronized and I don't know how automatically do it.

I tryed gstreamer - it worked better:

```
gst-launch-1.5 -em \
  rtpbin name=rtpbin latency=5 \
  udpsrc port=20002 caps="application/x-rtp,media=(string)audio,clock-rate=(int)48000,encoding-name=(string)OPUS" ! rtpbin.recv_rtp_sink_0 \
    rtpbin. ! queue ! rtpopusdepay ! opusdec ! audioconvert ! audioresample ! voaacenc ! mux. \
  udpsrc port=20000 caps="application/x-rtp,media=(string)video,clock-rate=(int)90000,encoding-name=(string)H264" ! rtpbin.recv_rtp_sink_1 \
    rtpbin. ! queue ! rtph264depay ! h264parse ! mux. \
  flvmux name=mux streamable=true ! filesink location=/home/oracle/test/q1.mp4
```

Sometimes video and audio were synced, but sometimes not. Also that convertation eats about 5% of CPU. So If I want to record with gstreamer  - I'll can support few streams on one machine. And As i noticed - record is not stable.

I undertand, that mediasoup is just base platform, but if you will write any example how with createRtpStreamer create stable record - huge number of developers wil say you 'THANKS!!!'


2) The second problem - I could'n find way how to translate streams via RTP from one ms to another. In last example for v3 you  talked how [with createPlainTransport do that](https://github.com/versatica/mediasoup-client/blob/v3/doc/ffmpeg.md), but in version 2 documentation dont explain that.

Without 2 that things no large product can be created with mediasoup,thow it works great for just retranslating streams.

I hope you will listen to that and create some howto(or best practive) with most important things for v3.

**Comment by ibc** [comment]
> And how long we shourl wait for v3 version? I see, you have started. But when we will see first release - it is 1 month, or may be half year?

We want to have a first v3 version for end of January, but cannot provide a specific ETA.


> I read all mailing lists, all documentation, but couldn't find good way to record video.

The `RtpStreamer` class will be removed in v3. At the end, in v2 it's just a `Consumer` plus a plain `RtpTransport` that can just be used to broadcast a specific `Producer` to a plain RTP remote endpoint.

In v3, the Node app will be able to create any kind of transports (WebRTC or plain RTP) and use them to broadcast **N** `producers` to a remote endpoint, but will be also able to inject external RTP into that transport and generate **M** `producers.

I don't think `ffmpeg` is good to save both audio and video. AFAIK it has a very poor RTCP support (no NACK support for instance). I expect `gstreamer` to be much better. However in v2, and as you posted in your comment, two different transports are required. In v3 you'll be able to bind `gstreamer` in a single port to receive both audio and video (assuming `gstreamer` supports it). That may help. You may also want to try the new [gst-plugins-bad-plugins-webrtcbin](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-bad/html/gst-plugins-bad-plugins-webrtcbin.html).

> The second problem - I could'n find way how to translate streams via RTP from one ms to another. In last example for v3 you  talked how [with createPlainTransport do that](https://github.com/versatica/mediasoup-client/blob/v3/doc/ffmpeg.md), but in version 2 documentation dont explain that.

Well, that's because it's a feature for v3 :)
It will be documented when done.

**Comment by havfo** [comment]
Great work on v3 so far!

In our project we plan on having a hybrid peer-2-peer and SFU mode, and the new architecture seems to make this much easier. We have a, so far, unpublished fork of mediasoup-client rewritten for peer-2-peer, but it is not very elegant to use two libraries together that handle everything up to and including Room level.

**Comment by havfo** [comment]
Yes, we use socket.io at the moment, and for peer-2-peer, the messages are passed directly to the other peer(s). So our mediasoup-client fork is talking to itself on the other side.

**Comment by ibc** [comment]
mediasoup-client v3 will just work with mediasoup v3.

Anyway v3 drops the "MEDIASOUP_PROTOCOL" so there isn't so much dependency between client and server anymore. In fact, in v3 it will be possible to publish media into the server without using mediasoup-client, for example using ffmpeg: https://github.com/versatica/mediasoup/blob/v3/doc/ffmpeg.md

**Comment by virtualfunction** [comment]
OK, that makes sense. Out of curiosity, what's sort of ball-park / estimated time frames do you have in mind here? 

I'm fairly new to MediaSoup, but dabbled with Kurento a while back only to find the development has ground to a halt. So it's nice/reassuring to see a project like this where there's lots of activity.

The reason I ask about time frames is that I'm trying to assert if I develop something against v2 knowing that I'll need to rewrite it when v3 comes out, as these appear to be significant design overhaul, or am I better to wait a bit but try and develop against the bleeding edge v3 release and save myself a few rewriting chores later on. It looks like v2 provides a number of high level abstractions / concepts (i.e. Rooms / Peers, etc) that will won't be there out of the box in v3. Obviously these abstractions seem to help with general use cases, but come at the cost of not always being as helpful for more niche use cases, and I'm guessing this is a motivating factor for this change.

I guess this goes on to another question that I'm sure others might also be thinking about... Do you think you'll be writing some sort of wrapper library that works with v3 that effectively allows for a more graceful transition?

On an unrelated note, the FFMPEG stuff looks great, it's just the sort of thing I'll be needing in due course as our broadcasting goes through a bit of pre-processing, so looking forward to this. From what I can infer, it looks like this will work with other media stacks like gstreamer too.

**Comment by ibc** [comment]
> OK, that makes sense. Out of curiosity, what's sort of ball-park / estimated time frames do you have in mind here?

We want to have a preliminar v3 version ready during February.

> The reason I ask about time frames is that I'm trying to assert if I develop something against v2 knowing that I'll need to rewrite it when v3 comes out, as these appear to be significant design overhaul, or am I better to wait a bit but try and develop against the bleeding edge v3 release and save myself a few rewriting chores later on. It looks like v2 provides a number of high level abstractions / concepts (i.e. Rooms / Peers, etc) that will won't be there out of the box in v3. Obviously these abstractions seem to help with general use cases, but come at the cost of not always being as helpful for more niche use cases, and I'm guessing this is a motivating factor for this change.

Since you perfectly got the motivation for v3 I encourage you to wait for it, yes.

> I guess this goes on to another question that I'm sure others might also be thinking about... Do you think you'll be writing some sort of wrapper library that works with v3 that effectively allows for a more graceful transition?

IMHO it would be a super wrapper library for both client and server side. I don't think we'll do something like that. We'll try to focus on proper documentation (much better than now).

> On an unrelated note, the FFMPEG stuff looks great, it's just the sort of thing I'll be needing in due course as our broadcasting goes through a bit of pre-processing, so looking forward to this. From what I can infer, it looks like this will work with other media stacks like gstreamer too.

Yes sure, as far as you can decide some RTP parameters such as codec name, payload type, ssrc, etc, you should be able to use any RTP stack to produce media into mediasoup v3.

**Comment by ibc** [comment]
We'll do big improvements in documentation for v3.

**Comment by Globik** [comment]
"And we'll try to make it easier to develop those producers in any language."

Please for C programming language too.

**Comment by yarekc** [comment]
hi,
Any news about v3 availability ?

**Comment by ibc** [comment]
You can check the progress in the `v3` branch of mediasoup, the `master` branch of mediasoup-client, and the `v3` branch of the mediasoup-demo project.

**Comment by ibc** [comment]
Hi all. mediasoup v3 is close. We are refactoring the simulcast stuff. Everything else is working fine and the new API looks very nice (IMHO).

There is no yet API documentation. However, those interested in v3 may take a look to the new [mediasoup-demo v3 branch](https://github.com/versatica/mediasoup-demo/tree/v3).

**Comment by lakano** [comment]
@ibc Thanks for your work! Do you have any idea of when the API v3 documentation could be available please? ( few days ? few weeks ?)

**Comment by ibc** [comment]
Let's say some weeks.

**Comment by Globik** [comment]
@lakano the idea is always there! But how to npm install mediasoup v3.0 on your computer?

**Comment by ibc** [comment]
> But how to npm install mediasoup v3.0 on your computer?

There is no npm package yet...

**Comment by denisrocks** [comment]
> @lakano the idea is always there! But how to npm install mediasoup v3.0 on your computer?

```
{
    "mediasoup-client": "git://github.com/versatica/mediasoup-client.git#master"
}
```

See more https://docs.npmjs.com/files/package.json#dependencies

**Comment by Globik** [comment]
Hey, @ibc , get rid of f***ing reactjs in your demo part. It's s*ck

**Comment by jmillan** [comment]
> Hey, @ibc , get rid of f**ing reactjs in your demo part. It's sck

@Globik, be original and build your own app instead of reusing a demo.

**Comment by ibc** [comment]
> Hey, @ibc , get rid of f**_ing reactjs in your demo part. It's s_ck

Oh sure!
I'll get rid of it because you don't like it.
And I'll do it for free to make you happy.
I'll rewrite the demo to vanilla JavaScript in 2030.
Anything else?

**Comment by yarekc** [comment]
:)
The demo is GREAT, but a little bit complex for people who starts with mediaSoup

But would be also great if we can have smaller snippets to start with
Thanks again for great work

**Comment by ibc** [comment]
Guys, still working in v3 which, indeed, will include much better doc and code snippets. It's just that we have not finished it yet.

**Comment by yarekc** [comment]
The demo is more like a showcase: this is what you achieve do... if you have good doc :)

**Comment by JanNemcik** [comment]
Hi, do you already now, when could the v3 be released? At least approximately, because we decided to use mediasoup for our project, which is gonna be more complex, so if we could start with the v3, that would definitely great, as there are really good improvements and simplifications.

**Comment by ibc** [comment]
v3 will be ready (if everything goes well) in some weeks. You can start using it already since the API is not gonna change much (in both mediasoup and mediasoup-client). However the API documentation is not yet written. You can use the mediasoup-demo project (branch "v3") as reference for now.

**Comment by JanNemcik** [comment]
@ibc thanks for your quick response, I'm glad to heat, that it's gonna be released in a few weeks

**Comment by Thooto** [comment]
Hi, firstly thanks a lot for this great project ! I really look forward for the completion of the v3 :)

Maybe you could help me on this one : I wish to use mediasoup together with an extra machine learning layer to analyse the video streams in real time, which would make use of the currently experimental workers feature of node.js (thus node's single thread base architecture shouldn't be a performance issue).

For this I would need to extract each frame of the streams (to pass them to the video analysis workers). Is there a way to do so with mediasoup v3 (as it seemed to be possible in the v1, referring to [your answer here](https://github.com/versatica/mediasoup/issues/27#issuecomment-219433728) if I understood correctly) and if so, any hint on how I could do it ?

Thank you !

**Comment by ibc** [comment]
With mediasoup v3 is terribly easy to forward a video stream to whichever endpoint (using plain RTP over UDP) and the other way around: injecting plain RTP from any endpoint.

Getting RTP packets via JavaScript events was dropped in v2. It's much more efficient to route them to any destination via UDP. Probably, by using GStreamer or similar you can consume those RTP packets and use them as your wish.

**Comment by Thooto** [comment]
Okay, that's what I understood from exploring the v2 but I wasn't sure about the reasons why it was dropped. I'll try working with gstreamer then ! Thanks for answering so quickly !

**Comment by ibc** [comment]
We could add it back. However it's really CPU expensive since all RTP packets must be serialized from C++ to the mediasoup Node process via IPC (connected Unix Sockets).

**Comment by jiyeyuran** [comment]
> mediasoup v3 will make broadcasting scenarios possible by allowing a room to use N media worker subprocesses. It will also make it possible to extend a room into N separate hosts running different instances of mediasoup.

Is this feature ready? It is possible to use plain RTP to achieve the goal.

**Comment by ibc** [comment]
Yes, it's ready, but not yet documented. Working on the v3 API documentation these days. We'll announce it in the mediasoup mailing list when ready.

**Comment by antidigital** [comment]
> I hope this will help people here understand the motivation for the new broadcasting design in v3:

Our test result show CPU almost exhausted when participants reaches 400+.  We already fixed a performance issue on std::list::size() caused by old gcc. gprof result shows most consuming api is sha related. Is it reasonable? I can only assume the test report your present is conducted without dtls ?

**Comment by Globik** [comment]
@antidigital how much CPUs on board?

**Comment by antidigital** [comment]
> @antidigital how much CPUs on board?
32, but does this matter? Of cause, I mean single core exhausted, from command top.

**Comment by ibc** [comment]
### Current status of mediasoup v3

Almost done. We are just adding sender-side bandwidth estimation (for now with REMB, Transport-CC will be added next) for automatically upgrade/downgrade simulcast spatial and temporal layers based on the endpoint's available bandwidth.

v3 documentation is work in progress but some sections are already written. Those are:

- The mediasoup v3 API (completed):
https://mediasoup.org/documentation/v3/mediasoup/api/

- Detailed information about "RTP Parameters and Capabilities" used in
mediasoup v3:
https://mediasoup.org/documentation/v3/mediasoup/rtp-parameters-and-capabilities/

- RTC Statistics in mediasoup v3:
https://mediasoup.org/documentation/v3/mediasoup/rtc-statistics/

**Comment by ibc** [comment]
A new section has been added explaining some important differences
between mediasoup v2 and v3:

https://mediasoup.org/documentation/v3/differences-between-v2-and-v3/

**Comment by Thooto** [comment]
Hi!
Thanks for the great advance on the v3! Really looking forward to trying it out 😃

> We could add it back. However it's really CPU expensive since all RTP packets must be serialized from C++ to the mediasoup Node process via IPC (connected Unix Sockets).

Maybe what I'll say is unfounded, but the other day I read about [Node C++ addons](https://nodejs.org/api/addons.html) which seem to offer a way to share memory between C++ programs and Node. Have you already heard of or considered this? I'm asking because I was thinking this could be a way to share packets directly with Node. But as I'm far from being comfortable with all the concepts involved with RTC, I can just ask you about this. I hope it makes some sense.

Cheers

**Comment by ibc** [comment]
That's true, but honestly I do not want to depend on Node addons internals for media processing. As the [FAQ](https://mediasoup.org/faq/#is-mediasoup-a-native-addon) says:

> mediasoup launches a set of C++ child processes (media workers) and communicates with them by means of inter-process communication. This approach leads to a media worker design not tiled to the internals of Node.js or V8 (which change in every new release).

Making the mediasoup worker a Node addon would also mean that both, the signaling plane and the media process, run in the same process. In mediasoup we can launch N workers (subprocesses).

Said that, in v3 is easy to forward a RTP stream to a UDP destination (can be localhost). And such a UDP destination can even be a Node.js UDP socket that reads the RTP packets being received on it.

**Comment by ibc** [comment]
> Thanks for the great advance on the v3 ! Really looking forward to trying it out 

BTW you can already try it. Just the sender-side bandwidth estimation is missing (working on it). The API is finished and documented. The mediasoup-client v3 API is not yet documented, but you can figure it out by checking the mediasoup-demo app.

**Comment by Thooto** [comment]
Okay, I understand the reasons for not using node addons, I wasn't sure whether you could create subprocesses with it. Anyway the RTP stream to UDP destinations seems to be a more than perfect solution for what I plan to do.
> BTW you can already try it.

True, that's just because I don't have the time yet to experiment with it :)

**Comment by ibc** [comment]
> Anyway the RTP stream to UDP destinations seems to be a more than perfect solution for what I plan to do.

Just in case, I've found a RTP parser for Node (I've not tested it):

https://github.com/fleg/rtp-parser

**Comment by Globik** [comment]
How about npm packet to test mediasoup v3? Or is better  to clone it from this github repo?

**Comment by ibc** [comment]
> How about npm packet to test mediasoup v3? Or is better to clone it from this github repo?

NPM packets will be published when v3 is released, not before. You can clone from GitHub for testing purposes.

**Comment by ibc** [comment]
mediasoup v3 is almost ready. [Sender side bandwidth estimation](https://github.com/versatica/mediasoup/commit/56d53011d46bc8108064814ac1141e0179062481) has been implemented, meaning that mediasoup now properly adapts the sending spatial and temporal layers based on the network capability of each remote consumer, which is a **huge** improvement.

As a side note, the API documentation of mediasoup v3 is already done:

v3 documentation is work in progress but some sections are already written. Those are:

* The mediasoup v3 API (completed):
https://mediasoup.org/documentation/v3/mediasoup/api/

* Detailed information about "RTP Parameters and Capabilities" used in
mediasoup v3:
https://mediasoup.org/documentation/v3/mediasoup/rtp-parameters-and-capabilities/

* RTC Statistics in mediasoup v3:
https://mediasoup.org/documentation/v3/mediasoup/rtc-statistics/

Working on the remaining documentation before releasing v3 packages. Let's close this issue since everything.
