### ISSUE TITLE
restart ice (forceTcp) cause consumers transport ice failed

### ISSUE THREAD

**Issue by yangjinecho** [versatica/mediasoup#228]
https://demo.mediasoup.org/?roomId=ylaq1tfh&forceTcp=true

restart ice (forceTcp) cause consumers transport ice failed

sorry for my pool english

**Comment by ibc** [comment]
Thanks. It was due to a bad decision in `WebRtcTransport.cpp` in which, when ICE disconnection happens (just possible in ICE over TCP) we closed the Transport.

Fixed in mediasoup 2.4.6.
