### ISSUE TITLE
PLI/FIR improvements

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#232]
* [ ] Should generate PLI / FIR for specific SSRC. Currently we generate PLI or FIR for all the SSRCs (in case of simulcast). Sometimes we just need a PLI / FIR for a specific SSRC (and avoid sending 3 PLIs instead of just one). This is harder than it seems due to how we use the `requestKeyframe()` method in Consumer, Producer and Transport.
* [ ] Currently the producer limits to 1 PLI every two seconds. If two PLIs are requested together, the second one is delayed for 1 second, and then a PLI is sent to the producer. The problem here is that, at that time, we may already receive a keyframe for the producer so sending a new PLI to the producer is a waste of resources. The producer should clean the "PLIs queue" (unset the flag and stop the timer) for every received keyframe.
   * **IMPORTANT:** As said in previous bullet, we cannot assume that, upon a PLI for any SSRC, the browser will generate keyframes for all video profiles. The producer "PLI queue" should treat independently PLIs for different profiles.
   * Issue reported in libwebrtc tracker: https://bugs.chromium.org/p/webrtc/issues/detail?id=10107

**Comment by ibc** [comment]
Done in v3 [here](55886a57a99217615d17efc691e90b0a243ffaaf) by using the new `KeyFrameRequestManager` class.

**Comment by yangpeiyong** [comment]
Could we cache keyframe data, and send them to consumer directly when receive PLI/FIR? So that we don't need to send PLI/FIR to producer.

**Comment by ibc** [comment]
That's not how RTP video works.
