### ISSUE TITLE
supportedRtpCapabilities: update rtcpFeedback

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#233]
Currently in v2, mediasoup is announcing these `rtcpFeedback`:

```js
rtcpFeedback :
[
	{ type: 'nack' },
	{ type: 'nack', parameter: 'pli' },
	{ type: 'nack', parameter: 'sli' },
	{ type: 'nack', parameter: 'rpsi' },
	{ type: 'nack', parameter: 'app' },
	{ type: 'ccm', parameter: 'fir' },
	{ type: 'ack', parameter: 'rpsi' },
	{ type: 'ack', parameter: 'app' },
	{ type: 'goog-remb' }
]
```

However, I don't think we support ' ack' , and not sure about others.

@jmillan can you please check them?

**Comment by ibc** [comment]
We should also update [doc/RTCP.md](https://github.com/versatica/mediasoup/blob/master/doc/RTCP.md). I don't think this is correct:

> BYE
> BYE information will be relayed from the remote RTP sender to the corresponding remote RTP receivers.

Not true.

> App
> App information will be relayed from the remote RTP sender to the corresponding remote RTP receivers.

Should not be true.

> XR
> The same logic is applied as to Receiver Reports.

We don't support XR.

> TMMBR / TMMBN
> RTCP-SR-REQ

We should not relay them.

> RAMS
> Applicable on multicast sessions.

WHAT?

etc

**Comment by jmillan** [comment]
```
rtcpFeedback :
[
	{ type: 'nack' },
	{ type: 'nack', parameter: 'pli' },
	{ type: 'nack', parameter: 'sli' },
	{ type: 'nack', parameter: 'rpsi' },
	{ type: 'nack', parameter: 'app' },
	{ type: 'ccm', parameter: 'fir' },
	{ type: 'ack', parameter: 'rpsi' },
	{ type: 'ack', parameter: 'app' },
	{ type: 'goog-remb' }
]
```
We do support all of them.

Those that we don't terminate are forwarded to the remote producer per design.

https://github.com/versatica/mediasoup/blob/master/worker/src/RTC/Transport.cpp#L195

**Comment by jmillan** [comment]
> We should also update doc/RTCP.md. I don't think this is correct:

true. It's damm old.

**Comment by ibc** [comment]
Done in v3.
