### ISSUE TITLE
PacketLoss forwarding for Opus

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#234]
Opus has an inband mechanism to send inband FEC. It's based on the `packetsLost` and/or `fractionLost` in the `ReceiverReports` received by the browser. If those are high, the browser sends more FEC. But, if mediasoup generates those `ReceiverReports` based on how it receives audio from the browser, the browser cannot adapt its inband FEC based on the worst `Consumer` (in Opus there is no NACK).

### Proposal

* If the audio Producer codec announces `useinbandfec=1`  (as OPUS does), when the mediasoup `RtpStreamRecv` (the one receiving the OPUS audio from the browser) needs to generate its own `ReceiverReport` it will ask all the `Consumers` about their last received `fractionLost` value (in `ReceiverReports` received from remote listeners).
* And it will choose the worst value and mangle the RR sent to the producer with that value in the `fractionLost` and the corresponding value in `packetsLost`.

**Comment by ggarber** [comment]
I think it should be the maximum and not the average of the remaining Consumers packetLoss values.

**Comment by ibc** [comment]
Wouldn't that be too hard? If there is a remote consumer with super bad network, should all the others be their inbound traffic super increased?

**Comment by ibc** [comment]
RFC 6716 and 8251 define the OPUS codec. Not sure what they say about how in band FEC must behave.

**Comment by ibc** [comment]
They say nothing...

**Comment by jmillan** [comment]
[here(https://tools.ietf.org/html/draft-ietf-rtcweb-fec-08#section-8)

**Comment by ibc** [comment]
@jmillan add your maths magic!

21fc53a11a8d8cecc5552038dc76483523afa427

**Comment by ibc** [comment]
We have a problem. Scenario:

* Producer sends audio and video on same transport.
* So we, mediasoup, generate RR with high frequency.
* The receiver just receives audio so sends as RR less often.
* Since we reset `worstRemoteFractionLost` after each RR generation, this means that for every 3-4 RRs we sent, we just apply the `worstRemoteFractionLost` in one of them.

So, if the audio Producer has 0 fraction lost and the receiver has 15 fraction lost (in every RR) we'd end sending RRs to the sender as follows:

* RR fractionLost: 15
* RR fractionLost: 0
* RR fractionLost: 0
* RR fractionLost: 15
* RR fractionLost: 0
* RR fractionLost: 0

In fact, I've added some logs and it's exactly what it happens:

```
  mediasoup:ERROR:worker[pid:61750] RTC::RtpStreamSend::ReceiveRtcpReceiverReport() | ---- RR received +2s
  mediasoup:ERROR:worker[pid:61750] RTC::RtpStreamRecv::GetRtcpReceiverReport() | ---- RR sent +323ms
  mediasoup:ERROR:worker[pid:61750] RTC::RtpStreamSend::ReceiveRtcpReceiverReport() | ---- RR received +2s
  mediasoup:ERROR:worker[pid:61750] RTC::RtpStreamRecv::GetRtcpReceiverReport() | ---- RR sent +2s
  mediasoup:ERROR:worker[pid:61750] RTC::RtpStreamRecv::GetRtcpReceiverReport() | ---- RR sent +39ms
  mediasoup:ERROR:worker[pid:61750] RTC::RtpStreamSend::ReceiveRtcpReceiverReport() | ---- RR received +3s
  mediasoup:ERROR:worker[pid:61750] RTC::RtpStreamRecv::GetRtcpReceiverReport() | ---- RR sent +2s
  mediasoup:ERROR:worker[pid:61750] RTC::RtpStreamRecv::GetRtcpReceiverReport() | ---- RR sent +689ms
  mediasoup:ERROR:worker[pid:61750] RTC::RtpStreamSend::ReceiveRtcpReceiverReport() | ---- RR received +3s
  mediasoup:ERROR:worker[pid:61750] RTC::RtpStreamRecv::GetRtcpReceiverReport() | ---- RR sent +2s
  mediasoup:ERROR:worker[pid:61750] RTC::RtpStreamRecv::GetRtcpReceiverReport() | ---- RR sent +358ms
```

Here a different approach:

* When the `RtpStreamRecv` of the Producer must generate its RR, it asks in that moment to all Consumers about their fraction lost and takes the worst one.
* However this design "breaks" or "events" based model.

@jmillan thoughts?

**Comment by ibc** [comment]
Almost done, wait...

**Comment by ibc** [comment]
Much better now: 69fd61b9fa0e68ce1808baef2e131d1ee0d653a7. Thanks for the tip @ggarber!

@jmillan, [here](https://github.com/versatica/mediasoup/blob/69fd61b9fa0e68ce1808baef2e131d1ee0d653a7/worker/src/RTC/RtpStreamRecv.cpp#L173) the TODO code. Basically, if `worstRemoteFractionLost > 0` it must be used to affect the resulting `packetLost` and `fractionLost` of the generated RR.

**Comment by jmillan** [comment]
Would it be necessary to adapt the `packetLost` of the generated RR as well as `fractionLost`?

I would say so, in order to be consistent, but I'm not sure here.

**Comment by ggarber** [comment]
Fast and great! The changes in 69fd61b look great.

For your consideration I think I don't update the packetsLost field because AFAIK that is only used for statistics and it is not clear it is better to have the publisher packets lost vs the worst subscriber packets lost in the statistics.   I'm not agains that either.

Good job!

**Comment by ibc** [comment]
Thanks. We are just mangling with "worst remote fraction lost" the `ReceiverReport` that we send to the publisher, but internally we store the real values. Our question is just whether, in the mangled RR we send to the publisher, we should mangle not just the `fractionLost` value but also the `packetsLost`. They both are 100% related so we think think that we must mangle both (otherwise they are inconsistent).

**Comment by ibc** [comment]
It seems that we are done!

### Scenario

* A peer producing OPUS audio (with `useinbandfec=1`).
* A peer consuming that OPUS audio.
* Downlink packet lost of 25% (with OSX Network Conditioner).

The producer is receiving mangled `ReceiverReport` with `fractionLost: 55`. Note that the maximum value is 255 (100% packet lost) and 55/255 = 0.21 (close to 25% so it makes sense):

<img width="1439" alt="screenshot 2019-02-12 at 23 00 49" src="https://user-images.githubusercontent.com/16191/52671576-b80d1b80-2f1b-11e9-9af1-9f30af1a272c.png">

The producer browser gets those values in the `ReceiverReport` it receives from mediasoup:

<img width="693" alt="screenshot 2019-02-12 at 23 00 30" src="https://user-images.githubusercontent.com/16191/52671704-12a67780-2f1c-11e9-9cf5-3154ad370c51.png">

* Increasing downlink packet lost to 75% we get:

> [local packetsLost/fractionLost:15/0, worst remote packetsLost/fractionLost:2647/195]

Note that 195/255 = 0.76 (close to 75% so it makes sense).

Also, the audio uplink bitrate is increased due to in band FEC:

<img width="332" alt="screenshot 2019-02-12 at 23 07 19" src="https://user-images.githubusercontent.com/16191/52671828-6f099700-2f1c-11e9-83ad-e77831d0c501.png">

**Comment by ibc** [comment]
This is supposed to be done.
