### ISSUE TITLE
RTCP general parsing issue (original len is not verified)

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#250]
Most of the RTCP packet parsers do something as follows:

* `RTCP::XxxxPacketParser::Parse()` is called with `data` and `len`.
* Such a function does some basic checks and creates a `XxxxPacket` instance by passing the `header` pointer as argument.

However, whether the original `len` matches the effective size of the parsed packet is never verified. I added a check for this in the REMB parser:

https://github.com/versatica/mediasoup/commit/37f20b2db300c07e73cfc205da2101be220bf8a5#diff-421855edbeab3334a51262bcb5f6daff

But I'm not sure this is the proper way to go, nor even sure if this check is needed or not. I leave this to you, @jmillan.

**Comment by jmillan** [comment]
So,

* For every RTCP packet we already check that the buffer length is at least as long as the length indicated in the RTCP common header [here](https://github.com/versatica/mediasoup/blob/fuzzer/worker/src/RTC/RTCP/Packet.cpp#L61)

* For every feedback packet we already check that the buffer length can also contain the feedback header [here](https://github.com/versatica/mediasoup/blob/fuzzer/worker/src/RTC/RTCP/Feedback.cpp#L122) and [here](https://github.com/versatica/mediasoup/blob/fuzzer/worker/src/RTC/RTCP/Feedback.cpp#L214)

Then is responsibility of every specific packet to check whether the RTCP can hold the parsing content (checking the common header length)

IMHO we are safe here.

**Comment by ibc** [comment]
Yes. I think that just some code cleanup could be done in the REMB parser which splits some checks in both the `Parse()` function and the `constructor`.

**Comment by jmillan** [comment]
Lets keep it as it is for now. `Parse()` verifies the common conditions and `constructor` the specifics for such buffer.
