### ISSUE TITLE
Add more fuzzing

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#260]
We need fuzzing for RTCP parsing and also for VP8 and H264 parsing.

* [ ] RTCP fuzzing in v2
* [x] RTCP fuzzing in v3
* [ ] Video payload fuzzing in v2
* [ ] Video payload fuzzing in v3

**Comment by jmillan** [comment]
:+1:

**Comment by jmillan** [comment]
RTCP fuzzing mostly done: d9107418679f87e1e92e096c04c671aee7374d80

**Comment by ibc** [comment]
Let's close this. Will add new fuzzing eventually.
