### ISSUE TITLE
Load,Scaling, simulcast support, java integration

### ISSUE THREAD

**Issue by aayushjains20** [versatica/mediasoup#266]
Hi there, might be silly questions but have some doubts.
1: How many multiparty calls can one mediasoup server support, my servers are octacore.(is there any specific number or does it depends on number of peers in room).

2.  Is mediasoup horizontal scalable, if yes then how. Is there any support doc for this.
3. Is simulcast support there in v2?
4. Is there recording support, if yes is there any demo project which I can look at?
5. My backend is in java 7, Is there any support doc or any example to help me with integration because all the examples I found are on node. 
Thanks in advance.

**Comment by ibc** [comment]
Hi. As the issue template said, please use the mediasoup public mailing list for questions and doubts.
