### ISSUE TITLE
Proper H264 and VP9 matching

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#269]
### Tasks

* [ ] H264 `profile-level-id` matching
* [ ] VP9 `profile-id` matching

### H264

Currently, in both mediasoup and mediasoup-client, we match H264 codecs by checking their `packetization-mode` (which typically is 0 or 1) and their the `profile-level-id`, which is a binary with complex matching rules (it's not a "string match" at all, however we do string matching right now).

```
a=rtpmap:100 H264/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtpmap:122 rtx/90000
a=fmtp:122 apt=102
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:121 rtx/90000
a=fmtp:121 apt=127
a=rtpmap:125 H264/90000
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 transport-cc
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=125
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d0032
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=108
a=rtpmap:124 H264/90000
a=rtcp-fb:124 goog-remb
a=rtcp-fb:124 transport-cc
a=rtcp-fb:124 ccm fir
a=rtcp-fb:124 nack
a=rtcp-fb:124 nack pli
a=fmtp:124 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640032
a=rtpmap:120 rtx/90000
a=fmtp:120 apt=124
```

Let's take a look to [libwebrtc](https://chromium.googlesource.com/external/webrtc/+/3c1e558449309be965815e1bf/webrtc/common_video/h264/profile_level_id_unittest.cc).

*Related:*

* [Chrome Ignores H264 profile-level-id on SDP offer](https://bugs.chromium.org/p/chromium/issues/detail?id=645599)
* [WebRTC fails to match compatible H264 profile-level-ids](https://bugs.chromium.org/p/webrtc/issues/detail?id=6400)
* [ORTC: determining common capabilities](https://github.com/w3c/ortc/issues/569)
* [stackverflow: Identify h264 profile and level from profile-level-id in sdp?](https://stackoverflow.com/questions/22960928/identify-h264-profile-and-level-from-profile-level-id-in-sdp/22970025)

### VP9

libwebrtc also indicates a `profile-id` within VP9.

```
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 profile-id=0
```

* `profile 0`: color depth: 8 bit/sample, chroma subsampling: 4:2:0
* `profile 1`: color depth: 8 bit, chroma subsampling: 4:2:0, 4:2:2, 4:4:4
* `profile 2`: color depth: 10–12 bit, chroma subsampling: 4:2:0
* `profile 3`: color depth: 10–12 bit, chroma subsampling: 4:2:0, 4:2:2, 4:4:4[20]

**Comment by ibc** [comment]
Once https://github.com/versatica/mediasoup/commit/602bd6d7c4b80a82e15870a97401ae770266d93d is done we can close this. VP9 and H265 stuff will be handled when we properly support them.

**Comment by balajinammalvar** [comment]
I am using this in android native app url i post in app 4443/?roomId=yhj3knsh&peerId=ryqxw6oc&forceVP9=true but in video streaming codec was H264 in web i was posting forceVP9= true why this error came please resolve this.... is this error came before in android for anyone pls help me out @ibc

**Comment by ibc** [comment]
Please, use the forum for usage questions, and not GitHub.
