### ISSUE TITLE
can't install mediasoup on a fresh install of linux mint

### ISSUE THREAD

**Issue by Espii** [versatica/mediasoup#271]
[npm-debug.log](https://github.com/versatica/mediasoup/files/2848427/npm-debug.log)

**Comment by jmillan** [comment]
could you run `make Release` by hand and  paste here the output log?

```bash
cd node_modules/mediasoup
make Release -C worker
```

**Comment by Espii** [comment]
node_modules/mediasoup doesn't exist because I just typed "npm install
mediasoup"

**Comment by jmillan** [comment]
> node_modules/mediasoup doesn't exist because I just typed "npm install mediasoup"

Are you sure? `npm install module` downloads the sources of `module` in the directory './node_modules/module' prior to installation.

**Comment by ibc** [comment]
Have you checked the requirements?

https://mediasoup.org/documentation/v2/mediasoup/installation/#requirements

**Comment by ibc** [comment]
Sorry. This issue has a template that you should have filled with software versions and more data. Instead you have decided to delete the template so now we need to make the same questions one by one.

Please open a new issue and properly fill the issue template.

**Comment by ibc** [comment]
BTW just confirmed right now that, by following the installation requirements, mediasoup does properly install in Linux Mint.

**Comment by Espii** [comment]
Ahh, sorry. I normally use windows and just downloaded/installed linux so I
could use this for livestream similar to twitch. Wasn't too familiar with
linux

I think I see the problem now,  I just installed nodejs and npm before
trying to install mediasoup. I didn't check to make sure that I had
python/clang/make also installed on the system

I'll try that now,  thanks
