### ISSUE TITLE
Hardcoded MTU (1500) and RTP/RTCP size checks

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#276]
`RTC/RtpPacket.hpp` defines:

```c++
// Max RTP length.
constexpr size_t RtpBufferSize{ 65536 };
// Max MTU size.
constexpr size_t MtuSize{ 1500 };
```

`RTC/RTCP/Packet.hpp` defines:

```c++
// Internal buffer for RTCP serialization.
constexpr size_t BufferSize{ 65536 };
```

We just check the `MtuSize` in `RtpStreamSend` when storing the sent packet into the retransmission buffer:

```c++
void RtpStreamSend::StorePacket(RTC::RtpPacket* packet)
{
	if (packet->GetSize() > RTC::MtuSize)
```

We use the `RTCP::BufferSize` to check if the length of our generated RTCP packet exceeds that value:

```c++
void WebRtcTransport::SendRtcp(uint64_t now)
{
		[...]

		// Ensure that the RTCP packet fits into the RTCP buffer.
		if (packet->GetSize() > RTC::RTCP::BufferSize)
		{
			MS_WARN_TAG(rtcp, "cannot send RTCP packet, size too big (%zu bytes)", packet->GetSize());
```

This means that mediasoup does not complain if the resulting RTCP compound packet is 65536 bytes long, which would require IP fragmentation in any non-localhost network, and would fail to reach the destination in many cases due the nature and status of Internet.

### TODO

* The RFC says somewhere that, if the resulting RTCP compound packet is too big, its content must be splitted into N compound packets. We should have it. Something like this (happy code):

```c++
if (packet->GetSize() > 1500)
{
	auto* subPacket = packet->GetSubcontent(1500);

	do
	{
		subPacket->Serialize(RTC::RTCP::Buffer);
		SendRtcpCompoundPacket(subPacket);

		subPacket = subPacket->GetSubcontent(1500);
	}
	while (subPacket != nullptr)
}
```

* We must check whether we need to verify `RTC::MtuSize` somewhere else.

* We must reconsider what `RTC::RtpBufferSize` and `RTC::RTCP::BufferSize` exactly mean.

**Comment by ibc** [comment]
(or we can just send SR/RR for each separate Producer/Consumer).

**Comment by ibc** [comment]
Also, not sure why we are using hardcoded `MtuSize = 1500`. In IPv6 it's smaller. 1200 is the proper value.

**Comment by ibc** [comment]
So `Transport.cpp` when calling `GetRtcp()`on Producers and Consumers, must split the resulting compound packets into N compound packets that do not exceed the max MTU.

**Comment by ibc** [comment]
Not 100% sure if we can close this issue. We already split RTCP compound packets bigger than `MtuSize`. However we do not check it we are sending RTP packets exceeding that size (that may happen if we add many RTP header extensions, etc).

Probably we should check the RTP packet size before setting RTP header extensions and not set all them if the resulting size would be higher than `MtuSize`.

**Comment by jmillan** [comment]
> Probably we should check the RTP packet size before setting RTP header extensions and not set all them if the resulting size would be higher than MtuSize.

This is more sensitive because in RTCP we split the content into multiple packets but all the info is sent. Here, if we don't send a header extension, it will lead to one or other problem (unless the extension is not used at destination).

**Comment by ibc** [comment]
Some extensions are just required for the first packets in the stream, such as mid and rid. We may just add them if we know that they won't make the packet size exceed the MTU size.

**Comment by ibc** [comment]
We are even removing RTP header extensions such as MID and RID, so we are good. Let's close.
