### ISSUE TITLE
Handle non signaled CNAME

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#277]
In summary, standard simulcast video does not include `CNAME` in the SDP offer, and unfortunately Chrome M74 fails to indicate the sending `cname`:

```js
videoRtpSender.getParameters().rtcp

// => {cname: "", reducedSize: true}
```

Currently, in mediasoup we depend on the `cname` signaled in the Producer's `rtpParameters` and copy it verbatim to its Consumers. If we didn't know such a `cname` value in advance, we should match RTCP SDES from the Producer, learn its `cname` and transmit it to the Consumers (so they will eventually generate new RTCP SDES with the real `cname` value).

### Related

* "Missing CNAME in RID based simulcast offer": https://github.com/w3c/webrtc-pc/issues/2114
* "RID based simulcast produces empty CNAME in sender.getParameters()": https://bugs.chromium.org/p/webrtc/issues/detail?id=10377

**Comment by ibc** [comment]
If we finally do not know the Producer CNAME in advance, we may react on received RTCP SDES, learn the CNAME from it, and pass it to all Consumers so they update their `rtpParameters`.

**Comment by fippo** [comment]
can you put "standard" in quotes while we try to figure out what the standard actually says?

**Comment by ibc** [comment]
> can you put "standard" in quotes while we try to figure out what the standard actually says?

_""""""""""""""""standard"""""""""""""""_

**Comment by ibc** [comment]
Funny enough: https://bugs.chromium.org/p/webrtc/issues/detail?id=10383

**Comment by ibc** [comment]
After testing such a commit and forcing Chrome 72 to not signal CNAME in `rtpParameters`, it happens that receiver Chrome does NOT like having multiple remote m= sections wihtout `a=ssrc+cname` lines. Period. It just renders the first audio and video and not the others.

**Comment by ibc** [comment]
Ok, so this is fixed. I've reverted the previous commit that notified in-runtime discovered Producer's CNAME to Consumers. That is nice but libwebrtc annoyingly [FAILS](https://bugs.chromium.org/p/webrtc/issues/detail?id=10385) if the remote SDP offer does not have `a=ssrc` lines with "cname" attribute.

New super easy approach in `transport.produce()` method:

* If the given `rtpParameters` do not have `rtcp.cname` we create a random one. Period.
* The CNAME is copied verbatim (via JS) to associated Consumers, so they will get such a CNAME.
* This also enables the use case in which we produce audio/video with ffmpeg, gstreamer or whatever that does not signal its CNAME.

**Comment by ibc** [comment]
**NOTE:** Super useful information to know how exactly libwebrtc inspects the remote SDP and generate streams/tracks in different cases:

https://cs.chromium.org/chromium/src/third_party/webrtc/pc/webrtc_sdp.cc?type=cs&sq=package:chromium&g=0&l=690
