### ISSUE TITLE
parse/read video orientation from extended headers

### ISSUE THREAD

**Issue by jseeley78** [versatica/mediasoup#278]
## Feature Request

Is there a reason reading the video orientation from the rtp extended header is not included in mediasoup v2; All the other extended headers seem to accounted for. There is a brief mention of it in the TestRtpPacket test, but no actual implementation. I have a forked mediasoup branch where I've implemented this feature and I return the video orientation value in the rtpstream "GetStats" function. Is this something that others would want in v2, or something in the roadmap for v3?

**Comment by ibc** [comment]
No special reason. We can add it into v3. Can you please provide info regarding what that header extension contains, RFC reference and how the item in the spec should look like?

**Comment by jseeley78** [comment]
You can read the following url for its description of Coordination of Video Orientation (CVO) ->
https://tools.ietf.org/html/draft-ietf-rtcweb-video-04 

Which refers to section 7.4.5 of 'TS26.114' ->
https://www.etsi.org/deliver/etsi_ts/126100_126199/126114/12.07.00_60/ts_126114v120700p.pdf

^ This defines how to read the data in the extended headers for CVO.
(also has some code comments which mirrors what is said in TS26.114)

This is how I implemented my read function for reference->
`	inline bool RtpPacket::ReadVideoOrientation(uint16_t* rotation) const
	{
		uint8_t extenLen;
		uint8_t cvoByte;
		uint8_t* extenValue;

		extenValue = GetExtension(RTC::RtpHeaderExtensionUri::Type::VIDEO_ORIENTATION, &extenLen);
		if (!extenValue || extenLen != 1) {
			return false;
		}
		/** 
			Coordination of Video Orientation
			Bit#       7 6 5 4 3 2  1  0(LSB)
			Definition 0 0 0 0 C F R1 R0

			C = Camera
			0: Front-facing camera, facing the user. If camera direction is unknown, this is the default value used.
			1: Back-facing camera, facing away from the user.

			F = Flip
			0: No flip operation. If the sending client flips value is unknown, this is the default value used.
			1: Horizontal flip operation

			R1 R0 = Rotation
			 0  0 = 0 rotation
			 0  1 = 90 CCW (aka: 270 CW)
			 1  0 = 180 CCW (aka: 180 CW)
			 1  1 = 270 CCW (aka: 90 CW)
		**/  
		cvoByte = Utils::Byte::Get1Byte(extenValue, 0);
		int rValue = (cvoByte & 0x03);
		switch (rValue) {
			case 3: // NOTE: using counter clockwise values
				*rotation = 270;
				break;
			case 2:
				*rotation = 180;
				break;
			case 1:
				*rotation = 90;
				break;
			default:
				*rotation = 0;
		}
		return true;
	}`

There is also an option here to read the 'flip' and 'camera' values which I didn't happen to need, but could be added in the same read function.

**Comment by ibc** [comment]
I'm not good at C bitwise operations: Could you help me defining the lines to extract both `flip` and `camera` integer values from the byte?

**Comment by ibc** [comment]
Even better, could you please provide some `cvoByte` examples (in bits) and their corresponding `rotation`, `flip` and `camera` values? (to write test units).

**Comment by jseeley78** [comment]
I'm not very good at it either; Given the code I gave as an example I believe it would be something like->

int flip = (cvoByte & (0x1 << 2));
int camera = (cvoByte & (0x1 << 3));

**Comment by ibc** [comment]
Thanks. I've improved it as follows (so both camera and flip become 1 or 0):

```c++
  uint8_t cameraValue   = ((cvoByte & 0b00001000) >> 3);
  uint8_t flipValue     = ((cvoByte & 0b00000100) >> 2);
  uint8_t rotationValue = (cvoByte & 0b00000011);
```

http://cpp.sh/8c5qw

**Comment by ibc** [comment]
Do you know which browser sends such a `video-orientation` extension in RTP packets? I may have done something wrong in my local code, but even if Chrome 73 (desktop and Android) supports this extension, I see no it in video RTP packets.

**Comment by ibc** [comment]
Ok, I get this in Chrome M73 desktop:

```
videoOrientation: camera:false,flip:false,rotation:0
```

The extension is just in some RTP packets (just in the very first 4 RTP packets and then in a few more later).

I don't see it when using chrome M72 Android. Which browser do you use that sends this extension?

**Comment by jseeley78** [comment]
safari on iOS and firefox/chrome on andoird was where i tested. I was able to see changing values while rotating the phone. keep in mind not every rtp packet will have the values however.

**Comment by ibc** [comment]
Mmm, then I'm doing something wrong. Indeed I see those values when I rotate my mobile, but `rotation` is always 0.

**Comment by ibc** [comment]
Ok, so this has been done in v3 [here](https://github.com/versatica/mediasoup/commit/855b3b9f9f710eeebc68ae3005ba5fe2363a4ff7):

> RtpPacket: read video-orientation RTP header extension:
> If any video-orientation RTP header extension has been detected, the
producer.getStats() will include a videoOrientation object in each stream.

Unfortunately I always get `camera:false,flip:false,rotation:0` even when using my mobile (HTC U11). May be it's related to the cam of my mobile, no idea.

@jseeley78, may you have a chance to test the v3 demo and check if you get proper video rotation values?

**Comment by ibc** [comment]
Ok, I've changed my mind. Instead of displaying the `videoOrientation` info into `producer.getStats()`, now it is a new Producer JS "videoorientationchange" event which is fired:

* the first time a packet with video-orientation extension is received, or
* when any of camera, flip or rotation values has changed.

The JS event is fired with an Object as single argument. The Object has three fields:

* `camera` (boolean)
* `flip` (boolean)
* `rotation` (0, 90, 180 or 270)

It's been added into the mediasoup-demo v3 branch: https://github.com/versatica/mediasoup-demo/commit/351b2e59069603667c8b5a36b33651af39bc9b25?ts=2

**Comment by ibc** [comment]
@jseeley78 if you wish, instead of deploying all the v3 demo, you can just join any room in https://v3demo.mediasoup.org with your mobile (and do many rotations and so on). Then let me know. I will check the logs to see if rotation values are different than just 0.

**Comment by ibc** [comment]
I always receive camera:0, flip:0, rotation:0. I mean, I receive packets with video-orientation RTP header extension when I rotate the mobile, but rotation values do not change. I think this may be my mobile rotating the webcam video source so libwebrtc detects the device rotation but the computed new `rotation` is zero again. Does it make sense?

NOTE: I'm just using Chrome and not a native WebRTC app.

**Comment by ibc** [comment]
I've been confirmed by some people that, indeed, Chrome is not sending `rotation` with values other than 0, so I'll close this issue. Please comment if there are any news.
