### ISSUE TITLE
SimulcastConsumer: should not allow passing a RTP packet if temporal layer not satisfied

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#281]
[Here](https://github.com/versatica/mediasoup/blob/21b4edc8a36b23846691018d5537ca5f1364a7e0/worker/src/RTC/SimulcastConsumer.cpp#L276) we may drop a packet if it does not satisfy the preferred temporal layer **even** if we used this packet to change current spatial layer.

This should not happen because the receiver will get frozen video.

**Comment by jmillan** [comment]
I want to think that a key frame will always satisfy it. Otherwise we would have to wait to another key frame to came and check again the temporal layer.

Must verify it.

**Comment by ibc** [comment]
> I want to think that a key frame will always satisfy it. Otherwise we would have to wait to another key frame to come and check again the temporal layer.

You may be in stream with spatial layer 2 and want to upgrade from temporal layer 0 to temporal layer 1. There is no keyframe here nor we have to wait to any keyframe. This is about temporal layers.

**Comment by jmillan** [comment]
> Here we may drop a packet if it does not satisfy the preferred temporal layer even if we used this packet to change current spatial layer.

If the packet is used to change current spatial layer then it is a keyframe, isn't it?

**Comment by ibc** [comment]
> If the packet is used to change current spatial layer then it is a keyframe, isn't it?

This [line](https://github.com/versatica/mediasoup/blob/21b4edc8a36b23846691018d5537ca5f1364a7e0/worker/src/RTC/SimulcastConsumer.cpp?ts=2#L276) does not happen "just" when switching to a new spatial layer. Let's assume a single spatial layer.

Anyway you could be right. I just don't think the code is ready enough for when we want to deal with temporal layers.

**Comment by jmillan** [comment]
[This  commit](https://github.com/versatica/mediasoup/commit/e3224ea5fed9f8ea94a1166146a63a787e358770) deals with temporal layer transitioning and indicates whether it must be sent over the wire or not.

**Comment by ibc** [comment]
WIP
