### ISSUE TITLE
Improve H264 key frame detection

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#283]
Courtesy of @lminiero:

https://github.com/meetecho/janus-gateway/commit/86a00fe94879478197e66754503a4ba7757e9a06

> Basically now we only switch when we receive a fragment/nal=7 (SPS/PPS), as there could be race conditions otherwise: nal=7 passes, switch requested, nal=5 arrives, it's a keyframe for us --> broken video, because the stream is missing the sps/pps with the right resolution info.
Safer to only do that when you get the SPS/PPS, which is either in the same packet as the keyframe, or in the packet(s) before

**Comment by ibc** [comment]
NOTE: We may not need to fix anything.

**Comment by jmillan** [comment]
> NOTE: We may not need to fix anything as we already did:

Yes, it is already done :-)

**Comment by jmillan** [comment]
https://github.com/versatica/mediasoup/blob/master/worker/src/RTC/Codecs/H264.cpp#L23

**Comment by ibc** [comment]
<img width="1000" alt="Untitled" src="https://user-images.githubusercontent.com/16191/54883795-da268180-4e69-11e9-8603-53451dcabb52.png">
