### ISSUE TITLE
[v3] Fails to downgrade to spatial layer 0 from 2

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#286]
Can reproduce it in the demo:

* Start consuming a video with 3 simulcast layers.
* Move the Consumer to spatial layer 0 (fast).
* The Consumer current spatial layer gets stuck into layer 1.

**Comment by jmillan** [comment]
Looking into this. I don't reproduce though.

**Comment by jmillan** [comment]
Reproducible when jumping from preferred spatial layer 2 to preferred spatial layer 0.

Fixing.

**Comment by jmillan** [comment]
fixed
