### ISSUE TITLE
Not receiving RTCP receiver reports on network packet loss 

### ISSUE THREAD

**Issue by jmillan** [versatica/mediasoup#289]
We are experiencing lack of RTCP receiver reports reception upon network packet loss.

Filled [bug in Chrome bugtracker](https://bugs.chromium.org/p/webrtc/issues/detail?id=10510)

**Comment by jmillan** [comment]
Not a bug in mediasoup (for now), but it's a show stopper.

**Comment by jmillan** [comment]
Debugging RTCP reception in mediasoup

**Comment by ibc** [comment]
Fixed in 8c666a866c7f917469eabbac4d3dbc03bc7bfa09.
