### ISSUE TITLE
Add TCP support in PlainRtpTransport

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#290]
This requires some love in a new `TcpClient.cpp` handler in mediasoup worker [libuv handles](https://github.com/versatica/mediasoup/tree/master/worker/src/handles). This way, a `PlainRtpTransport` could behave as TCP client instead of just as a TCP server (of course this will require a setting such as `tcpRole`).

**Comment by jnoring** [comment]
One quick suggestion: I'd instead push people towards using a TURN server (for example, coturn).  Here are the reasons why:

1. If someone needs TCP, then they are likely deploying into an enterprise network that is highly restricted.
2. If someone needs TCP, they also most likely need TCP 443, which means there's a port collision with media soup for the signaling channel.
3. If someone needs TCP, then they also likely need HTTP CONNECT for handling enterprise networks that have a proxy.

For all of those situations, it makes more sense to route traffic through a TURN server.  And architecturally, I think media soup ends up being "cleaner" if it sticks to UDP as the preferred transport.

Just food for thought.  But maybe you have different reasons for wanting to add TCP support.

**Comment by ibc** [comment]
This issue is about adding TCP support for plain RTP transport, so not related to WebRTC clients that, indeed, can already use a TURN server.

Said that, there are use cases in which you may need to send/receive plain RTP to/from mediasoup using TCP instead of UDP. For instance, ffmpeg RTP stack is somehow buggy when it uses UDP.

**Comment by ibc** [comment]
Let's close this issue. I just forgot that using RTP over TCP requires [RFC 4571](https://tools.ietf.org/html/rfc4571#section-2) ("Framing RTP and RTCP over TCP"), which is obviously implemented in mediasoup (we do support ICE/DTLS/RTP/RTCP over TCP) but it's not implemented in by ffmpeg. So adding TCP support to the `PlainRtpTransport` in mediasoup would be completely useless since there is no implementation out there that could use it.
