### ISSUE TITLE
Trying to build version3, fatal error:

### ISSUE THREAD

**Issue by Globik** [versatica/mediasoup#293]
We primarily use GitHub as an issue tracker. Please, use the mediasoup public mailing list for usage and support questions:
> 
> https://groups.google.com/forum/#!forum/mediasoup
>
bits/libc-header-start.h no such file or directory. Which version of opennssl are you using?
No chance for 32 bit computers? I found this header in i386-linux-gnu directory.

**Comment by ibc** [comment]
C++ dep versions are indicated in `worker/scripts/get-dep.sh` script.

No idea about that error, but Google says [things](https://www.google.com/search?q=bits%2Flibc-header-start.h&oq=bits%2Flibc-header-start.h).

Comment again if there is a real issue to fix (I don't keep unclear issues here).

**Comment by Globik** [comment]
The issue that mediasoup don't support 32 bit computers. It's a pity.

**Comment by ibc** [comment]
Honestly no idea what should be done to support 32 bit machines. We are not against them, it's just that have never found the need to support them. PR welcome.
