### ISSUE TITLE
No key frames in H264 with simulcast (Chrome issue)

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#296]
* v3

Somehow, when using H264 with simulcast, sometimes the consumer does not receive a key frame for the selected Producer's RTP stream. This produces no video reception until the browser itself sends a PLI.

It can be reproduced in the demo app by forcing H264 with `?forceH264=true`.

**Comment by jmillan** [comment]
Not easily reproducible. In localhost I'm not able to reproduce. In the demo I've seen it once but didn't get the logs. 

Verified that Chrome always sends the key frames of every streams that is currently sending.

**Comment by jmillan** [comment]
Easily reproducible in the demo when adding a loss percentage (ie: 10%) to the uplink

**Comment by jmillan** [comment]
I'm just checking the H264 parser. I'll check some reference implementations out there.

**Comment by ibc** [comment]
Bug reported in Chromium: https://bugs.chromium.org/p/webrtc/issues/detail?id=10585

As explained in there, it does work in Chrome Canary 76.0.3778.0. It fails in current stable 74.0.3729.108 (OSX).

Let's leave this issue open until we get confirmation/feedback from Chromium developers (and also as temporal "documentation").

**Comment by ibc** [comment]
The issue does not happen in Chrome 74.0.3729.131 (current stable). Honestly no idea, but let's close this issue.

**Comment by ibc** [comment]
The issue also happens in latest Canary 76.0.3786.0  and latest Chrome stable 74.0.3729.131. Let's reopen this.

**Comment by ibc** [comment]
Bug found in libwebrtc: https://bugs.chromium.org/p/webrtc/issues/detail?id=10585#c13

NOTE: As explained in that issue, if the simulcast layer 0 (low) is disabled (`encodings[0].active = false`)  then libwebrtc won't send key frames upon PLI for layer medium or high... Ugly. Confirmed with VP8:

```js
s = PC1.getSenders()[1]; p = s.getParameters(); p.encodings[0].active=true; s.setParameters(p)
```

Note however that, as explained in the libwebrtc issue, the issue in H264 is **also** that libwebrtc H264 encoder has spatial layer 0 as the highest one (while in VP8 it's the lowest one).

Let's close this issue.
