### ISSUE TITLE
Use mediasoup with Vuejs and Node server?

### ISSUE THREAD

**Issue by BenderBendingDev** [versatica/mediasoup#310]
We primarily use GitHub as an issue tracker. Please, use the mediasoup public mailing list for usage and support questions:
> 
> https://groups.google.com/forum/#!forum/mediasoup
>

Hello,

My question is if it can be used (there is documentation about it) to make use of this magnificent component in my project, I am really impressed!

I hope you can help me. Many thanks!!

**Comment by ibc** [comment]
Hi. As the issue template clearly says:

> We primarily use GitHub as an issue tracker. Please, use the mediasoup public mailing list for usage and support questions:
> 
> https://groups.google.com/forum/#!forum/mediasoup
>
