### ISSUE TITLE
unbuntu 18.04 release compile need cflags add '-fPIC'

### ISSUE THREAD

**Issue by baiyfcu** [versatica/mediasoup#315]
/usr/bin/ld: /mnt/d/git/mediasoup-demo/server/node_modules/mediasoup/worker/out/Release/libopenssl.a(bio_ssl.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /mnt/d/git/mediasoup-demo/server/node_modules/mediasoup/worker/out/Release/libopenssl.a(d1_lib.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /mnt/d/git/mediasoup-demo/server/node_modules/mediasoup/worker/out/Release/libopenssl.a(d1_msg.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /mnt/d/git/mediasoup-demo/server/node_modules/mediasoup/worker/out/Release/libopenssl.a(d1_srtp.o): relocation R_X86_64_32 against `.data' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /mnt/d/git/mediasoup-demo/server/node_modules/mediasoup/worker/out/Release/libopenssl.a(methods.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /mnt/d/git/mediasoup-demo/server/node_modules/mediasoup/worker/out/Release/libopenssl.a(packet.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /mnt/d/git/mediasoup-demo/server/node_modules/mediasoup/worker/out/Release/libopenssl.a(pqueue.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC

file "common.gypi"
      'Release':
      {
        'cflags': [ '-g', '-Wno-unknown-warning-option']
      }

to 
      'Release':
      {
        'cflags': [ '-g', '-Wno-unknown-warning-option','-fPIC' ]
      }

recompile with -fPIC is ok.

**Comment by ibc** [comment]
Interesting. Do you know the implications of adding `-fPIC`? BTW, has your host a 32 bits CPU?

**Comment by ibc** [comment]
`-fPIC` has been added. Waiting for validation in Travis-CI. Once validated, will be released in mediasoup 3.1.4. Thanks.

**Comment by baiyfcu** [comment]
> `-fPIC` has been added. Waiting for validation in Travis-CI. Once validated, will be released in mediasoup 3.1.4. Thanks.

Beginner Mo Guai ,thank you for reminding.
