### ISSUE TITLE
BWE: missing proper RTP probator to allow layer up switch in all scenarios

### ISSUE THREAD

**Issue by jmillan** [versatica/mediasoup#316]
### Steps to reproduce

1. Start one producer sending N video streams to mediasoup.
2. Start one simulcast consumer for the previous producer, having negotiated REMB.
3. Make sure the remote consumer is receiving video.
4. Limit the network uplink bandwidth on the consumer endpoint to a bitrate lower than the required for the lowest quality stream sent by the producer.
5. The REMB value `availableOutgoingBitrate` will decrease to a value lower than the bitrate required for the lowest quality stream sent by the producer.
6. Given the previous point, mediasoup will stop forwarding video RTP to the remote consumer.
7. Given the previous point, and beacause of libwebrtc REMB implementation, the received REMB values will remain low.
8. Given the previous point, mediasoup will never forward video RTP to the remote consumer.
### 

The case described above was not considered in the design. There is no outgoing RTP to make the REMB values grow. And our probation does not generate RTP packets but re-sends (multiple times) packets that are being forwarded.

It looks to me that we should improve our probation mechanism in a way that in the absence of RTP packets coming from the producer,  we **generate** RTP packets in order to allow the incoming REMB values grow to a point where we could start routing video RTP to the remote consumer. This should only happen when there is no real RTP being forwarded and there is at least a consumer that is waiting for a minimum available outgoing bandwidth in order to be able to send RTP.

**Comment by ibc** [comment]
Although we clearly need to handle this in a better way (by having independent RTP probing) the scenario above can just happen if the `minimumAvailableOutgoingBitrate` (defaults to 100,000bps) given in the `WebRtcTransport` options is lower than the bitrate of the lowest simulcast/SVC spatial/temporal layer (0:0).

If, for example, the simulcast producer has 3 spatial layers with a single temporal layer, and the lowest spatial layer (the low resolution stream) has a bitrate of 300,000bps and `minimumAvailableOutgoingBitrate` is set to `400,000`, the issue above will never happen.

As a temporal solution, I'm gonna increase `minimumAvailableOutgoingBitrate` to 300,000, which seems more reasonable than 100,000.

NOTE: Still we need to do independent RTP probation somehow.

**Comment by ibc** [comment]
Let's remove the "BUG" label since it just happens in very corner case scenarios.

**Comment by jmillan** [comment]
👍

**Comment by ibc** [comment]
So we'll create a standalone RTP probator to fix this scenario.

**Comment by ibc** [comment]
This will be fixed once Transport-CC sender side is included (#177).
