### ISSUE TITLE
Large number of 'layerschange' events (version 3.1.5)

### ISSUE THREAD

**Issue by kwindla** [versatica/mediasoup#318]
## Bug Report

Discourse thread: https://mediasoup.discourse.group/t/large-number-of-layerschange-events-with-mediasoup-3-1-5/118

When upgrading from 3.1.4 to 3.1.5, I am now seeing 10-20 'layerschange' events per second that affect only the temporalLayer, for every consumer with simulcast streams. There's a noticeable visual impact on video framerate as well.

**Iñaki indicates that this is happening in the official demo, too. Also, that it happens in both VP8 and H264 simulcast, but it does not happen in VP9 SVC.**

```
mediasoup:worker[pid:21853] RTC::Transport::ReceiveRtcpPacket() | no Consumer found for received Receiver Report [ssrc:905464878] +273ms
  demo-app consumer layerschange d93-483-083b->d93-483-083b cam-video { spatialLayer: 1, temporalLayer: 2 } +233ms
  demo-app consumer layerschange d93-483-083b->d93-483-083b cam-video { spatialLayer: 1, temporalLayer: 0 } +36ms
  demo-app consumer layerschange d93-483-083b->d93-483-083b cam-video { spatialLayer: 1, temporalLayer: 1 } +1ms
  demo-app consumer layerschange d93-483-083b->d93-483-083b cam-video { spatialLayer: 1, temporalLayer: 0 } +66ms
  mediasoup:worker[pid:21853] RTC::Transport::ReceiveRtcpPacket() | no Consumer found for received Receiver Report [ssrc:905464878] +263ms
  demo-app consumer layerschange d93-483-083b->d93-483-083b cam-video { spatialLayer: 1, temporalLayer: 2 } +160ms
  demo-app consumer layerschange d93-483-083b->d93-483-083b cam-video { spatialLayer: 1, temporalLayer: 0 } +31ms
  demo-app consumer layerschange d93-483-083b->d93-483-083b cam-video { spatialLayer: 1, temporalLayer: 1 } +0ms
  demo-app consumer layerschange d93-483-083b->d93-483-083b cam-video { spatialLayer: 1, temporalLayer: 0 } +72ms
  mediasoup:worker[pid:21853] RTC::Transport::ReceiveRtcpPacket() | no Consumer found for received Receiver Report [ssrc:905464878] +282ms
  demo-app consumer layerschange d93-483-083b->d93-483-083b cam-video { spatialLayer: 1, temporalLayer: 2 } +177ms
  demo-app consumer layerschange d93-483-083b->d93-483-083b cam-video { spatialLayer: 1, temporalLayer: 0 } +30ms
  demo-app consumer layerschange d93-483-083b->d93-483-083b cam-video { spatialLayer: 1, temporalLayer: 1 } +1ms
```

To reproduce:

1. `https://github.com/daily-co/mediasoup-sandbox.git`
2. cd mediasoup-sandbox/single-page/
3. npm install
4. DEBUG="mediasoup*, demo-app*" npm run start
5. open http://localhost:3000/ in a web browser
6. click on "send camera streams"
7. click on the "subscribe" button next to "my cam-video"
8. see the debug messages from the 'layerschange' event handler in the server terminal window

Reproduces for me on Chrome 75.0.3770.80/Linux, Chrome 75.0.3770.100/OS X, Safari 12.1.1/OS X, Chrome 75.0.3770.100/Windows, and Firefox 67.0.1/Windows.

### Your environment

- Operating system: Ubuntu 18 LTS and Docker node:10.16.0-alpine
- Node version: 10.16.0
- npm version: 6.9.0
- gcc/clang version:
- mediasoup version: 3.1.5
- mediasoup-client version: 3.1.6

**Comment by ibc** [comment]
Super thanks. Fixes in ca3166026f420c3dbe3c0e3e39aa2a9f13abe726.

Releasing 3.1.6 right now.
