### ISSUE TITLE
Armbian: error: unrecognized command line option ‘-m64’

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#321]
* Armbian based on Debian Buster release.

`npm install` fails:

```
/home/xxxxxx/server/node_modules/mediasoup/worker/out/Release/obj.target/openssl/deps/openssl/openssl/ssl/bio_ssl.o
cc: error: unrecognized command line option ‘-m64’
```

Some related stuff:

* https://github.com/openssl/openssl/issues/7655
* https://github.com/Level/leveldown/issues/359
* https://github.com/Theano/Theano/commit/2cc4b74a0b0e176332b638152a30f65df72e6635

In addition we may need to modernize our GYP files to track new changes in Node ones (they do set "m64" in some places):

* https://github.com/nodejs/node/blob/master/common.gypi
* https://github.com/nodejs/node/blob/master/node.gyp

**Comment by ibc** [comment]
BTW we have updated OpenSSL to 1.1.1c in mediasoup "v3" branch (no NPM version available yet). It would be great if somebody could check whether it fixes the issue described above.

**Comment by prizemprov** [comment]
I have followed these steps and the error still exists.

$ git clone https://github.com/versatica/mediasoup.git
$ cd mediasoup
$ git checkout v3
$ cd worker
$ make

>   CC(target) /home/abc/mediasoup/worker/out/Release/obj.target/openssl/deps/openssl/openssl/ssl/bio_ssl.o
> cc: error: unrecognized command line option '-m64'
> make[1]: *** [deps/openssl/openssl.target.mk:789: /home/abc/mediasoup/worker/out/Release/obj.target/openssl/deps/openssl/openssl/ssl/bio_ssl.o] Error 1
> make[1]: Leaving directory '/home/abc/mediasoup/worker/out'
> make: *** [Makefile:23: default] Error 2
>

**Comment by krishisola** [comment]
Hi Inaki,

I'm evaluating Amlogic S905x based boards. These are available as Android TV boxes in the market. Ex: X96 Android TV box. But, I've loaded Armbian Buster (Linux) O/S and working with Mediasoup based solution. Then found the reported error (-m64) while building the nodejs part of my application.

I did test the latest v3 commit and updated my findings in the above post (from prizemprov).

Do let me know if I need to do anything specific and can verify again.

**Comment by ibc** [comment]
Thanks. Can you please enter the mediasoup/worker/deps/openssl/openssl folder and compile openssl manually via configure, make etc? 

And if it works, please paste some lines of the build process to see which gcc command line options are being applied.

**Comment by krishisola** [comment]
[ms-ssl-make.txt](https://github.com/versatica/mediasoup/files/3393574/ms-ssl-make.txt)

Tried to build openssl and attached the build log. All looks fine except the last line as "Error". Was not sure. Hence attached the entire log.

The output of config is as follows:

> Operating system: aarch64-whatever-linux2
> Configuring OpenSSL version 1.1.1c (0x1010103fL) for linux-aarch64
> Using os-specific seed configuration
> Creating configdata.pm
> Creating Makefile
>

**Comment by ibc** [comment]
Can you tell me the exact configure/make calls you did? Just to test the same here.

**Comment by ibc** [comment]
I'll ask for something else if you don't mind. May you clone [node.js](https://github.com/nodejs/node) master branch into your device and do the following?

* `cd node`

* Edit [configure.py](https://github.com/nodejs/node/blob/master/configure.py) and apply this patch:

```diff
diff --git a/configure.py b/configure.py
index 2376095719..4fe1982fc8 100755
--- a/configure.py
+++ b/configure.py
@@ -879,9 +879,13 @@ def host_arch_cc():
       if rtn != 's390':
         break
 
+  print('1 ------------- host_arch_cc():', rtn)
+
   if rtn == 'mipsel' and '_LP64' in k:
     rtn = 'mips64el'
 
+  print('2 ------------- host_arch_cc():', rtn)
+
   return rtn
 
 
@@ -958,9 +962,15 @@ def configure_node(o):
   # the Makefile resets this to x86 afterward
   if target_arch == 'x86':
     target_arch = 'ia32'
+
+  print('3 ------------- target_arch:', target_arch)
+
   # x86_64 is common across linuxes, allow it as an alias for x64
   if target_arch == 'x86_64':
     target_arch = 'x64'
+
+  print('4 ------------- target_arch:', target_arch)
+
   o['variables']['host_arch'] = host_arch
   o['variables']['target_arch'] = target_arch
   o['variables']['node_byteorder'] = sys.byteorder
```

* `./configure`

In my mac it prints:

```
$ ./configure
1 ------------- host_arch_cc(): x64
2 ------------- host_arch_cc(): x64
3 ------------- target_arch: x64
4 ------------- target_arch: x64
[...]
```

Can you print it? I need to know which arch it's detecting.

**Comment by krishisola** [comment]
> I'll ask for something else if you don't mind. May you clone [node.js](https://github.com/nodejs/node) master branch into your device and do the following?
> 
> * `cd node`
> * Edit [configure.py](https://github.com/nodejs/node/blob/master/configure.py) and apply this patch:
> 
> ```diff
> diff --git a/configure.py b/configure.py
> index 2376095719..4fe1982fc8 100755
> --- a/configure.py
> +++ b/configure.py
> @@ -879,9 +879,13 @@ def host_arch_cc():
>        if rtn != 's390':
>          break
>  
> +  print('1 ------------- host_arch_cc():', rtn)
> +
>    if rtn == 'mipsel' and '_LP64' in k:
>      rtn = 'mips64el'
>  
> +  print('2 ------------- host_arch_cc():', rtn)
> +
>    return rtn
>  
>  
> @@ -958,9 +962,15 @@ def configure_node(o):
>    # the Makefile resets this to x86 afterward
>    if target_arch == 'x86':
>      target_arch = 'ia32'
> +
> +  print('3 ------------- target_arch:', target_arch)
> +
>    # x86_64 is common across linuxes, allow it as an alias for x64
>    if target_arch == 'x86_64':
>      target_arch = 'x64'
> +
> +  print('4 ------------- target_arch:', target_arch)
> +
>    o['variables']['host_arch'] = host_arch
>    o['variables']['target_arch'] = target_arch
>    o['variables']['node_byteorder'] = sys.byteorder
> ```
> 
> * `./configure`
> 
> In my mac it prints:
> 
> ```
> $ ./configure
> 1 ------------- host_arch_cc(): x64
> 2 ------------- host_arch_cc(): x64
> 3 ------------- target_arch: x64
> 4 ------------- target_arch: x64
> [...]
> ```
> 
> Can you print it? I need to know which arch it's detecting.

abc@x96:~/node$ ./configure
1 ------------- host_arch_cc(): arm64
2 ------------- host_arch_cc(): arm64
3 ------------- target_arch: arm64
4 ------------- target_arch: arm64

**Comment by krishisola** [comment]
From the script ../mediasoup/worker/scripts/configure.py
- platform.machine() returns "aarch64" which doesn't have a check in "def host_arch():"
- Hence, the -Dhost_arch='aarch64' and -Dtarget_arch='aarch64'
- This could be resulting in the -m64 error while compiling ssl related files

Is this a possible fix?
> diff --git a/worker/scripts/configure.py b/worker/scripts/configure.py
> index 962186b0..553c2f6b 100755
> --- a/worker/scripts/configure.py
> +++ b/worker/scripts/configure.py
> @@ -25,10 +25,13 @@ except ImportError:
>  
>  def host_arch():
>    machine = platform.machine()
>    if machine == 'i386': return 'ia32'
>    if machine == 'x86_64': return 'x64'
> +  if machine == 'aarch64': return 'arm64'
>    if machine.startswith('arm'): return 'arm'
>    if machine.startswith('mips'): return 'mips'
>    return machine  # Return as-is and hope for the best.
>  
>  def compiler_version():

With above change, did a clean build of mediasoup/worker. Build is successful.

**Comment by ibc** [comment]
I've read that, indeed, "aarch64" == "arm64" so looks good. I'll commit to v2 branch and let you know. Thanks!

**Comment by ibc** [comment]
I've pushed to v3 branch. Can you please try this?

```bash
$ git clone https://github.com/versatica/mediasoup.git
$ cd mediasoup
$ git checkout v2
$ cd worker
$ make
$ cd ..
$ npm run test
```

Please confirm that it works and I'll release 2.6.13 with the fix (and also in v3 branch).

**Comment by ibc** [comment]
Let's reopen until confirmed by @krishisola

**Comment by ibc** [comment]
Well, let's assume it's ok. Releases done (v2.6.13 and v3.2.1). If something is wrong please notify here :)

**Comment by krishisola** [comment]
Verified v2.6.13. All good.
Thank you for your quick fix.

**Comment by ibc** [comment]
Great!

**Comment by ibc** [comment]
And thank you for the fix above :)

**Comment by jmillan** [comment]
Thanks @krishisola!

**Comment by cicadabear** [comment]
#### On the arm64 machine or container, install x86-64-linux-gnu-gcc , ```debian:bookworm``` is what I'm using.
```
# apt-get install g++-x86-64-linux-gnu libc6-dev-amd64-cross
```
#### Maybe you need to install other amd64 libs on the arm64 platform
```
# dpkg --add-architecture amd64 
# apt-get udate
# apt-get install libjpeg-dev:amd64
```
