### ISSUE TITLE
Leak in TcpConnection

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#325]
As @mariat-atg is investigating (in v2 but it's mostly the same) it seems to be a leak in `TcpConnection` class:

https://github.com/LivelyVideo/mediasoup/commit/b511177967306cf2d2276899a04a13424637387a

I've created a branch [tcp-connection-leak](https://github.com/versatica/mediasoup/tree/tcp-connection-leak) in v3 by adding global `num_rtc_tcp_connections` and `num_tcp_connections` counters that are increased and decreased in their corresponding constructor and destructor.
Indeed I see that the counters do not become 0 when reloading the web app! They just decrease if I call `window.CLIENT.close()` in the browser console, but If I reload the web they do not decrease.

**NOTE:** Once this is fixed, it will be applied to both v3 and v2.

### Testing scenario

Run the demo server with `logLevel: "debug"` and `logTags: [ "ice" ]` and with proper `DEBUG` env variable:

```bash
$ server/ DEBUG="*INFO* *WARN* *ERROR* *mediasoup:worker*" INTERACTIVE=true ./server.js
```

Enter the demo app in two tabs in the same room forcing TCP:

* The first one will just produce (`&consume=false`) so it will generate a single transport (peerconnection):

```
https://LOCAL-DOMAIN:3000/?roomId=foo&info=true&consume=false&forceTcp=true
```

* The second one will nor produce neither consume (no peerconnection is created). It just needed to avoid that, on last participant left, the room is closed:

```
https://LOCAL-DOMAIN:3000/?roomId=foo&info=true&consume=false&produce=false
```

In the logs (due to tab 1):

```
  mediasoup:ERROR:worker[pid:61289] TcpConnection::TcpConnection() | >>> num_tcp_connections: 1 +0ms
  mediasoup:ERROR:worker[pid:61289] RTC::TcpConnection::TcpConnection() | >>> num_rtc_tcp_connections: 1 +3ms
  mediasoup:worker[pid:61289] TcpConnection::OnUvRead() | connection closed by peer, closing server side +0ms
  mediasoup:ERROR:worker[pid:61289] TcpConnection::Close() | >>> num_tcp_connections: 1 (calling uv_close()) +3ms
  mediasoup:worker[pid:61289] TcpServer::OnTcpConnectionClosed() | TCP connection closed +1ms
  mediasoup:ERROR:worker[pid:61289] TcpConnection::onClose() | >>> num_tcp_connections: 1 +0ms
  mediasoup:ERROR:worker[pid:61289] TcpConnection::TcpConnection() | >>> num_tcp_connections: 2 +5ms
  mediasoup:ERROR:worker[pid:61289] RTC::TcpConnection::TcpConnection() | >>> num_rtc_tcp_connections: 2 +0ms
  mediasoup:worker[pid:61289] RTC::IceServer::HandleTuple() | transition from state 'new' to 'connected' +6ms
  mediasoup:worker[pid:61289] RTC::WebRtcTransport::OnIceServerSelectedTuple() | ICE selected tuple +0ms
  mediasoup:worker[pid:61289] RTC::WebRtcTransport::OnIceServerConnected() | ICE connected +595ms
  mediasoup:worker[pid:61289] RTC::IceServer::HandleTuple() | transition from state 'connected' to 'completed' +2ms
  mediasoup:worker[pid:61289] RTC::WebRtcTransport::OnIceServerCompleted() | ICE completed +0ms
```

The `onClose` may happen because Chrome is connecting the server remote IP from two local IPs, and once the first connects at TCP level, it closes the second TCP connection. That's ok.
  * The **problem** here is that `onClose` is being called but no class destructor is being called! so here a leak!!!
  * I think the problem is that `TcpConnection::Close()` is being called, but not the destructor.

Then in the tab 1 console run `window.CLIENT.close()`. It will close the WebSocket connection, so the demo server will call `webRtcTransport.close()`. It does destroys the TCP connections (all but the one that was "closed" but not destroyed above):

```
  mediasoup:ERROR:worker[pid:60890] RTC::TcpConnection::~TcpConnection() | >>> num_rtc_tcp_connections: 1 +50s
  mediasoup:ERROR:worker[pid:60890] TcpConnection::~TcpConnection() | >>> num_tcp_connections: 1 +0ms
  mediasoup:ERROR:worker[pid:60890] TcpConnection::onClose() | >>> num_tcp_connections: 1
```

**Comment by ibc** [comment]
NOTE: I'm adding more debug logs in the branch.

**Comment by ibc** [comment]
I think I've fixed it in that branch.

**Comment by ibc** [comment]
So the issue is fixed in mediasoup 3.2.5 and also in mediasoup 2.6.14 in this [commit](https://github.com/versatica/mediasoup/commit/3e98a74c01fa61a41165839839a9472864ffa0a9?ts=2).

@mariat-atg can you take a look at it? I'll close the issue for now.

**Comment by mariat-atg** [comment]
Apologies, I was not receiving github updates till now, will pick up the fix in the morning, looks like that's it.

**Comment by ibc** [comment]
Don't worry, it was Sunday anyway :)

**Comment by mariat-atg** [comment]
Tested overnight in v2, it is doing fine in prod. Thank you for fixing!

**Comment by ibc** [comment]
Great!
