### ISSUE TITLE
Consider new npm-scripts.js usage

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#340]
In "devel" branch there is now a `npm-scripts.js` Node script to manage "scripts" in `package.json` in a more friendly way. It also replaces the `worker/win-tasks.js`.

@haiyangwu may you please take a look to it and let me know you think about it? Thanks a lot.

**Comment by ibc** [comment]
BTW @haiyangwyu, is this necessary (in `win-tasks.js` or in my `npm-tasks.js` that replaces it)?

```js
PYTHON = process.env.PYTHON || 'python';
GULP = path.join(__dirname, '..', 'node_modules', '.bin', 'gulp');
MSBUILD = process.env.MSBUILD || 'MSBuild';
MEDIASOUP_BUILDTYPE = process.env.MEDIASOUP_BUILDTYPE || 'Release';
MEDIASOUP_TEST_TAGS = process.env.MEDIASOUP_TEST_TAGS || '';
```

Note that this script is executed via `npm run` so NPM puts `./node_modules/.bin` into the `PATH`. So why do we need to reference those binaries in `./node_modules/.bin`?

**Comment by haiyangwu** [comment]
> BTW @haiyangwyu, is this necessary (in `win-tasks.js` or in my `npm-tasks.js` that replaces it)?
> 
> ```js
> PYTHON = process.env.PYTHON || 'python';
> GULP = path.join(__dirname, '..', 'node_modules', '.bin', 'gulp');
> MSBUILD = process.env.MSBUILD || 'MSBuild';
> MEDIASOUP_BUILDTYPE = process.env.MEDIASOUP_BUILDTYPE || 'Release';
> MEDIASOUP_TEST_TAGS = process.env.MEDIASOUP_TEST_TAGS || '';
> ```
> 
> Note that this script is executed via `npm run` so NPM puts `./node_modules/.bin` into the `PATH`. So why do we need to reference those binaries in `./node_modules/.bin`?

Just a copy of `GULP = ../node_modules/.bin/gulp`  from [Makefile](https://github.com/versatica/mediasoup/blob/v3/worker/Makefile).

 Anyway, use `GULP = process.env.GULP || 'gulp'` seems better.

**Comment by haiyangwu** [comment]
The new branch [npm-scripts](https://github.com/versatica/mediasoup/tree/npm-scripts) looks clean and simpler. I'll take a deep look at it tonight. 🤓

**Comment by ibc** [comment]
> Just a copy of `GULP = ../node_modules/.bin/gulp` from Makefile.

Yep, but that's because we want to be able to run `make` within the `worker/` folder without calling any `npm run` script .)

So I'll simplify it, thanks for confirming.

And yes, please, let me know if the *npm-scripts* branch works fine for you in Windows.

**Comment by ibc** [comment]
BTW, even if it works now in `devel` branch with `--no-arguments` in `run-os-scripts`, I'd still want to check how the `nmp-scripts` branch works since I think it's simpler.

**Comment by ibc** [comment]
BTW I've merged "npm-scripts" branch into "devel" branch, so please better test the "devel" branch in Windows (I've also removed the "npm-scripts" branch). Thanks!

**Comment by ibc** [comment]
If there is something wrong, please report here. I'll close this issue for now since, in theory, everything should work in "devel" branch in Windows.

**Comment by haiyangwu** [comment]
@ibc Yes, the `npm-scripts.js` is better and the "devel" branch worked in Windows. 

Use these code below to support `lint:node` in Windows.
```
execute('set MEDIASOUP_NODE_LANGUAGE=typescript&&eslint -c .eslintrc.js --ext=ts src/');
execute('set MEDIASOUP_NODE_LANGUAGE=javascript&&eslint -c .eslintrc.js --ext=js --ignore-pattern \'!.eslintrc.js\' .eslintrc.js gulpfile.js npm-scripts.js test/');
```
> don't add extra whitespace after `set MEDIASOUP_NODE_LANGUAGE=typescript`

**Comment by ibc** [comment]
Thanks, can we use [cross-env](https://www.npmjs.com/package/cross-env) instead (so common code for Unix and Windows)?

```js
execute('cross-env MEDIASOUP_NODE_LANGUAGE=typescript eslint -c .eslintrc.js --ext=ts src/');
execute('cross-env MEDIASOUP_NODE_LANGUAGE=javascript eslint -c .eslintrc.js --ext=js --ignore-pattern \'!.eslintrc.js\' .eslintrc.js gulpfile.js npm-scripts.js test/');
```

Pushed to "devel" branch BTW, so just test it :)

**Comment by haiyangwu** [comment]
` cross-env` seems a better solution which deals with more scenario. I'll test it and give u feedback ASAP, but tomorrow, I just closed the remote TeamViewer connection with my windows. 🙃

**Comment by haiyangwu** [comment]
@ibc Confirmed, `cross-env` works in Windows.

**Comment by ibc** [comment]
Fantastic. More closer than ever to 3.3.0 with transport-cc support, Windows support and Typescript :)
