### ISSUE TITLE
Relax the strict restriction of knowing the packet origin on plain transports

### ISSUE THREAD

**Issue by artushin** [versatica/mediasoup#341]
## Feature Request

Is there a reason to do the compare on https://github.com/versatica/mediasoup/blob/v3/worker/src/RTC/PlainRtpTransport.cpp#L605 for plain transports? I would imagine all use cases for plain transports are securely within a private network and having that check forces the user to have to port allocate on both the rtp sender and receiver and then communicate both ports to mediasoup before starting to send. Effectively, this means you can never start a sender after setting up the transport.

**Comment by ibc** [comment]
That's not true.

1. You first create the `PlainRtpTransport` in mediasoup server with your desired listen IP.
2. It will get a random port (and optionally also a RTCP port).
3. You read those listening ports via `transport.tuple.localPort` and `transport.rtcpTuple.localPort`.
4. You communicate the IP and port(s) of the mediasoup server transport to your RTP remote endpoint.
5. Then you run the remote endpoint and tell it to send RTP to that IP:port.
6. Then, once you know the local RTP/RTCP port(s) of your remote endpoint, you communicate them to mediasoup server and call `plainRtpTransport.connect({ ip, port, [rtcpPort] })`.

Alternatively, in step 1 above you can set `comedia: true` so step 6 is not needed.
