### ISSUE TITLE
Write our own bandwidth estimator

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#344]
**UPDATE: Work in progress**

Instead of depending in libwebrtc and its GCC implementation, we may move to BBR. However, we should then also replace the libwebrtc "probation" logic with our own one.

Spec and docs about BBR:

* [draft-cardwell-iccrg-bbr-congestion-control](https://tools.ietf.org/html/draft-cardwell-iccrg-bbr-congestion-control)
* [BBR: Congestion-Based Congestion Control](https://queue.acm.org/detail.cfm?id=3022184)
* [google/bbr](https://github.com/google/bbr)

Or NADA: https://tools.ietf.org/html/rfc8698

**Comment by yangpeiyong** [comment]
Does BBR support UDP?

**Comment by ibc** [comment]
> Does BBR support UDP?

It's implemented in QUIC, so yes.

**Comment by thayallans** [comment]
Have you gotten around to implementing this yet ?

**Comment by ibc** [comment]
This is not a forum, sorry.

**Comment by benbro** [comment]
Chrome removed the BBR experiment.
> Cleanup: Removes unused BBR congestion controller.
https://webrtc.googlesource.com/src.git/+/5c356bb9b159858d5dd6507773d3060202056b99

**Comment by ibc** [comment]
Thanks, we are not doing BBR anyway.

**Comment by benbro** [comment]
Do you plan to implement NADA  or something else? Is there something to track?

**Comment by ibc** [comment]
We'll update when there is progress.

**Comment by jonassmedegaard** [comment]
SCReAM (**S**elf-**C**locked **R**at**e** **A**daptation for **M**ultimedia) continues to be actively developed at https://github.com/EricssonResearch/scream

**Comment by wangyoucao577** [comment]
Why decide to write another bandwidth estimator? Any problem of the libwebrtc implementation?

**Comment by jonassmedegaard** [comment]
I am not involved with developing Mediasoup, but my guess is that libwebrtc is a painful dependency due to its over-the-fence development style by Google.

**Comment by jmillan** [comment]
>  libwebrtc is a painful dependency due to its over-the-fence development style by Google.

Basically, yes.

**Comment by wangyoucao577** [comment]
@jonassmedegaard  @jmillan  Thanks very much for the quick answer! But..if so, how about other transport related parts of `libwebrtc`? Such as re-transmission, FEC, etc. Will it be sufficient to remove Google dependency once the new congestion controller implemented?

**Comment by ibc** [comment]
We just use libwebrtc dep for BWE.

**Comment by wangyoucao577** [comment]
So how about the ARQ, FEC strategies? Does the `mediasoup` project contain them already? Any docs? How's the effects in weak network connections compare with libwebrtc implementation? Thanks!

**Comment by ibc** [comment]
Please, questions and discussions in the forum, not here.

**Comment by wangyoucao577** [comment]
Will do. Sorry.

**Comment by ldecicco** [comment]
@ibc any update on this? It would be very nice to have this implemented as an interface. Any pointer to a branch where this is in the working? Thanks!

**Comment by ibc** [comment]
No much updates yes, sorry.

**Comment by jmillan** [comment]
@ldecicco,

We could have a discussion about this topic.

**Comment by ldecicco** [comment]
We sure can!

**Comment by ibc** [comment]
Finally libwebrtc is being updated and our friend Eugene is tuning it, so in the short/medium term we are not gonna complete this task. Let's close it.
