### ISSUE TITLE
[Windows] Support for Visual Studio 2019

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#347]
Here a fork of mediasoup adding support for VS 2019. It seems that gyp is not doing it correctly so this fork modified gyp files:

* https://github.com/aoslee/mediasoup/commit/1fa405557fec87296f6bd28f4a10f1e9940b2118

Does it make sense? If so, we should send a PR to gyp project in Google Source Code:

* https://bugs.chromium.org/p/gyp/issues

Related issue in GYP project:

* https://github.com/nodejs/node-gyp/issues/1663

/CC @haiyangwu

**Comment by haiyangwu** [comment]
* [aoslee@1fa4055](https://github.com/aoslee/mediasoup/commit/1fa405557fec87296f6bd28f4a10f1e9940b2118) this commit makes sense and made it work to generate Visual Studio 2019 Project Struct.

* [gyp@eb296f67da](https://chromium.googlesource.com/external/gyp/+/eb296f67da078ec01f5e3a9ea9cdc6d26d680161%5E%21/) This is the similar code from gyp project in Google Source Code.

@ibc In my opinion, merging this commit is better for there's no timeline gyp project add this feature.

**Comment by ibc** [comment]
Thanks. However, honestly I wouldn't like to have a modified version of `gyp` within mediasoup. I just want to run `./scripts/get-dep.sh gyp` (being in `mediasoup/worker/` folder) from time to time without having to worry about re-applying local changes again and again.

In the past we had a problem in `gyp` due to issues with Python3:

* https://bugs.chromium.org/p/gyp/issues/detail?id=36#c59

@saghul fixed it and I commented his patch into the issue:

* https://bugs.chromium.org/p/gyp/issues/detail?id=36#c59

Finally, they added it to master branch:

* https://chromium.googlesource.com/external/gyp/+/da63cb0ffdbcedd0231ffac027adf1bce7391391%5E%21/
* https://chromium.googlesource.com/external/gyp/+/4f1618abf348fea8a58555841a26518899a57f0a%5E%21/

However, we were told to upload patches as peer [here](https://bugs.chromium.org/p/gyp/issues/detail?id=36#c75). So, I expect that if a "PR" is sent it will be accepted.

Does it make sense?

**Comment by haiyangwu** [comment]
> without having to worry about re-applying local changes again and again

Agree and it makes sense. 😏

**Comment by ibc** [comment]
Hi, somehow I've changed a bit my mind. Once there is a PR in gyp project, I'm open to modify the gyp source code in mediasoup and wait for gyp to adopt the PR. The same applies to the other Windows related project (in case it has any relationship with gyp).

**Comment by ibc** [comment]
Hi, any progress on this? Has been the issue reported to GYP project?

NOTE: https://gyp.gsrc.io/docs/Hacking.md

**Comment by ibc** [comment]
Ok, I've created the CL:

* https://chromium-review.googlesource.com/c/external/gyp/+/1982599

Please comment on it if possible. Note that, if any developer asks me, I won't be able to explain anything (I've just copied the change above, I cannot test in Windows and never used MSV).

**Comment by ibc** [comment]
I've pushing a new branch `issue-347` with the above exact commit: 

* https://github.com/versatica/mediasoup/commit/d739ef6d8a210a1cf2adefa7ce0f23b0f67c891f

I'd like that the CL uploaded to GYP project is approved (so we don't need to manage our "own" GYP source code). Anyway, if you guys confirm that the branch is ok, I'll merge into `v3`.

**Comment by ibc** [comment]
**UPDATE:** I've merged (and then deleted) the `issue-347` into `v3` and released in mediasoup 3.4.8.

Let's keep this issue open to remember that, in theory, we are waiting got GYP to accept the CL, so we don't have to manage our own modified GYP sources:

* https://chromium-review.googlesource.com/c/external/gyp/+/1982599

**Comment by ibc** [comment]
Just decided to drop gyp and move to CMake. See #359.

**Comment by james133** [comment]
support cmake vc2019,xcode,clion 
https://github.com/yanhua133/mediasoup-sfu-cpp

**Comment by jmillan** [comment]
No idea what that is about @james133.

**Comment by nazar-pc** [comment]
We moved away from GYP as a build system, so this particular issue should now be irrelevant, closing.
