### ISSUE TITLE
sequence number removed from the NACK list due to max retries

### ISSUE THREAD

**Issue by vishnusadanandan** [versatica/mediasoup#351]
## Bug Report

RTC::NackGenerator::GetNackBatch() | sequence number removed from the NACK list due to max retries

### Your environment

- Operating system: Linux
- Node version: v12.13.1
- npm version: 6.12.1
- gcc/clang version:
- mediasoup version: 3.7
- mediasoup-client version: 3.3.3

### Issue description
I got above error while i am connecting from a web client

**Comment by ibc** [comment]
So you open a **bug** report just to get clarification about what log means, right?

Sorry, it does not work that way.
