### ISSUE TITLE
Enable SRTP and RTX/NACK and PipeTransport (and SRTP in PlainTransport)

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#352]
When connecting two `PipeTransports` running in `Routers` in different hosts (so the network link may generate packet lost and may need RTP encryption for security), we may wish to have RTX/NACK and SRTP enabled:

#### RTX/NACK

Enable RTX and NACK for RTP retransmission.

#### SRTP

Useful to protect the RTP and RTCP traffic if both Routers are located in different hosts.

**Comment by ibc** [comment]
We also have to enable RTX on PipeTransports for scenarios in which a PipeTransport interconnects two workers in different hosts with potential packet loss.

**Comment by ibc** [comment]
WIP!

Support for RTX and NACK into `PipeTransports` is done in the new "pipetransport-rtx" branch. Here the [commit](https://github.com/versatica/mediasoup/commit/af65f7a268a956de3279e10d1f323f63e8a2834f).

To enable it, just add `enableRtx: true` in `router.createPipeRouter(options)` in both `Routers` that are supposed to run in different hosts.

if anyone can try it I would appreciate it.

**Comment by ibc** [comment]
And now the "pipetransport-srtp" branch has also **SRTP for PipeTransport** (in addition to RTX/NACK).


### We need testing!

If anyone wants to help, checkout the mediasoup "pipetransport-srtp" GIT branch and try the following (assuming that you already use `router.createPipeTransport()` API to communicate two `Routers` located in the same host or different hosts):


### Enable RTX in PipeTransport (for video)

* Add `enableRtx: true` to `router.createPipeRouter(options)` in both `Routers`.
* That's all. Of course, if you can generate packet lost in the link that connects both `PipeTransports`that would be great.


### Enable SRTP in PipeTransport

* Add `enableSrtp: true` to `router.createPipeRouter(options)` in both `Routers`.
* Read the new `pipeTransport1.srtpKey` getter and call `pipeTransport2.connect(options)` in the other `PipeTransport` by adding `srtpKey` into `options` (`srtpKey` value must be the value of `pipeTransport1.srtpKey`). And vice-versa.
* The RTP and RTCP in both directions should become SRTP and SRTCP.
* If you connect a browser to consume from `pipeTransport2` you should get valid audio/video.

**Comment by alex-outsourci** [comment]
That's awesome you added support of SRtp to PipeTransport, but @ibc do you plan to do the same for PlainRtpTransport?

**Comment by ibc** [comment]
> That's awesome you added support of SRtp to PipeTransport, but @ibc do you plan to do the same for PlainRtpTransport?

I've added SRTP to `PipeTransports` because I got some time and there were many users requesting it. Not unlimited time here. But [donations](https://mediasoup.org/sponsors/#become-a-sponsor) usually work.

**Comment by ibc** [comment]
Some changes in `pipetransport-srtp` branch:

PipeTransport: use new `SrtpParameters`dictionary if `enableSrtp` is true:

- `pipeTransport.keySrtp` has been removed.
- added `pipeTransport.srtpParameters` which has:
  - `cryptoSuite` (always 'AES_CM_128_HMAC_SHA1_80')
  - `keyBase64`
- `pipeTransport.connect()` no longer requires remote `srtpKey` but remote `pipeTransport.srtpParameters`.

**Comment by ibc** [comment]
"pipetransport-srtp" branch merged into "v3" branch and deleted. Will be released soon.

**Comment by ibc** [comment]
So this is done (including SRTP in `PlainTransport`):

https://mediasoup.discourse.group/t/mediasoup-3-5-0-is-out-with-srtp-and-rtx-in-pipetransport-and-more/617

mediasoup 3.5.0 is out.

### NEWS

- ✅ `PipeTransport`: add support for SRTP and RTP retransmission (RTX + NACK).
- ✅ `PlainTransport`: Add support for SRTP. New "tuple" event.

---------

By enabling RTP retransmission and SRTP in `PipeTransports`, now it's possible to interconnect mediasoup servers running in different hosts or even in different countries, no matter how good the network link is, by using encrypted RTP in both directions.

---------

SRTP in `PlainTransport` is useful to connect non WebRTC endpoints that support SRTP (such as many SIP devices) to mediasoup.

* SRTP guidelines in the [website](http://mediasoup.org/documentation/v3/communication-between-client-and-server/#guidelines-for-srtp-capable-endpoints)

In addition, `PlainRtpTransport` has been renamed to `PlainTransport` (the old naming still is valid and marked as DEPRECATED).

As a bonus: new “tuple” and “rtcpTuple” events in `PlainTransport` that notify the application when the remote RTP/RTCP origin has been discovered (if comedia mode is set).
