### ISSUE TITLE
Drop gyp, move to CMake

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#359]
Rationale:

* Nobody is maintaining `gyp`.
* `libuv` is dropping `gyp`.
* We (mediasoup authors) have to provide and maintain our own `xxx.gyp` for `libsrtp`, `usrsctp` and more deps we use, while those libraries do support `CMake` out of the box.
* There is `gyp` issues in Windows that nobody fixes (even if reported in `gyp` project) and affect mediasoup (see #345 and #347).

So let's move to `CMake`:

* Should choose a `CMake` version available in most common platforms (Debian, Ubuntu, OSX, etc). 
* Avoid the very latest and coolest `CMake` version since some of its features are not implemented by most common versions such as 3.7.

Ping @saghul because I can.

**Comment by saghul** [comment]
Current worker deps:

|Name|CMake support upstream?|
|--|--|
|catch| ✅ |
|getopt| ✅ |
|json| ✅ |
|lcov| 🚫 |
|libsrtp| ✅ |
|libuv| ✅ |
|libwebrtc| 🚫  |
|netstring| 🚫  |
|openssl| 🚫 |
|usrsctp| ✅ |

Out of these, I'd say OpenSSL is the trickiest one. An option would be to move to BoringSSL, which does support CMake out of the box. The rest are pretty small and writing CMakefiles for them should be trivial.

**Comment by ibc** [comment]
Wow, thanks! BTW:

* `lcov` is not really used in mediasoup (I mean, it's not built).
* Regarding `libwebrtc` we only use a subset of files so it shouldn't be hard to make a `CMakelists.txt` for it (wait, it depends on `abseil-cpp` lib but it does provide `CMakelists.txt`).
* `netstring` is two files code :)
* `openssl`... wow, didn't know that... Moving to BoringSSL is an option, of course, but somehow I don't want to rely on so many Google-managed projects... sad.

**Comment by saghul** [comment]
>     * `openssl`... wow, didn't know that... Moving to BoringSSL is an option, of course, but somehow I don't want to rely on so many Google-managed projects... sad.

It already has the necessary APIs for QUIC unlike OpenSSL (still in PR) so maybe it's a sign from, the future! 😎

**Comment by barry-ran** [comment]
[OpenSSL-CMake](https://github.com/pol51/OpenSSL-CMake)

**Comment by ibc** [comment]
> [OpenSSL-CMake](https://github.com/pol51/OpenSSL-CMake)

It's a 4 years old project.

**Comment by holmbuar** [comment]
Please correct me if I am interrupting or misunderstanding, this is just a friendly attempt to contribute. I copied this from the BoringSSL Git [1]:

>Although BoringSSL is an open source project, it is not intended for general use, as OpenSSL is. We don't recommend that third parties depend upon it. Doing so is likely to be frustrating because there are no guarantees of API or ABI stability.

[1]: https://boringssl.googlesource.com/boringssl/

**Comment by barry-ran** [comment]
[openssl-cmake](https://github.com/janbar/openssl-cmake)

**Comment by barry-ran** [comment]
I am trying to move mediasoup to cmake. I have made some attempts and it should be successful ([mediasoup-cmake](https://github.com/barry-ran/mediasoup-cmake))

**Comment by ibc** [comment]
Interesting, This will be very useful for us.

Just wondering: Did you use `openssl-cmake` project into it? And what else did you have to modify (other than creating the `CMakeLists.txt` file)?

BTW I tried it in OSX and it seems to work, but I get these warnings:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../libcrypto.a(ebcdic.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../libcrypto.a(async_null.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../libcrypto.a(async_win.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../libcrypto.a(rsaz_exp.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../libcrypto.a(cms_cd.c.o) has no symbols

[...]

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../libssl.a(ssl_utst.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../libssl.a(t1_trce.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../libssl.a(ssl_utst.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../libssl.a(t1_trce.c.o) has no symbols
```

**Comment by barry-ran** [comment]
> libssl.a(ssl_utst.c.o) has no symbols

Yes, I used openssl-cmake. Now the mediasoup-cpp worker can only be compiled and run. It has not been rigorously tested. I will continue to improve it later (for example, [there](https://github.com/barry-ran/mediasoup-cmake/blob/55c83dd9a1e78b764b1360d644510dd19b1328be/worker/CMakeLists.txt#L270) are some compilation options not added, I am not sure What question), now I just hope it can help you.

**Comment by ibc** [comment]
Thanks, don't hesitase in updating this issue with your progress, please.

**Comment by jmillan** [comment]
Hi @barry-ran,

I see that [mediasoup-cpp](https://github.com/barry-ran/mediasoup-cpp) is a separate project, not a mediasoup branch.

Could you please make it a mediasoup branch (out of current mediasoup v3 version) so it's easier to compare, collaborate and actually merge? We would like to put some efforts on this.

Thanks

**Comment by barry-ran** [comment]
Hi @jmillan ,
Ok i will do it, give me some time

**Comment by jmillan** [comment]
> Ok i will do it, give me some time

:+1:

**Comment by barry-ran** [comment]
> Hi @jmillan ,
> Ok i will do it, give me some time

Hi @jmillan ,
Sorry for not finishing till now，I cut off the [feat/gyp-move-to-camke](https://github.com/barry-ran/mediasoup/commits/feat/gyp-move-to-camke) branch based on 3.6.7, I try to small changes:
1. replace openssl with [openssl-cmake](https://github.com/janbar/openssl-cmake)
2. add CMakeLists.txt
3. build on [github action](https://github.com/barry-ran/mediasoup/actions/runs/134962848)

It has not been rigorously tested.  [There](https://github.com/barry-ran/mediasoup/blob/22059312445c397c01b7912395bae2e568c26696/worker/CMakeLists.txt#L278) are some compilation options not added, I am not sure What question (Because I don’t know much about these options).

**Comment by jmillan** [comment]
Thanks @barry-ran

**Comment by jmillan** [comment]
Hi @barry-ran,

I'm getting the following error when trying to compile your branch:

<img width="1100" alt="Screenshot 2020-06-17 at 17 33 58" src="https://user-images.githubusercontent.com/732340/84918387-d27f7800-b0c0-11ea-8d3a-f27586d5fc32.png">

Such file is not present in `deps/openssl/openssl/crytpo`

**Comment by barry-ran** [comment]
> Hi @barry-ran,
> 
> I'm getting the following error when trying to compile your branch:
> 
> <img alt="Screenshot 2020-06-17 at 17 33 58" width="1100" src="https://user-images.githubusercontent.com/732340/84918387-d27f7800-b0c0-11ea-8d3a-f27586d5fc32.png">
> 
> Such file is not present in `deps/openssl/openssl/crytpo`

Hi @jmillan ,
You should build it with cmake:
```
mkdir build
cd build
cmake ..
cmake --build .
```

**Comment by mabuchner** [comment]
@barry-ran I tried to compile your branch on Windows with Visual Studio 2017, but CMake gave me the following error during configuration

```
-- Building for: Visual Studio 15 2017
-- Check if the system is big endian
-- Searching 16 bit integer
CMake Error at C:/Program Files/CMake/share/cmake-3.19/Modules/TestBigEndian.cmake:30 (message):
  TEST_BIG_ENDIAN needs either C or CXX language enabled
Call Stack (most recent call first):
  CMakeLists.txt:4 (TEST_BIG_ENDIAN)
```

To fix this, I had to move the `project` definition to the top of the `CMakeLists.txt` file

```cmake
cmake_minimum_required(VERSION 3.16)

set(PROJECT_NAME "mediasoup-worker")
project(${PROJECT_NAME})

...
```

Afterwards I was able to configure and build with CMake

```sh
cmake -S . -B build -G "Visual Studio 15 2017" -A x64
cmake --build build --config Release
```

Finally, I had to copy `mediasoup-worker.exe`, `usrsctp.dll` and `uv.dll` to `mediasoup/worker/out/Release`. I also tried to specify the `CMAKE_INSTALL_PREFIX` and build the `INSTALL` target, but nothing was installed.

**Comment by jmillan** [comment]
Hi @barry-ran,

Sorry for the long time without feedback.

Would you be willing to make a PR agains current v3?

**Comment by jmillan** [comment]
I've just tried and had the same issue @mabuchner had.

**Comment by barry-ran** [comment]
> @barry-ran I tried to compile your branch on Windows with Visual Studio 2017, but CMake gave me the following error during configuration
> 
> ```
> -- Building for: Visual Studio 15 2017
> -- Check if the system is big endian
> -- Searching 16 bit integer
> CMake Error at C:/Program Files/CMake/share/cmake-3.19/Modules/TestBigEndian.cmake:30 (message):
>   TEST_BIG_ENDIAN needs either C or CXX language enabled
> Call Stack (most recent call first):
>   CMakeLists.txt:4 (TEST_BIG_ENDIAN)
> ```
> 
> To fix this, I had to move the `project` definition to the top of the `CMakeLists.txt` file
> 
> ```cmake
> cmake_minimum_required(VERSION 3.16)
> 
> set(PROJECT_NAME "mediasoup-worker")
> project(${PROJECT_NAME})
> 
> ...
> ```
> 
> Afterwards I was able to configure and build with CMake
> 
> ```shell
> cmake -S . -B build -G "Visual Studio 15 2017" -A x64
> cmake --build build --config Release
> ```
> 
> Finally, I had to copy `mediasoup-worker.exe`, `usrsctp.dll` and `uv.dll` to `mediasoup/worker/out/Release`. I also tried to specify the `CMAKE_INSTALL_PREFIX` and build the `INSTALL` target, but nothing was installed.

try this?
```
cmake --build . --config Release --target install
```

**Comment by barry-ran** [comment]
> Hi @barry-ran,
> 
> Sorry for the long time without feedback.
> 
> Would you be willing to make a PR agains current v3?

Ok i will do it

**Comment by jmillan** [comment]
Thank you!

**Comment by mabuchner** [comment]
> try this?
> 
> ```
> cmake --build . --config Release --target install
> ```

I tried

```sh
cmake -S . -B build -G "Visual Studio 15 2017" -A x64 -D CMAKE_INSTALL_PREFIX="build/install"
cmake --build build --config Release --target install
```

The CMake summary says

```
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18363.
-- summary of build options:
    Install prefix:  C:/Users/user.name/project-name/node_modules/mediasoup/worker/build/install
    Target system:   Windows
    Compiler:
      C compiler:    C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
      CFLAGS:         /DWIN32 /D_WINDOWS
```

But as before nothing was installed.

**Comment by barry-ran** [comment]
> > Hi @barry-ran,
> > Sorry for the long time without feedback.
> > Would you be willing to make a PR agains current v3?
> 
> Ok i will do it

Hi @jmillan @mabuchner 

 I rebased current v3 and fixed some error, this [pr](https://github.com/versatica/mediasoup/pull/546)
I've tested the following command:
```
cmake .. -D CMAKE_INSTALL_PREFIX=./dist
cmake --build . --target install
```
mediasoup-worker.exe and uv.dll is installed in the ./dist/lib/Debug directory (usrsctp is static now)

**Comment by nazar-pc** [comment]
BTW, was Meson under consideration?
I see many projects transition to it eventually.

**Comment by ibc** [comment]
> BTW, was Meson under consideration?
> 
> I see many projects transition to it eventually.

We want something that it's already integrated into most of the C/C++ libraries used by mediasoup. Meson is not.

**Comment by nazar-pc** [comment]
I'm far from either of those, but it seems like using CMake projects in Meson is relatively straightforward: https://mesonbuild.com/CMake-module.html

So you'd use dependencies that already have CMake support as is.

**Comment by ibc** [comment]
I don't even know CMake so I'm not gonna learn Meson to integrate CMake into it XD

**Comment by nazar-pc** [comment]
I found this option for OpenSSL: https://github.com/viaduck/openssl-cmake
It will download desired OpenSSL version during build step, thus should be easier to maintain and keep up to date with OpenSSL updates. Will also reduce size of NPM package and Rust crate (I had to request to bump the limit for crate size to even publish mediasoup-sys).

**Comment by ibc** [comment]
Late thanks, @nazar-pc. Unclear whether such a OpenSSL will come with the optimized build options that have been merged into mediasoup today. Will see when we come back to this topic.

**Comment by nazar-pc** [comment]
I'm learning CMake to make this happen, but approaching from a different angle.

GYP can actually produce CMakeLists.txt files, with current GYP config it actually produces two (Release and Debug).

After minor tweaks it seems to build most of the stuff just fine as is. I'll try to combine both files into one and then swapping explicit instructions for building dependencies with includes/imports/whatever it is called in CMake. That will make ensure there is a working build all along and wouldn't necessarily block CMake introduction on upstream CMake support on every dependency too much.

I'll see where it goes, but no promises, no ETA.

**Comment by ibc** [comment]
Are you learning CMake? 😀😀😀😀

**Comment by ibc** [comment]
Just in case, here another approach: https://github.com/versatica/mediasoup/pull/602

**Comment by nazar-pc** [comment]
If some of subscribed to this issue have time to look at and maybe even test #622, it would be very helpful!
