### ISSUE TITLE
C++: Remove inline methods

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#366]
We use too many `inline` methods, declared and **defined** in the corresponding `.hpp` files.

Using `inline` is not the panacea. In increases compilation time and executable size (the latter is not a big issue for us). But, overall, we have ended with many classes having half of their methods defined in the `.cpp` file and the other half in the `.htpp` file. And we cannot use `MS_XXXX` logging functions in `.hpp` files.

@jmillan what about getting rid of **all** `inline` methods? If so, we may have to create new `.cpp` files (for instance, for all classes in `Utils/` folder).

**Comment by jmillan** [comment]
I find it OK moving inline methods defined in .hpp files into .cpp. Maybe one line getters could remain in .hpp files, just for the shake of readability?

**Comment by ibc** [comment]
Why is that "readability"? In other words, are these inline methods "getters"?

```c++
	/* Inline methods. */

	inline bool SimpleConsumer::IsActive() const
	{
		// clang-format off
		return (
			RTC::Consumer::IsActive() &&
			this->producerRtpStream &&
			this->producerRtpStream->GetScore() > 0u
		);
		// clang-format on
	}

	inline std::vector<RTC::RtpStreamSend*> SimpleConsumer::GetRtpStreams()
	{
		return this->rtpStreams;
	}
```

**Comment by jmillan** [comment]
just this type:

```c++
inline std::vector<RTC::RtpStreamSend*> SimpleConsumer::GetRtpStreams()
	{
		return this->rtpStreams;
	}
````

But I have no strong opinion here, it's just cosmetic.

**Comment by ibc** [comment]
We may even avoid the `inline` section in .hpp files and directly define the method in the method declaration within the `class` declaration.

**Comment by jmillan** [comment]
> We may even avoid the inline section in .hpp files and directly define the method in the method declaration within the class declaration.

yes

**Comment by ibc** [comment]
Some work being done in `issue-366-remove-inline-methods` branch.
