### ISSUE TITLE
Update DTLS ciphers

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#367]
Right now we are using ciphers as they were in an old version of Chrome/libwebrtc:

```c++
ret = SSL_CTX_set_cipher_list(
		  DtlsTransport::sslCtx, "ALL:!ADH:!LOW:!EXP:!MD5:!aNULL:!eNULL:@STRENGTH");
```

We should modernize it. Chrome's current ciphers are:

`"DEFAULT:!NULL:!aNULL:!SHA256:!SHA384:!aECDH:!AESGCM+AES256:!aPSK"`

More info:

* https://github.com/ssllabs/research/wiki/SSL-and-TLS-Deployment-Best-Practices

**Comment by ibc** [comment]
Let's keep the issue open until verified.

**Comment by fippo** [comment]
can confirm i've been using that cipher set for ages (~2016) without issues

**Comment by ibc** [comment]
Thanks!
