### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [versatica/mediasoup#370]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like in [the function “FeedbackItem::Serialize”](https://github.com/versatica/mediasoup/blob/4e4639319a928a990df1a85752dfbf8c262c32fb/worker/include/RTC/RTCP/FeedbackItem.hpp#L55 "Update candidate").

**Comment by ibc** [comment]
Thanks. We'll eventually clean those C++ minor details. We don't need an open bug for this (already in our internal TODO). 

Thanks.

**Comment by elfring** [comment]
How do you think about to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by ibc** [comment]
We already use clang-tidy. Please read `Building.md` file.

If you have improvements for it (such as the option you reference) please provide a PR and will check it.

**Comment by elfring** [comment]
:crystal_ball: Are you even going to increase the usage of smart pointers?

**Comment by ibc** [comment]
Probably. But, why is that important? Do you see any leak or non freed pointer?

**Comment by elfring** [comment]
Smart pointers can help to reduce relevant source code, can't they?
