### ISSUE TITLE
Errors during npm install

### ISSUE THREAD

**Issue by litashg** [versatica/mediasoup#374]
9016 warn ws@7.2.3 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
9017 warn ws@7.2.3 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
9018 warn mediasoup_v3_example@0.8.0 No repository field.
9019 verbose stack Error: mediasoup@3.5.6 postinstall: `node npm-scripts.js postinstall`
9019 verbose stack Exit status 1
9019 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
9019 verbose stack     at EventEmitter.emit (events.js:189:13)
9019 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
9019 verbose stack     at ChildProcess.emit (events.js:189:13)
9019 verbose stack     at maybeClose (internal/child_process.js:970:16)
9019 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
9020 verbose pkgid mediasoup@3.5.6
9021 verbose cwd /Users/Hennadii/Projects/mediasoup
9022 verbose Darwin 17.7.0
9023 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
9024 verbose node v10.15.1
9025 verbose npm  v6.4.1
9026 error code ELIFECYCLE
9027 error errno 1
9028 error mediasoup@3.5.6 postinstall: `node npm-scripts.js postinstall`
9028 error Exit status 1
9029 error Failed at the mediasoup@3.5.6 postinstall script.
9029 error This is probably not a problem with npm. There is likely additional logging output above.
9030 verbose exit [ 1, true ]

**Comment by ibc** [comment]
Oh, you ignored the bug report template. Closed.
