### ISSUE TITLE
Npm install Failed - [Errno 2] No such file or directory [CentOs]

### ISSUE THREAD

**Issue by chamikara1998** [versatica/mediasoup#376]
Npm installed failed in Digital Ocean Droplet

`Traceback (most recent call last):
  File "./scripts/configure.py", line 83, in <module>
    (major, minor), is_clang = compiler_version()
  File "./scripts/configure.py", line 36, in compiler_version
    proc = subprocess.Popen(CC.split() + ['--version'], stdout=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
make: *** [default] Error 1
make: Leaving directory `/root/node_modules/mediasoup/worker'`

My System pieces of information are mentioned below

OS - Cent OS 7
make - GNU Make 3.82
python - 2.7 & 3
gcc - 9.1
node - v10.19.0

### Your environment

- Operating system: Cent OS 7
- Node version:  v10.19.0
- npm version: 6.13.4
- gcc/clang version:  9.1
- mediasoup version: 3.5.6
- mediasoup-client version: tried only server

**Comment by ibc** [comment]
Do a git clone of mediasoup (not mediasoup-demo) into a different folder. Enter into mediasoup/worker folder, run make and paste the output here.

**Comment by chamikara1998** [comment]
Traceback (most recent call last):
  File "./scripts/configure.py", line 87, in <module>
    raise RuntimeError('gcc <= 4.8 not supported, please upgrade your gcc')
RuntimeError: gcc <= 4.8 not supported, please upgrade your gcc
make: *** [default] Error 1

**Comment by chamikara1998** [comment]
Then I tried

CC=gcc-9.1 make

output

Traceback (most recent call last):
  File "./scripts/configure.py", line 83, in <module>
    (major, minor), is_clang = compiler_version()
  File "./scripts/configure.py", line 36, in compiler_version
    proc = subprocess.Popen(CC.split() + ['--version'], stdout=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
make: *** [default] Error 1

**Comment by ibc** [comment]
Now you see your problem.

https://mediasoup.org/documentation/v3/mediasoup/installation/#linux-osx-and-any-nix-system

**Comment by ibc** [comment]
Try with Python 2.

**Comment by chamikara1998** [comment]
Hello IBC Problem Solved.

Problem with GCC Version

`sudo yum install devtoolset-9-toolchain`
`scl enable devtoolset-9 bash`

This fixed issue. Anyway thank you so much.
