### ISSUE TITLE
Upload prebuilt mediasoup-worker by github actions

### ISSUE THREAD

**Issue by keroxp** [versatica/mediasoup#378]
Hi, We're using mediasoup for our product. This is awesome!

On installing from npm, building mediasoup-worker (in postinstall) is quite heavy, especially when building docker image. I found that `MEDIASOUP_WORKER_BIN` is useful for speed up of building by specifying prebuilt worker binary. 

So how about uploading mediasoup-worker binary to github release on tagged?  puppeteer downloads chromium binary in installing. I'm understanding that built `mediasoup-worker` can run by stand-alone, is correct?

Thanks.

**Comment by ibc** [comment]
mediasoup must build many C/C++ deps (openssl, libuv, usrsctp, etc) so we cannot create a magic static binary that works in all platforms (all Linux/BSD distributions and versions and OSX).

**Comment by cqh963852** [comment]
Can we create different static binary for linux osx and windows?

**Comment by ibc** [comment]
> Can we create different static binary for linux osx and windows?

It depends. Who is "we"?

**Comment by cqh963852** [comment]
> > Can we create different static binary for linux osx and windows?
> 
> It depends. Who is "we"?

I means,If there is a way can create different binary.let me try it.Although i am not familiar c++ addon.

**Comment by ibc** [comment]
I assume it's possible to create binaries and store them somewhere and then pull them during `npm install mediasoup`. It's just that we don't have time for that now.
