### ISSUE TITLE
Add support for multichannel OPUS

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#381]
It seems that we may need to just add support for OPUS codecs with MIME type `audio/multiopus` and read the number of channels (4, 6, etc) from `codec.channels` as usual.

We also need to do it in mediasoup-client and libmediasoupclient.

References:

* [Surround Sound (5.1 and 7.1) in lib#webrtc and Chrome](https://webrtcbydralex.com/index.php/2020/04/08/surround-sound-5-1-and-7-1-in-libwebrtc-and-chrome/) by @agouaillard.
* [Added support for multichannel Opus audio (surround)](https://github.com/meetecho/janus-gateway/pull/2059) in Janus,

**Comment by nazar-pc** [comment]
FYI, I started hacking on this in https://github.com/nazar-pc/mediasoup/tree/multiopus
