### ISSUE TITLE
Support End-to-End Encryption with WebRTC Insertable Streams

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#383]
We should wait for AV1 Generic dependency descriptor and SFrame to be both sync’ed.

**Specs:**

* [draft-omara-sframe](https://tools.ietf.org/html/draft-omara-sframe)
* [RTP Payload Format For AV1](https://aomediacodec.github.io/av1-rtp-spec/), includes the [Dependency Descriptor RTP Header Extension](https://aomediacodec.github.io/av1-rtp-spec/#dependency-descriptor-rtp-header-extension) definition which is supposed to be generic in the future (to handle any codec).
* [AOMediaCodec/av1-rtp-spec](https://github.com/AOMediaCodec/av1-rtp-spec) in GitHub.
* [Layer Refresh Request (LRR) RTCP Feedback Message](https://tools.ietf.org/html/draft-ietf-avtext-lrr), needed for SVC codecs (although not yet implemented in libwebrtc).

**Reading:**

* https://webrtchacks.com/true-end-to-end-encryption-with-webrtc-insertable-streams/
* https://mediasoup.discourse.group/t/e2eme-with-sframes-in-chrome/762/7
* [Explainer - WebRTC Insertable Streams](https://github.com/alvestrand/webrtc-media-streams/blob/master/explainer.md)
* [About E2EE key exchange and keyframe implications](https://github.com/w3c/webrtc-extensions/pull/37#issuecomment-628774128)

**Comment by davedoesdev** [comment]
How does this relate to https://tools.ietf.org/html/draft-ietf-perc-double-12 ?

**Comment by ibc** [comment]
What is the exact question?

**Comment by davedoesdev** [comment]
Are insertable streams an implementation of the "PERC: SRTP Double Encryption Procedures" spec?

**Comment by davedoesdev** [comment]
Ah I see you already answered this https://mediasoup.discourse.group/t/e2eme-with-sframes-in-chrome/762

**Comment by tapionx** [comment]
:+1:

**Comment by Klagio** [comment]
Hi! Is there a timeline for E2EE support?

**Comment by ibc** [comment]
> Hi! Is there a timeline for E2EE support?

Please, read the issue description. This is not something that can be done really now.

Anyway this issue is not for discussions, use the public forum for questions, please. Deleting these comments.

**Comment by lbennett-stacki** [comment]
https://github.com/medooze/sframe

**Comment by vpalmisano** [comment]
It works on the demo without any modifications to the mediasoup libraries: https://github.com/versatica/mediasoup-demo/pull/105

With VP9 there are no limitations in the encryption algorithm.
For VP8 and OPUS a starting offset should be added to allow the SFU to correctly parse the media packets (https://github.com/webrtc/samples/blob/gh-pages/src/content/insertable-streams/endtoend-encryption/js/worker.js#L19).

**Comment by ibc** [comment]
Thanks to @vpalmisano this is done and already available in the online mediasoup demo:

* https://v3demo.mediasoup.org/?roomId=YOUR_ROOM_ID&info=true&e2eKey=YOUR_KEY_HERE

Just replace `YOUR_ROOM_ID` and `YOUR_KEY_HERE` with whatever strings and open the link in two Chrome/Canary tabs. If you remove e2eKey from the URL params in one of the tabs and reload it, you will just listen to and see garbage.
