### ISSUE TITLE
freeze on safari mobile ios 13.2

### ISSUE THREAD

**Issue by bilicio** [versatica/mediasoup#385]
## Bug Report

**IMPORTANT:** We primarily use GitHub as an issue tracker. Just open an issue here if you have encountered a bug in mediasoup.

If you have questions or doubts about mediasoup or need support, please use the mediasoup Discourse Group instead:

https://mediasoup.discourse.group

If you got a crash in mediasoup, please try to provide a core dump into the issue report:

https://mediasoup.org/support/#crashes-in-mediasoup-get-a-core-dump

### Your environment

- Operating system:
- Node version:
- npm version:
- gcc/clang version:
- mediasoup version:
- mediasoup-client version:

### Issue description

Im using the demo online version of the app and on mac chrome i can see the two cameras normally but on safari mobile the two cameras are static freeze.

**Comment by ibc** [comment]
Thanks for ignoring the whole issue template.
