### ISSUE TITLE
Add support in the JS API to send arbitrary RTP packets

### ISSUE THREAD

**Issue by ggarber** [versatica/mediasoup#39]
Something in the sender side equivalent to the on packet event in the receiver side:

Maybe soemthing like:
```
RtpSender.send(packet: Buffer|RtpObject)
```

**Comment by ibc** [comment]
Yep, it will be done. However, prior to that I need to deal with "virtual peers" implementation (this is: local/virtual peers that do not have an associated `Transport`(s) and so on.

**Comment by notedit** [comment]
cool     i have done this in my  native  code.

**Comment by notedit** [comment]
can we do this now?

**Comment by ibc** [comment]
No. In fact, receiving RTP packets in JS has been removed in v2. Now we have [room.createRtpStreamer()](https://mediasoup.org/documentation/mediasoup/api/#room-createRtpStreamer) to mirror RTP to a given IP:port using plain RTP over UDP.

In the future we'll also add a way to inject plain RTP (over UDP) into a room so all the participants will receive it via WebRTC.

**Comment by notedit** [comment]
i see that change.  but still wait the  raw rtp sender api,  so that we  can mix other media service with mediasoup.

**Comment by ibc** [comment]
Support for receiving plain RTP is being done in the [plainRtpTransport](https://github.com/versatica/mediasoup/tree/plainRtpTransport) branch.
