### ISSUE TITLE
Consumer enables rtx, when RtpCapabilities not include rtx 

### ISSUE THREAD

**Issue by craterone** [versatica/mediasoup#390]
## Bug Report

RtpCapabilities
https://gist.github.com/craterone/8bd67fe66d2ec86285fcfa6b82bb7793

It seems mediasoup not check rtx with codec. I only set rtx with `VP8` and `VP9` , but it also enables rtx in `H264`.

Maybe We should set `rtxSupported` , after check parameters.
https://github.com/versatica/mediasoup/blob/v3/src/ortc.ts#L961

### Your environment

- Operating system: macOS
- Node version:  -
- npm version: - 
- gcc/clang version:
- mediasoup version: latest, v3
- mediasoup-client version:

**Comment by ibc** [comment]
No, this is on purpose. mediasoup supports RTX for any video codec. This is explained in the docs.
