### ISSUE TITLE
Worker crash

### ISSUE THREAD

**Issue by aetheon** [versatica/mediasoup#392]
## Bug Report
Worker crashes every so often, I've got a crash every 2 days or so.

core dump: https://drive.google.com/file/d/14IBZCsx4DXAsLHJ70K05tsvIxBrvqA_w/view

### Your environment

- Operating system: ubuntu1~18.04
- Node version: v10.19.0
- npm version: 6.13.4
- gcc/clang version: gcc 8.4.0 / g++7.5.0 / cc 8.4.0 / c++ 7.5.0
- mediasoup version: 3.5.8
- mediasoup-client version: 3.6.5

**Comment by ibc** [comment]
Attaching the coredump binary file is useless because we don't have your `mediasoup-worker` binary. Please check the steps in https://mediasoup.org/support/#crashes-in-mediasoup-get-a-core-dump.

**Comment by ibc** [comment]
Also the fact that you have different veersions for `gcc / cc` and `g++ / c++` is terribly suspicious. They are supposed to be the same.

**Comment by aetheon** [comment]
ah no just reset the machines to have 3.5.9. I'll do these steps next time it happens, provided its not fixed by that version. I'll close it for now tks.

**Comment by ibc** [comment]
Good news them :)

Thanks.
