### ISSUE TITLE
failed at the mediasoup@3.5.9 postinstall script while installing packages 

### ISSUE THREAD

**Issue by surya-vamsi2310** [versatica/mediasoup#393]
Hello 
after cloning git, and installing npm im getting error message something like this 
**failed at the mediasoup@3.5.9 postinstall script**

Can anyone help me please

**Comment by yadavpradeep786** [comment]
I'm also facing the same issue. Why all bugs are closed without solution?

**Comment by ibc** [comment]
Because they provide absolutely zero data, and they don't even fill the issue template.
