### ISSUE TITLE
Move to GitHub Actions?

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#397]
Just wondering if there is any benefit in moving from Travis-CI to GitHub Actions. It seems that GitHub Actions makes it easier to test in Mac and Windows. Example:

* https://github.com/eslint/eslint/blob/master/.github/workflows/ci.yml

**Comment by jmillan** [comment]
I was thinking on the very same.

**Comment by ibc** [comment]
Thanks to @nazar-pc for PR #521 that fixes this issue.
