### ISSUE TITLE
Implement simulcast

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#40]
**mediasoup** must be ready to accept simulcast from clients and choose the appropriate simulcast profile to forward to other participants based on their network bandwidth or other parameters (such as selection via API).

- [x] Check `RtpStreamSend` health to dynamically select a lower simulcast profile (do probation).
- [x] Wait for a RTP full frame before switching the Consumer simulcast profile to another one.
- [x] Rewrite VP8 `PictureId` and `TTL0IDX`.
- [x] Be ready for 1 byte `PictureId`:
  - https://bugs.chromium.org/p/webrtc/issues/detail?id=7877
  - https://bugzilla.mozilla.org/show_bug.cgi?id=1402242

* Docs: https://github.com/ibc/mediasoup/wiki/Simulcast-&-SVC

**Comment by jtg-gg** [comment]
hi @ibc any timeline when simulcast will be supported ?

**Comment by ibc** [comment]
Not before 1.0.

However, simulcast stuff in Chrome is an undocumented hack, the simulcast draft is terribly complex and no idea about Firerox+simulcast. So it may be better to directly go to VP9 SVC.

**Comment by jtg-gg** [comment]
@ibc I've just tested mediasoup and encounter problem that senders would adapt bitrate to the worst receiver conditions. any idea how to handle this issue ?

I've read that VP8 support temporal scalability, is this supported in media soup ? if yes how to enable it ?

**Comment by ibc** [comment]
That is not true. mediasoup does not adapt senders bitrate to the worst receiver. Please check current RTCP status:

https://github.com/ibc/mediasoup/issues/29#issuecomment-277628024

Also the wiki: https://github.com/ibc/mediasoup/wiki

And no, Chrome's VP8 temporal scalability (which is enabled with the simulcast hack) is not yet supported.

**Comment by ibc** [comment]
Some code to be applied in order to manage simulcast in `RtpReceiver`:

```c+
diff --git a/worker/src/RTC/RtpReceiver.cpp b/worker/src/RTC/RtpReceiver.cpp
index aa35696..209a008 100644
--- a/worker/src/RTC/RtpReceiver.cpp
+++ b/worker/src/RTC/RtpReceiver.cpp
@@ -291,14 +291,14 @@ namespace RTC
 
 	void RtpReceiver::GetRtcp(RTC::RTCP::CompoundPacket *packet, uint64_t now)
 	{
-		if (this->rtpStream)
+		if (static_cast<float>((now - this->lastRtcpSentTime) * 1.15) >= this->maxRtcpInterval)
 		{
-			if (static_cast<float>((now - this->lastRtcpSentTime) * 1.15) >= this->maxRtcpInterval)
+			for (auto it = this->rtpStreams.begin(); it != this->rtpStreams.end(); ++it)
 			{
-				RTC::RTCP::ReceiverReport* report = this->rtpStream->GetRtcpReceiverReport();
+				auto rtpStream = it->second;
+				RTC::RTCP::ReceiverReport* report = rtpStream->GetRtcpReceiverReport();
 
-				// TODO: This assumes a single stream for now.
-				report->SetSsrc(this->rtpParameters->GetEncodingMediaSsrc(0));
+				report->SetSsrc(this->rtpParameters->GetEncodingMediaSsrc(it->first));
 				packet->AddReceiverReport(report);
 
 				this->lastRtcpSentTime = now;
```

**Comment by ibc** [comment]
Mostly done. Still missing:

* Check `RtpStreamSend` health to dynamically select a lower simulcast profile.
* Wait for a RTP full frame before switching the `Consumer` simulcast profile to another one.

**Comment by jmillan** [comment]
- [ ] Check RtpStreamSend health to dynamically select a lower simulcast profile.
- [x] Wait for a RTP full frame before switching the Consumer simulcast profile to another one.

**Comment by jmillan** [comment]
@ibc, I think we can close this one.

**Comment by ibc** [comment]
Yep.
