### ISSUE TITLE
Data channel termination on mediasoup itself

### ISSUE THREAD

**Issue by nazar-pc** [versatica/mediasoup#400]
## Feature Request
It would be very convenient to be able to terminate DataChannel on mediasoup and be able to send/receive messages from application.

One use case is to control application (the room for instance) using existing DataChannel connection.

Another use case is smart routing on application level, where messages arrive at application, are inspected and then conditionally forwarded somewhere. This is basically an advanced version of what SFU already does, but it requires a ton of complexity on application level to implement with current API.

Currently implementing such things requires using https://github.com/latysheff/node-sctp and rather complex dance with creating additional DataChannel connections and keep it in sync with other stuff.

Assumption here is that it is not very complex in terms of implementation in contrast to handling audio/video on application level.

### API
Maybe something like `AppDataConsumer` and `AppDataProducer` that can be attached to router as application-level entities:
```
appDataProducer.send(message: Buffer|string|...)

appDataConsumer.on('message', fn())
```
And those can then be routed as usual.

**Comment by jnoring** [comment]
+1

Most media servers repurpose their signaling layer (for example, socket-io) to handle application level messages.  This has some clear disadvantages compared to using a datachannel as an application-layer transport.

Currently, we have RESTful API endpoints for signaling, and once the peer connection is established, we use a data channel to send/receive application-layer messages.  We experienced the same pain.  But it's worth it to get rid of a redundant persistent connection to the server.

**Comment by friksa** [comment]
Why not use Protoo?  You cannot use WebRTC datachannels until you used a signaling protocol to create them.  IMO Protoo is perfect for that and already terminated on the server.

**Comment by ibc** [comment]
I agree that this would be a good feature, and I feel your pain when trying to use `node-sctp` (although it works). Too complex setup.

The complexity of this proposal (which we already considered in the past) is that it breaks a bit the mediasoup design:

- The media (audio/video/SCTP) transmission with mediasoup is done via transports (WebRTC, plain, pipe transports).
- All those transports inherit from a base `Transport` in C++ land.
- On top of a transport (no matter which kind of transport) you can create `Producers`, `Consumers`, `DataProducers` and `DataConsumers`.

So the way to go would be:

- Add a new `DataTransport` which inherits from `Transport` but does not allow RTP traffic.
- On top of such a `DataTransport`, the application could just create `DataProducers` and `DataConsumers`.
- A `DataProducer` created in a `DataTransport` could rely messages to `DataConsumers` (no matter in which kind of transport those were created).
- Such a `DataTransport` (in mediasoup-worker C++ land) would be connected to Node land somehow.
  - Here we need a transmission format to send and receive text and binary messages plus the `id` of the corresponding `DataProducer`.
  - We may use a `UnixSocket` (as we already use to communicate mediasoup (Node) with mediasoup-client (C++).
  - Probably we could reuse the already existing `UnixStreamSocket.cpp` class.

So the API would look like this:

```js
const dataTransport = await route.createDataTransport();
const webrtcTransport = await route.createWebRtcTransport(...);

const dataProducer = await dataTransport.produceData({
  id,
  sctpStreamParameters,
  label,
  protocol,
  appData,
});

const dataConsumer = await webrtcTransport.consumeData({
  dataProducerId: dataProducer.id
});

// New API.
dataProducer.send('hi');

// The message will be delivered to the WebRTC endpoint via DataChannel.
```

**Comment by ibc** [comment]
BTW working on this.

**Comment by ibc** [comment]
Working on this in the [datachannel-termination](https://github.com/versatica/mediasoup/tree/datachannel-termination) branch.

For now, a new `DeviceChannel` C++ class has been created to enable bidirectional transmission of text/binary payloads between Node process and `mediasoup-worker` process by using a `UnixSocket` pair.

**Comment by ibc** [comment]
Opss... https://github.com/versatica/mediasoup/pull/409

**Comment by ibc** [comment]
And this: https://github.com/versatica/mediasoup-demo/pull/99

**Comment by ibc** [comment]
Done. Will be announced in a new mediasoup version (today if possible, otherwise next days).
