### ISSUE TITLE
Error: Unknown platform: win32

### ISSUE THREAD

**Issue by SupertigerDev** [versatica/mediasoup#407]
## Bug Report

**IMPORTANT:** We primarily use GitHub as an issue tracker. Just open an issue here if you have encountered a bug in mediasoup.

If you have questions or doubts about mediasoup or need support, please use the mediasoup Discourse Group instead:

https://mediasoup.discourse.group

If you got a crash in mediasoup, please try to provide a core dump into the issue report:

https://mediasoup.org/support/#crashes-in-mediasoup-get-a-core-dump

### Your environment

- Operating system: Windows 10 Pro 64 Bit
- Node version: 12.16.2
- npm version: 6.14.4
- mediasoup version: latest

### Issue description

When running this command:
```npm i mediasoup```

i get this error:
```
if (!platforms[platform]) throw new Error('Unknown platform: ' + platform)
                          ^

Error: Unknown platform: win32
    at Object.<anonymous> (D:\Coding\NodeJS Projects\MediaSoupTest\node_modules\clang-tools-prebuilt\install.js:24:33)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

**Comment by jmillan** [comment]
Use https://mediasoup.discourse.group/ for questions.

Check the archives for the same topic before formulating your question. It's been already answered few times.

**Comment by SupertigerDev** [comment]
It's not really a question but whatever. Imma just find something else. Thanks.

**Comment by ibc** [comment]
Have you checked existing issues?

**Comment by SupertigerDev** [comment]
Hey, I managed to get it to work with WSL but meh, Imma just give up. This seems way to complicated for me. more complicated to something like websockets. Thanks.

**Comment by friksa** [comment]
I can tell you from experience that this is the best option.  It is worth reading he docs and investing the time.

**Comment by SupertigerDev** [comment]
The docs have soo many things and idk what I'm looking for. There should be a very simple usage example or a simple quick start guide just like socket.io or discord.js have on their website.

I guess I will try again today but I doubt I will get far.

**Comment by ibc** [comment]
Ok. Don't hesitate to complain in the mediasoup public forum rather than here.
