### ISSUE TITLE
video freezing and frame-rate drops with high packets loss

### ISSUE THREAD

**Issue by MichaelShu3333** [versatica/mediasoup#412]
I used h.264/vp8 codec in behind 3 cases, and found that bursts of video freezed and frame-rate dropped with 20% uplink packets loss with FEC & nack. 
mode:
case 1: simple 
case 2: svc 
case 2: simulcast 

mediasoup 3.5.15
OS: debian 10

I find video become more and more blur :
simple mode, the packets loss is about 1% used FEC & nack, but video sometimes freezed and frame-rate dropped.
svc and simulcast mode, video always freezed and frame-rate dropped.
I want to know why and how to reduce video freezed and frame-rate dropped and make video streams more smooth

**Comment by ibc** [comment]
Please, ask in the mediasoup forum. We don't provide support/questions in GitHub.

**Comment by MichaelShu3333** [comment]
thx
