### ISSUE TITLE
Incorrect value in consumer.getStats()

### ISSUE THREAD

**Issue by geongun20** [versatica/mediasoup#414]
### Your environment

- Operating system: Ubuntu 18.04.4
- Node version: 10.20.1
- npm version: 6.14.4
- gcc/clang version: 7.5.0
- mediasoup version: 3.5.9
- mediasoup-client version: 3.6.5

### ssrc from producer.getStats() over time
![image](https://user-images.githubusercontent.com/43872798/83592481-69aee080-a595-11ea-9397-73aa6148d94a.png)

### ssrc from consumer.getStats() over time
![image](https://user-images.githubusercontent.com/43872798/83592643-c0b4b580-a595-11ea-96c8-ac1b258d0596.png)

### packetsLost from producer.getStats() over time
![image](https://user-images.githubusercontent.com/43872798/83592468-6287d280-a595-11ea-9ae6-850192653f5d.png)

### packetsLost from consumer.getStats() over time
![image](https://user-images.githubusercontent.com/43872798/83592406-3ec48c80-a595-11ea-844d-716f28bd5119.png)

### Issue description
I am strongly sure that this weird situation occured by mixing with other media in consumer.getStats(). This kind of situations occurs for most of consumers.

**Comment by ibc** [comment]
@jmillan perhaps we are updating related members **also** when computing scores so they affect next computation of packet loss? Something like that happened in the past.

**Comment by jmillan** [comment]
Probably. Need to reproduce and do some testing.

**Comment by jmillan** [comment]
@geongun20,

`packetsLost` in consumer stats are directly taken from RTCP ReceiverReport received by the endpoint, we don't do any calculation.

Looking at the stats of the endpoint you should also see this discrepancy.

I'llI close the issue, don't hesitate to comment anything if needed.
