### ISSUE TITLE
Set score:0 when dtx:true is set in encoding and there is no RTP

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#415]
When a Producer is created with `dtx:true` in an `encoding` we do not run the RTP inactivity timer in `RtpStreamRecv` so when such a stream stops sending RTP, we keep `score:10`.

In those cases, we should also run the RTP inactivity timer with a much higher value (i.e. 5-10 seconds).

**Comment by jmillan** [comment]
:+1:

**Comment by albyho** [comment]
👍
