### ISSUE TITLE
postinstall causes "npm prune --production" to rebuild everything

### ISSUE THREAD

**Issue by nazar-pc** [versatica/mediasoup#417]
### Issue description
This should not recompile everything when pruning dev dependencies.
https://github.com/versatica/mediasoup/blob/07c206ee86d5a411e6c9253e43d9fd1b7f3ba15a/npm-scripts.js#L121-L134

My Dockerfile looks like this:
<details>

```dockerfile
FROM node:13

WORKDIR /code

COPY .npmrc /code/.npmrc
COPY package.json /code/package.json
COPY package-lock.json /code/package-lock.json

RUN ["npm", "ci"]

FROM node:13

WORKDIR /code

COPY --from=0 /code /code

RUN ["npm", "prune", "--production"]

FROM node:13

WORKDIR /code

COPY --from=0 /code /code
COPY tsconfig.json /code/tsconfig.json
COPY tslint.json /code/tslint.json
COPY src /code/src

RUN ["npm", "run", "test"]
RUN ["npm", "run", "build"]

FROM node:13

WORKDIR /code

COPY --from=1 /code /code
COPY --from=2 /code/dist /code/dist

ENTRYPOINT ["node", "/code/dist/index.js"]
```

</details>

The idea is to cache as much as possible. Which is why all depenencies are installed first, which will be used for TypeScript build, then from the same dependencies non-production modules are pruned and then build artifact is deployed.

Currently pruning also causes mediasoup build to restart, which increases build time significantly and causes some other difficulties as well.

Maybe add some check that build was already finished or something like that?

UPD: This can be an improvement rather than a bug though.

**Comment by ibc** [comment]
I don't understand what this issue or feature request is about. mediasoup is a NPM library and, like any other, it's just installed (and hence compiled) when a new version is requested or available (based on SEMVER logic in `package.json`).

**Comment by nazar-pc** [comment]
The issue is that it is compiled once on `npm ci` and then once again if `npm prune --production` is called after that.

**Comment by ibc** [comment]
I have no idea about why it's compiled twice following those steps. First time I know about `npm prune` command. I just don't know about it and honestly don't have time to investigate it for now.

**Comment by nazar-pc** [comment]
Closing, seems to be an upstream issue in NPM itself
