### ISSUE TITLE
Starting applications with PM2 on Windows pops up blank console

### ISSUE THREAD

**Issue by BlueMagnificent** [versatica/mediasoup#418]
### My environment

- Operating system:  Win10 and Win Server 2012
- Node version: v12.16.1
- npm version: v6.13.7
- mediasoup version: v3.5.9

### Issue description
Starting applications with PM2  pops up blank console window generated by the mediasoup-worker executable ( judging from the full execution path shown as the title of the console ).

It does this for every worker process spawned.

Note that executing this same app through cmd does not generate any console directly from the mediasoup-worker executable.

Fortunately, It turned out that adding `windowsHide: true` to the options of `child_process_1.spawn()` in `src/Worker.ts` shown below solved the problem:
https://github.com/versatica/mediasoup/blob/1d1da457ea48450f5fa085982bf6178c20f08a85/src/Worker.ts#L263-L285

**Comment by ibc** [comment]
Can you send a PR?

**Comment by BlueMagnificent** [comment]
Sure, right away
