### ISSUE TITLE
Notify Consumers about all Producer layers/scores

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#420]
- `consume.on('layerschange')` tells the app about new current spatial and temporal layers being delivered to the consuming endpoint.
- `consumer.on('score')` tells the app about the score of the consuming endpoint (media from mediasoup to endpoint) and also about the score of the specific stream of the Producer.

But we lack a way to tell the app (via `Consumer` events) about the number of layers available (and per stream score) in the associated `Producer`.

Use case: I'm receiving a video in my browser and get information about current layers from the server. However I also want to know if I¡m receiving the maximum layers that the producing endpoint is currently sending or not. In other words: _"am I receiving your low quality video stream because my downlink is not good? or because your browser has dropped the medium and high layers temporary?"_.

**Comment by ibc** [comment]
Working in https://github.com/versatica/mediasoup/tree/feature-420 branch.

**Comment by nazar-pc** [comment]
I'm not sure this is necessary. Consumer options already contain this info in `rtpParameters.encodings[].scalabilityMode` property and scalability mode doesn't change over time from what I understand.

UPD: Ah, you want to know when producer downgrades quality? Then you can listen for score on corresponding producer...

**Comment by ibc** [comment]
`scalabilityMode` just tells the Consumer how many spatial layers (RTP streams in case of simulcast) and temporal it can receive. This issue (and the already finished PR #421) is about dynamically notifying the Consumer about the score of each RTP stream in the Producer.

Example:

- Alice creates a simulcast Producer to send video with 3 streams (low, medium, high quality) and N temporal layers each stream (irrelevant here).
- Bob consumes it so its `Consumer` has `scalabilityMode: "S3T3"`.
- Bob starts receiving the high quality stream so `consumer.currentLayers = { spatialLayer: 2, temporalLayer 2 }`.
- Eventually Bob receives the medium stream so `consumer.currentLayers = { spatialLayer: 1, temporalLayer: 2 }`.
- Bob does not know whether this is because mediasoup decided that there is no enough bandwidth to send the high stream to Bob **or** because Alice dropped the high quality stream.
- With PR #421 Bob can know the reason by looking at the `consumer.score` (the new `producerScores` array).
- If for instance Alice dropped the high stream, `producerScores` in `consumer.score` will look like `[10, 10, 0]`.
- That's the purpose of this feature.

**Comment by ibc** [comment]
@nazar-pc please take a look to the gifs I've added in https://github.com/versatica/mediasoup/pull/421 to understand this feature.

**Comment by ibc** [comment]
Done.
