### ISSUE TITLE
 Two integers division is an integer not float in c/c++

### ISSUE THREAD

**Issue by MichaelShu3333** [versatica/mediasoup#423]
## Bug Report
 Two integers division is integer not float in c/c++

### Your environment
- Operating system: Debian 10.4
- Node version: 
- npm version:
- gcc/clang version: 8.3
- mediasoup version: 3.6.6 
- mediasoup-client version:

### Issue description
in mediasoup worker/src/RTC/RtpStream.cpp:
this->score = static_cast<uint8_t>(std::round(totalScore / samples));
totalScore / samples is an integer in c/c++, not a float,
if totalScore equal 28 and samples equal 10, so std::round(totalScore / samples) is 2 not expect 3
so can change to:
`this->score = static_cast<uint8_t>(std::round(float(totalScore) / samples));`
or 
`this->score = static_cast<uint8_t>(std::round(static_cast<float>(totalScore)  / samples));`

**Comment by ibc** [comment]
Thanks, will do. Next time do not hesitase to send a PR :)

**Comment by MichaelShu3333** [comment]
Sorry, next time I will send to PR.  :)

**Comment by ibc** [comment]
Don't worry and thanks :+1:
