### ISSUE TITLE
Only cache one piece of media datas for one producer

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [versatica/mediasoup#425]
## Feature Request
For NACK, I find that now mediasoup media server cache one piece of media datas for each consumer,  there exists a problem, may cache more redundant datas between consumers.  In my opinion, the cache data should only cache one piece of data for one producer. Just like the rtmp GOP cache. Hope give some explain for this design.

**Comment by ibc** [comment]
In each Consumer we store mangled packets, this is RTP packets already adapted to the receiving endpoint (CSeq, RTP timestamp, VP8 payload ids, etc. modified). We also store the packets encoded in RTX format when needed). We cannot just store the packets in the Producer.

Anyway, please start a discussion in the forum if you wish. This won't be done so closing the issue.
