### ISSUE TITLE
Make it possible to consume RTP packets in DirectTransport

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#433]
```ts
const consumer = await directTransport.consume({ producerId: xxxxx });

consumer.on('rtp', (rtpPacket: Buffer) => {
  // Do stuff with the binary RTP packet.
});

// Send RTCP packet.
directTransport.sendRtcp(packet);

directTransport.on('rtcp', (rtcpPacket: Buffer) => {
  // Do stuff with the binary RTCP packet.
});
```

In addition this would be great:

```ts
const producer = await directTransport.produce(
  {
    kind: xxxx, 
    rtpParameters: xxxx,
   etc
  });

// Send RTP packet.
producer.send(rtpPacket);
```

@jmillan thoughts?

**Comment by jmillan** [comment]
Yep, absolutely.

**Comment by jnoring** [comment]
Oh man.  +1000, yes please.

**Comment by jnoring** [comment]
I'm probably getting greedy, but have you considered something like:

```
consumer.on('compressedVideoFrame', ( ... ) => {
});

consumer.on('compressedAudioFrame', ( ... ) => {
});
```

...although I realize this is quite a bit more difficult, because it would require reconstructing frame data from packets, which is non-trivial, particularly given all possible codecs, simulcast/svc, etc.

**Comment by ibc** [comment]
No. mediasoup is a SFU, it does not encode/decode frames. That's up to the RTP endpoint. The RTP endpoint (the one that runs `consumer.on('rtppacket')`) will also need to implement a jitter buffer, RTCP NACK etc.

This design opens the door to have a RTP stack in JavaScript, but that's not trivial.

**Comment by ibc** [comment]
opps...

https://github.com/versatica/mediasoup/pull/434

**Comment by jnoring** [comment]
> No. mediasoup is a SFU, it does not encode/decode frames. That's up to the RTP endpoint. The RTP endpoint (the one that runs `consumer.on('rtppacket')`) will also need to implement a jitter buffer, RTCP NACK etc.
> 
> This design opens the door to have a RTP stack in JavaScript, but that's not trivial.

To be clear, I'm not proposing it "encode/decode" frames.  I'm proposing it would reconstruct compressed frames.  Those are entirely different things.

And yes, even reconstructing compressed frames would require a jitter buffer, NACKs (and possibly PLIs), etc.  I understand it's not trivial, because I wrote that code for licode.

**Comment by ibc** [comment]
Yes, got it. But does not the purpose of a SFU but of a RTP endpoint. Look at the rtp.js repo here in versatica org.

**Comment by jnoring** [comment]
I'm not sure I follow that comment.

**Comment by ibc** [comment]
I just mean that the purpose of a SFU is to route RTP packets and not do things like jitterbuffer (which is required by an RTP endpoint). 

Here I'm creating a RTP endpoint in TypeScript (super WIP yet): https://github.com/versatica/rtp.js

**Comment by ibc** [comment]
Done in #434 (merged). To be released in 3.6.13 soon.

**Comment by ghost** [comment]
Hello I want to do something like this

```
const directTransport = await router.createDirectTransport();
const myproducer = await directTransport.produce(
  {
    kind: xxxx, 
    rtpParameters: xxxx,
  });



const consumer2 = await directTransport.consume({ producerId: producer.id,rtpCapabilities});
consumer2.on('rtp', (rtpPacket) => {
	myproducer.send(rtpPacket);
});
```
Is this possible ?

**Comment by ibc** [comment]
Please use the mediasoup forum for questions.
