### ISSUE TITLE
strp_stream created unexcepted

### ISSUE THREAD

**Issue by penguinol** [versatica/mediasoup#435]
We found an issus when using PipeTransport transmit streams.

We made a large conference  so we need to transmit streams between mediasoup-workers.

We will create one recv PipeTransport and one send PipeTransport between two workers, and all the streams are transmitting on them.

There are two clients knowned as A and B. A is on worker1, and B is on worker2.

When the fisrt time A watched B, it's ok.Then A left the conference and then rejoined, this time A can't hear B.

After some research, we found the reason:

Beacuse our system is a distributed system, so we remove producers and consumers on pipe-transport asynchronous.

Because of this, the producer on worker1 may removed before the consumer on worker2.

When we remove producer we will also remove the srtp_stream( #426 ), but the consumer is not deleted and is continually sending rtp packets. 

The transport on worker1 will re-create the strp_stream case we decrypt the packet before checking the ssrc/rid/mid.

When A rejoin the conference, we will create producer and consumer on pipe-transport again.

Beacuse the strp_stream is already created, so we will reuse it.

The seq num of the stream sent by woker2 is starting from 1, and strp_stream of producer can not decrypt it, as follow.

`WRTC::SrtpSession::DecryptSrtp() | srtp_unprotect() failed: replay check failed (bad index) (srtp_err_status_replay_fail)`

I think it's a bug, we can not guarantee the pipe-transport of producer not receive rtp packet after remove the conusmer  because of networker delay.

And it is also a safty risk, we can send some fake rtp packets to the transport, and this will let the transport create a lot of useless srtp_streams and cost cpu and memory.

**Comment by ibc** [comment]
Interesting. Here a proposal:

- When creating a `RtpStreamRecv` in a `Producer`, let's delete the new SSRC from the SRTP transport.

Would that work?

> And it is also a safty risk, we can send some fake rtp packets to the transport, and this will let the transport create a lot of useless srtp_streams and cost cpu and memory.

Please check `PipeTransport::OnRtpDataReceived()` in `PipeTransport.cpp`:

```c++
		// Decrypt the SRTP packet.
		if (HasSrtp() && !this->srtpRecvSession->DecryptSrtp(const_cast<uint8_t*>(data), &len))
		{
			RTC::RtpPacket* packet = RTC::RtpPacket::Parse(data, len);

			if (!packet)
			{
				MS_WARN_TAG(srtp, "DecryptSrtp() failed due to an invalid RTP packet");
			}
			else
			{
				MS_WARN_TAG(
				  srtp,
				  "DecryptSrtp() failed [ssrc:%" PRIu32 ", payloadType:%" PRIu8 ", seq:%" PRIu16 "]",
				  packet->GetSsrc(),
				  packet->GetPayloadType(),
				  packet->GetSequenceNumber());

				delete packet;
			}

			return;
		}

		// Verify that the packet's tuple matches our tuple.
		if (!this->tuple->Compare(tuple))
		{
			MS_DEBUG_TAG(rtp, "ignoring RTP packet from unknown IP:port");

			return;
		}
```

perhaps we should validate the source of the packet (`this->tuple->Compare(tuple)`) **before** decrypting the packet? However the same should be done in `PlainTransport` in which it would be much more difficult due to additional logic when a RTP packet is received.

Can you open a separate issue for this second concern? ("Avoid SRTP stream leak due to random SSRC values").

**Comment by penguinol** [comment]
Maybe we should check the ssrc/rid/mid before we decrypt the packet, because the rtp header is not encrypted.

**Comment by ibc** [comment]
> Maybe we should check the ssrc/rid/mid before we decrypt the packet, because the rtp header is not encrypted.

This won't be true once we implement SRTP encrypted extensions.

**Comment by ibc** [comment]
Let's handle the second issue (libsrtp leak) in a separate issue here: https://github.com/versatica/mediasoup/issues/437 and let's focus here in just the consumer/producer issue when using pipe transports.

**Comment by ibc** [comment]
@penguinol this should be fixed in `issue-435` branch (PR #438). Can you please check it so we release a new version?

**Comment by penguinol** [comment]
So you generate a random ssrc for pipe to fix it, am I right?
It should fix the problem.

**Comment by ibc** [comment]
> So you generate a random ssrc for pipe to fix it, am I right?

Yes, the `PipeConsumer` will now generate random SSRCs instead of copying the "mapped" ones of its `Producer`.

> It should fix the problem.

ok, will merge.
