### ISSUE TITLE
Avoid SRTP leak by deleting invalid SSRCs after STRP decryption

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#437]
Related to #435.

Currently when SRTP is enabled in any transport and a RTP packet is received:

- We decrypt SRTP first in the specific transport class. In `WebRtcTransport` we check packet source first, but this is irrelevant since malicious packets with random SSRC may be sent from the valid source.
- Then we call the parent `Transport::ReceiveRtpPacket()`.
- There we look for the corresponding `Producer` via `this->rtpListener.GetProducer(packet)`.
- If not found, we call `RecvStreamClosed(packet->GetSsrc())` to tell the child class to remove this SSRC.

This is not enough, since the packet may have valid MID/RID so a `Producer` would be found anyway. If then the SSRC is random for each packet, we are leaking `libsrtp`by creating more and more SRTP streams.

* **NOTE:** This is because we do `policy.ssrc.value = 0;` in `SrtpSession` constructor.

### Conclusion

If the SSRC is malicious (different random values being received) we'll leak. We need to remove the SRTP stream for the given SSRC in case the packet is not valid (which may be told by both the `Transport` and the `Producer`.

**Comment by penguinol** [comment]
https://github.com/meetecho/janus-gateway/blob/bb0ab0931644599e05c72acbfd1e759761242023/ice.c#L2285

In Janus, they do check ssrc/rid/mid before decrypt the packet.

But you are right, when we support encrypted rtp header extensions, we can't get rid/mid before decrypting the packet.

For PipeTransport, it's not a big problem, cause we use ssrc only.

But for WebrtcTransport, we need to consider more.

**Comment by jmillan** [comment]
What about this

```diff
diff --git a/worker/src/RTC/Transport.cpp b/worker/src/RTC/Transport.cpp
index bc2f2e070..b75a2c507 100644
--- a/worker/src/RTC/Transport.cpp
+++ b/worker/src/RTC/Transport.cpp
@@ -1628,6 +1628,9 @@ namespace RTC
                        case RTC::Producer::ReceiveRtpPacketResult::RETRANSMISSION:
                                this->recvRtxTransmission.Update(packet);
                                break;
+                       case RTC::Producer::ReceiveRtpPacketResult::DISCARDED:
+                               RecvStreamClosed(packet->GetSsrc());
+                               break;
                        default:;
                }
```

**Comment by ibc** [comment]
The packet may be discarded due to super old Seq or something like that. Is it a good idea to delete the SRTP stream in that case? Well, in fact it would be re-generated upon receipt of next RTP packet...

Said that, note that this is not yet enough. In pipe and plain transports we do SRTP decrypt (which may create a new SRTP stream) **before** we check the packet source.

**Comment by jmillan** [comment]
> Said that, note that this is not yet enough. In pipe and plain transports we do SRTP decrypt (which may create a new SRTP stream) before we check the packet source.

This is solvable in `OnRtpDataReceived` by calling `RecvStreamClosed` if the just decrypted RTP packet does not come from a valid source.

**Comment by penguinol** [comment]
We may also consider the situation of decrypting failed.

**Comment by jmillan** [comment]
> The packet may be discarded due to super old Seq or something like that. 

In that case `Producer::ReceiveRtpPacket` will return `ReceiveRtpPacketResult::MEDIA`. So the stream won't be deleted.
