### ISSUE TITLE
Support for video/ulpfec and video/red codecs

### ISSUE THREAD

**Issue by ambyjkl** [versatica/mediasoup#449]
## Feature Request
Packet loss is a common issue in WebRTC and while video/rtx does a great job when there is low latency, its benefits are drastically diminished when latency is high and even the retransmitted packets get lost. Hence it would be great if mediasoup would add support for these error correction formats.

**Comment by ibc** [comment]
We will implement FLEXFEC when really available in WebRTC clients. No need to keep a GitHub issue open for this. Thanks.

**Comment by ambyjkl** [comment]
Well this is kind of a big deal for us at the moment, what is the difficulty level to implement this? We'll see if we can have someone help building this. Considering we are generating the ulpfec packets on gstreamer before piping them into mediasoup and we just want to pass on the packets to consumers, is there anything special that would need to be done on mediasoup's end?

**Comment by ibc** [comment]
We don't want to implement ULPFEC because FLEXFEC looks much better, but it's still experimental in libwebrtc.

> what is the difficulty level to implement this?

Lack of time. Not just to implement it but also to give exact guidance to others about how to do it. To clarify: I cannot become an expert right now in UPLFEC just to explain others how to implement it in mediasoup.

**Comment by ambyjkl** [comment]
I see, that's definitely true, FLEXFEC indeed looks a lot better. It may take a long time before it makes it into libwebrtc on stable chrome, which is why ULPFEC seems like a more realistic option to us at the moment. Let's see if we are able to find someone with a good understanding of ULPFEC help implement this.
