### ISSUE TITLE
ortc.getConsumerRtpParameters codec comparison issue

### ISSUE THREAD

**Issue by binxie33** [versatica/mediasoup#452]
- Operating system: Ubuntu Server 18.04
- Node version:  v8.10.0
- npm version: 3.5.2
- gcc/clang version: 7.5.0
- mediasoup version: v3
- mediasoup-client version: v3

### Issue description

In mediasoup ortc.getConsumerRtpParameters fails to select the usable codecs when comparing codes arrays like
[ {h264-aaa}, {rtx}, {h264-bbb}, {rtx}]
[ {h264-ccc}, {rtx}, {h264-bbb}, {rtx}]

The consumerParams.codecs will be like: [{rtx}, {h264-bbb}, {rtx}]], and it will throw UnsupportedError('no compatible media codecs') even though {h264-bbb} is usable.

```
       // Ensure there is at least one media codec.
	if (consumerParams.codecs.length === 0 || isRtxCodec(consumerParams.codecs[0]))  //{rtx} is the first codec
	{
		throw new UnsupportedError('no compatible media codecs');
	} 
```

### proposed fix
```
    let rtxSupported = false;
    for ( let i = 0; i < consumableCodecs.length; i++) {

        const codec = consumableCodecs[i];

        // don't compare rtx 
        if (isRtxCodec(codec))
            continue;

        const matchedCapCodec = caps.codecs
            .find((capCodec) => matchCodecs(capCodec, codec, { strict: true }));
        if (!matchedCapCodec)
            continue;
        codec.rtcpFeedback = matchedCapCodec.rtcpFeedback;
        consumerParams.codecs.push(codec);

        const nextCodec = consumableCodecs[i + 1];
        if (nextCodec 
            && isRtxCodec(nextCodec) 
            && nextCodec.parameters.apt === codec.payloadType)
        {
            if (!rtxSupported )
                rtxSupported = true;

            consumerParams.codecs.push(nextCodec);
        }
        
    }
```

**Comment by ibc** [comment]
I don't like that solution. You are assuming that the RTX codec always comes **after** its associated media codec. That works for your specific use case and may break other legitimate ones.

What we should do is clean `consumerParams.codecs` by removing RTX codecs in there that are not associated to a media codec in `consumerParams.codecs`.

**Comment by binxie33** [comment]
Oh, my mistake. I agree your approach is better. I got the impression that RTX codecs always comes after its associated codec from **mediasoup-client/ortc.reduceCodecs** function. It is basically doing the same.  Maybe we should fix that function as well.

**Comment by ibc** [comment]
I don't see nothing wrong in mediasoup-client `ortc.reduceCodecs()` function...

**Comment by ibc** [comment]
Please check the branch `issue-452` and let me know if this fixes the bug in your scenario:

https://github.com/versatica/mediasoup/pull/453

**Comment by binxie33** [comment]
Thanks for the quick fix. I tested in my environment and confirmed it works fine.

**Comment by ibc** [comment]
Great, merging and releasing.
