### ISSUE TITLE
Documentation website certificate expired (mediasoup.org)

### ISSUE THREAD

**Issue by bfelbo** [versatica/mediasoup#455]
## Bug Report

FYI, it seems like the documentation website's certificate just expired (see screenshot below). I've confirmed that this is an issue across devices / networks.

![image](https://user-images.githubusercontent.com/23178145/92047756-cc517d00-ed3a-11ea-9955-c31390d49a60.png)

**Comment by jmillan** [comment]
Thanks for noticing @bfelbo.

Cert has been renewed.
