### ISSUE TITLE
yarn install causes mediasoup-worker ENOENT

### ISSUE THREAD

**Issue by hugomallet** [versatica/mediasoup#459]
Hi,

On MacOS in a project using yarn and workspaces, every time i launch yarn (install) i have to rebuild mediasoup because of this error :

```sh
Error: spawn .../node_modules/mediasoup/worker/out/Release/mediasoup-worker ENOENT
```

Then i have to run `npm rebuild mediasoup` to fix this error.

Any idea ?

Thanks

**Comment by ibc** [comment]
Please use the public mediasoup forum for questions.

**Comment by hugomallet** [comment]
This looks like an issue no ?

**Comment by ibc** [comment]
You cannot guarantee that this is a bug in mediasoup, can you?

Please describe the problem in the forum by providing steps to reproduce (we don't use yarn and I don't know what "workspaces" are).
