### ISSUE TITLE
Debug version make failed

### ISSUE THREAD

**Issue by bianxg** [versatica/mediasoup#460]
### Your environment

- Operating system: Ubuntu 16.04.6 LTS
- Node version: 
- npm version:
- gcc/clang version: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
- mediasoup version:   "mediasoup": "^3.5.14",
- mediasoup-client version:

### Issue description
I git clone https://github.com/edumeet/edumeet

$cd edumeet/server/node_modules/mediasoup/worker
$make clean
$export MEDIASOUP_BUILDTYPE=Debug
$ make

it shows some compile errors (It's ok when export MEDIASOUP_BUILDTYPE=Release):

../deps/libwebrtc/libwebrtc/modules/include/module_common_types_public.h:89:55: required from here
../deps/libwebrtc/libwebrtc/modules/include/module_common_types_public.h:24:68: error: overflow in constant expression [-fpermissive]
constexpr U kBreakpoint = (std::numeric_limits::max() >> 1) + 1;
^
../deps/libwebrtc/libwebrtc/modules/include/module_common_types_public.h:24:68: error: overflow in constant expression [-fpermissive]
cc1plus: warning: unrecognized command line option ‘-Wno-unknown-warning-option’
cc1plus: warning: unrecognized command line option ‘-Wno-parentheses-equality’

**Comment by bianxg** [comment]
I update mediasoup version 3.6.19
$make -j4 BUILDTYPE=Debug -C out
the result is same

**Comment by ibc** [comment]
I cannot reproduce it in Linux Debian with gcc 6. 

Try the following, please. In `worker/common.gypi` line 31 remove the `'-fwrapv'` option and try again.

**Comment by bianxg** [comment]
It's ok now. Thanks.
$ cd ~/project/edumeet/server/node_modules/mediasoup/worker
$ /home/test/anaconda2/bin/python2 ./scripts/configure.py -R mediasoup-worker
$ make -j4 BUILDTYPE=Debug -C out
