### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by sajalsoumalya** [versatica/mediasoup#461]
## Bug Report

**IMPORTANT:** We primarily use GitHub as an issue tracker. Just open an issue here if you have encountered a bug in mediasoup.

If you have questions or doubts about mediasoup or need support, please use the mediasoup Discourse Group instead:

https://mediasoup.discourse.group

If you got a crash in mediasoup, please try to provide a core dump into the issue report:

https://mediasoup.org/support/#crashes-in-mediasoup-get-a-core-dump

### Your environment

- Operating system: Ubuntu 16.04 LTS
- Node version: 13.0.1
- npm version: 6.12.0
- gcc/clang version: 5.4.0
- mediasoup version: N/A
- mediasoup-client version: N/A

### Issue description

When Ever I am Trying to Installing Mediasoup it is giving me the error 
i have tried using normal Install And Git clone but i am Gtting this error  Again and  Again 
```
/usr/bin/ld: /home/admin/mediasoup/worker/out/Release/libopenssl.a(bio_ssl.o): file class ELFCLASS64 incompatible with ELFCLASS32
/usr/bin/ld: final link failed: File in wrong format
collect2: error: ld returned 1 exit status
mediasoup-worker.target.mk:240: recipe for target '/home/admin/mediasoup/worker/out/Release/mediasoup-worker' failed
make[1]: *** [/home/admin/mediasoup/worker/out/Release/mediasoup-worker] Error 1
make[1]: Leaving directory '/home/admin/mediasoup/worker/out'
Makefile:23: recipe for target 'default' failed
make: *** [default] Error 2
make: Leaving directory '/home/admin/mediasoup/worker'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mediasoup@3.6.19 postinstall: `node npm-scripts.js postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mediasoup@3.6.19 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-10T17_08_33_384Z-debug.log
root@jisu-Conv:/home/admin/mediasoup# ^C
```
Please Help Me Out

**Comment by ibc** [comment]
Please, use the forum for questions and problems.
