### ISSUE TITLE
[Windows] Make mediasoup work with WinRTC

### ISSUE THREAD

**Issue by wbokkers** [versatica/mediasoup#467]
## Mediasoup for WinRTC
WinRTC is Microsoft's effort to bring WebRTC to native Windows apps. It would be great if mediasoup could be used on top of WinRTC. 

For more information on WinRTC:
https://github.com/microsoft/winrtc
https://www.youtube.com/watch?v=TNtn0Oa8rxI

**Comment by ibc** [comment]
mediasoup is a library for Node. It doesn't need to run on top of anything but Node.q

**Comment by wbokkers** [comment]
I think this issue is in the wrong place. Sorry for that. 
I meant to ask this for libmediasoupclient which is on top of WebRTC as I understand.

**Comment by wbokkers** [comment]
Or even that is not the right place, since I'm in need for WinRT components. Now I need to compile libwebrtc from Google, build libmediasoupclient and make some layer myself (like the Android and iOS third party efforts) for use in a WinRT context. These efforts are always behind the latest situation on both WebRTC and mediasoup.
