### ISSUE TITLE
npm ERR! mediasoup@3.6.21 postinstall: `node npm-scripts.js postinstall`

### ISSUE THREAD

**Issue by Diljitsingh14** [versatica/mediasoup#469]
> clang-tools-prebuilt@0.1.4 postinstall E:\Projects\Node js projects\mds\node_modules\clang-tools-prebuilt
> node install.js

E:\Projects\Node js projects\mds\node_modules\clang-tools-prebuilt\install.js:24
if (!platforms[platform]) throw new Error('Unknown platform: ' + platform)
                          ^

Error: Unknown platform: win32
    at Object.<anonymous> (E:\Projects\Node js projects\mds\node_modules\clang-tools-prebuilt\install.js:24:33)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

> mediasoup@3.6.21 postinstall E:\Projects\Node js projects\mds\node_modules\mediasoup
> node npm-scripts.js postinstall

npm-scripts.js [INFO] running task "postinstall"
npm-scripts.js [INFO] executing command: python ./worker/scripts/configure.py --format=msvs -R mediasoup-worker
npm WARN enoent ENOENT: no such file or directory, open 'E:\Projects\Node js projects\mds\package.json'
npm WARN mds No description
npm WARN mds No repository field.
npm WARN mds No README data
npm WARN mds No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: clang-tools-prebuilt@0.1.4 (node_modules\clang-tools-prebuilt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: clang-tools-prebuilt@0.1.4 postinstall: `node install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mediasoup@3.6.21 postinstall: `node npm-scripts.js postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mediasoup@3.6.21 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nebula\AppData\Roaming\npm-cache\_logs\2020-09-26T07_41_07_412Z-debug.log

**Comment by ibc** [comment]
Issue ignored due to the reporter's laziness.

**Comment by dinfer** [comment]
> Issue ignored due to the reporter's laziness.

I met the same problem. What do you mean? @ibc

**Comment by dinfer** [comment]
`clang-tools-prebuilt` does not support win32 system. 

https://github.com/hokein/clang-tools-prebuilt/blob/master/install.js#L17-L22

Is the installation doc outdated ?

https://mediasoup.org/documentation/v3/mediasoup/installation/#windows

**Comment by ibc** [comment]
That's why it's optional: https://github.com/versatica/mediasoup/blob/v3/package.json#L78

**Comment by ibc** [comment]
The problem is that such a lib does not indicate in package.json that it does not work in Windows:

https://github.com/hokein/clang-tools-prebuilt/blob/master/package.json

But I can't change that.

Run npm install with --production
