### ISSUE TITLE
Add access to os.loadAvg() on workers

### ISSUE THREAD

**Issue by dblencowe** [versatica/mediasoup#470]
## Feature Request

Allow access to os.loadAvg() on workers to allow easier computation of resource usage without having to parse the report coming out of the current getResourceUsage() function.

https://nodejs.org/api/os.html#os_os_loadavg

Happy to do a pull request for this myself if you think it'd be worth while.

**Comment by dblencowe** [comment]
Closing as looking through the code I realise that the workers don't run a node process

**Comment by ibc** [comment]
Load avg is OS global, not per process nor per CPU core.
Anyway, we won't include into mediasoup anything that can be just retrieved using Node.js APIs or 3rd party dependencies.
