### ISSUE TITLE
Request for patreon or other options for us to support this fantastic project

### ISSUE THREAD

**Issue by Starcounter-Jack** [versatica/mediasoup#475]
## Feature Request
Please open up a Patreon page or something such that you can keep this fantastic product going. My hope is that this piece of software is discovered by more developers. It is by far the best way to incorporate sound/video/screenshare into your node application.

**Comment by ibc** [comment]
We have this already: https://mediasoup.org/sponsor/

**Comment by Starcounter-Jack** [comment]
Sorry for the sloppy research on my part!

**Comment by Starcounter-Jack** [comment]
Private contribution made. Will continue as my economy allows. Will advice our company to become a recurring backer as soon as feasible. Thanks for the good work.
