### ISSUE TITLE
Permanent broadcasters..

### ISSUE THREAD

**Issue by fairbairn** [versatica/mediasoup#478]
## Feature Request

We're using the demo to set up a broadcasting room.  We've been working with it successfully for weeks now so I believe we understand it pretty well.

However, we have a problem regarding broadcaster persistence...

I've noticed when we're creating a PlainTransport broadcaster to stream into a room via RTP, that after setting up the transports and beginning the stream (RTP/UDP + RTCP/UDP over 2 different ports), everything works, unless there is a break in the RTP stream for just a second or so...

After that occurs, even if we stop and start under the 5 second hard-coded limit, all of the scores goes to 0, and the stream never recovers within the demo app.

It's as if the broadcast is unable to start back.

Traffic over the RTP and RTCP ports are both occurring, but the scores remain at 0, and so the video feed is frozen.

Is there a way in which we can mark a producer stream to have some tolerance in terms of timeout or the ability to remain inactive indefinitely - like we pause a live broadcast, but we want it in the room for when we unpause, and keep the ports the same?

I believe some kind of flag (inactive?) gets set on the stream after any slight interruption in the flow (we've even set dtx to true, and cycled it well under 5000ms and it still happens), and despite the fact that traffic resumes, it never flips back allowing the packets to stream through to the consumers.

**Comment by ibc** [comment]
Please, let's open a topic in the forum. This is not a bug but an usage problem/question.
