### ISSUE TITLE
lib/index.d.ts declares version as template value __MEDIASOUP_VERSION__

### ISSUE THREAD

**Issue by jonassmedegaard** [versatica/mediasoup#483]
Function `taskReplaceVersion()` in build routines in `npm-scripts.js` replaces `__MEDIASOUP_VERSION__` with actual version, but only for JavaScript files.

Seems the TypeScript file `lib/index.d.ts` should also declare actual version instead of the placeholder string.

**Comment by ibc** [comment]
No, that's is written when running `npm run typescript: build` as explained in the `doc/Building.md` file for developers.

**Comment by jonassmedegaard** [comment]
@ibc I suspect that you are mistaken - i.e. I think that indeed it is the _intention_ of `taskReplaceVersion()` to replace `__MEDIASOUP_VERSION__` also for typescript files but fails to do as intended (and documented).

Both my own local execution and the lib/* files released at tag 3.6.27 contains the placeholder string in file `lib/index.d.ts`.

**Comment by ibc** [comment]
Run "npm run typescript:build" after you change version in package.json as we do.

**Comment by jonassmedegaard** [comment]
If "we" are versatica then is https://github.com/versatica/mediasoup/blob/v3/lib/index.d.ts#L12 how the constant `version` is intended to be declared?

**Comment by ibc** [comment]
Fixed

**Comment by jonassmedegaard** [comment]
Thanks for (I guess) confirming that indeed this issue was real.

Not sure if you care, but your approach (quickly closing, telling me that I am doing it wrong, then when I insist just fix without revisiting that earlier judgement) leaves me with a feeling that you want only high-level user reports, and are not really interested in bugreports of this kind.

**Comment by jonassmedegaard** [comment]
I am not offended (I can easily spend my time elsewhere) - just letting you know the kind of impression it leaves when you take the time to second-guess how the bugreporter is wrong but don't take the time to retract such speculations when they turn out to be (at best) irrelevant.

**Comment by ibc** [comment]
Believe me, at the same time I was fixing this I was also closing 3 issues at work. I just couldn't comment more.
And also believe me, I'm not interested in high-level user reports.

Thanks for reporting and insisting.

**Comment by jonassmedegaard** [comment]
I believe you :-)
