### ISSUE TITLE
Firefox only error - Missing rid

### ISSUE THREAD

**Issue by xplatsolutions** [versatica/mediasoup#486]
### Your environment

- Operating system: macOS Catalina 10.15.7 (19H15)
- Node version: v14.9.0
- npm version: 6.14.8
- gcc/clang version: X
- mediasoup version: ^3.6.28
- mediasoup-client version: ^3.6.22
- Firefox version: 83.0 (64-bit)

### Issue description

Mediasoup error starting video producer.
It is failing in the below method.

```
this.videoProducer = await this.sendTransport.produce({
        track: videoTrack,
        encodings,
        codecOptions: {
          videoGoogleStartBitrate: 1000,
        },
        codec,
      })
```
The params passed are:
```
encodings:
[
  {
    "scaleResolutionDownBy": 4,
    "maxBitrate": 500000
  },
  {
    "scaleResolutionDownBy": 2,
    "maxBitrate": 1000000
  },
  {
    "scaleResolutionDownBy": 1,
    "maxBitrate": 5000000
  }
]

codecOptions: 
{
  videoGoogleStartBitrate: 1000,
}

codec: undefined
``` 

Chrome and Safari are working properly.

**Comment by ibc** [comment]
I don't understand. Did you already reproduce the issue in 3.6.22?

Also, the error happens in client side and not in mediasoup side, right? Please clarify it and paste the exact error.

**Comment by ofrzeta** [comment]
We experience the same error with a current version of the official demo in Firefox/Linux. The error message in the js console is:

`mediasoup-demo:ERROR:RoomClient enableWebcam() | failed:TypeError: Missing rid`

**Comment by ibc** [comment]
Yes, this was a bug due to an untested PR that I happily merged 2 days ago: https://github.com/versatica/mediasoup-client/pull/146

Fixing it.

**Comment by ibc** [comment]
Fixed in https://github.com/versatica/mediasoup-client/commit/4cc90b5cad859c5b6b1915ffaa1e4014d25eab1e and released in mediasoup-client 3.6.23.

**Comment by xplatsolutions** [comment]
Confirming `mediasoup-client 3.6.23` fixed the Firefox Missing rid issue. Amazing! Thank you :)

**Comment by andrewlin12** [comment]
My apologies - only tested it for my scenarios and not in general. Will try to be more diligent next time.

**Comment by ibc** [comment]
Don't worry. Thanks :)
