### ISSUE TITLE
WebRTC not connecting when listen IP is "0.0.0.0"

### ISSUE THREAD

**Issue by j1elo** [versatica/mediasoup#487]
### Your environment

- Operating system: Ubuntu 16/18 (Xenial, Bionic)
- Node version: 14.15.1
- npm version: 6.14.9
- gcc/clang version: 5.4.0
- mediasoup version: 3.6.28
- mediasoup-client version: 3.6.23

### Issue description

I'm not getting video from Chrome into mediasoup, during localhost development, when the `WebRtcTransportOptions.listenIps[0].ip` is `0.0.0.0`, but it works if the IP is `127.0.0.1`. Note that I want it to be `0.0.0.0` because I want mediasoup listening on both my loopback (127.0.0.1) and ethernet (192.168.1.x) network interfaces. This way I can quickly test from either my dev machine or different computers in the LAN.

DISCLAIMER: I am doing this although [docs seem to forbid it](https://mediasoup.org/documentation/v3/mediasoup/api/#WebRtcTransportOptions) ("*Do not use “0.0.0.0” into listenIps. Values in listenIps must be specific bindable IPs in the host.*"), because immediately after that they seem to allow it ("*If you use “0.0.0.0” or “::” into listenIps, then you need to also provide announcedIp in the corresponding entry in listenIps.*"). Thus, I'm setting:

* `ip = 0.0.0.0`.
* `announcedIp = <automatically set to either 127.0.0.1 or 192.168.1.x, as needed>`

However this setup fails for tests done in **localhost**:

### What happens when it works

With `listenIps: [{ ip: "127.0.0.1", announcedIp: "127.0.0.1" }]`

Wireshark capture: [mediasoup-127.0.0.1-ok.pcapng.gz](https://github.com/versatica/mediasoup/files/5679732/mediasoup-127.0.0.1-ok.pcapng.gz)

* An SDP is sent to Chrome, containing an ICE candidate with mediasoup's `WebRtcTransport.iceCandidates`, which contains the announced IP `127.0.0.1` and an UDP port.
* Chrome sends a STUN Binding request from the machine's LAN address **192.168.1.x**, to the mediasoup announced address 127.0.0.1 and given port.
* mediasoup responds with a STUN Binding Success, sending it **from 127.0.0.1**.
* mediasoup sends a DTLS Client Hello **from 127.0.0.1**.
* Chrome sends a DTLS Server Hello.
* From here, communications follow up as expected (ending up with transmission of UDP packets from Chrome to mediasoup).

### What happens when it fails (mediasoup-0.0.0.0-fail.pcapng)

With `listenIps: [{ ip: "0.0.0.0", announcedIp: "127.0.0.1" }]`

Wireshark capture: [mediasoup-0.0.0.0-fail.pcapng.gz](https://github.com/versatica/mediasoup/files/5679733/mediasoup-0.0.0.0-fail.pcapng.gz)

* An SDP is sent to Chrome, containing an ICE candidate with mediasoup's `WebRtcTransport.iceCandidates`, which contains the announced IP `127.0.0.1` and an UDP port.
* Chrome sends a STUN Binding request from the machine's LAN address 192.168.1.x, to the mediasoup announced address 127.0.0.1 and given port.
* mediasoup responds with a STUN Binding Success, sending it **from 192.168.1.x**.
* mediasoup sends a DTLS Client Hello from **192.168.1.x**.
* Chrome never sends a DTLS Server Hello.
* Comms are not established and video never arrives to mediasoup.

### What might be happening

My understanding is that Chrome probably is ignoring the STUN Binding Success, and the DTLS Client Hello UDP packages whose source IP doesn't match with the expected IP that was obtained from the initial ICE candidate. I.e., Chrome expects a DTLS Client Hello from 127.0.0.1, but it gets one from 192.168.1.x so it is discarded.

As for the question "*Why is Chrome sending data from 192.168.1.x instead of 127.0.0.1?*" I think the answer is that Chrome simply prefers to use the LAN address before using the loopback interface. However it still expects the other peer (mediasoup) to use its announced IP as the source of its own packets.

### Proposed solution

With the data I have in my hands, the solution seems to be that mediasoup should send its STUN and DTLS packets not from the same interface they were received, but from the interface that is currently configured as `announcedIp`. I.e. don't mimic the *UDP Destination* field of incoming Binding Requests, because that address might not be valid for the intended purpose.

Or maybe, if you think that's confusing / has some other negative implications, maybe go for the simpler definite ban of using `0.0.0.0` from mediasoup (in the docs but also a runtime check will probably help users avoid misconfiguration issues in the future).

**Comment by ibc** [comment]
> With the data I have in my hands, the solution seems to be that mediasoup should send its STUN and DTLS packets not from the same interface they were received, but from the interface that is currently configured as `announcedIp`. I.e. don't mimic the _UDP Destination_ field of incoming Binding Requests, because that address might not be valid for the intended purpose.

This is not the purpose of the `announcedIp`. It is supposed to be a public IP (or even a **hostname**) which may NOT exist in the host, so its not bindable at all. So this is typically needed when running mediasoup in a server with private IP and an external public IP mapped to it (AWS, Google Cloud, etc).

> - An SDP is sent to Chrome, containing an ICE candidate with mediasoup's WebRtcTransport.iceCandidates, which contains the announced IP 127.0.0.1 and an UDP port.
>- Chrome sends a STUN Binding request from the machine's LAN address 192.168.1.x, to the mediasoup announced address 127.0.0.1 and given port.

This is perfectly fine. You told mediasoup to bind in 0.0.0.0 so, based on OS routing table, the kernel will choose the appropriate interface to send packets.

> - mediasoup responds with a STUN Binding Success, sending it from 192.168.1.x.
> - mediasoup sends a DTLS Client Hello from 192.168.1.x.
> - Chrome never sends a DTLS Server Hello.

So this is up to Chrome/libwebrtc. It may not like the fact that the remote SDP announces UDP 127.0.0.1 as remote address and then it receives the ICE response from 129.168.1.x.

**NOTE:** I'm even surprised that it works for you in the first scenario. Chrome (at least in the past) did **NOT** accept UDP 127.0.0.1 as remote address.

BTW, no magic here, in your scenario you must bind into a specific IP.

**Comment by j1elo** [comment]
> > With the data I have in my hands, the solution seems to be that mediasoup should send its STUN and DTLS packets not from the same interface they were received, but from the interface that is currently configured as `announcedIp`. I.e. don't mimic the _UDP Destination_ field of incoming Binding Requests, because that address might not be valid for the intended purpose.
> 
> This is not the purpose of the `announcedIp`. It is supposed to be a public IP (or even a **hostname**) which may NOT exist in the host, so its not bindable at all. So this is typically needed when running mediasoup in a server with private IP and an external public IP mapped to it (AWS, Google Cloud, etc).

Oh yes you're right, I was being shortsighted there with this use case. Of course, the announced IP should be set to the IP where mediasoup *can be reached*, not necessarily a physical network address of the machine *where it is running*. So my proposed solution would not work for the general case.

> > * An SDP is sent to Chrome, containing an ICE candidate with mediasoup's WebRtcTransport.iceCandidates, which contains the announced IP 127.0.0.1 and an UDP port.
> > * Chrome sends a STUN Binding request from the machine's LAN address 192.168.1.x, to the mediasoup announced address 127.0.0.1 and given port.
> 
> This is perfectly fine. You told mediasoup to bind in 0.0.0.0 so, based on OS routing table, the kernel will choose the appropriate interface to send packets.

Yes, this is part of the expected behavior.

> > * mediasoup responds with a STUN Binding Success, sending it from 192.168.1.x.
> > * mediasoup sends a DTLS Client Hello from 192.168.1.x.
> > * Chrome never sends a DTLS Server Hello.

*This*, however, is exactly the 3 points that are part of the unexpected behavior.

Is mediasoup **not** explicitly choosing to send packets *from* the address 192.168.1.x? In other words: is the Source IP address of these packets a choice made by mediasoup, or by the kernel routing?

> So this is up to Chrome/libwebrtc. It may not like the fact that the remote SDP announces UDP 127.0.0.1 as remote address and then it receives the ICE response from 129.168.1.x.

I'd understand if this is after all only actionable at the level of Chrome. Although in my mind it makes some sense that they expect packets coming from the same IP address that was announced.

> **NOTE:** I'm even surprised that it works for you in the first scenario. Chrome (at least in the past) did **NOT** accept UDP 127.0.0.1 as remote address.

Really? Sounds surprising, but in any case I guess they must have reverted that decision at some point... it doesn't seem too logical not allowing Chrome to establish a standard P2P connection between instances in the same machine, if the machine is not connected to any router.

> BTW, no magic here, in your scenario you must bind into a specific IP.

Yeah that's the simplest solution, although I wanted to be able to use 0.0.0.0... and also I thought it might be worth reporting as maybe uncovering a subtle bug of some sort in mediasoup (just in case... to see your thoughts)

**Comment by ibc** [comment]
> Is mediasoup **not** explicitly choosing to send packets _from_ the address 192.168.1.x? In other words: is the Source IP address of these packets a choice made by mediasoup, or by the kernel routing?

mediasoup passes 0.0.0.0 to live which does a syscall with it. It's kernel routing.

BTW don't forget that you can bind into many IPs.

**Comment by j1elo** [comment]
Avoiding 0.0.0.0 altogether seems to be the best and safest option. Thanks for the insights
