### ISSUE TITLE
web client can not receive video when comsume prefer spatial layer 2 while produce setMaxSpatialLayer 1 or 0

### ISSUE THREAD

**Issue by bianxg** [versatica/mediasoup#488]
## Bug Report

web client can not receive video when comsume prefer spatial layer 2 while produce setMaxSpatialLayer 1 or 0

### Your environment

- Operating system: ubuntu1~16.04.12
- Node version: v13.14.0
- npm version:
- gcc/clang version: 
- mediasoup version : 3.6.24
- mediasoup-client version: 3.6.21

### Issue description
1 web client can not receive video when comsume prefer spatial layer 2 while produce setMaxSpatialLayer 1 or 0
2 the mediasoup log show: 
mediasoup:Channel [pid:2432] (trace) RTC::SimulcastConsumer::UpdateTargetLayers() +0ms
mediasoup:Channel [pid:2432] RTC::SimulcastConsumer::UpdateTargetLayers() | target layers changed [spatial:-1, temporal:-1, consumerId:6edcf06e-01a4-4837-b3a2-3a601903c81c] +0ms 

The normal log should be :
mediasoup:Channel [pid:2432] (trace) RTC::SimulcastConsumer::UpdateTargetLayers() +1ms
mediasoup:Channel [pid:2432] RTC::SimulcastConsumer::UpdateTargetLayers() | using spatial layer 1 as RTP timestamp reference +0ms
mediasoup:Channel [pid:2432] RTC::SimulcastConsumer::UpdateTargetLayers() | target layers changed [spatial:1, temporal:0, consumerId:681d18b2-47c3-4e64-85c9-31e4afe47d70] +0ms 

3 the video will not be recovered forever when this happen.

The reasons may be that the condition is not satisfied:
"RTP streams of our TS reference spatial layer and the given  spatial layer, have Sender Report" on 
inline bool SimulcastConsumer::CanSwitchToSpatialLayer(int16_t spatialLayer) const

**Comment by ibc** [comment]
Please use the mediasoup Discourse forum for questions. This is not a well defined issue description.
