### ISSUE TITLE
source is missing referenced license file for libwebrtc

### ISSUE THREAD

**Issue by jonassmedegaard** [versatica/mediasoup#495]
Files below `worker/deps/libwebrtc/libwebrtc` commonly contain this:
```
 *  Use of this source code is governed by a BSD-style license
 *  that can be found in the LICENSE file in the root of the source
 *  tree. An additional intellectual property rights grant can be found
 *  in the file PATENTS.  All contributing project authors may
 *  be found in the AUTHORS file in the root of the source tree.
```
but the referenced files `LICENSE` and `PATENTS` are missing.

File `worker/deps/libwebrtc/README.md` does not explicitly mention the origin of the code (that would be nice), but mentions a git hash, so I guess this is the files that needs to be included: https://webrtc.googlesource.com/src/+/2bac7da1349c75e5cf89612ab9619a1920d5d974/LICENSE
https://webrtc.googlesource.com/src/+/2bac7da1349c75e5cf89612ab9619a1920d5d974/PATENTS

**Comment by ibc** [comment]
Thanks, done.
