### ISSUE TITLE
images contain embedded non-free color profiles

### ISSUE THREAD

**Issue by jonassmedegaard** [versatica/mediasoup#496]
The files `art/mediasoup-banner.png`and `art/mediasoup-v3.png` contains embedded ICC color calibration profile which is `Copyright Apple Inc.` and contain no free license.

Those image files most likely have no real need for those color profiles and can simply have them stripped.

In case you (like many others where I reported similar issues) are curious how to check for this, the command-line tool `exiftool` part of perl module `Image::Exiftool` does an excellent job of digging out metadata like that.

**Comment by ibc** [comment]
I have no idea what "ICC color calibration" is. I did those images with some open source vector images application. I'd appreciate if you explain how to use those command line tools you mean (zero experience with Perl), or even better if you could create a PR with the "fixed" images.

**Comment by jonassmedegaard** [comment]
A color profile is a way to define "white means this, black means this, rgb color code xxyyzz means this" tied to some "color space" - more info at https://en.wikipedia.org/wiki/ICC_profile

You most likely want to use same color space as is the default for web - sRGB - and then you don't need to embed any ICC, because web standards have defined sRGB to be the default color space when undefined for an image.

That's the reason I suggest to strip the profile data: They are explicitly stating what would be implied anyway - and the way they are stated is copyright protected.

Some free tools may happily inject non-free code into your works - there are many definitions of "Free" some of which excludes graphics code or font code or audio code or running-on-a-different-chip code (a.k.a. firmware).

You need not grok perl to use exiftool - just as you need not grok C++ and Rust to use Firefox.  I mentioned the language only to aid in locating the tool.

On a Debian-based system, you can inspect metadata of PNG files like this:
```
sudo apt install libimage-exiftool-perl
exiftool art/mediasoup-banner.png
```
Among the many metadata fields extracted, notice `Profile Copyright` which states that Apple claim copyright for that piece of code (without including a license for free use of the code), which makes it non-free.

One way to strip the ICC color profile is with exiftool itself:
```
exiftool -icc_profile:all= art/mediasoup-banner.png
```

...but if you don't have exiftool on your system then there are many other options - among more popular ones are `pngcrush` and `optipng`.

Sorry, I won't push code changes to Github due to (possibly unfounded) concerns over their terms of service - more info at https://lwn.net/Articles/716372/

I can provide code changes elsewhere for you to grab, but I guess it is then easier for you to do those changes yourself.

**Comment by ibc** [comment]
Thanks, done.
