### ISSUE TITLE
README file missing for worker/src/Utils/String.cpp clarifying which BSD license apply

### ISSUE THREAD

**Issue by jonassmedegaard** [versatica/mediasoup#497]
The file `worker/src/Utils/String.cpp` contain this:
```
 * This software may be distributed under the terms of the BSD license.
 * See README for more details.
```
but the referenced file `README` is missing.

I guess this is the file that needs to be included: http://web.mit.edu/freebsd/head/contrib/wpa/README

**Comment by ibc** [comment]
Thanks, done.
