### ISSUE TITLE
libuv uv_loop_t initialization

### ISSUE THREAD

**Issue by woshiniuren** [versatica/mediasoup#505]
## Bug Report

**IMPORTANT:** We primarily use GitHub as an issue tracker. Just open an issue here if you have encountered a bug in mediasoup.

If you have questions or doubts about mediasoup or need support, please use the mediasoup Discourse Group instead:

https://mediasoup.discourse.group

If you got a crash in mediasoup, please try to provide a core dump into the issue report:

https://mediasoup.org/support/#crashes-in-mediasoup-get-a-core-dump

### Your environment

- Operating system: cenos 7
- Node version:
- npm version:
- gcc/clang version: 9.0
- mediasoup version:3.X.X
- mediasoup-client version:

### Issue description
Hey guys , in  DepLibUV::ClassInit() function ,why not use "DepLibUV::loop = uv_default_loop()" instead of  "DepLibUV::loop = new uv_loop_t;  int err = uv_loop_init(DepLibUV::loop);" ?

**Comment by ibc** [comment]
Please use the mediasoup Discourse Group for questions as the issue template clearly said.
