### ISSUE TITLE
Node.js createWorker randomly fails

### ISSUE THREAD

**Issue by dimoochka** [versatica/mediasoup#513]
### Your environment

- Operating system: Ubuntu 20.04 LTS, Kernel 5.4.0-54-generic
- Node version: v12.16.3
- npm version: 6.14.8
- gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
- mediasoup version: 3.6.30

### Issue description

As stated in the title, occasionally the createWorker function returns a falsy value (not sure if it's null or false). I had to code around it (see below for my code structure, it's pretty simple but maybe I'm missing something). It only happens occasionally so I have some difficulty reproducing it. Not a big deal, subsequent calls to createWorker seem to work fine.

PS. mediasoup is amazing. Thanks for a great product!!!

My code:
```
const mediasoup = require('mediasoup');
async function new_worker() {
	let worker = await mediasoup.createWorker({rtcMinPort: config.minport, rtcMaxPort: config.maxport});
	worker.on('died', () => { ... });
	return worker;
}
var worker_counter=0;
async function new_router() {
	var worker=false;
	while (!worker) {
		if (worker_counter<config.max_workers) {
			workers[worker_counter]=await new_worker();
		}
		worker=workers[worker_counter%config.max_workers];
		if (!worker) {
			console.log("WORKER CREATION FAILURE! Trying again ...");
			await sleep(1000);
		}
	}
...
}
```

**Comment by ibc** [comment]
Please use the public forum for usage questions or usage issues.
