### ISSUE TITLE
 No such file or directory in /node_modules/mediasoup/worker/out/Makefile'  make: *** [Makefile:24: default] Error 1 make: Leaving directory 

### ISSUE THREAD

**Issue by venkatuday** [versatica/mediasoup#516]
i am trying to install mediasoup in ubuntu 20.04 and i have all the requirements listed in mediasoup official documentation
node version >= v10.0.0
python version 2 and 3 also there
make
gcc version 9.3

i tried "sudo npm install", "sudo npm install mediasoup@3" and also "sudo python=python2 npm install" ,"sudo python=python3 npm install"

the error is 

Entering directory '/home/user_name/project/meridian-media-layer-api/node_modules/mediasoup/worker'
python3 ./scripts/configure.py -R mediasoup-worker
./deps/gyp/pylib/gyp/input.py:1186: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if the_dict_key is 'variables' and variable_name in the_dict:
['-R', 'mediasoup-worker', '/home/user_name/project/meridian-media-layer-api/node_modules/mediasoup/worker/mediasoup-worker.gyp', '-I', '/home/user_name/project/meridian-media-layer-api/node_modules/mediasoup/worker/common.gypi', '--depth=.', '-f', 'make', '-Goutput_dir=/home/user_name/project/meridian-media-layer-api/node_modules/mediasoup/worker/out', '--generator-output', '/home/user_name/project/meridian-media-layer-api/node_modules/mediasoup/worker/out', '-Dgcc_version=93', '-Dclang=0', '-Dhost_arch=x64', '-Dtarget_arch=x64', '-Dopenssl_fips=', '-Dmediasoup_asan=false', '-Dnode_byteorder=little']
Traceback (most recent call last):
  File "./scripts/configure.py", line 111, in <module>
    run_gyp(gyp_args)
  File "./scripts/configure.py", line 49, in run_gyp
    rc = gyp.main(args)
  File "./deps/gyp/pylib/gyp/__init__.py", line 545, in main
    return gyp_main(args)
  File "./deps/gyp/pylib/gyp/__init__.py", line 530, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "./deps/gyp/pylib/gyp/generator/make.py", line 2147, in GenerateOutput
    root_makefile = open(makefile_path, 'w')

i also tried sudo apt-get update

nothing is working our for me.....not able to find out the exact probelm

**Comment by ibc** [comment]
Ask in the forum
