### ISSUE TITLE
🦀 Similarities and differences between Rust port and original TypeScript version

### ISSUE THREAD

**Issue by nazar-pc** [versatica/mediasoup#519]
For comprehensive answer refer to https://docs.rs/mediasoup

TL;DR:
* similarities:
  * also a library, identically low level
  * uses the same unmodified C++ worker codebase
  * similar structure and API to TypeScript
* differences:
  * API leverages idiomatic Rust concepts around ownership, borrowing and concurrency
  * workers run in threads instead of processes
  * currently Rust version uses different versioning than TypeScript
  * Linux and macOS are supported, Windows is WIP

**Comment by ibc** [comment]
So the idea behind this issue is to document future/temporal differences between the TypeScript and Rust layers, right?

**Comment by nazar-pc** [comment]
Yes, I will update it as things change.

**Comment by ibc** [comment]
Should we keep this issue open? I don't see much value on it.

**Comment by nazar-pc** [comment]
Let's close this already :slightly_smiling_face:
