### ISSUE TITLE
Allow data producer to send data to the specified data consumer.

### ISSUE THREAD

**Issue by jiyeyuran** [versatica/mediasoup#542]
## Feature Request
For now, DataProducer only broadcasts data to all DataConsumers. It would be helpful to add a method like `sendTo(dataConsumerId, data)` in DataProducer to send data to the specified data consumer.

**Comment by ibc** [comment]
That's not how DataProducer/DatraConsumer are designed for.

You can create a separate DataProducer and just create an associated DataConsumer. Or you can have a single DataProducer between client and server, and have a single DataConsumer in server side (on top of a DirectTransport), receive messages in your server Node app from client, then "dataproduce" them to desired devices.

**Comment by jiyeyuran** [comment]
Do you mean to create a DataProducer in server for each device?

**Comment by ibc** [comment]
Yep. But please, let's move the discussion to the forum.
