### ISSUE TITLE
NACK Messages

### ISSUE THREAD

**Issue by mainisameer** [versatica/mediasoup#549]
we are getting the following messages in our log file .
I am also attaching a link to the website which seems to describe a race condition in handling NACK messages. 
2021-04-26T17:04:11: 2021-04-26T17:04:11.340Z mediasoup:WARN:Channel [pid:38456] RTC::NackGenerator::GetNackBatch() | sequence number removed from the NACK list due to max retries [filter:time, seq:55422]
And this one goes on for a while , found another article which was talking about there being an issue with NACK handling
https://blog.csdn.net/The_Old_man_and_sea/article/details/114795247

**Comment by jmillan** [comment]
That log doesn't represent a bug in mediasoup.

If you find an issue in NACK handling please report it properly.

**Comment by jmillan** [comment]
Reopening since I've just seen this feature request was requested from the forum.

**Comment by jmillan** [comment]
Adding additional information from the forum:

Mediasoup has a retransmission problem in the case of packet disorder. Mediasoup detects whether packet drops are sequentially spaced according to the packet serial number, so if there is a packet disorder, mediasoup sends THE NACK immediately, but it may actually be very small between the packets to reach the actual interval, just wait a little while, you can form a continuous package, avoid sending NACK.

In this regard, there is a WebRTC-SendNackDelayMs parameter setting in the webrtc that sets the delay time that THE ACK sends

**Comment by penguinol** [comment]
> 我们在日志文件中收到以下消息。
> 我还在网站上附加了一个链接，该链接似乎描述了在处理NACK消息时的比赛条件。
> 2021-04-26T17：04：11：2021-04-26T17：04：11.340Z mediasoup：WARN：Channel [pid：38456] RTC :: NackGenerator :: GetNackBatch（）| 由于最大重试次数而从NACK列表中删除了序列号[filter：time，seq：55422]
> 并且持续了一段时间，找到了另一篇关于NACK处理
> [https：//blog.csdn的问题.net / The_Old_man_and_sea / article / details / 114795247](https://blog.csdn.net/The_Old_man_and_sea/article/details/114795247)

This log means that we've tried to send retransmission requests for several times. but have not received retransmitted packets.
Uselly it's caused by network isuss.

**Comment by penguinol** [comment]
> 从论坛添加其他信息：
> 
> 在数据包混乱的情况下，Mediasoup存在重传问题。Mediasoup会检测是否根据数据包序列号按顺序排列了数据包丢包，因此，如果有数据包混乱，mediasoup会立即发送THE NACK，但实际上在数据包之间达到实际间隔可能很小，请稍等片刻，您可以形成一个连续的包，避免发送NACK。
> 
> 在这方面，webrtc中有一个WebRTC-SendNackDelayMs参数设置，用于设置ACK发送的延迟时间

#511 is the same problem.
I've made a patch(see https://github.com/penguinol/mediasoup/commit/7ad0c2f6947f65e4769c377038d0822d07e40197) which add a delay before sending nack.
But i'm not sure whether the SendNackDelayMs should be a gobal property or a property for every producer.

**Comment by mainisameer** [comment]
@penguinol  Thank you and want to just confirm that is your patch in production and you are not seeing any issues with it. Thank you.

**Comment by ibc** [comment]
> @penguinol Thank you and want to just confirm that is your patch in production and you are not seeing any issues with it. Thank you.

May I know which patch do you mind? Can we have a PR?

**Comment by mainisameer** [comment]
I am refering to the patch he has made
"I've made a patch(see penguinol@7ad0c2f) which add a delay before sending nack.". Looks like he had also raised the same issue no 511.
Appreciate your correspondance.

**Comment by penguinol** [comment]
> I am refering to the patch he has made
> "I've made a patch(see [penguinol/mediasoup@7ad0c2f](https://github.com/penguinol/mediasoup/commit/7ad0c2f)) which add a delay before sending nack.". Looks like he had also raised the same issue no 511.
> Appreciate your correspondance.

The log you paste here does not mean there is a bug, it's a normal behaviour.
It usually means there is unrepairable packet loss due to network or other reasons.
There is max retry times for nack, if the packet is not received after the max retransmission request, you will see the log.

The log has nothing to do with the issuse described in the blog and my patch will not resolve your "issuse".
You need to learn more about rtcp retransmission mechanism.

**Comment by vv-yakovlev** [comment]
@penguinol can you make a PR. I've faced with immediatly nack sending at packet reordering too
@ibc, please pay attention at this issue

**Comment by ibc** [comment]
> @ibc, please pay attention at this issue

I promise that I ignore this kind of direct mentions.

**Comment by penguinol** [comment]
> @penguinol can you make a PR. I've faced with immediatly nack sending at packet reordering too
> @ibc, please pay attention at this issue

OK, i will make a pr this week.
A little busy these days.

**Comment by Randeerwithanage** [comment]
**That log does not indicate a mediasoup bug.**

_If you discover a problem with the way NACK is handled, please report it correctly._
