### ISSUE TITLE
Consumer MID question?

### ISSUE THREAD

**Issue by WangHoi** [versatica/mediasoup#551]
Regarding RFC5888  9.1 Mid Value in Answers

The "mid" attribute is an identifier for a particular media stream.
Therefore, the "mid" value in the offer **MUST be the same** as the "mid"
value in the answer. 

But I found inside 'transport.ts', MID for consumer is generated by a per-transport counter.
And i can't force a MID in ConsumerOptions.

This results interop problem with Linphone.
btw, linphone provides offer with MID 'as' for audio track.

**Comment by ibc** [comment]
Use the support forum for questions.
