### ISSUE TITLE
Closing Cam Freezes Browser - Galaxy S21 / Chrome 90.0.4430.91

### ISSUE THREAD

**Issue by NYCypher007** [versatica/mediasoup#553]
## Bug Report
Browser freezes on cam close.  For Galaxy S21 and S21Ultra on Chrome. 
Tested here: https://v3demo.mediasoup.org/

Application Version: Chrome 90.0.4430.91
Operating System: Android 11; SM-G998U Build/RP1a.200720.012

It does not freeze on 
Chrome Beta: 91.0.4472.35
Chrome Canary: 92.0.4500.2

**Comment by ibc** [comment]
mediasoup and mediasoup-client cannot make Chrome freeze. If that happens then it's a bug in Chrome.
