### ISSUE TITLE
Implements getStats()

### ISSUE THREAD

**Issue by jmillan** [versatica/mediasoup#56]
[ Identifiers for WebRTC's Statistics API](https://www.w3.org/TR/webrtc-stats/#dom-rtcmediastreamstats-trackids)

Being these two elements the ones with most important for now:

-  [RTCInboundRTPStreamStats](https://www.w3.org/TR/webrtc-stats/#dom-rtcinboundrtpstreamstats)
- [RTCOutboundRTPStreamStats](https://www.w3.org/TR/webrtc-stats/#dom-rtcoutboundrtpstreamstats)

**Comment by jmillan** [comment]
Accomplished in #150. Yet to be documented.

**Comment by vr000m** [comment]
@karhikbr82 could you PTAL

**Comment by jmillan** [comment]
This is not a getStats implementation as defined in WebRTC nor ORTC. All the information related to the WebRTC objects is already in JavaScript.

Regarding to this merge:

`outbound-rtp` and `inbound-rtp` are almost as in the spec . `transport` too, but it is missing the ICE candidates (we are setting there the selected socket tuples).

In order to make a full `getStats` API  as in the spec there's work to be done in JavaScript side, where all the rest of information is already given.

**Comment by ibc** [comment]
This is done. good work @jmillan
