### ISSUE TITLE
InvalidStateError: AwaitQueue closed

### ISSUE THREAD

**Issue by prayaslashkari** [versatica/mediasoup#561]
## Bug Report

![image](https://user-images.githubusercontent.com/25193916/118780113-592c6e80-b8a9-11eb-8315-fe9088c8a34d.png)

### Your environment

- Operating system: macOS Big Sur
- Node version: 14.15.3
- npm version: 6.14.9
- gcc/clang version: Apple clang version 12.0.5 (clang-1205.0.22.9)
- mediasoup version: ^3.5.14
- mediasoup-client version: ^3.6.5

**Comment by prayaslashkari** [comment]
Any idea about this? I am using Mediasoup with React Native.

Stack Trace

![image](https://user-images.githubusercontent.com/25193916/118780813-0e5f2680-b8aa-11eb-94fb-8bf17af5a1f3.png)

**Comment by ibc** [comment]
Not a bug. Please use the mailing list for usage questions or problems.
