### ISSUE TITLE
Call is freezing on demo.mediasoup.org

### ISSUE THREAD

**Issue by qasim483** [versatica/mediasoup#563]
## Bug Report

I am using mediasoup on my server. But my call gets frozen after 20 or 30 seconds. I have tested it on https://v3demo.mediasoup.org/ and the same thing is happening there as well.
I have tried with different internet connections. I have tried it on different devices. Sometimes it works fine. For some people its working fine. 

https://www.youtube.com/watch?v=YsE4-e_7nsc

Here is the video explaining about this error in more details:

**Comment by ibc** [comment]
Please use the mediasoup forum for usage questions/problems.

**Comment by qasim483** [comment]
Posted it there. no feedback

https://mediasoup.discourse.group/t/call-is-freezing-on-demo-mediasoup-org/2807

**Comment by ibc** [comment]
I'm sorry, that's not a excuse to report a mediasoup bug (it's not that).

**Comment by qasim483** [comment]
sorry, but it looks like some bug to me. thats why I posted it here too. Can you please check my video?

**Comment by ibc** [comment]
Trust me, I'm not gonna check any video.

**Comment by qasim483** [comment]
Trust me, its not normal. Random people in my contact are facing this. Occasionally frozen of calls.
It could be my ISP. But Zoom and skype are always working fine. So there is something missed in mediasoup. 
Consider having hundreds of calls and lot of people having this issue. And there is no reason why it's happening. Then we are dead in this business.

**Comment by ibc** [comment]
This is my last comment in this issue (I'll lock it after it). Feel free to continue in the forum, not here.

No. We don't accept bug reports this way. Period. If mediasoup failed at 20-30 seconds many more people would have realized of it, including companies using it in production.

Said that: "the demo fails for me" is a perfect topic to be ignored by us, sorry, no time for this. mediasoup provides you with LOT of debugging mechanisms documented in the website. Probably you are running the demo project and that's all. Sorry, if you want to report an issue do it properly.
