### ISSUE TITLE
Mediasoup takes forever to install

### ISSUE THREAD

**Issue by piyushgarg-dev** [versatica/mediasoup#564]
## Bug

Mediasoup server library takes forever to install. I have used yarn as well as npm. I am facing this issue with the latest release. If I try to install version 3.5.3, it installs successfully. kindly please see to it.

**Comment by ibc** [comment]
So you have deleted the full issue template because, obviously, knowing your OS and other software versions is not useful here.

Closing the issue. Please ask in the mediasoup public forum.

**Comment by aetheon** [comment]
> kindly please see to it.

@piyushgarg195 open source doesn’t work like this. Please contribute and avoid demanding free work from other people.
