### ISSUE TITLE
Screen at 90 ° or 180 ° as soon as you look at a Safari iPhone 8 / iOS 14.6 user on mediasoup-client

### ISSUE THREAD

**Issue by Madriix** [versatica/mediasoup#577]
I tested https://v3demo.mediasoup.org/?roomId=[name] on both a Safari iPhone 8 iOS 14.6 and a Windows 7 Firefox, and I turned on the "4 webcams" and on my computer I see the user of the iphone at 90 °.

How to solve this problem without going through the settings of the iphone (because the majority of users will not)?

This problem also exists on https://github.com/meething/meething-mediasoup and also on https://github.com/meething/meething (without P2P, P2P must be activated and the 90 ° problem or 180 ° will not exist

This problem also does not occur on https://github.com/dmotz/trystero (this is p2p / torrent)

Could the problem come from the mediasoup server or not?

**Comment by nazar-pc** [comment]
This is not a mediasoup fault, this is Firefox not supporting RTP header that describes video rotation yet.
Please report to Firefox and post a link here.

**Comment by Madriix** [comment]
Indeed it comes from Firefox. I tested on Chrome, I can see the iphone user in the right direction

**Comment by ibc** [comment]
https://mediasoup.org/faq/#when-consuming-a-video-in-firefox-it-does-not-properly-rotate

**Comment by Madriix** [comment]
@ibc thanks

https://github.com/meething/meething-mediasoup/blob/master/client/lib/room.js#L59 in line 59 I added this:
```

  routerRtpCapabilities.headerExtensions = routerRtpCapabilities.headerExtensions.
    filter((ext) => ext.uri !== 'urn:3gpp:video-orientation');
```


it works well now

It's not dangerous if I don't add if() : if (supportsVideoOrientationHeaderExtension) ?

**Comment by ibc** [comment]
Questions in the forum, please.
