### ISSUE TITLE
can not install windows

### ISSUE THREAD

**Issue by SysVR** [versatica/mediasoup#582]
i installed windows 10 21H1 on
vs2017 community (C++ Desktop)
Python 2.7
node-v14.17.0-win-x64

environment PATH added C:\Program Files (x86)\MSBuild\14.0\Bin AND C:\node-v14.17.0-win-x64
GYP_MSVS_VERSION Value 2017

cmd admin
C:\node-v14.17.0-win-x64>npm install mediasoup@3 --save

> mediasoup@3.7.11 postinstall C:\node-v14.17.0-win-x64\node_modules\mediasoup
> node npm-scripts.js postinstall

npm-scripts.js [INFO] running task "postinstall"
npm-scripts.js [INFO] executing command: python ./worker/scripts/configure.py --format=msvs -R mediasoup-worker
Python [            ......] / postinstall: info lifecycle mediasoup@3.7.11~postinstall: Failed to exec postinstall scripnpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mediasoup@3.7.11 postinstall: `node npm-scripts.js postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mediasoup@3.7.11 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Full log.
[2021-06-06T03_30_57_575Z-debug.log](https://pastebin.pl/view/aac6b96f)

**Comment by ibc** [comment]
This is already reported. Check existing issues. And BTW this is gonna be fixed once we move from GYP to CMake (there is also an issue about it), so closing.

**Comment by SysVR** [comment]
Thank you very much.
I wish I could build WindowsBinary on Linux: ......
(Build with WSL)

**Comment by SysVR** [comment]
@ibc 
windows 10 21H1 on
vs2017 community (C++ Desktop)
Node.js 14.17.0 (ia32)
python-3.9.5-amd64

environment:
MSBuild Path 
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin
GYP_MSVS_VERSION Value 2017
---------------------------------------------------------------------------------
Select and pause the console when mediasoup-worker.sln is generated.
Then open mediasoup-worker.sln with another software, "delete blank line" and save it.
Release the selection and continue.
Compilation completed.

How to speed up the build.
-m[:number]
Specifies the maximum number of concurrent processes to be used during a build. If this switch is not included, the default value is 1. If you include this switch without specifying a value, MSBuild will use up to the number of processors on your computer.

FullLog

https://pastebin.pl/view/5e32dcd2
