### ISSUE TITLE
Mediasoup installation failed in EC2 instance(Ubuntu 20.04)

### ISSUE THREAD

**Issue by keshavsuman** [versatica/mediasoup#583]
**I am getting this issue while installing mediasoup in my ubuntu 20.04 at ec2 instance**

> mediasoup@3.7.12 postinstall /usr/local/lib/node_modules/mediasoup
> node npm-scripts.js postinstall

npm-scripts.js [INFO] running task "postinstall"
npm-scripts.js [INFO] executing command: make -C worker
make: Entering directory '/usr/local/lib/node_modules/mediasoup/worker'
python3 ./scripts/configure.py -R mediasoup-worker
./deps/gyp/pylib/gyp/input.py:1186: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if the_dict_key is 'variables' and variable_name in the_dict:
['-R', 'mediasoup-worker', '/usr/local/lib/node_modules/mediasoup/worker/mediasoup-worker.gyp', '-I', '/usr/local/lib/node_modules/mediasoup/worker/common.gypi', '--depth=.', '-f', 'make', '-Goutput_dir=/usr/local/lib/node_modules/mediasoup/worker/out', '--generator-output', '/usr/local/lib/node_modules/mediasoup/worker/out', '-Dgcc_version=93', '-Dclang=0', '-Dhost_arch=x64', '-Dtarget_arch=x64', '-Dopenssl_fips=', '-Dmediasoup_asan=false', '-Dnode_byteorder=little']
Traceback (most recent call last):
  File "./scripts/configure.py", line 113, in <module>
    run_gyp(gyp_args)
  File "./scripts/configure.py", line 51, in run_gyp
    rc = gyp.main(args)
  File "./deps/gyp/pylib/gyp/__init__.py", line 545, in main
    return gyp_main(args)
  File "./deps/gyp/pylib/gyp/__init__.py", line 530, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "./deps/gyp/pylib/gyp/generator/make.py", line 2147, in GenerateOutput
    root_makefile = open(makefile_path, 'w')
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/node_modules/mediasoup/worker/out/Makefile'
make: *** [Makefile:24: default] Error 1
make: Leaving directory '/usr/local/lib/node_modules/mediasoup/worker'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mediasoup@3.7.12 postinstall: `node npm-scripts.js postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mediasoup@3.7.12 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-07T12_42_20_727Z-debug.log

**Comment by keshavsuman** [comment]
Hey, please tell me what to do how can i resolve thsi isssue . i am not getting any answers over google

**Comment by ibc** [comment]
Ask in the forum please
