### ISSUE TITLE
Crash when sharing screen from Chrome using VP9 SVC

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#588]
## Bug Report

No data enough yet. I've been told about this via DM and there is also a topic about this (without core dump) in the forum: https://mediasoup.discourse.group/t/worker-dies/2925

**Comment by fippo** [comment]
I've filed a crash bug. View-restricted but i'll update if there are any results.

**Comment by ibc** [comment]
> I've filed a crash bug. View-restricted

Do you mean a crash bug report in Chromium/libwebrtc? It should not justify that mediasoup crashes.

**Comment by fippo** [comment]
i've only seen a chrome crash.

**Comment by ibc** [comment]
Ah
