### ISSUE TITLE
Audio issue when participants more than 5

### ISSUE THREAD

**Issue by edwinsyarief** [versatica/mediasoup#590]
Hi,

I'm using the latest Mediasoup version (V3).

There is audio issue when participants reach above 5. Sometimes newConsumer for audio not triggered for 6th participant, so participants is only able to see 6th participant's video, but no audio. But sometimes newConsumer is triggered, but the audio is so small (very hard to hear). But, when participants leave on by one, the audio become loud and louder, until two participants left in the room (host and 6th participant)

Does someone have the same issue?

Best Regards,
Edwin

**Comment by ibc** [comment]
Questions in the forum as explained in the issue template that you deleted.
