### ISSUE TITLE
Fixed Installing on windows !!! 

### ISSUE THREAD

**Issue by bakamaru** [versatica/mediasoup#596]
Installing on windows, I've faced a lot problem some how i've managed to run it on windows.
First problem was heapdump,I don't know exactly it's causing so much pain on windows though in ubuntu it is working nicely, so just commented the usage of heapdump inside interactiveserver,js file.
`//const heapdump = require('heapdump');`
and at line no 489
// heapdump.writeSnapshot(filename, (error, filename) =>
						// {
						// 	if (!error)
						// 	{
						// 		this.log(`heapdump snapshot writen to ${filename}`);
						// 		this.log(
						// 			'learn how to use it at https://github.com/bnoordhuis/node-heapdump');
						// 	}
						// 	else
						// 	{
						// 		this.error(`heapdump snapshot failed: ${error}`);
						// 	}
						// });

one of another problem is mediasoup library which is not running its postinstall script during installation of mediasoup only on windows.If other windows dependencies were installed on windows machine(vc++,cmake ) then navigate inside node_modules\mediasoup and run following command 
`npm run postinstall`
this will publish mediasoup-worker.exe inside worker/out/release folder which is required to run mediasoup server on windows.
If everything goes as i mentioned you'll be happy running mediasoup on your windows.
Cheers!!!!

**Comment by nazar-pc** [comment]
There is no `heapdump` dependency in mediasoup, so I'm not sure where it is coming from.

postinstall not running is either an issue with your setup specifically or with npm itself, but not with mediasoup.

I think there is no mediasoup issue with description given so far, please open a topic for discussion on the forum instead: https://mediasoup.discourse.group/

**Comment by ibc** [comment]
Yes please. Let's use the forum, this is not a mediasoup issue.
