### ISSUE TITLE
[3.7.18] build fails on windows

### ISSUE THREAD

**Issue by binlux** [versatica/mediasoup#604]
OS : windows 10
all versions less than 3.7.18 can build with no errors

**Comment by ibc** [comment]
You don't even provide any error. We cannot do anything with this information, sorry.

**Comment by binlux** [comment]
@ibc compiling is fine, but the problem is when linking . that's what i noticed

![shoot](https://user-images.githubusercontent.com/11628272/125168398-4ba2af00-e19d-11eb-85e4-379e1e762212.PNG)

**Comment by nazar-pc** [comment]
CI for Windows would be nice to have

**Comment by stefanberea** [comment]
Same error as in the picture above. I made sure openssl 1.1.1 is installed and accessible from the command line. I tried to build the VS solution from the node module and got the same result.

**Comment by nazar-pc** [comment]
OpenSSL is bundled with mediasoup, it doesn't use OpenSSL installed on the system.

**Comment by sujinhuan** [comment]
the same error on windows

**Comment by mingdesoft** [comment]
the same error on windows

**Comment by nazar-pc** [comment]
Folks, writing the same message over and over again doesn't help.
Put :+1: on the first message, then consider debugging and contributing a fix back to mediasoup.
https://github.com/versatica/mediasoup/pull/598 is where OpenSSL changes comes from.

**Comment by Vbitz** [comment]
I suspect the problem comes from this change in #598

https://github.com/versatica/mediasoup/blob/237f7b2ac6aaf68868df413df523e5848a8a2a4e/worker/common.gypi#L9

The original error is caused by some of the required source files being missing from the build. I suspect this is specific to the configs for Windows (like ASM files not being built or linked correctly).

**Comment by woodfe** [comment]
It seems the openssl.vcxproj generated by gyp did not compile asm files:

>   <ItemGroup>
    <None Include="config\archs\linux-x86_64\asm_avx2\crypto\aes\aesni-mb-x86_64.s"/>
    <None Include="config\archs\linux-x86_64\asm_avx2\crypto\aes\aesni-sha1-x86_64.s"/>
    <None Include="config\archs\linux-x86_64\asm_avx2\crypto\aes\aesni-sha256-x86_64.s"/>
    <None Include="config\archs\linux-x86_64\asm_avx2\crypto\aes\aesni-x86_64.s"/>
    <None Include="config\archs\linux-x86_64\asm_avx2\crypto\aes\vpaes-x86_64.s"/>
    <None Include="config\archs\linux-x86_64\asm_avx2\crypto\bn\rsaz-avx2.s"/>
    <None Include="config\archs\linux-x86_64\asm_avx2\crypto\bn\rsaz-x86_64.s"/>
    <None Include="config\archs\linux-x86_64\asm_avx2\crypto\bn\x86_64-gf2m.s"/>
    <None Include="config\archs\linux-x86_64\asm_avx2\crypto\bn\x86_64-mont.s"/>
    <None Include="config\archs\linux-x86_64\asm_avx2\crypto\bn\x86_64-mont5.s"/>
    <None Include="config\archs\linux-x86_64\asm_avx2\crypto\camellia\cmll-x86_64.s"/>
    <None Include="config\archs\linux-x86_64\asm_avx2\crypto\chacha\chacha-x86_64.s"/>
    <None Include="config\archs\linux-x86_64\asm_avx2\crypto\ec\ecp_nistz256-x86_64.s"/>
    <None Include="config\archs\linux-x86_64\asm_avx2\crypto\ec\x25519-x86_64.s"/>
    <None Include="config\archs\linux-x86_64\asm_avx2\crypto\md5\md5-x86_64.s"/>
    <None Include="config\archs\linux-x86_64\asm_avx2\crypto\modes\aesni-gcm-x86_64.s"/>
    <None Include="config\archs\linux-x86_64\asm_avx2\crypto\modes\ghash-x86_64.s"/>
    <None Include="config\archs\linux-x86_64\asm_avx2\crypto\poly1305\poly1305-x86_64.s"/>
    <None Include="config\archs\linux-x86_64\asm_avx2\crypto\rc4\rc4-md5-x86_64.s"/>
    <None Include="config\archs\linux-x86_64\asm_avx2\crypto\rc4\rc4-x86_64.s"/>
    <None Include="config\archs\linux-x86_64\asm_avx2\crypto\sha\keccak1600-x86_64.s"/>
    <None Include="config\archs\linux-x86_64\asm_avx2\crypto\sha\sha1-mb-x86_64.s"/>
    <None Include="config\archs\linux-x86_64\asm_avx2\crypto\sha\sha1-x86_64.s"/>
    <None Include="config\archs\linux-x86_64\asm_avx2\crypto\sha\sha256-mb-x86_64.s"/>
    <None Include="config\archs\linux-x86_64\asm_avx2\crypto\sha\sha256-x86_64.s"/>
    <None Include="config\archs\linux-x86_64\asm_avx2\crypto\sha\sha512-x86_64.s"/>
    <None Include="config\archs\linux-x86_64\asm_avx2\crypto\whrlpool\wp-x86_64.s"/>
    <None Include="config\archs\linux-x86_64\asm_avx2\crypto\x86_64cpuid.s"/>
    <None Include="config\archs\linux-x86_64\asm_avx2\engines\e_padlock-x86_64.s"/>
    <None Include="openssl.gyp"/>
  </ItemGroup>

because openssl_asm_avx2.gypi condition falls to default target:

>     }, {
      # Other architectures don't use assembly
      'includes': ['config/archs/linux-x86_64/asm_avx2/openssl.gypi'],
    }], 

If I change this line to:
> 'includes': ['config/archs/VC-WIN64A/asm_avx2/openssl.gypi'], 

It will generate MASM vcxproj items.
Don't know why it fails to match 'target_arch=="x64" and OS=="win"' in gyp

**Comment by nazar-pc** [comment]
Looks like `nasm` might be required on Windows, maybe it just silently fails that step, but still proceeds all the way to the linking stage?

I wouldn't expect anyone to run mediasoup under Windows in production, so it might make sense to just force non-ASM OpenSSL on Windows.

Please try #614.

**Comment by woodfe** [comment]
Found scripts/configure.py outputs -Dtarget_arch=AMD64
> def host_arch():
    machine = platform.machine()
    if machine == 'i386': return 'ia32'
    if machine == 'x86_64': return 'x64'
    if machine == 'aarch64': return 'arm64'
    if machine == 'arm64': return 'arm64'
    if machine == 'mips64': return 'mips64el'
    if machine.startswith('arm'): return 'arm'
    if machine.startswith('mips'): return 'mips'
    return machine  # Return as-is and hope for the best.

add a line to convert it to x64
>    if machine == 'AMD64': return 'x64'

But got another error:
> call "D:\Work\roadtest\ne
w\mediasoup\worker\deps\openssl\.\setup_env.bat" && set CYGWIN=nontsec&& set INTDIR=Release\obj\openssl\&& set INPUTPAT
H=config\archs\VC-WIN64A\asm_avx2\crypto\aes\aesni-mb-x86_64.asm && bash -c "\"nasm.exe\" \"-f win64\" \"-DNEAR\" \"-Ox
\" \"-g\" \"-o\" \"`cygpath -m \\\"${INTDIR}\\\"`/aesni-mb-x86_64.obj\" \"`cygpath -m \\\"${INPUTPATH}\\\"`\""”

It seems custom rules is not applied, but gyp default cygwin rules?
>     }, 'target_arch=="x64" and OS=="win"', {
      'includes': ['config/archs/VC-WIN64A/asm_avx2/openssl.gypi'],
      'rules': [
        {
          'rule_name': 'Assemble',
          'extension': 'asm',
          'inputs': [],
          'outputs': [
            '<(INTERMEDIATE_DIR)/<(RULE_INPUT_ROOT).obj',
          ],
          'action': [
            'nasm.exe',
            '-f win64',
            '-DNEAR',
            '-Ox',
            '-g',
            '-o', '<(INTERMEDIATE_DIR)/<(RULE_INPUT_ROOT).obj',
            '<(RULE_INPUT_PATH)',
          ],
        }
      ],

**Comment by nazar-pc** [comment]
Yeah, with AMD64 you need nasm installed to compile assembly.

Added `AMD64` detection into #614 as well.

**Comment by woodfe** [comment]
Add 'msvs_cygwin_shell': 0, to custom rules to prevent from using cygwin shell.

>      'includes': ['config/archs/VC-WIN64A/asm_avx2/openssl.gypi'],
      'rules': [
        {
          'rule_name': 'Assemble',
          'extension': 'asm',
          'msvs_cygwin_shell': 0,
          'inputs': [],
          'outputs': [
            '<(INTERMEDIATE_DIR)/<(RULE_INPUT_ROOT).obj',
          ],
          'action': [
            'nasm.exe',
            '-f win64',
            '-DNEAR',
            '-Ox',
            '-g',
            '-o', '<(INTERMEDIATE_DIR)/<(RULE_INPUT_ROOT).obj',
            '<(RULE_INPUT_PATH)',
          ],
        }
      ],

**Comment by woodfe** [comment]
Add 'msvs_cygwin_shell': 0, to custom rules to prevent from using cygwin shell.

>      'includes': ['config/archs/VC-WIN64A/asm_avx2/openssl.gypi'],
      'rules': [
        {
          'rule_name': 'Assemble',
          'extension': 'asm',
          'msvs_cygwin_shell': 0,
          'inputs': [],
          'outputs': [
            '<(INTERMEDIATE_DIR)/<(RULE_INPUT_ROOT).obj',
          ],
          'action': [
            'nasm.exe',
            '-f win64',
            '-DNEAR',
            '-Ox',
            '-g',
            '-o', '<(INTERMEDIATE_DIR)/<(RULE_INPUT_ROOT).obj',
            '<(RULE_INPUT_PATH)',
          ],
        }
      ],

> 
> 
> Looks like `nasm` might be required on Windows, maybe it just silently fails that step, but still proceeds all the way to the linking stage?
> 
> I wouldn't expect anyone to run mediasoup under Windows in production, so it might make sense to just force non-ASM OpenSSL on Windows.
> 
> Please try #614.

disable asm on windows is ok

**Comment by nazar-pc** [comment]
> Add 'msvs_cygwin_shell': 0, to custom rules to prevent from using cygwin shell.

But that wouldn't magically add `nasm.exe` to fix compile error.

Also I do not use Windows basically at all, so I didn't test the PR myself (would be great to see contribution with CI setup for it though).
