### ISSUE TITLE
Timestamp is not increased correctly when switching layers.

### ISSUE THREAD

**Issue by penguinol** [versatica/mediasoup#615]
Look at picture below:
![image](https://user-images.githubusercontent.com/14129614/126580289-944ba8b6-751c-4f8d-9fe8-490658057835.png)
The packets on the left is received by mediasoup, and on the right is sent by mediasoup.
The video source is a 2 spatial-layers simulcast stream.
```
seq = 13294, time = 2538709271 -> seq = 30856, time = 2538709271  offset 0
seq = 13295, time = 2538709271 -> seq = 30857, time = 2538709271  offset 0
seq = 13296, time = 2538709271 -> seq = 30858, time = 2538709271  offset 0
switch layer
seq = 26483, time = 2538709271 -> seq = 30859, time = 2538712241 offset 33 * 90
seq = 26484, time = 2538709271 -> seq = 30859, time = 2538712241 offset 33 * 90
```
The timestamp of the two stream is the same, so we set the offset to 33ms when switching layer.
According to https://github.com/versatica/mediasoup/blob/237f7b2ac6aaf68868df413df523e5848a8a2a4e/worker/src/RTC/SimulcastConsumer.cpp#L792-L798

And then we switch layer again
![image](https://user-images.githubusercontent.com/14129614/126593854-2af8a419-2292-4365-a21a-8c61b6f78d02.png)
```
seq = 26660, time = 2539111121 -> seq = 31036, time = 2539114091 offset 33 * 90
seq = 26661, time = 2539111121 -> seq = 31037, time = 2539114091 offset 33 * 90
seq = 13429, time = 2539111121 -> not sps/pps, drop
switch layer
seq = 13430, time = 2539114001 -> seq = 31038, time = 2539114091 offset 1 * 90
seq = 13431, time = 2539114001 -> seq = 31039, time = 2539114091 offset 1 * 90
```
So we can see the timestamp of two stream is different, but is changed to the same value.
Because of  2539114001 is less than 2539114091, we go into this if case
https://github.com/versatica/mediasoup/blob/d63758499e16e45894fc41bb765145aacae7bb04/worker/src/RTC/SimulcastConsumer.cpp#L747-L750
And `offset  = 2539114091 - 2539114001 = 90` according to 
https://github.com/versatica/mediasoup/blob/d63758499e16e45894fc41bb765145aacae7bb04/worker/src/RTC/SimulcastConsumer.cpp#L758-L759

It lead to decode error on mac os, and is may be one of the causes of #408

**Comment by ibc** [comment]
Excellent catch. Finally a good explanation for #408. Please let's some days to take a look to this, we won't forget.

**Comment by penguinol** [comment]
> Excellent catch. Finally a good explanation for #408. Please let's some days to take a look to this, we won't forget.

Well, I think this is just one of the reasons which cause #408. Fix this will not fully resolve the problem.

I'm still applying https://github.com/penguinol/mediasoup/commit/de2ed3f9a8a1a36e7ca5b392390fb44da30f4341 on our product environment.

**Comment by jmillan** [comment]
@penguinol, could you please try this change?

This is indeed a bug, we should be increasing the `extraOffset` instead of decreasing it. As per your given data in this issue, this should fix the issue.

```diff
diff --git a/worker/src/RTC/SimulcastConsumer.cpp b/worker/src/RTC/SimulcastConsumer.cpp
index af38255e8..93c466574 100644
--- a/worker/src/RTC/SimulcastConsumer.cpp
+++ b/worker/src/RTC/SimulcastConsumer.cpp
@@ -806,7 +806,7 @@ namespace RTC

                                        // Increase the timestamp offset for the whole life of this Producer stream
                                        // (until switched to a different one).
-                                       tsOffset -= tsExtraOffset;
+                                       tsOffset += tsExtraOffset;
                                }
                        }

```

**Comment by penguinol** [comment]
> @penguinol, could you please try this change?
> 
> This is indeed a bug, we should be increasing the `extraOffset` instead of decreasing it. As per your given data in this issue, this should fix the issue.
> 
> ```diff
> diff --git a/worker/src/RTC/SimulcastConsumer.cpp b/worker/src/RTC/SimulcastConsumer.cpp
> index af38255e8..93c466574 100644
> --- a/worker/src/RTC/SimulcastConsumer.cpp
> +++ b/worker/src/RTC/SimulcastConsumer.cpp
> @@ -806,7 +806,7 @@ namespace RTC
> 
>                                         // Increase the timestamp offset for the whole life of this Producer stream
>                                         // (until switched to a different one).
> -                                       tsOffset -= tsExtraOffset;
> +                                       tsOffset += tsExtraOffset;
>                                 }
>                         }
> ```

Decreasing here means increasing timestamp, because `uint32_t timestamp = packet->GetTimestamp() - this->tsOffset;`
#626 is the way that we fix the problem.

**Comment by jmillan** [comment]
> Decreasing here means increasing timestamp

Indeed.
