### ISSUE TITLE
Question about AudioLevelObserver::Update

### ISSUE THREAD

**Issue by tishion** [versatica/mediasoup#623]
https://github.com/versatica/mediasoup/blob/ec42b2592fbd7c0161ed953e3c6105ad38e8c213/worker/src/RTC/AudioLevelObserver.cpp#L145-L163

Just a simple question about the following  two lines:
 		if (avgDBov >= this->threshold) 
 			mapDBovsProducer[avgDBov] = producer; 

lets say if there are two producers with the same average  volume number, the first added one will be overwritten by the second one, is this designated behavior?

**Comment by nazar-pc** [comment]
This issue tracker is for bug reports primarily, please post your question [on the forum](https://mediasoup.discourse.group/)

**Comment by tishion** [comment]
> This issue tracker is for bug reports primarily, please post your question [on the forum](https://mediasoup.discourse.group/)

sorry，will move to forum now.
