### ISSUE TITLE
mediasoup-demo_v3 video quality not good

### ISSUE THREAD

**Issue by airx** [versatica/mediasoup#624]
**background:**
mediasoup demo v3, lan environment:
server: 192.168.3.5
client_1: 192.168.3.6, chrome 92, send 1280x720 vp8(or vp9), svc.
client_2: 192.168.3.7, chrome 92, watch client_1 video stream.

**question:** 
At the beginning client_2 can recieve 1280x720 stream from client_1, after 5-15s later, stream always downgrade to 960x540 or 640x360.
Why svc downgrade in such a good lan bandwidth environment? ? Feel no sense^^

**Comment by nazar-pc** [comment]
This issue tracker is primarily for bug reports, please ask questions [on the forum](https://mediasoup.discourse.group/).
