### ISSUE TITLE
Compiling mediasoup in docker:ubuntu:20.04

### ISSUE THREAD

**Issue by balazskreith** [versatica/mediasoup#630]
-

**Comment by nazar-pc** [comment]
I do not think this is a bug in mediasoup, we have CI system in place for tracking such issues and it passes all checks and tests just fine. Please provide more info (like `Dockerfile` used) on the forum.

**Comment by balazskreith** [comment]
-

**Comment by nazar-pc** [comment]
@balazskreith this is not a bug in mediasoup, please use forum for discussion.

José asked you a very specific thing: to get core dump, there is no point to create an issue just to say you don't have it.
