### ISSUE TITLE
[Bug] srtp will crash on 64 bit big-endian

### ISSUE THREAD

**Issue by xia-chu** [versatica/mediasoup#635]
https://github.com/versatica/mediasoup/blob/73ec18a8c959cb44343ff9d3ac052eae87286b3f/worker/src/RTC/SrtpSession.cpp#L164

The `len` parameter is the type of`size_t*`, which on 64 bit environment， it is a 64 bit integer number。
But `int` usually will be 32 bit long,  if we take address of 64 bit integer number as `int *` on  big-endian  machine,  
we will take the address of its high 4 bytes。

**Comment by ibc** [comment]
Please open another bug by properly filling the issue template and provide more data and rationale.
