### ISSUE TITLE
[Bug] srtp will crash on 64 bit big-endian machine

### ISSUE THREAD

**Issue by xia-chu** [versatica/mediasoup#636]
## Bug Report

Srtp will crash on 64 bit big-endian machine

### Your environment

- Operating system: some 64 bit system
- Cpu: some big-endian machine 

### Issue description
These code my cause crash:
https://github.com/versatica/mediasoup/blob/73ec18a8c959cb44343ff9d3ac052eae87286b3f/worker/src/RTC/SrtpSession.cpp#L164

The `len` parameter is the type of`size_t*`, which on 64 bit environment,  it is a 64 bit integer number。
But `int` usually will be 32 bit long,  if we take address of 64 bit integer number as `int *` on  big-endian  machine,  
we will take the address of its high 4 bytes。If `srtp` write vlaue `1024` to it,  the vlaue of `len` will be `1024 << 32`.

**Comment by ibc** [comment]
Thanks a lot. Will check and fix it in next days.

**Comment by ibc** [comment]
Thanks for the report. Would you mind taking a look to PR https://github.com/versatica/mediasoup/pull/637 (and test it if possible)?

**Comment by xia-chu** [comment]
Thank you very much, but I don't have a big-endian machine to test. I also received these feedback from others。
I don't think the previous code is perfect，i think this problem should be fixed.

**Comment by ibc** [comment]
Please, next time don't close the issue. Let's please close the issue (automatically) when the PR that solves it is merged.

**Comment by xia-chu** [comment]
ok thanks!



发自我的iPhone


------------------ Original ------------------
From: Iñaki Baz Castillo ***@***.***&gt;
Date: Mon,Aug 16,2021 9:46 PM
To: versatica/mediasoup ***@***.***&gt;
Cc: 夏楚 ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [versatica/mediasoup] [Bug] srtp will crash on 64 bit big-endian machine (#636)





 
Please, next time don't close the issue. Let's please close the issue (automatically) when the PR that solves it is merged.
