### ISSUE TITLE
Pre-build images

### ISSUE THREAD

**Issue by piranna** [versatica/mediasoup#641]
## Feature Request

Can we provide pre-build images of `mediasoup` instead of require to compile it each time it's installed? We can use https://github.com/prebuild/prebuildify or some other similar module to generate, publish and download the pre-build images, and it can be automated as part of the CI infraestructure so there's no extra work for anybody :-)

**Comment by ibc** [comment]
We were already asked to do this in the past but own't do it, for N reasons:

- This means that we have to maintain all those binaries for different OSs/archs => more work for us.
- mediasoup C++ component (mediasoup-worker) is not a Node addon but a completely separate process so none of those modules can help here.

**Comment by piranna** [comment]
> * This means that we have to maintain all those binaries for different OSs/archs => more work for us.

Totally agree on this, this can be more work, but maybe can be delegated to community... I hope some client can provide me some slots someday to work on this and provides a PR, but nothing until now... :-(


> * mediasoup C++ component (mediasoup-worker) is not a Node addon but a completely separate process so none of those modules can help here.

That modules can help since they can provide the already compiled binaries, no matter if they are Node.js native modules or independent executables. I have been using in the past `prebuild` package to provide prebuild images of NodeOS, and they were executables, root filesystems, or in some cases full disk images...

**Comment by ibc** [comment]
> > * This means that we have to maintain all those binaries for different OSs/archs => more work for us.
> 
> Totally agree on this, this can be more work, but maybe can be delegated to community... I hope some client can provide me some slots someday to work on this and provides a PR, but nothing until now... :-(

Delegating to community means that we cannot release a new version until "the community" manages those new binaries for every supported OS and arch, plus our release capabilities would depend on external factors. This is not gonna work and definitely this is not something we are gonna do. Actually compiling mediasoup is just a few minutes in a powerful multi-core machine.
