### ISSUE TITLE
How well does this scale ?

### ISSUE THREAD

**Issue by anubhav-gig** [versatica/mediasoup#649]
I have a requirement of holding video conferences. What is the maximum number of users can we have with this ?

**Comment by ibc** [comment]
Zero

**Comment by avoitenko-logitech** [comment]
I am inspired how you are building community around Mediasoup project 👏.

**Comment by avoitenko-logitech** [comment]
It is so friendly and supportive.

**Comment by ibc** [comment]
When people try to ask a support for question in GitHub they clearly read the "use the forum" text. It's not my fault if they ignore it, plus I have exactly zero interest in prerecorded questions such as "how many users does mediasoup support?".
