### ISSUE TITLE
fixed port

### ISSUE THREAD

**Issue by syhstonesyh** [versatica/mediasoup#657]
## Bug Report

- mediasoup version:3.8.4

### Issue description
I see that the document supports fixed ports, but I make mistakes when using them, mediasoup V3.8.4

mediasoup:Channel request() [method:router.createWebRtcTransport, id:8] +59ms
  mediasoup:ERROR:Channel [pid:1341388 RTC::PortManager::Bind() | throwing MediaSoupError: uv_udp_bind() failed [transport:udp, ip:'192.168.0.111', port:42001: address already in use +0ms
  mediasoup:ERROR:Channel [pid:1341388 Worker::OnChannelRequest() | throwing MediaSoupError: uv_udp_bind() failed [transport:udp, ip:'192.168.0.111', port:42001: address already in use [method:router.createWebRtcTransport]

**Comment by syhstonesyh** [comment]
Multiple webrtctransport cannot use the same port

**Comment by syhstonesyh** [comment]
I want to create multiple WebrTCTransport with a single port, after all, exposing too many ports is not safe

**Comment by nazar-pc** [comment]
This is an advanced feature and no one can help if you specify the same port for 2 transports or the port is already used by another app. It is your job to ensure port is available and isn't used twice.

Closing as there is no mediasoup bug here.

If you have questions, create a thread on the forum: https://mediasoup.discourse.group/
