### ISSUE TITLE
Custom installation path

### ISSUE THREAD

**Issue by information-security** [versatica/mediasoup#658]
## Feature Request
Currently, `mediasoup-worker` is built on every `npm install` run. This has made our CI workflow very time taking. It would be great if we could cache the build files.

My proposal would be to use an environment variable such as `MEDIASOUP_BUILD_PATH`. If set, the package would compile the source files on the first run of `npm i` and the build artifacts would be then copied to the path specified in this variable. On subsequent runs, package installer could check for the existence as well as version compatibility of the required files (such as mediasoup-worker.exe) in this directory and skip the build step if those conditions are met.

Thanks.

**Comment by nazar-pc** [comment]
There is already `MEDIASOUP_OUT_DIR` environment variable supported and re-builds take very small amount of time if `npm i` was already called before and nothing has changed just as you said.

I don't think there is something to be done here, if you have any questions, please ask them on the forum: https://mediasoup.discourse.group/

**Comment by information-security** [comment]
Isn't this variable supported on windows? ([configure.py](https://github.com/versatica/mediasoup/blob/d63758499e16e45894fc41bb765145aacae7bb04/worker/scripts/configure.py#L60)). In that case, what is your opinion about adding a simple `copy` command on your postinstall script for windows platform?
As a matter of fact, running the following command doesn't work as expected in windows. The binaries are always copied to node_modules/mediasoup/worker/out dir no matter what the value of `MEDIASOUP_OUT_DIR` is:
_`set MEDIASOUP_OUT_DIR=D:\my_project\.npm&&npm install`_

Apart from that, `MEDIASOUP_OUT_DIR` is used only in C++ build and will not be checked by any of the nodejs modules.
So to achieve what I was asking, It is required to use `MEDIASOUP_WORKER_BIN` in addition to `MEDIASOUP_OUT_DIR`.

The procedure would be to first use the `MEDIASOUP_OUT_DIR` to install the binaries in your desired path, then use `MEDIASOUP_WORKER_BIN` to let the mediasoup know where to find the executable. Note that `MEDIASOUP_WORKER_BIN` must point to the executable file itself not the containing directory.
Another thing is that, investigating the [code](https://github.com/versatica/mediasoup/blob/d63758499e16e45894fc41bb765145aacae7bb04/worker/scripts/configure.py#L16), an absolute path must be provided for the `MEDIASOUP_OUT_DIR` which happens to be the reason for having `MEDIASOUP_OUT_DIR` not working in windows .

Considering above-mentioned facts, with due respect, I believe these two variables could be merged somehow for easier installation/usage. Don't you think so? (@nazar-pc) I mean a single environment variable to be used during the installation and mediasoup will remember the path provided in that variable for its further execution.
