### ISSUE TITLE
RPC documentation

### ISSUE THREAD

**Issue by ClosetGeek-Git** [versatica/mediasoup#660]
## Feature Request
You should document the rpc protocol that is used to control the c++ side of Mediasoup. This would open up a world of possibilities for controlling Mediasoup (python, php, go, etc)

**Comment by nazar-pc** [comment]
This API is not public and thus doesn't need to be documented. You can check the source code though and figure out what it is from there (note that if #644 is merged it will change slightly).

There is A LOT of stuff that needs to be taken care of even when you have such an API, so it is not very useful on its own.

mediasoup supports Node.js and Rust, no other languages/platforms are planned to be officially supported at the moment, which didn't stop people from writing unofficial wrappers for Go, C# and probably some others already (according to mediasoup forum).
