### ISSUE TITLE
There is no RTP flow for plain transports created for Firefox

### ISSUE THREAD

**Issue by HadiAghandeh** [versatica/mediasoup#661]
- Operating system: 5.10.61-1-MANJARO (tested on Ubuntu 20.04 too)
- Node version: V16.5.0
- npm version: 7.19.1
- gcc/clang version: gcc 11.1.0 
- mediasoup version: 3.8.4
- mediasoup-client version: 3.6.41

### Issue description

There is no RTP flow for plain transports created for firefox.
How to reproduce:
Create any producers (video or audio and choose a codec by your own choice) at Firefox browsers.
At server side create a plain transport and a consumer that consume on the producer:
```
  const rtpTransportConfig = config.plainRtpTransport;
  const rtpTransport = router.createPlainTransport(rtpTransportConfig);

    await rtpTransport.connect({
      ip: '127.0.0.1',
      port: remoteRtpPort, // available ports
      rtcpPort: remoteRtcpPort
    });

const codecs = [];
  // Codec passed to the RTP Consumer must match the codec in the Mediasoup router rtpCapabilities
  const routerCodec = router.rtpCapabilities.codecs.find(
    codec => codec.kind === producer.kind
  );
  codecs.push(routerCodec);

  const rtpCapabilities = {
    codecs,
    rtcpFeedback: []
  };

  const rtpConsumer = await rtpTransport.consume({
    producerId: producer.id,
    rtpCapabilities,
  });

  rtpConsumer.enableTraceEvent([ 'rtp' ]);
  rtpConsumer.on('trace', (trace) => {
    console.info('consumer trace',trace);
  });
```

You will not see any log when using Firefox.

**Comment by ibc** [comment]
Firefox cannot use plain RTP. Neither Chrome. They implement WebRTC. 

Please use the forum for usage questions or usage problems. No issue/bug here at all.

**Comment by HadiAghandeh** [comment]
@ibc 
Yes browsers can not use plain streams. What I meant is that when you create a plain transport from a WebRTC stream for recording or any other purposes (not using inside any browsers) no flow of RTP is found. This issue occurs only when you are using Firefox as the source of the WebRTC stream.

**not working**: Firefox -> webrtc -> server -> RTP
**working**: Chrome -> webrtc -> server -> RTP

**Comment by ibc** [comment]
I see, but that cannot be a bug in mediasoup but a wrong usage in your side. There are many users doing exactly that (for recording etc) with Firefox. Please use the forum. I know you already asked in the forum but we cannot handle your problem in GitHub issues because it's not a bug.

**Comment by HadiAghandeh** [comment]
Its relieve to know it is not a bug. I will create another forum question.

**Comment by ibc** [comment]
Ensure whether media from Firefox is really teaching mediasoup. First check whether ICE and DTLS are connected etc. There are tons of logs and stats to check that in mediasoup and mediasoup-client for that.
