### ISSUE TITLE
Redundant info in dumps

### ISSUE THREAD

**Issue by piranna** [versatica/mediasoup#670]
At https://github.com/versatica/mediasoup/blob/0a4ab953721b2971a749968ea145c2166b12cde7/worker/src/RTC/Router.cpp#L86 it's being filled a `mapProducerIdConsumerIds` entry in the dumps, that's a bit superfluous since we already have too `mapConsumerIdProducerId`, so one of the two can be removed. The same is happening in other places and dumps. Since this is a breaking change, it should be targeting next major version.

**Comment by nazar-pc** [comment]
`.dump()` method is not even part of official public API (it is not mentioned in the official documentation and it is hidden in Rust as well even though it is technically available in both cases). It is used in tests and I don't see why it needs to be changed really.

**Comment by piranna** [comment]
Make sense then... Is there any way to enforce they are hidden in Javascript API? It seems Typescript transpilation remove all kind of visibility and access checks when transpiled... I think maybe we should use private properties instead of `private` keyword in next major, it will prevent me to use some smart hacks but also will make code more secure just by preventing people doing them.

**Comment by nazar-pc** [comment]
These are used in tests, they can't use `private` on them in TypeScript, they are just undocumented.

**Comment by piranna** [comment]
I was not talking about setting this ones as private, but about private properties like Workers._routers that are being efectively accesible on runtime fue to how Typescript works, while they shouldn't. That's why I said to replace usage of Typescript 'private' keyword for JavaScript private properties

**Comment by ibc** [comment]
ES private fields are being added in this pending PR that would be merged in @nazar-pc's ongoing Meson PR.

https://github.com/nazar-pc/mediasoup/pull/2

So let's close this :)
