### ISSUE TITLE
 private class variables

### ISSUE THREAD

**Issue by ccamensuli** [versatica/mediasoup#677]
hi, 

Since 3.9.0  

Now Ts transpilation makes  maps as private class variables  (with WeakMap)

Example :

in class Router.ts 
``` ts
// Transports map.
readonly #transports: Map<string, Transport> = new Map();
```

 I can't recover < router._transports > map in  router object 

in transpiled class Router.js
``` js
// Transports map.
 _transports.set(this, new Map());

.......

exports.Router = Router;
_internal = new WeakMap(), _data = new WeakMap(), _channel = new WeakMap(), _payloadChannel = new WeakMap(), _closed = new WeakMap(), _appData = new WeakMap(), _transports = new WeakMap(), _producers = new WeakMap(), _rtpObservers = new WeakMap(), _dataProducers = new WeakMap(), _mapRouterPipeTransports = new WeakMap(), _pipeToRouterQueue = new WeakMap(), _observer = new WeakMap();

```

This way is also with other classes  example transports 

_consumers , _producers , _dataProducers ...

Maybe there is another way to get these variables ?

or maybe it is necessary to create accessors ?
or maybe  you don't want to make these variables public ?

Thank you for your attention.
christophe

**Comment by nazar-pc** [comment]
`._X` properties were never public and never mentioned in documentation. In fact properties/methods starting with `_` are private by convention in older JS codebases. With 3.9.0 they are made properly private.

Subscribe to events as mentioned in documentation if you want to keep track of any of those.
