### ISSUE TITLE
Emit `close` after `died`

### ISSUE THREAD

**Issue by piranna** [versatica/mediasoup#680]
## Feature Request

According to docs, all objects emit a `close` event no matter their reason, having emitted before other events like `transportclose`, `producerclose`... When a `Worker` dies, it's not being call the `close` event after emitted the `died` event. I know that if `died` event is emitted it's because some nasty bug has surfaced in the `Worker` and should be reported with a core dump, but in addition to that, I'm suggesting to make `Worker` to also emit the `close` event to make it orthogonal to the other objects APIs. I'm asking for this because it can be very useful for clean-up tasks without needing to register both `close` and `died` events.

**Comment by ibc** [comment]
> According to docs, all objects emit a close event no matter their reason, having emitted before other events like transportclose, producerclose..

This is not true. Router, Transport, Producer, Consumer, etc classes don't emit "close" event, so it wouldn't make sense that Worker did it.

**Comment by ibc** [comment]
If you mean observer "close" event, Worker also emits it:

https://mediasoup.org/documentation/v3/mediasoup/api/#worker-observer-on-close

If Worker's observer doesn't emit "close" when Worker emits "died", then that's a bug, but AFAIK it does (if not, please report it).

**Comment by piranna** [comment]
> This is not true. Router, Transport, Producer, Consumer, etc classes don't emit "close" event, so it wouldn't make sense that Worker did it.

> If you mean observer "close" event, Worker also emits it:
>
> mediasoup.org/documentation/v3/mediasoup/api/#worker-observer-on-close

Ok, it's true, no Mediasoup object emit a `close` event, but their `observer`s, fair enought... In this case, it's more correct to talk about `Worker.observer` close event.


> If Worker's observer doesn't emit "close" when Worker emits "died", then that's a bug, but AFAIK it does (if not, please report it).

I didn't see any explicit reference in the docs about `close` being emitted after `died`, but looking at [`Worker` code](https://github.com/versatica/mediasoup/blob/v3/node/src/Worker.ts), I can't see any direct relationship between them either... :-/ When getting a failed `exit` event or an `error` event from the child process, `died` is emitted, but `close` event [is only emitted when calling to `close()` method](https://github.com/versatica/mediasoup/blob/fc5ebd0334d2f054f927642aabaefa0fbdb433e6/node/src/Worker.ts#L502). Other objects, for example `Router`, [emit explicitly `workerclose` and `close` at the same time](https://github.com/versatica/mediasoup/blob/fc5ebd0334d2f054f927642aabaefa0fbdb433e6/node/src/Router.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L322-L325).

If I'm correct, it's not being currently emitted `close` after `died`, and fix would be just to add `this.#observer.safeEmit('close');` after both calls to `this.safeEmit('died');`. Is it?

**Comment by ibc** [comment]
Indeed this is a bug. this.close() should be called after all cases in which "died" is emitted.

Can you make a PR and verify that it doesn't break anything please?

**Comment by piranna** [comment]
> Can you make a PR and verify that it doesn't break anything please?

Done at https://github.com/versatica/mediasoup/pull/682.

**Comment by ibc** [comment]
Let's close this feature request /  issue since the description was not accurate and there is an ongoing PR

**Comment by piranna** [comment]
> Let's close this feature request / issue since the description was not accurate and there is an ongoing PR

Agree.
