### ISSUE TITLE
[regression] `close` event is not emitted inmediatly on 3.9.0

### ISSUE THREAD

**Issue by piranna** [versatica/mediasoup#681]
### Your environment

- Operating system: Ubuntu Linux 21.04
- Node version: v16.11.1
- npm version: 8.0.0
- gcc version: 10.3.0
- mediasoup version: 3.8.4 -> 3.9.0
- mediasoup-client version: not aplicable

### Issue description

After upgrading `mediasoup` from 3.8.4 to 3.9.0 my Mafalda tests has started to fail, more exaclty this one:

```js
  test("routers are closed if they don't have transports", function () {
    return Promise.all([
      router.createDirectTransport(),
      router.createDirectTransport(),
    ]).then(function ([transport1, transport2]) {
      expect(workers.size).toBe(1);
      expect(transports.size).toBe(2);

      transport1.close();

      expect(workers.size).toBe(1);
      expect(transports.size).toBe(1);

      transport2.close();

      expect(workers.size).toBe(0);
      expect(transports.size).toBe(0);
    });
  });
```

`router` is an instance of `MafaldaRouter`, but internally it's using a Mediasoup `Router`. `workers` and `transports` are `Map` objects that store regular mediasoup `Worker` and `Transport` objects where I'm listening to their observer `close` event to remove them, and both `transport1` and `transport2` are regular Mediasoup `DirectTransport` objects.

With mediasoup `3.8.4`, when calling to `transport1.close()`, the `close` event of `transport1.observer` is emitted inmediatly, so `transport1` is removed from `transports` Map, but with mediasoup `3.9.0` the `close` event is emitted in the next tick, so it happens after the `expect(transports.size).toBe(1)` checking and fails because `transports.size` is 2. Commenting this checks, it showed the same happens with `expect(workers.size).toBe(0)` check after `transport2.close()`, being `workers.size` equal to 1 instead of 0 (internally, Mafalda closes `Router` instances when they don't have `Transport`s or `RtpObserver`s, and close `Worker` instances when they have no `Router`s).

Upgrade from mediasoup 3.8.4 to 3.9.0 is the only change in the code, confirmed twice after fully removing `node_modules` folder.

**Comment by ibc** [comment]
```js
const mediasoup = require('mediasoup');

async function run() {
	const worker = await mediasoup.createWorker();
	const router = await worker.createRouter();
	const transport = await router.createPlainTransport({
		listenIp: '0.0.0.0'
	});

	transport.observer.on('close', () => {
		console.log('------- transport observer "close" event');
	})

	transport.close();
	console.log('------- transport closed');
}

run();
```

Output:

```
------- transport observer "close" event
------- transport closed
```

So obviously transport observer "close" event is emitted immediately and not in next tick. The `close()` method of `Transport.ts` clearly shows it.

**Comment by piranna** [comment]
Then, how is it possible that behaviour changes after the upgrade, moving back to 3.8.4 it works, and setting 3.9.0 fails again always and in a totally reproducible way? What else can be causing this? If I was doing some async operation that add delays, that would be happening also with 3.8.4... isn't it? I'm confused :-/

**Comment by ibc** [comment]
The only relevant change is the usage of private members in classes such as this.#observer instead of this._observer. I fail to see how it could behave differently in your case. Just try my code above in your Node environment and see.

**Comment by piranna** [comment]
```js
    const {
      router,
      router: {id, observer, _transports},
      worker
    } = await this._createRouter()
```

Ok, it was my fault, I was accessing to the private `_transports` property, that obviously in 3.9.0 doesn't exist... I was looking for `._`, so I missed this one 😅 🤦🏻‍♂️ .

**Comment by ibc** [comment]
:)
