### ISSUE TITLE
Split sender and receiver Transport classes

### ISSUE THREAD

**Issue by piranna** [versatica/mediasoup#686]
## Feature Request

For next v4, have explicit send and recv Transport classes instead of being them implicit by using `create()` or `produce()` methods.

Current API leads to think that Transport are bidirectional and a single one can be used for both send and receive, this is specially important when working with WebRtcTransport coming from RTCPeerConnection API, but this also happens for example with PipeTransport since you need to exchange both endpoints IP and port and set them in both `connect()` methods.

What I'm suggesting here, is to have pairs of Transport classes explicit in their direction. For example, we could have a `WebRtcConsumerTransport` that has a `consume()` and `dataConsume()` methods that create `Consumer` and `DataConsumer` objects, and a `WebRtcProducerTransport` with `produce()` and `produceData()` methods that create `Producer` and `DataProducer` objects. This is different from current API where we have a `WebRtcTransport` class with all the previous methods, so intuitively you can think that a single instance can create both `Consumer`s and `Producer`s, leading to confusion and bugs if you are not setf-disciplinated, also after using Mediasoup for long time.

Explicit > Implicit :-)

**Comment by nazar-pc** [comment]
I might be missing something, but I don't think `WebRtcTransport` on the backend is inherently unidirectional. Yes, mediasoup-client kind of enforces this, but I believe it is possible to use mediasoup with custom client library such that `WebRtcTransport` is used both for consuming and producing.

**Comment by ibc** [comment]
As @nazar-pc said, there is absolutely zero limitation in transport being bidirectional in mediasoup side. That's just a mediasoup-client design decision due the complexities of SDP handling with bidirectional streams. There is no reason to split mediasoup transport in producing and consuming ones.

**Comment by piranna** [comment]
So, maybe I confused terms between `mediasoup` and `mediasoup-client`. I though the enforcement on `mediasoup-client` was to make its API more alike to Node.js one. So, are you saying that mediasoup Node.js `PipeTransport` and the other Transports, are all bidirectional? Or is it a per-type basis?

(In `mediasoup-client` this suggestion still applies ;-) )

**Comment by ibc** [comment]
All transports in mediasoup are fully bidirectional. Zero limitations in this regard:

- https://mediasoup.org/documentation/v3/mediasoup/api/#Transport
- https://mediasoup.org/documentation/v3/mediasoup/api/#WebRtcTransport

**Comment by piranna** [comment]
> All transports in mediasoup are fully bidirectional. Zero limitations in this regard

Then maybe I got wrong with `mediasoup-client`, I though they were limitations for example in PipeTransport because you need to open a TCP port to send and another to receive, or something like this. If that's not the case and I can freely consume and produce on all of them, better for me :-) Thanks for the clarification :-D

**Comment by piranna** [comment]
Regarding this, I've just remembered: at https://github.com/versatica/mediasoup/blob/7ba88354b88117e0e7d68faafaeb1c7a97721a3b/node/src/Router.ts#L794-L795 only it's being set the pair of pipeTransports in one way. Since they are bidirectional (yes, I've just finally confirmed this ;-) ), shouldn't we register it for both routers, so in case the destination one wants to pipe back to the source one, there's no need to create a new PipeTransport, just reuse the current one? It say, add this line there:

```js
router.#mapRouterPipeTransports.set(this, [ remotePipeTransport, localPipeTransport ]);
```

And the same later for desregister them, obviously. How do you see it?

**Comment by ibc** [comment]
For that we should compute a unique index for the map of Router pair, which should have the same value no matter router1.pipeToRoute(router2) or vice-versa is called. Probably a helper that creates a string with the concatenated ids of both routers placing first the one who is <= the other (string comparison).

**Comment by piranna** [comment]
> a string with the concatenated ids of both routers placing first the one who is <= the other (string comparison)

That another option, and that way there would be just only a single entry in the map instead of need to add two of them. What one do you see it's better?

**Comment by ibc** [comment]
See PR https://github.com/versatica/mediasoup/pull/697
