### ISSUE TITLE
Build failed in windows after change build system in 3.9.0

### ISSUE THREAD

**Issue by sajjad-fatehi** [versatica/mediasoup#689]
### Your environment

- Operating system: Windows 10 19043.1237 built
- Node version: 14.15.1
- npm version: 6.14.8
- gcc/clang version: Visual studio 2017/2019
- mediasoup version: 3.9.0

### Issue description

hi mediasoup team.
i started new project that uses mediasoup ... so i wana use latest version of it 
i tried what i do every time to install mediasoup in windows and figured out install guide in docs was changed ... so i tried to do requirements and install again ... after so many tests and get errors (change version of vs ... search for issues and ...) i couldn't fix it 
this is about meson log : 

this is the error : 
**meson.build:1:0: ERROR: Compiler cl can not compile programs.**

```
Build started at 2021-10-23T16:55:29.352266
Main binary: C:\Users\***\AppData\Local\Programs\Python\Python310\python.exe
Build Options: -Db_ndebug=true -Db_pie=true -Db_staticpic=true -Dbuildtype=release
Python system: Windows
The Meson build system
Version: 0.59.2
Source dir: F:\mediaserver\node_modules\mediasoup\worker
Build dir: F:\mediaserver\node_modules\mediasoup\worker\out\Release
Build type: native build
Project name: mediasoup-worker
Project version: undefined
Sanity testing C compiler: cl
Is cross compiler: False.
Sanity check compiler command line: cl sanitycheckc.c /Fesanitycheckc.exe /MD /nologo /showIncludes /link
Sanity check compile stdout:
sanitycheckc.c
LINK : fatal error LNK1104: cannot open file 'MSVCRT.lib'

-----
Sanity check compile stderr:

-----

meson.build:1:0: ERROR: Compiler cl can not compile programs. 
```

thanks !

**Comment by nazar-pc** [comment]
Discussed with solutions at https://mediasoup.discourse.group/t/mediasoup-installation-error-in-windows-10-in-vscode-react-project/3452, I'll fix it and update documentation soon-ish.

**Comment by sajjad-fatehi** [comment]
thanks ! ill check it out and also wait for your updates .
