### ISSUE TITLE
Cannot run "make clean-all" if python3 version is updated in system

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#693]
### Your environment

- Operating system: macOS BigSur
- Node version: 16.0.0
- npm version: 7.20.5
- gcc/clang version: Apple clang version 13.0.0 (clang-1300.0.29.3)
- mediasoup version: 3.9.0

### Issue description

I had python3.7 installed using Homebrew and mediasoup properly built using it. Later I uninstalled python3.7 and upgraded to python3.9.

```
$ which python3
/usr/local/bin/python3

$ ll /usr/local/bin/python3
lrwxr-xr-x  1 ibc  admin    40B Oct 18 19:40 /usr/local/bin/python3@ -> ../Cellar/python@3.9/3.9.7_1/bin/python3
```

In `mediasoup/worker/` folder:

```
$ npm test

> mediasoup@3.9.0 test
> npm run test:node && npm run test:worker


> mediasoup@3.9.0 test:node
> npm run worker:build && node npm-scripts.js test:node


> mediasoup@3.9.0 worker:build
> node npm-scripts.js worker:build

npm-scripts.js [INFO] running task "worker:build"
npm-scripts.js [INFO] executing command: make -C worker
/Users/ibc/src/v3-mediasoup/worker/out/pip/bin/meson setup \
		--buildtype release \
		-Db_ndebug=true \
		-Db_pie=true \
		-Db_staticpic=true \
		--reconfigure \
		"" \
		/Users/ibc/src/v3-mediasoup/worker/out/Release || \
		/Users/ibc/src/v3-mediasoup/worker/out/pip/bin/meson setup \
			--buildtype release \
			-Db_ndebug=true \
			-Db_pie=true \
			-Db_staticpic=true \
			"" \
			/Users/ibc/src/v3-mediasoup/worker/out/Release
/bin/sh: /Users/ibc/src/v3-mediasoup/worker/out/pip/bin/meson: /usr/local/opt/python/bin/python3.7: bad interpreter: No such file or directory
/bin/sh: /Users/ibc/src/v3-mediasoup/worker/out/pip/bin/meson: /usr/local/opt/python/bin/python3.7: bad interpreter: No such file or directory
make: *** [setup] Error 126
```

```
$ ll /usr/local/opt/python/bin/
total 24
lrwxr-xr-x  1 ibc  admin    52B Aug 30 21:19 2to3@ -> ../Frameworks/Python.framework/Versions/3.9/bin/2to3
lrwxr-xr-x  1 ibc  admin    56B Aug 30 21:19 2to3-3.9@ -> ../Frameworks/Python.framework/Versions/3.9/bin/2to3-3.9
lrwxr-xr-x  1 ibc  admin    53B Aug 30 21:19 idle3@ -> ../Frameworks/Python.framework/Versions/3.9/bin/idle3
lrwxr-xr-x  1 ibc  admin    55B Aug 30 21:19 idle3.9@ -> ../Frameworks/Python.framework/Versions/3.9/bin/idle3.9
-rwxr-xr-x  1 ibc  wheel   244B Oct 18 19:40 pip3*
-rwxr-xr-x  1 ibc  wheel   244B Oct 18 19:40 pip3.9*
lrwxr-xr-x  1 ibc  admin    54B Aug 30 21:19 pydoc3@ -> ../Frameworks/Python.framework/Versions/3.9/bin/pydoc3
lrwxr-xr-x  1 ibc  admin    56B Aug 30 21:19 pydoc3.9@ -> ../Frameworks/Python.framework/Versions/3.9/bin/pydoc3.9
lrwxr-xr-x  1 ibc  admin    55B Aug 30 21:19 python3@ -> ../Frameworks/Python.framework/Versions/3.9/bin/python3
lrwxr-xr-x  1 ibc  admin    62B Aug 30 21:19 python3-config@ -> ../Frameworks/Python.framework/Versions/3.9/bin/python3-config
lrwxr-xr-x  1 ibc  admin    57B Aug 30 21:19 python3.9@ -> ../Frameworks/Python.framework/Versions/3.9/bin/python3.9
lrwxr-xr-x  1 ibc  admin    64B Aug 30 21:19 python3.9-config@ -> ../Frameworks/Python.framework/Versions/3.9/bin/python3.9-config
-rwxr-xr-x  1 ibc  wheel   231B Oct 18 19:40 wheel3*
```

Running `make clean-all`:

```
$ make clean-all
/Users/ibc/src/v3-mediasoup/worker/out/pip/bin/meson subprojects purge --include-cache --confirm
make: /Users/ibc/src/v3-mediasoup/worker/out/pip/bin/meson: No such file or directory
make: *** [clean-subprojects] Error 1
```

The fact that a task such as `make clean-all` depends on python worries me a bit for things like this.

Anyway, current status: I don't know how to solve this. A proper `make clean-all` would probably fix this, but I cannot run it.

**Comment by ibc** [comment]
Confirmed that `rm -rf worker/out/` fixes the issue. The problem is that `make clean-all` depends on `clean-subprojects` task which depends on `meson-ninja` task which invokes `$(PYTHON)`.

**Comment by nazar-pc** [comment]
Yeah, this is an interesting case, you could also do `make clean-pip` designed just for fixing such cases.

I think we could just do `|| true` for subprojects cleanup, but I'm not sure this is the right strategy since it will silently leave things broken. I feel like we need to test if Meson is working and reinstall it if that is not the case.

Do you think `make clean-pip` is sufficient?

**Comment by ibc** [comment]
My basic question is: why couldn't "make clean-all" just delete some folders and files and that's all? Why does it need to run meson/python commands?

**Comment by nazar-pc** [comment]
`subprojects` directory contains both dependencies that we specify as well as downloaded and extracted dependencies in the process of Meson operation

In order to properly clean up just those downloaded stuff, Meson is needed. Otherwise it will be a bit painful to maintain as we update dependencies.

**Comment by ibc** [comment]
I'd like to know what is needed in subprojects folder (what must be deleted) in order to reset it to its initial state. I mean, everything that is gitignored in that folder should be deleted and that should make things work without requiring any meson command, do I miss something?

**Comment by nazar-pc** [comment]
In `.gitignore` we ignore everything and then un-ignore a few things that we care about. With deletion we need the opposite operation and I wasn't brave enough to write it in Makefile's syntax.

**Comment by ibc** [comment]
Fair enough. So we need to document in Building.md what "make clean-pip" does. 

Can you explain it, please?

**Comment by nazar-pc** [comment]
OK, I will later.

**Comment by nazar-pc** [comment]
Hm, actually it is already in there: https://github.com/versatica/mediasoup/blob/v3/doc/Building.md#make-clean-pip

**Comment by ibc** [comment]
Sorry I missed it. This happens when I check things in mobile.

I'll close this issue since it's a rare corner case and there is a way to solve it already.

But just a question, and sorry if already answered: why don't we call "clean-pip" in "clean-all"?

**Comment by nazar-pc** [comment]
`clean-all` restores everything to the state as if no commands were run at all.

So it will delete not only `out/pip` and `out/Release`, but also the whole `out` directory instead. Since `out` is deleted, there is not need to delete nested directories manually before that. But since Meson downloads dependencies into `subprojects` directory for some reason and need to be cleaned too, `clean-subprojects` is a dependency of `clean-all` and thus requires things that got broken once your Python was updated.

**Comment by ibc** [comment]
Clear. Thanks.
