### ISSUE TITLE
MEDIASOUP_WORKER_BIN still requires Make and Python in v3.9

### ISSUE THREAD

**Issue by j1elo** [versatica/mediasoup#694]
### Your environment

- Operating system: Debian 10 Buster (Docker)
- Node version: 16
- npm version: 8
- gcc/clang version: N/A
- mediasoup version: 3.9.0
- mediasoup-client version: N/A

### Issue description

Commit https://github.com/versatica/mediasoup/commit/b447f7bc568168cdc4a96ceee7d607be624daf3f#diff-0e4b0cf2dfea5eb3fd7fcefa330bbcbe8ec35f53426f00d14f34a94281ed7a2aL123-R135 broke the ability of using `MEDIASOUP_WORKER_BIN` to preclude having to install build tools.

**Before the change**, setting `MEDIASOUP_WORKER_BIN=/path/to/mediasoup-worker` would result in the ability to simply run `npm install` in a clean minimal Debian system (tested with Docker, but probably a "real" setup would be similar), where none of the tools used by the build system are installed. This made sense because the usage of `MEDIASOUP_WORKER_BIN` meant that no build-system related operations needed to be done, only exclusively NPM related actions (install JS dependencies).

**After the change**, it is impossible to run `MEDIASOUP_WORKER_BIN=/path/to/mediasoup-worker npm install` without first having to install *Make* or *Python* (including pip!), which won't then really be used, given that the mediasoup binary is already provided somewhere else.

**Proposed solution**: Evaluate the possibility to restore all the `'postinstall'` actions to be inside an `if (!process.env.MEDIASOUP_WORKER_BIN)`, as it was before the mentioned change.

**Comment by nazar-pc** [comment]
Oh, you are right. Can you submit a PR with a fix?

**Comment by j1elo** [comment]
Yeah, if it's only that... but I said "evaluate" to get some opinions on that: should the `execute(${MAKE} -C worker);` be moved back to `postinstall`? or it is wanted to keep a separate `worker:build` stage?

**Comment by nazar-pc** [comment]
`if (!process.env.MEDIASOUP_WORKER_BIN)` should just be moved to `postinstall` instead of `worker:build`. `postinstall` was updated to make sure you don't keep a bunch of build time-only stuff in the `node_modules` all the time (which is hundreds of megabytes).

Also if you are using a container, you'd typically have a multi-stage build, so the final image doesn't have to have Make or Python even, just Node.js (and `MEDIASOUP_WORKER_BIN` is not required either, you just copy `node_modules` from the previous step).

**Comment by j1elo** [comment]
> `if (!process.env.MEDIASOUP_WORKER_BIN)` should just be moved to `postinstall` instead of `worker:build`

Got it!

> Also if you are using a container, you'd typically have a multi-stage build, so the final image doesn't have to have Make or Python even, just Node.js (and `MEDIASOUP_WORKER_BIN` is not required either, you just copy `node_modules` from the previous step).

Actually, I have a temporary build stage 1 and a final stage 2. On **Stage 1** all build dependencies are installed, a usual `npm ci` is issued, npm does its thing installing everything, and the mediasoup worker binary is compiled.

**Stage 2** is similar but more optimized: env var `NODE_ENV="production"` is set, only the mediasoup binary is copied from stage 1, `MEDIASOUP_WORKER_BIN` is set, and npm is told to only install the runtime dependencies, with `npm ci --omit=dev`.

It's this last step where the issues appeared, because both Python PIP and Make need to be installed. But I'll open a PR with the change you suggested, so it becomes possible again to follow this workflow.

**Comment by nazar-pc** [comment]
> Stage 2 is similar but more optimized

You probably want to do `npm prune --production` at the end of Stage 1 instead, might be faster and you wouldn't need to use `MEDIASOUP_WORKER_BIN` at all.

**Comment by j1elo** [comment]
I'm just following the good practice principle of starting from the smallest base and adding only the strictly required pieces to make the application work.

Running some installation and then the opposite to uninstall unneeded pieces might end up with a similar result, but it's more convoluted and possibly not better. Note that with `npm prune --production` we'd still be left with a system where Python and all build tools have been installed, so those would need to be pruned too... it's just easier and safer to start from a clean baseline and add whatever is really needed, and nothing more.

**Comment by nazar-pc** [comment]
`npm prune --production` was designed specifically for the use case you have. You need to run it at the end of the first stage, you just copy `node_modules` and `dist` into second stage that is based on clean Node.js image. No Python needed.

**Comment by j1elo** [comment]
Oh I see!!! You were just talking about removing the need to repeat the NPM installation process of production-only dependencies in Stage 2

Yeah that's a very good improvement. Everyday we learn something new, thanks for pointing that out! I'll delve in the "prune" command docs.

**Comment by ibc** [comment]
So is this ready to merge?

**Comment by nazar-pc** [comment]
As far as I'm concerned yes
