### ISSUE TITLE
NMAKE :  U1052: file 'worker' not found in mediasoup@3.9

### ISSUE THREAD

**Issue by developer-ind** [versatica/mediasoup#696]
### Your environment

- Operating system: Windows 10
- Node version: 14.17.6
- npm version: 6.14.15
- mediasoup version: 3.9

### Issue description
I have follow the mediasoup installation instructions but I am getting the below errors: 
> node npm-scripts.js postinstall

npm-scripts.js [INFO] running task "postinstall"
npm-scripts.js [INFO] executing command: node npm-scripts.js worker:build
npm-scripts.js [INFO] running task "worker:build"
npm-scripts.js [INFO] executing command: make -C worker
NMAKE :  U1052: file 'worker' not found
Stop.
npm WARN test_me@1.0.0 No description
npm WARN test_me@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mediasoup@3.9.0 postinstall: `node npm-scripts.js postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mediasoup@3.9.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ramij\AppData\Roaming\npm-cache\_logs\2021-10-28T06_37_45_582Z-debug.log

Can someone help me out?

**Comment by nazar-pc** [comment]
Documentation clearly says you need GNU Make, not Nmake, which is a different thing.
