### ISSUE TITLE
Emit Worker `died` event before Routers `workerclosed` ones

### ISSUE THREAD

**Issue by piranna** [versatica/mediasoup#698]
At https://github.com/versatica/mediasoup/blob/053c2e08c6b7cb1880ce390ad58308d9fdcbf6dc/node/src/Worker.ts#L597-L607 the Worker `died` event is emitted before Worker `close` event, but it's emitted after the Routers `close` events. Being "died" the event reason that makes the Worker to close, it should be emitted before the `close` event of the Routers, so they can also get the "why" before doing the closing, allowing to process it before the close, lefting that one just only for clean-up tasks. This is similar to what happens with Producer `close` event, that's the one dispatching Consumer `producerclose` and `close` events:

https://github.com/versatica/mediasoup/blob/053c2e08c6b7cb1880ce390ad58308d9fdcbf6dc/node/src/Consumer.ts#L585-L603

Fix is just a matter of move `this.safeEmit('died', error);` line before the loop, nothing else. This way flow would be the same as Producer close: Worker `died` -> Routers `close` -> Worker definitely `close`.

As a side note, I don't know if also it would make sense to have a Router `workerdied` event the same that it exists a `transportclosed` one, but that's not needed for this issue, and if so it can be discussed in another new one.

**Comment by ibc** [comment]
Solved in 16683acbb18f194a54a3656c11d758a2a5948ef5
