### ISSUE TITLE
Allow access to Consumer's transportId

### ISSUE THREAD

**Issue by j1elo** [versatica/mediasoup#700]
## Feature Request

Given that the Consumer's `transportId` is already [right there](https://github.com/versatica/mediasoup/blob/053c2e08c6b7cb1880ce390ad58308d9fdcbf6dc/node/src/Consumer.ts#L165), I'd like to propose that applications can save having to keep an extra dictionary of <Consumer, Transport>, and instead be able to simply read the Transport ID from the Consumer itself. This is also safer and less error prone, having a single "source of truth".

My request is for Consumers, but I guess the same could be said about Producers.

The getter code seems that would be trivial to add, just like there already is a `Consumer.producerId()` getter, it would be a `Consumer.transportId()` getter.

If this idea seems reasonable and gets an OK, I can file a PR with the change.

**Comment by ibc** [comment]
I am against this kind of getters. I've done crazy things with mediasoup and never needed them. The app is supposed to wrap mediasoup objects somewhere else. If Consumer exposes a transportId and the user app needs to read it, it means that the app doesn't know  in which transport the consumer was created, and it also means that the user app should maintain a map of <transportId, Transport> which of course mediasoup does not provide with. 

So this PR may just make things a bit "easier" for a specific mediasoup usage but still needs the cooperation of the user app to give sense to such a consumer.transportId. If we accept this PR we are promoting bad mediasoup usages ("I have called `consumer = transport.consume()` but later I don't know in which transport I created that consumer") and we are gonna see feature requests asking for `router.getTransports()` or `transport.getProducers()`. This means that the app is not properly managing mediasoup objects and needs to rely on mediasoup helpers/getters to make the app logic work.

Definitely I don't want to open this door for good reasons. It's not the first time I get this request and in all cases the requester was able to redesign his app to properly manage mediasoup objects without requiring those things in mediasoup API.

**Comment by j1elo** [comment]
> in all cases the requester was able to redesign his app to properly manage mediasoup objects without requiring those things in mediasoup API

Yeah, the way to work around this for everybody I guess is to keep multitude of maps that allow to match between ids and instances. Adding to the overhead of cleaning it up everywhere, which yeah is not terribly horrible, but adds a lot of noise where DRY would be preferable.

You're spot on: my app is making Transports on one side, then passing them to an isolated component that makes Consumers. This latter one doesn't keep track, nor cares, about which Transport the Consumer was made from. It wouldn't seem necessary to maintain such *duplicated* relationship, being that the Consumer itself already has the knowledge of which Transport it belongs to.

But I get it, it just doesn't fit the design view of the API. Nothing much to add, except that thanks for the explanation!

**Comment by ibc** [comment]
👍

**Comment by piranna** [comment]
Yeah, the MIT vs Berkeley APIs design philosofy schools: easy to use by the users, or low level minimalism :-)
