### ISSUE TITLE
Replace Makefile with Python script

### ISSUE THREAD

**Issue by nazar-pc** [versatica/mediasoup#701]
I see people struggle on Windows with following installation instructions, it would be possible to simplify things for everyone if instead of using GNU Make and its Makefile (and have to deal with other Make implementations on WIndows and various other platforms) we used a Python script, in that case things would "just work" as soon as people have MSVS and Python installed, no extra steps would be required.

Pros:
* no need to install MinGW/MSYS and edit `Path` for them on Windows
* no need to manually configure MSVS environment before doing `npm i` on Windows
* no dependency and confusion with Make on any platform (GMake, NMake, etc.)
* more flexibility is what we can write there with sane syntax

Cons:
* Script will definitely be much longer than current Makefile as Makefile is specifically designed to execute a series of commands

This primarily affects Windows, but might potentially benefit other platforms too.

**Comment by ibc** [comment]
`Makefile` has a dependency mechanism by which a task depends on others, but those are just executed if needed. For example:

```make
libmediasoup-worker: setup flatc
```

"setup" and "flatc" dependency tasks will just run if they didn't run before, and somehow `make` knows that. 

The question is: how to do that with a Python or whatever script?

**Comment by nazar-pc** [comment]
We'd have to track the state somehow, not very difficult if you ask me

**Comment by ibc** [comment]
I'm pretty sure it's difficult. How would you check if some .cpp file has changed (or a new one has been added) and if so compile it and relink etc?

**Comment by nazar-pc** [comment]
That is an interesting feature of Make, but unnecessary for our use case

**Comment by ibc** [comment]
How is that unnecessary for our use case? That use case is 58% of my whole life.

**Comment by ibc** [comment]
Some stuff I've found, but doing a proper review of them is hard:

- https://github.com/casey/just
- https://www.pyinvoke.org
- https://pydoit.org

**Comment by nazar-pc** [comment]
I mean we don't use it to compile things. Compilation is taken care of by Meson, we just use it to run other apps.

**Comment by ibc** [comment]
> I mean we don't use it to compile things. Compilation is taken care of by Meson, we just use it to run other apps.

Yes, but if we blindly invoke the Meson command that compiles the worker immediately after having called it, it will recompile everything.

Ah no, it won't.

**Comment by ibc** [comment]
So I'm reading the docs of https://github.com/casey/just. Problem I see is that it's not a "pure Python library" that can be installed using `pip` (which we already depend on in `Makefile`) but instead a per OS package is needed (or manual installation using `wget` etc).

So I assume this is not a valid choice for us, right?

**Comment by ibc** [comment]
HELLO!!!
I'm doing this:

`/Users/ibc/tmp/invoke-testing/tasks.py`:
```python
import sys;
import os;
import inspect;
from pip._internal import main as pipmain;
from invoke import task;


PYTHON = os.getenv('PYTHON') or sys.executable;
ROOT_DIR = os.path.dirname(os.path.abspath(
    inspect.getframeinfo(inspect.currentframe()).filename
));
MEDIASOUP_OUT_DIR = os.getenv('MEDIASOUP_OUT_DIR') or '{}/out'.format(ROOT_DIR);
MEDIASOUP_BUILDTYPE = os.getenv('MEDIASOUP_BUILDTYPE') or 'Release';
PIP_DIR = '{}/pip'.format(MEDIASOUP_OUT_DIR);
MESON_VERSION = os.getenv('MESON_VERSION') or '1.2.1';
# Let's use a specific version of ninja to avoid buggy version 1.11.1:
# https://mediasoup.discourse.group/t/partly-solved-could-not-detect-ninja-v1-8-2-or-newer/
# https://github.com/ninja-build/ninja/issues/2211
# https://github.com/ninja-build/ninja/issues/2212
NINJA_VERSION = os.getenv('NINJA_VERSION') or '1.10.2.4';

print('PYTHON:', PYTHON);
print('ROOT_DIR:', ROOT_DIR);
print('MEDIASOUP_OUT_DIR:', MEDIASOUP_OUT_DIR);
print('MEDIASOUP_BUILDTYPE:', MEDIASOUP_BUILDTYPE);
print('PIP_DIR:', PIP_DIR);


@task
def meson_ninja(ctx):
    """
    Installs meson and ninja (also updates Python pip and setuptools packages)
    """

    if os.path.isdir(PIP_DIR) :
        return;

    # Updated pip and setuptools are needed for meson.
    # `--system` is not present everywhere and is only needed as workaround for
    # Debian-specific issue (copied from https://github.com/gluster/gstatus/pull/33),
    # fallback to command without `--system` if the first one fails.
    try:
        ctx.run(
            f'{PYTHON} -m pip install --system --target={PIP_DIR} pip setuptools',
            echo=True,
            hide=True
        );
    except:
        ctx.run(
            f'{PYTHON} -m pip install --target={PIP_DIR} pip setuptools',
            echo=True
        );

    # Workaround for NixOS and Guix that don't work with pre-built binaries, see:
    # https://github.com/NixOS/nixpkgs/issues/142383.
    PIP_BUILD_BINARIES = '';

    if os.path.isfile('/etc/NIXOS') or os.path.isdir('/etc/guix') :
        PIP_BUILD_BINARIES = '--no-binary :all:';

    # Install meson and ninja using pip into our custom location, so we don't
    # depend on system-wide installation.
    ctx.run(
        f'{PYTHON} -m pip install --upgrade --target={PIP_DIR} {PIP_BUILD_BINARIES} meson=={MESON_VERSION} ninja=={NINJA_VERSION}',
        echo=True
    );


@task(pre=[meson_ninja])
def foo(ctx):
    """
    Foo things (until I figure out how to define a default task)
    """
    print('foo!');
```

```
$ cd /Users/ibc/tmp/invoke-testing
$ invoke foo
PYTHON: /usr/local/opt/python@3.11/bin/python3.11
ROOT_DIR: /Users/ibc/tmp/invoke-testing
MEDIASOUP_OUT_DIR: /Users/ibc/tmp/invoke-testing/out
MEDIASOUP_BUILDTYPE: Release
PIP_DIR: /Users/ibc/tmp/invoke-testing/out/pip
/usr/local/opt/python@3.11/bin/python3.11 -m pip install --target=/Users/ibc/tmp/invoke-testing/out/pip pip setuptools
Collecting pip
  Using cached pip-23.3.1-py3-none-any.whl.metadata (3.5 kB)
Collecting setuptools
  Using cached setuptools-69.0.2-py3-none-any.whl.metadata (6.3 kB)
Using cached pip-23.3.1-py3-none-any.whl (2.1 MB)
Using cached setuptools-69.0.2-py3-none-any.whl (819 kB)
Installing collected packages: setuptools, pip
Successfully installed pip-23.3.1 setuptools-69.0.2
/usr/local/opt/python@3.11/bin/python3.11 -m pip install --upgrade --target=/Users/ibc/tmp/invoke-testing/out/pip  meson==1.2.1 ninja==1.10.2.4
Collecting meson==1.2.1
  Using cached meson-1.2.1-py3-none-any.whl.metadata (1.7 kB)
Collecting ninja==1.10.2.4
  Using cached ninja-1.10.2.4-py2.py3-none-macosx_10_9_universal2.macosx_10_9_x86_64.macosx_11_0_arm64.macosx_11_0_universal2.whl (231 kB)
Using cached meson-1.2.1-py3-none-any.whl (962 kB)
Installing collected packages: ninja, meson
Successfully installed meson-1.2.1 ninja-1.10.2.4
foo!
```

😌😌😌
