### ISSUE TITLE
Private properties are not properly being transpiled

### ISSUE THREAD

**Issue by piranna** [versatica/mediasoup#704]
At https://github.com/versatica/mediasoup/blob/16683acbb18f194a54a3656c11d758a2a5948ef5/node/tsconfig.json#L6 it's being set to use ES2020 target and library (with target set, library is redundant, by the way), but transpiled code is still using WeakMaps instead of proper EcmaScript private properties. Can this be reviewed?

As a side note: why is being transpiled code included in repo, instead of being gitignored and generated on npm `prepare` script?

**Comment by ibc** [comment]
> with target set, library is redundant, by the way

How is this? In `lib` you can add things such as "dom" which definitely changes the set of available APIs in TypeScript, and AFAIK this is not related at all to the output format (`target` field).

BTW fixed here: https://github.com/versatica/mediasoup/commit/a9a0255ff9f9996aebe51d66d0a204c926502dbe

**Comment by ibc** [comment]
> As a side note: why is being transpiled code included in repo, instead of being gitignored and generated on npm prepare script?

Because that would require `typescript` being part of `dependencies` rather than `devDependencies`. This is an endless topic. I do know that there are different opinions and different ways to go. No perfect solution. We just took this decision, which is as good or bad as others.

**Comment by piranna** [comment]
> How is this? In `lib` you can add things such as "dom" which definitely changes the set of available APIs in TypeScript, and AFAIK this is not related at all to the output format (`target` field).

At [Typescript documentation](https://www.typescriptlang.org/tsconfig#target):

> Changing target also changes the default value of lib. You may “mix and match” target and lib settings as desired, but you could just set target for convenience.

So if setting only `"target": "es2020"`, it will set `"lib": "es2020"` implicitly. For Node.js this is just enough to support everything from Node.js 12 up to now. Explicit usage of `lib` field is only needed for fine tuning what Javascript APIs to support or do transpilation to.


> BTW fixed here: [a9a0255](https://github.com/versatica/mediasoup/commit/a9a0255ff9f9996aebe51d66d0a204c926502dbe)

Ok, thanks, that was not being effective before.


> Because that would require `typescript` being part of `dependencies` rather than `devDependencies`. This is an endless topic. I do know that there are different opinions and different ways to go. No perfect solution. We just took this decision, which is as good or bad as others.

When using the [prepare](https://docs.npmjs.com/cli/v7/using-npm/scripts#prepare-and-prepublish) script, it's only executed when downloaded as a git dependency, or when packaging and publishing to `npm` registry, so there's no need to have `typescript` as a dependency instead of devDependency, since published code is the already transpiled one. You can take a look at the packages I have put in the [mediasoup-helpers](https://github.com/versatica/mediasoup/issues/705) issue to have an example of how they looks and work.

**Comment by ibc** [comment]
> When using the prepare script, it's only executed when downloaded as a git dependency

So the parent project cannot run `npm install --production` because typescript is needed to transpile mediasoup (since it's a GIT dependency rather than a NPM dependency).

As I said, I understand there are different approaches here, but I'm pretty sure that including JS transpiled code in the repo is not that bad and there is no drawback about it.

**Comment by piranna** [comment]
> So the parent project cannot run `npm install --production` because typescript is needed to transpile mediasoup (since it's a GIT dependency rather than a NPM dependency).

I have not check that use case, but yes, if it's being used as a git dependency, then it would fail. In any case, according to how `npm` is designed, it should not be used as a git dependency in production, but instead packaged and published somewhere, also a simple HTTP server or a `file://` URL is enough for that.


> As I said, I understand there are different approaches here, but I'm pretty sure that including JS transpiled code in the repo is not that bad and there is no drawback about it.

No, it doesn't have any special hurt besides having published generated / transpiled code instead just only sources, otherwise is fine.
