### ISSUE TITLE
[macOS] v3.9+ failing to compile abseil-cpp-20210324.2

### ISSUE THREAD

**Issue by simpleshadow** [versatica/mediasoup#706]
## Bug Report

Receive the following error upon `yarn add mediasoup`:

```
FAILED: subprojects/abseil-cpp-20210324.2/libabsl_base.a.p/absl_base_internal_cycleclock.cc.o 
c++ -Isubprojects/abseil-cpp-20210324.2/libabsl_base.a.p -Isubprojects/abseil-cpp-20210324.2 -I../../subprojects/abseil-cpp-20210324.2 -fcolor-diagnostics -DNDEBUG -std=c++11 -O3 -Wno-sign-compare -march=armv8-a+crypto -MD -MQ subprojects/abseil-cpp-20210324.2/libabsl_base.a.p/absl_base_internal_cycleclock.cc.o -MF subprojects/abseil-cpp-20210324.2/libabsl_base.a.p/absl_base_internal_cycleclock.cc.o.d -o subprojects/abseil-cpp-20210324.2/libabsl_base.a.p/absl_base_internal_cycleclock.cc.o -c ../../subprojects/abseil-cpp-20210324.2/absl/base/internal/cycleclock.cc
error: unknown target CPU 'armv8-a+crypto'
note: valid target CPU values are: nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cascadelake, cooperlake, cannonlake, icelake-client, icelake-server, tigerlake, sapphirerapids, alderlake, knl, knm, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, znver2, znver3, x86-64, x86-64-v2, x86-64-v3, x86-64-v4
```
v3.8.4 installs so I'm guessing something changed from the v3.7.1 release that added M1 support (#548)?

### Your environment

- Operating system: macOS Monterey (Macbook Air M1, 2020)
- Node version: 17.0.1
- npm version: 8.1.1
- gcc/clang version: clang-1300.0.29.3 (Apple)
- mediasoup version: 3.9+

**Comment by nazar-pc** [comment]
According to https://github.com/abseil/abseil-cpp/issues/970 you might actually try to cross-compile it. Make sure your compiler is for ARM. People had other issues of a similar nature the other way around: https://mediasoup.discourse.group/t/partly-solved-could-not-detect-ninja-v1-8-2-or-newer/3464

**Comment by nazar-pc** [comment]
Yeah, looks like your compiler is x86-64, you need ARM compiler instead on M1 machine.

**Comment by simpleshadow** [comment]
roger! thanks @nazar-pc, will have a look.

**Comment by olegmelnik** [comment]
@simpleshadow Did you resolve your issue? I have the same problem

**Comment by satoren** [comment]
I have the same problem too with `cargo test` at the latest v3 branch.

**Comment by nazar-pc** [comment]
It doesn't help that you have the same issue.

Please do your research and feel free to contribute to documentation on how to fix this unfortunate quirk of Apple's AMD64->AArch64 transition process.

**Comment by satoren** [comment]
Hmm, I don't know why, but in my environment, c files seem to compile to arm64 and c++ files to x86_64.

```
deps/libwebrtc/liblibwebrtc.a.p/libwebrtc_rtc_base_rate_statistics.cc.o:    Mach-O 64-bit object x86_64
subprojects/openssl-1.1.1l/libcrypto.a.p/crypto_aes_aes_core.c.o:    Mach-O 64-bit object arm64 :
```

When executing manually complete command in generated compile_commands.json, that output to arm64 :confused:

**Comment by ibc** [comment]
@satoren you are not even using mediasoup 3.9.X which has a completely new build system so your report is not useful at all.

**Comment by satoren** [comment]
@ibc 
The new build system is `meson`, right? It used. And the same problem also occurred when using an npm package(`"mediasoup": "3.9.2"`).

**Comment by satoren** [comment]
I discovered that the ninja binary is x86_64.
That downloaded from [pip](https://www.wheelodex.org/projects/ninja/wheels/ninja-1.10.2.2-py2.py3-none-macosx_10_9_universal2.macosx_10_9_x86_64.macosx_11_0_arm64.macosx_11_0_universal2.whl/) by [Makefile](https://github.com/versatica/mediasoup/blob/v3/worker/Makefile#L58) 

The build was successful when replaced ninja binary to aarch64(installed from brew) instead of x86_64.
I don't know how to fix this, but it's probably not just my environment.

**Comment by ibc** [comment]
@nazar-pc is this something we can fix in Makefile by checking current arch and forcing download of proper ninja version?

**Comment by nazar-pc** [comment]
I need to research, looks like PIP bug to me, but I'll investigate. Let's reopen this for now as I believe this is something we can act upon.

**Comment by satoren** [comment]
I think it's the PIP ninja package bug too. There is only one version for mac and the name includes universal but just only has x86_64.

**Comment by ibc** [comment]
I wonder if we can override ninja in case the user set a NINJA environment variable, so at least we can provide with a workaround and document it in the Installation section.

**Comment by nazar-pc** [comment]
I think we can just force it to build Ninja from source like for some other obscure Linux distros.

**Comment by ibc** [comment]
> I think we can just force it to build Ninja from source like for some other obscure Linux distros.

I don't see any important backwards if we do that, right?

**Comment by nazar-pc** [comment]
Should be fine, just installation will take longer on that platform. Still worth reporting to ninja or PIP developers.
I'll look into it when I have some free time, very busy right now.

**Comment by satoren** [comment]
I added --no-binary=ninja to the pip install command and try to build it. However, it seems that cmake is required to build ninja. When cmake install, build is a success. This is for users, the only difference seems to be whether to install ninja or cmake prerequired.

So I tried replaced to
```Makefile
	$(PYTHON) -m pip install --upgrade --target=$(PIP_DIR) $(PIP_BUILD_BINARIES) meson cmake 
	PATH=$(PIP_DIR)/bin:${PATH}; cmake --help
	PATH=$(PIP_DIR)/bin:${PATH}; $(PYTHON) -m pip install --upgrade --target=$(PIP_DIR) --no-binary=ninja $(PIP_BUILD_BINARIES) ninja
```

`PATH=$(PIP_DIR)/bin:${PATH}; cmake -version` is worked, but build of ninja get the error below.
```
Building wheels for collected packages: ninja
  Building wheel for ninja (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /Applications/Xcode.app/Contents/Developer/usr/bin/python3 /Users/masataka/projects/mediasoup/worker/out/pip/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/gz/b25ct8g14tvg1h5yp0g0t31h0000gn/T/tmp8ezz1sxh
       cwd: /private/var/folders/gz/b25ct8g14tvg1h5yp0g0t31h0000gn/T/pip-install-74qzsecx/ninja_870e781ae6074371854545825c900c92
  Complete output (13 lines):
  Traceback (most recent call last):
    File "/Users/masataka/projects/mediasoup/worker/out/pip/bin/cmake", line 5, in <module>
      from cmake import cmake
  ModuleNotFoundError: No module named 'cmake'
    File "/private/var/folders/gz/b25ct8g14tvg1h5yp0g0t31h0000gn/T/pip-build-env-romsll86/overlay/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 564, in setup
      cmkr = cmaker.CMaker(cmake_executable)
    File "/private/var/folders/gz/b25ct8g14tvg1h5yp0g0t31h0000gn/T/pip-build-env-romsll86/overlay/lib/python3.8/site-packages/skbuild/cmaker.py", line 95, in __init__
      self.cmake_version = get_cmake_version(self.cmake_executable)
    File "/private/var/folders/gz/b25ct8g14tvg1h5yp0g0t31h0000gn/T/pip-build-env-romsll86/overlay/lib/python3.8/site-packages/skbuild/cmaker.py", line 81, in get_cmake_version
      raise SKBuildError(
  Traceback (most recent call last):
  
  Problem with the CMake installation, aborting build. CMake executable is cmake
  ----------------------------------------
  ERROR: Failed building wheel for ninja
```

**Comment by nazar-pc** [comment]
Appears to be an upstream regression, please follow https://github.com/scikit-build/ninja-python-distributions/issues/88 for updates. Once that is fixed it should start working in mediasoup automatically.

**Comment by satoren** [comment]
Thank you for your support. Now I just have to wait for the release of the rust version. 😉

**Comment by nazar-pc** [comment]
Should work now, please test

**Comment by satoren** [comment]
It worked! thanks.

**Comment by olegmelnik** [comment]
@nazar-pc I still can't upgrade to 3.9.2

**Comment by nazar-pc** [comment]
@olegmelnik, no idea what issue you have exactly, please create discussion on the forum.
