### ISSUE TITLE
Rust videoroom demo not working

### ISSUE THREAD

**Issue by lbennett-stacki** [versatica/mediasoup#710]
### Your environment

- Operating system: Windows 11 - WSL2 debian 11
- Node version:  16.11.1
- npm version: 8.1.0
- gcc/clang version: 10.2.1
- mediasoup version: 0.8.5 rust crate
- mediasoup-client version: 3.6.43

### Issue description

Hello, I'm happy to move this to discourse if you don't want to track demo bugs here.

I was really happy to see a rust crate for mediasoup. Unfortunately the demo seems to not work perfectly, despite the equivalent node demos working.
I would love to help debug and fix this issue so others that come across with a preference for the rust crate don't run into the same problems.

It seems general signalling is working just fine. I suspect we have a simple configuration issue here, potentially around DTLS?

As stated, participants can join rooms, set up producers and consumers that all make sense. However, the stream never seems to actually start processing.

This is the result of running the demo (please ignore the simple styling changes I have made):

![Screenshot 2021-11-14 114907](https://user-images.githubusercontent.com/5678671/141679537-c08a2791-0eb2-41e2-a794-4e11b46f4b36.png)

The most suspicious/smelly insight I've found is that dtlsState of the transport is stuck to `new`, never even initiating a connection it seems.

![Screenshot 2021-11-14 115348](https://user-images.githubusercontent.com/5678671/141679726-5e4800d4-03d8-4396-81a2-709501f9fe30.png)

I swapped out `dtls_files` to point to local self-signed certs instead of the auto-generated certs but still not helpful.

Init message:

![Screenshot 2021-11-14 115929](https://user-images.githubusercontent.com/5678671/141679895-ecf93414-7bc1-4ed2-b9b3-49841644669f.png)

Here we have the logs from the rust server:

```
Room 2d47808d-6201-4c2f-aee1-9fd7b4582c47 closed
Room 2d47808d-6201-4c2f-aee1-9fd7b4582c47 created
[participant_id 488d4303-1e3c-49a4-b3b0-ecb283bb1ca8] WebSocket connection created
[participant_id 488d4303-1e3c-49a4-b3b0-ecb283bb1ca8] Producer transport connected
[participant_id 488d4303-1e3c-49a4-b3b0-ecb283bb1ca8] Audio producer created: cb046d23-5879-467b-8e58-4256df96682b
[participant_id 488d4303-1e3c-49a4-b3b0-ecb283bb1ca8] Video producer created: 1e43bda2-f5a8-48a4-9c11-d10af949b75e

[participant_id 8826e320-b6b2-4604-83f4-8c2cbeff5560] WebSocket connection created
[participant_id 8826e320-b6b2-4604-83f4-8c2cbeff5560] Producer transport connected
[participant_id 8826e320-b6b2-4604-83f4-8c2cbeff5560] Audio producer created: 8e912d08-e08f-4943-aac5-eec90acb3c0d
[participant_id 488d4303-1e3c-49a4-b3b0-ecb283bb1ca8] Audio consumer created: a18816f0-5291-4f68-aed2-9caa510b596d
[participant_id 488d4303-1e3c-49a4-b3b0-ecb283bb1ca8] Consumer transport connected
[participant_id 488d4303-1e3c-49a4-b3b0-ecb283bb1ca8] Successfully resumed Audio consumer a18816f0-5291-4f68-aed2-9caa510b596d
[participant_id 8826e320-b6b2-4604-83f4-8c2cbeff5560] Video producer created: 5fba7661-8c97-4518-9239-cd6900103a4f
[participant_id 8826e320-b6b2-4604-83f4-8c2cbeff5560] Audio consumer created: 05d3c10f-6a0d-4c11-b052-a748e29b7064
[participant_id 488d4303-1e3c-49a4-b3b0-ecb283bb1ca8] Video consumer created: aa371e28-f461-4377-9f6c-bda8368a05ba
[participant_id 8826e320-b6b2-4604-83f4-8c2cbeff5560] Consumer transport connected
[participant_id 8826e320-b6b2-4604-83f4-8c2cbeff5560] Successfully resumed Audio consumer 05d3c10f-6a0d-4c11-b052-a748e29b7064
[participant_id 488d4303-1e3c-49a4-b3b0-ecb283bb1ca8] Successfully resumed Video consumer aa371e28-f461-4377-9f6c-bda8368a05ba
[participant_id 8826e320-b6b2-4604-83f4-8c2cbeff5560] Video consumer created: dbbe7b0f-0880-4b77-bb80-ec44678a77a4
[participant_id 8826e320-b6b2-4604-83f4-8c2cbeff5560] Successfully resumed Video consumer dbbe7b0f-0880-4b77-bb80-ec44678a77a4
```

I have seen that the `WorkerSettings`  are set to have a higher debug level than this, showing dtls errors etc. Which I don't see currently, which is odd.

Hope you can help, thanks for your time and for contributing such a great project to the OSS community!

**Comment by snack-0verflow** [comment]
+1 Got the same issue, would love to use the rust version as well

**Comment by nazar-pc** [comment]
I think this is because Rust demos configure mediasoup to listen on `127.0.0.1` (more secure on development machine) and you are running it in the VM. Change that to 0.0.0.0 (and probably specify IP address of the VM WSL creates) and it should start working.

You don't need to touch/specify `dtls_files` in 99.9% when working with mediasoup.

**Comment by lbennett-stacki** [comment]
@nazar-pc Thanks for the speedy response. I also suspected it may be an issue with WSL and have tried setting the listen IP of the rust server and transport to `0.0.0.0` but it didn't work. I have also tried setting the `announced_ip` to the IP of WSL (which shouldn't matter too much as network has already been shared) but this hasn't worked.

Also I thought it would have been a problem mostly with the workers on various ports but the node project seemed to run from WSL so maybe is something else, but still related to WSL.

Thanks for confirming it's probably not tls files. I'll keep looking down the WSL networking route to see what else I can shake out of it.

**Comment by nazar-pc** [comment]
Note that by default mediasoup uses UDP, you can try to force TCP and see if that helps, maybe WSL doesn't work well with UDP. I'll close this for now as I don't think there is an issue with a demo as such. Better move this discussion to the forum.

**Comment by lbennett-stacki** [comment]
I've just come back after a long break and have found setting the right `announced_ip` to the wsl host (run`wsl hostname -I` in powershell). This didn't work right away. I then `yarn install mediasoup --latest` and... it worked. I'm not sure if this is a crazy coincidence and updating the `announced_ip` is the main factor, or if part of some npm install hook is getting things running. But I definitely tried that a couple times beforehand and it didn't work. Audio is now being consumed and I'll see what's up with the video but that's progress enough for me. After I've fixed video I'll remove all node modules just to confirm it has nothing to do with it.

Thanks again for your help

**Comment by nazar-pc** [comment]
Rust examples shouldn't need any npm or yarn commands :man_shrugging:
