### ISSUE TITLE
Use `debug.extend()` on `Logger`

### ISSUE THREAD

**Issue by piranna** [versatica/mediasoup#711]
At https://github.com/versatica/mediasoup/blob/20d11ff455d61796196f02fe2735c3d65160a31d/node/src/Logger.ts#L13-L30, `Logger` class create new `debug` instance for each one of the loggers. I propose to use instead `debug.extend()` function they have an implicit hierarchy. Logging output would be the same, so there would not be breaking changes here, and I also know that logger it's only intended for debugging purposses and not as a general puposse logging mechanishm, but doing so it would make it easier to integrate it with other systems.

**Comment by ibc** [comment]
We use stdout for debug logs and stderr for warn and error logs, so AFAIK extend() is not valid. I may be wrong. Anyway, is it that important? Basically our Logger class already manages namespaces the same way as extend() does. I don't see any benefit here.

**Comment by piranna** [comment]
I'm trying to integrate and unify all logging mechanisms in my company project, so wanted to redirect `debug` logger to `moleculer` one.

Namespaces are ok, but using `extend()` would propagate inherited `debug.log()` one instead of using always global one. This way it would be possible to set it at `mediasoup` namespace and it would propagate to all Mediasoup loggers, not conflicting with other ones that can be defined for other modules.

**Comment by piranna** [comment]
I can do a PR for that if it can help to see it clearer.

**Comment by ibc** [comment]
Sure, do the PR, but please ensure that debug logs are still sent to stdout and warn and error logs to stderr. Otherwise we cannot accept it.

**Comment by piranna** [comment]
No issues, I'll take care of that on the default functionality :-)
