### ISSUE TITLE
error install mediasoup 

### ISSUE THREAD

**Issue by linqiang69672187** [versatica/mediasoup#716]
when install server ,error
--------------------------------------

root@eastcom-OptiPlex-7070:/usr/mediasoup-demo/server# npm install
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

> bufferutil@4.0.5 install /usr/mediasoup-demo/server/node_modules/bufferutil
> node-gyp-build

> utf-8-validate@5.0.7 install /usr/mediasoup-demo/server/node_modules/utf-8-validate
> node-gyp-build

> heapdump@0.3.15 install /usr/mediasoup-demo/server/node_modules/heapdump
> node-gyp rebuild

make: 进入目录“/usr/mediasoup-demo/server/node_modules/heapdump/build”
  CXX(target) Release/obj.target/addon/src/heapdump.o
  SOLINK_MODULE(target) Release/obj.target/addon.node
  COPY Release/addon.node
make: 离开目录“/usr/mediasoup-demo/server/node_modules/heapdump/build”

> mediasoup@3.9.2 postinstall /usr/mediasoup-demo/server/node_modules/mediasoup
> node npm-scripts.js postinstall

npm-scripts.js [INFO] running task "postinstall"
npm-scripts.js [INFO] executing command: node npm-scripts.js worker:build
npm-scripts.js [INFO] running task "worker:build"
npm-scripts.js [INFO] executing command: make -C worker
make: 进入目录“/usr/mediasoup/worker”
# Updated pip and setuptools are needed for meson
# `--system` is not present everywhere and is only needed as workaround for
# Debian-specific issue (copied from
# https://github.com/gluster/gstatus/pull/33), fallback to command without
# `--system` if the first one fails.
/usr/bin/python3 -m pip install --system --target=/usr/mediasoup/worker/out/pip pip setuptools || \
        /usr/bin/python3 -m pip install --target=/usr/mediasoup/worker/out/pip pip setuptools || \
        echo "Installation failed, likely because PIP is unavailable, if you are on Debian/Ubuntu or derivative please install the python3-pip package"
/usr/bin/python3: No module named pip
/usr/bin/python3: No module named pip
Installation failed, likely because PIP is unavailable, if you are on Debian/Ubuntu or derivative please install the python3-pip package
# Install `meson` and `ninja` using `pip` into custom location, so we don't
# depend on system-wide installation.
/usr/bin/python3 -m pip install --upgrade --target=/usr/mediasoup/worker/out/pip  meson ninja
/usr/bin/python3: No module named pip
Makefile:48: recipe for target 'meson-ninja' failed
make: *** [meson-ninja] Error 1
make: 离开目录“/usr/mediasoup/worker”
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mediasoup@3.9.2 postinstall: `node npm-scripts.js postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mediasoup@3.9.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-25T08_56_03_192Z-debug.log
root@eastcom-OptiPlex-7070:/usr/mediasoup-demo/server#

**Comment by ibc** [comment]
Template deleted. Issue closed.

**Comment by nazar-pc** [comment]
> No module named pip

Please read installation instructions, there is nothing wrong with mediasoup here.
