### ISSUE TITLE
Throw exception if using `0.0.0.0` as `ip` without acompaning `announcedIp`

### ISSUE THREAD

**Issue by piranna** [versatica/mediasoup#717]
At https://mediasoup.org/documentation/v3/mediasoup/api/#TransportListenIp, documentation says

> If you use “0.0.0.0” or “::” as ip value, then you need to also provide announcedIp.

and more specifically for WebRtcEndpoint, at https://mediasoup.org/documentation/v3/mediasoup/api/#WebRtcTransportOptions it says

> Do not use “0.0.0.0” into listenIps. Values in listenIps must be specific bindable IPs in the host.
> If you use “0.0.0.0” or “::” into listenIps, then you need to also provide announcedIp in the corresponding entry in listenIps.

I've checked at source code and found that `listenIps` option is already being checked that's a string or an object at https://github.com/versatica/mediasoup/blob/20d11ff455d61796196f02fe2735c3d65160a31d/node/src/Router.ts#L358-L375 or throwing an exception, so it would be easy to check that `0.0.0.0` corner case and throw an exception about bad config too.

**Comment by ibc** [comment]
We don't want to enter into networking/routing specific stuff nor make hard assumptions about how interfaces are configured in each system. If we did this, we should do the same for IPv6 and should also do many other checks.

I think it's clear enough if we provide some guidelines in the documentation as we do.

**Comment by piranna** [comment]
> I think it's clear enough if we provide some guidelines in the documentation as we do.

Yes, but we've been busy on that two developers for two days due to this. I agree on not entering into networking/routing specific stuff, but being clearly an identified bad configuration, it should throw an exception or notify the issue someway.

**Comment by ibc** [comment]
> Yes, but we've been busy on that two developers for two days due to this

It's documented, right? :)

> I agree on not entering into networking/routing specific stuff, but being clearly an identified bad configuration

No, it's not. It probably is, but I'm not 100% sure whether in some networking setups it's valid for an endpoint to contact 0.0.0.0 directly. And I don't want to include networking checks in JavaScript.

**Comment by piranna** [comment]
> It's documented, right? :)

Yes... :-/


> No, it's not. It probably is, but I'm not 100% sure whether in some networking setups it's valid for an endpoint to contact 0.0.0.0 directly.

How can we sure about that? Where we can read or ask to about this? Never knew of any situation where a request to `0.0.0.0` is valid, all that I've read is it isn't.


> And I don't want to include networking checks in JavaScript.

That's another topic, but yes, if doing checking for this corner case, maybe it would make sense to do it in `libmediasoupclient` so it's done in all platforms, including C++. Good point on this.

**Comment by ibc** [comment]
> How can we sure about that? Where we can read or ask to about this?

That's exactly the things: I don't want to know that and I don't need to know that. I leave routing decisions to users.
