### ISSUE TITLE
cant build

### ISSUE THREAD

**Issue by chennasi** [versatica/mediasoup#732]
yright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS E:\FullWorkingProject\WorkingWEBRTC\MediaSoup\medias3\3.9.2> npm install

> mediasoup@3.9.2 postinstall
> node npm-scripts.js postinstall

npm-scripts.js [INFO] running task "postinstall"
npm-scripts.js [INFO] executing command: node npm-scripts.js worker:build
npm-scripts.js [INFO] running task "worker:build"
npm-scripts.js [INFO] executing command: make -C worker
make: Entering directory 'E:/FullWorkingProject/WorkingWEBRTC/MediaSoup/medias3/3.9.2/worker'
process_begin: CreateProcess(NULL, dirname E:/FullWorkingProject/WorkingWEBRTC/MediaSoup/medias3/3.9.2/worker/Makefile, ...) failed.
Makefile:7: pipe: No error
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
'[' is not recognized as an internal or external command,
operable program or batch file.
python -m pip install --system --target=e:/FullWorkingProject/WorkingWEBRTC/MediaSoup/medias3/3.9.2/worker/out/pip pip setuptools || \
        python -m pip install --target=e:/FullWorkingProject/WorkingWEBRTC/MediaSoup/medias3/3.9.2/worker/out/pip pip setuptools || \
        echo "Installation failed, likely because PIP is unavailable, if you are on Debian/Ubuntu or derivative please install the python3-pip package"

Usage:
  C:\Program Files\Python311\python.exe -m pip install [options] <requirement specifier> [package-index-options] ...
  C:\Program Files\Python311\python.exe -m pip install [options] -r <requirements file> [package-index-options] ...
  C:\Program Files\Python311\python.exe -m pip install [options] [-e] <vcs project url> ...
  C:\Program Files\Python311\python.exe -m pip install [options] [-e] <local project path> ...
  C:\Program Files\Python311\python.exe -m pip install [options] <archive url/path> ...

no such option: --system
Collecting pip
  Using cached pip-21.3.1-py3-none-any.whl (1.7 MB)
Collecting setuptools
  Using cached setuptools-59.5.0-py3-none-any.whl (952 kB)
Installing collected packages: setuptools, pip
  WARNING: Value for scheme.platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: C:\Users\chenn\AppData\Local\Temp\pip-target-59q5f0n8\DLLs\python
  sysconfig: C:\Users\chenn\AppData\Local\Temp\pip-target-59q5f0n8\lib\python
  WARNING: Additional context:
  user = False
  home = 'C:\\Users\\chenn\\AppData\\Local\\Temp\\pip-target-59q5f0n8'
  root = None
  prefix = None
Successfully installed pip-21.3.1 setuptools-59.5.0
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Program Files\Python311\python.exe -m pip install --upgrade pip' command.
python -m pip install --upgrade --target=e:/FullWorkingProject/WorkingWEBRTC/MediaSoup/medias3/3.9.2/worker/out/pip  meson ninja
Collecting meson
  Using cached meson-0.60.2-py3-none-any.whl (838 kB)
Collecting ninja
  Using cached ninja-1.10.2.3-py2.py3-none-win_amd64.whl (292 kB)
Installing collected packages: ninja, meson
Successfully installed meson-0.60.2 ninja-1.10.2.3
e:/FullWorkingProject/WorkingWEBRTC/MediaSoup/medias3/3.9.2/worker/out/pip/bin/meson setup \
        --buildtype release \
        -Db_ndebug=true \
        -Db_pie=true \
        -Db_staticpic=true \
        --reconfigure \
        "" \
        e:/FullWorkingProject/WorkingWEBRTC/MediaSoup/medias3/3.9.2/worker/out/Release || \
        e:/FullWorkingProject/WorkingWEBRTC/MediaSoup/medias3/3.9.2/worker/out/pip/bin/meson setup \
                --buildtype release \
                -Db_ndebug=true \
                -Db_pie=true \
                -Db_staticpic=true \
                "" \
                e:/FullWorkingProject/WorkingWEBRTC/MediaSoup/medias3/3.9.2/worker/out/Release
Directory does not contain a valid build tree:
E:\FullWorkingProject\WorkingWEBRTC\MediaSoup\medias3\3.9.2\worker\out\Release
The Meson build system
Version: 0.60.2
Source dir: E:\FullWorkingProject\WorkingWEBRTC\MediaSoup\medias3\3.9.2\worker
Build dir: E:\FullWorkingProject\WorkingWEBRTC\MediaSoup\medias3\3.9.2\worker\out\Release
Build type: native build
Project name: mediasoup-worker
Project version: undefined

meson.build:1:0: ERROR: Compiler cl can not compile programs.

A full log can be found at E:\FullWorkingProject\WorkingWEBRTC\MediaSoup\medias3\3.9.2\worker\out\Release\meson-logs\meson-log.txt
make: *** [Makefile:65: setup] Error 1
make: Leaving directory 'E:/FullWorkingProject/WorkingWEBRTC/MediaSoup/medias3/3.9.2/worker'
npm ERR! code 1
npm ERR! path E:\FullWorkingProject\WorkingWEBRTC\MediaSoup\medias3\3.9.2
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node npm-scripts.js postinstall

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chenn\AppData\Local\npm-cache\_logs\2021-12-12T13_48_34_236Z-debug-0.log
PS E:\FullWorkingProject\WorkingWEBRTC\MediaSoup\medias3\3.9.2> npm install  

> mediasoup@3.9.2 postinstall
> node npm-scripts.js postinstall

npm-scripts.js [INFO] running task "postinstall"
npm-scripts.js [INFO] executing command: node npm-scripts.js worker:build
npm-scripts.js [INFO] running task "worker:build"
npm-scripts.js [INFO] executing command: make -C worker
make: Entering directory 'E:/FullWorkingProject/WorkingWEBRTC/MediaSoup/medias3/3.9.2/worker'
process_begin: CreateProcess(NULL, dirname E:/FullWorkingProject/WorkingWEBRTC/MediaSoup/medias3/3.9.2/worker/Makefile, ...) failed.
Makefile:7: pipe: No error
e:/FullWorkingProject/WorkingWEBRTC/MediaSoup/medias3/3.9.2/worker/out/pip/bin/meson setup \
        --buildtype release \
        -Db_ndebug=true \
        -Db_pie=true \
        -Db_staticpic=true \
        --reconfigure \
        "" \
        e:/FullWorkingProject/WorkingWEBRTC/MediaSoup/medias3/3.9.2/worker/out/Release || \
        e:/FullWorkingProject/WorkingWEBRTC/MediaSoup/medias3/3.9.2/worker/out/pip/bin/meson setup \
                --buildtype release \
                -Db_ndebug=true \
                -Db_pie=true \
                -Db_staticpic=true \
                "" \
                e:/FullWorkingProject/WorkingWEBRTC/MediaSoup/medias3/3.9.2/worker/out/Release
Directory does not contain a valid build tree:
E:\FullWorkingProject\WorkingWEBRTC\MediaSoup\medias3\3.9.2\worker\out\Release
The Meson build system
Version: 0.60.2
Source dir: E:\FullWorkingProject\WorkingWEBRTC\MediaSoup\medias3\3.9.2\worker
Build dir: E:\FullWorkingProject\WorkingWEBRTC\MediaSoup\medias3\3.9.2\worker\out\Release
Build type: native build
Project name: mediasoup-worker
Project version: undefined

meson.build:1:0: ERROR: Compiler cl can not compile programs.

A full log can be found at E:\FullWorkingProject\WorkingWEBRTC\MediaSoup\medias3\3.9.2\worker\out\Release\meson-logs\meson-log.txt
make: *** [Makefile:65: setup] Error 1
make: Leaving directory 'E:/FullWorkingProject/WorkingWEBRTC/MediaSoup/medias3/3.9.2/worker'
npm ERR! code 1
npm ERR! path E:\FullWorkingProject\WorkingWEBRTC\MediaSoup\medias3\3.9.2
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node npm-scripts.js postinstall

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chenn\AppData\Local\npm-cache\_logs\2021-12-12T13_51_37_338Z-debug-0.log
PS E:\FullWorkingProject\WorkingWEBRTC\MediaSoup\medias3\3.9.2>

**Comment by nazar-pc** [comment]
It doesn't appear that you have followed installation instructions. Please read https://mediasoup.org/documentation/v3/mediasoup/installation/ top to bottom and if you still have issues search [forum](https://mediasoup.discourse.group/) for answers and if that doesn't help, create a new topic on the forum unless you are convinced there is something wrong with mediasoup itself.

**Comment by chennasi** [comment]
i followed all still error
