### ISSUE TITLE
Renomination support

### ISSUE THREAD

**Issue by penguinol** [versatica/mediasoup#734]
Do mediasoup support ICE Renomination or suppose to support it ?

In verison 1.2.5, mediasoup added support for ICE renomination in sdp.
https://github.com/versatica/mediasoup/commit/994e3651cb6f14b18206bcf4546e12a5a67c72f8

But mediasoup-worker does not actully process NOMINATION attribute. 

When client truned on renomination, it will never sending a STUN packet with USE-CANDIDATE.
And mediasoup will use the address in first bind request as selected tuple.
But when client sending a STUN packet with NOMINATION later, mediasoup will not switch to it.

**Comment by ibc** [comment]
We already update the 5-tuple when mediasoup receives a STUN with USE-CANDIDATE but indeed we should implement this.

This is the spec: https://datatracker.ietf.org/doc/html/draft-thatcher-ice-renomination
