### ISSUE TITLE
Is Producer Consumer 1-to-1

### ISSUE THREAD

**Issue by jeffery30162** [versatica/mediasoup#735]
Hi I am trying to understand the producer consumer concept. 

Example:
 A voice call with 5 users
 Each user with two transports, producer and consumer (or one transport for producing and consuming?)
 Each user is also producing a microphone audio stream to the server

How many consumers does each user need? Does each user need a consumer for each other user in the call (n-1)?
Can I combine producer tracks to use in one consumer?

What is the best practice to achieve this?

Thanks

**Comment by nazar-pc** [comment]
Questions on the [forum](https://mediasoup.discourse.group/)
