### ISSUE TITLE
Mediasoup doesn't clean up after node postinstall build

### ISSUE THREAD

**Issue by jcpage** [versatica/mediasoup#736]
## Bug Report

I noticed that the mediasoup node modules is over 55MB, which didn't seem to make sense.  Poking around I see most of that is Python files and compiled object files, which I don't believe are needed at run time.

### Your environment

- Operating system: MacOS 12.0.1,  M1 Max arm64
- Node version: 16.13.1
- npm version: 8.3.0
- gcc/clang version: Apple clang version 13.0.0 (clang-1300.0.29.3)
- mediasoup version: 3.9.2
- mediasoup-client version: N/A

### Issue description

I have a partial solution - in this script:

       case 'postinstall':
        {
                if (!process.env.MEDIASOUP_WORKER_BIN)
                {
                        execute('node npm-scripts.js worker:build');
                        execute(`${MAKE} clean-pip -C worker`);
                        execute(`${MAKE} clean-subprojects -C worker`);
                }

                break;
        }

in this case "clean-subprojects" uses meson which needs Python, so the previous step "clean-pip" just gets undone as the following one re-installs pip.  Swapping the order of those should at least keep pip from being reinstalled.

After that there is still about 33MB left, though.

I went into the build output and recursively deleted all ".o" and ".a" files, along with some other large temp files (build.ninja, compile_commands.json, .ninja_*) and the whole module is down to about 9MB. (Removing everything from worker except mediasoup-worker gets the while thing down to about 5.5MB but I'd consider deleting the sources beyond what a build cleanup script would want to do and left to anyone really wanting to optimize for their own uses...)

Summary: low hanging fruit would be just to swap the clean commands so clean-pip is last.  But if you added another cleanup step just to remove the temporary object/build output from worker/out/Release that would make the whole project take less than 10MB, which is really nice when packaging it into a container, etc.

**Comment by nazar-pc** [comment]
Thanks for reporting this, indeed we might want to improve this.
I think I know how to resolve this in a nice way, working on a PR.
