### ISSUE TITLE
Not using pair key in `pipeToRouter()`

### ISSUE THREAD

**Issue by piranna** [versatica/mediasoup#738]
At https://github.com/versatica/mediasoup/blob/ec186c5d3616c1ef622b163c3b1ce5ba9ecc67f1/node/src/Router.ts#L725 `pipeToRouter()` is using only destination Router ID as key of the pair of Router instances, as it was discussed in https://github.com/versatica/mediasoup/pull/697. Later on https://github.com/versatica/mediasoup/blob/ec186c5d3616c1ef622b163c3b1ce5ba9ecc67f1/node/src/Router.ts#L810-L813 it's being stored at `mapRouterPairPipeTransportPairPromise` with `router.id` and at `addPipeTransportPair()` with `this.id`, so not using pair key at all but just storing them twice (equally acceptable) and removing it later on both https://github.com/versatica/mediasoup/blob/ec186c5d3616c1ef622b163c3b1ce5ba9ecc67f1/node/src/Router.ts#L774-L786 and https://github.com/versatica/mediasoup/blob/ec186c5d3616c1ef622b163c3b1ce5ba9ecc67f1/node/src/Router.ts#L949-L966. Is this right? The rest of the pair selection code seems to be ok, just only missing the `[this.id, router.id].sort().join(',')` part, isn't it? Or am I missing something? Are we storing the pair in local pairs and also in remote Router ones instead of having a common list with unique IDs? Is it just not using a global list the only reason of doing it that way?

**Comment by ibc** [comment]
Please let's not open issues in GH for asking questions or having discussions.

> Are we storing the pair in local pairs and also in remote Router ones instead of having a common list with unique IDs? Is it just not using a global list the only reason of doing it that way?

Yes

**Comment by piranna** [comment]
> Please let's not open issues in GH for asking questions or having discussions.

Yeah, sorry for that, I first was writting a bug report since only saw the first `const pipeTransportPairKey = router.id` line and got confused with it being the key and though it was a bug, but later while writting the bug issue I was collecting references on the code to see if there was something I was overlooking, that's why finally I asked about it to ensure my conclusions were right, code got to be a bit complex to understand in this feature...

**Comment by ibc** [comment]
Code got a bit complex to avoid having global state, but not that much.

**Comment by piranna** [comment]
> Code got a bit complex to avoid having global state, but not that much.

Logic is fine, and I really like the aproach, very smart :-) It's more about code structure, that Promise with Promise.then() inside... ugh :-/
