### ISSUE TITLE
centos npm install error

### ISSUE THREAD

**Issue by lujune** [versatica/mediasoup#745]
### Your environment

- Operating system:
- Node version:17.3
- npm version:8.12
- gcc/clang version:8.5
- mediasoup version:3.9.311
- mediasoup-client version:

### Issue description
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/versatica/mediasoup.git
npm ERR! git@github.com: Permission denied (publickey)

1.ssh -T git@github.com is ok
2.in the shell,"git --no-replace-objects ls-remote ssh://git@github.com/versatica/mediasoup.git"  get recv
3.set git config,git config --list recv
url.https://.insteadof=git://
url.https://git.scm.domain.com.insteadof=git://git.scm.domain.com
url.https://github.com/.insteadof=git@github.com:
url.https://github.com/versatica/mediasoup.git/.insteadof=ssh://git@github.com/versatica/mediasoup.git
http.sslverify=false
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/versatica/mediasoup-demo.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.v3.remote=origin
branch.v3.merge=refs/heads/v3

but but the issue aslo exist

**Comment by nazar-pc** [comment]
Looks like you try to install mediasoup from git for some reason and don't have permission to access repo via SSH just like error clearly says.
Switch to release from NPM or use HTTPS endpoint if you have to.

There is no mediasoup issue here.
