### ISSUE TITLE
MacOS Version 11.6:Compile time mediasoup-worker Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by lanhaiyang** [versatica/mediasoup#746]
## Bug Report

![image](https://user-images.githubusercontent.com/13830318/147641112-30051999-1244-47e4-9e57-6d481e3ee521.png)

![image](https://user-images.githubusercontent.com/13830318/147641134-e7c32eb4-f496-4cc6-a863-4b729ebe649c.png)

use [mediasoup-demo](https://github.com/versatica/mediasoup-demo/)
```
npm install
```
Compile time mediasoup-worker 
Undefined symbols for architecture x86_64:

### Installation Environment: 
Node version : v16.13.1
npm version : 8.3.0
make: GNU Make 3.81
gcc and g++ version 7.5.0
clang version: Apple clang version 13.0.0 (clang-1300.0.29.3)
python: 3.9.7

OS:
macOS ： 11.6
CPU: Intel Core i5

### mediasoup 

[mediasoup-demo](https://github.com/versatica/mediasoup-demo)
- mediasoup version: 3.9.3

### bug description

help me
No solution found online

**Comment by nazar-pc** [comment]
Looks like you have mix of macOS and non-macOS build artifacts. Remove `node_modules` and try again.

I don't see mediasoup issue here, please use https://mediasoup.discourse.group/ for questions instead.

**Comment by lanhaiyang** [comment]
ok thank
