### ISSUE TITLE
a problem about simulcast

### ISSUE THREAD

**Issue by seamory** [versatica/mediasoup#747]
## Bug Report

**IMPORTANT:** We primarily use GitHub as an issue tracker. Just open an issue here if you have encountered a bug in mediasoup.

If you have questions or doubts about mediasoup or need support, please use the mediasoup Discourse Group instead:

https://mediasoup.discourse.group

If you got a crash in mediasoup, please try to provide a core dump into the issue report:

https://mediasoup.org/support/#crashes-in-mediasoup-get-a-core-dump

### Your environment

- Operating system: Ubuntu WSL 1 on Windows 10
- Node version: v16.13.0
- npm version: 8.1.4
- gcc/clang version: latest
- mediasoup version: 3.9.2
- mediasoup-client version: 3.6.47

### Issue description
client will only send the first three encoding rtp if produce encoding is more than three. 
i don't know mediasoup is only support three rtp or not, i don't see any limit of quantity for simulcast in description.

![Snipaste_2021-12-31_12-24-41](https://user-images.githubusercontent.com/20828349/147803263-58e5524f-1d3a-4cc8-877f-38e3c6a55f49.png)
![Snipaste_2021-12-31_12-24-52](https://user-images.githubusercontent.com/20828349/147803264-4ce24f6f-ab86-4ed1-8042-430470433dfe.png)
![Snipaste_2021-12-31_12-25-04](https://user-images.githubusercontent.com/20828349/147803265-d8b14f1e-ad30-4107-8627-a6cf64241274.png)

**Comment by nazar-pc** [comment]
Just like the first line in the issue template says, use forum for questions.

I wouldn't recommend you to use more than 3 encodings as [some browsers will crash because of that](https://bugzilla.mozilla.org/show_bug.cgi?id=1683934)
