### ISSUE TITLE
Does it support h265 encoding?

### ISSUE THREAD

**Issue by XianWang-Lu** [versatica/mediasoup#752]
I use a browser supported h265 named "科达浏览器",but the codec.mimeType of RtpCodecCapability getted by mediasoup-client from browser is "video/HEVC",not "video/h265".On the server,when I modify the value "video/VP9" to "video/HEVC" in config.js,it throws "Not Supported" error.
It seems to support h265 video encoding, but I can't find how to implement it.So if it supports h265 video encoding?

**Comment by nazar-pc** [comment]
No, H265 is not supported by mediasoup at the moment, see https://github.com/versatica/mediasoup/blob/v3/node/src/supportedRtpCapabilities.ts

**Comment by XianWang-Lu** [comment]
![image](https://user-images.githubusercontent.com/70087097/148710592-f5e1328b-ed79-4d09-ae65-5b748e78c0fc.png)
I see "H265" appeared here.

**Comment by nazar-pc** [comment]
Hm, indeed, apparently it is a known codec, but there is no special support for it in the worker yet: https://github.com/versatica/mediasoup/tree/v3/worker/src/RTC/Codecs

**Comment by ibc** [comment]
H265 simulcast or svc is not yet supported. Please, make questions in the forum, don't open and issue for asking them.
