### ISSUE TITLE
Installation fails under path with whitespaces

### ISSUE THREAD

**Issue by nazar-pc** [versatica/mediasoup#753]
### Your environment

- mediasoup version: 3.9.4

### Issue description
When installed under directory whose path has whitespaces, installation fails, see https://mediasoup.discourse.group/t/mediasoup-installation-issue-ubuntu-20-04-node-16-13-1-pip-21-3-1-python-3-8-10/3804, we need to fix that.

**Comment by ibc** [comment]
Is this a bug in our code or in some underlying lib or build system?

**Comment by nazar-pc** [comment]
I believe some paths need to be taken into quotes in the Makefile, didn't dig into details yet, so it is all on our side.

**Comment by techhjork** [comment]
> ### Creating Mediasoup Files in  using other other  local disk space in Dual Boot 

Basically i am on **Dual boot** and using other local disk space 'Volume/Backend/mediasoup/mediasoup-3'
so maybe thats why i was facing that issue that time

But as @nazar-pc  said for changing directory 
i clone that repo.  in Desktop and same process and issue resolved but getting some warning 

Link of warning of C in [**Mediasoup Discourse**](https://mediasoup.discourse.group/t/mediasoup-installation-issue-ubuntu-20-04-node-16-13-1-pip-21-3-1-python-3-8-10/3804/3?u=techhjork)
![image](https://user-images.githubusercontent.com/62848979/149116296-6a998b3e-ac0e-4b33-8eb3-bb350ccefa94.png)

hope Mediasoup Team will fix these also 

**And Thanks for this helping Community** 

i will ask more Questions in future

**Comment by CosmosisT** [comment]
The whitespace is a feature I thought?

**Comment by ibc** [comment]
> When installed under directory whose path has whitespaces, installation fails, see https://mediasoup.discourse.group/t/mediasoup-installation-issue-ubuntu-20-04-node-16-13-1-pip-21-3-1-python-3-8-10/3804

@nazar-pc the linked post doesn't seem related to having white spaces in the installation path, do I miss something?

**Comment by nazar-pc** [comment]
It does, see, target is `/media/tech/New Volume/Backend/mediasoup/mediasoup-3/worker/out/pip`, then you see "invalid requirement", which is suspiciously the part of the path after whitespace:
```
ERROR: Invalid requirement: 'Volume/Backend/mediasoup/mediasoup-3/worker/out/pip'
```

**Comment by ibc** [comment]
I've tried everything and this is hell. Not even sure there is a fix, and impossible to fix it in all OS.

So I've fixed this issue another way:

<img width="1163" alt="CleanShot-2022-12-10-at-13 21 51@2x" src="https://user-images.githubusercontent.com/16191/206854890-4d72ce76-cf1a-4241-8cb6-39e890484bce.png">

**Comment by nazar-pc** [comment]
I'm sure there is a fix, but not sure we want it in the codebase. Not supporting whitespaces is certainly one way to "fix" it :joy:

**Comment by ibc** [comment]
Searching for "Makefile whitespaces" is just maddening. I just gave up. Add I love the fix 😅

**Comment by RamanSB** [comment]
I would not say this issue has been resolved. I had a whitespace in my Filepath and it didn't work, when the whitespace was removed - it worked.

**Comment by ibc** [comment]
Yes. As explained in comments above we gave up. And we documented that the installation path cannot have white spaces. PRs are welcome, we don't know how to fix that.

**Comment by ibc** [comment]
This is probably fixed in PR https://github.com/versatica/mediasoup/pull/1239/ in commit https://github.com/versatica/mediasoup/pull/1239/commits/c7720f2da4f399a81d1b482cf28d8d604207ff19.
