### ISSUE TITLE
worker fail

### ISSUE THREAD

**Issue by chennasi** [versatica/mediasoup#759]
## Bug Report
yarn install v1.22.17
warning package.json: License should be a valid SPDX license expression
info No lockfile found.
warning mirotalksfu@1.0.0: License should be a valid SPDX license expression
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 372.20s.
PS D:\Scenario\mirotalksfu-main> npm start   

> mirotalksfu@1.0.0 start
> node app/src/Server.js

[2022-01-20 21:38:12.129] [Server] WORKERS: 4
[2022-01-20 21:38:12.250] [Server] 

        ███████╗██╗ ██████╗ ███╗   ██╗      ███████╗███████╗██████╗ ██╗   ██╗███████╗██████╗
        ██╔════╝██║██╔════╝ ████╗  ██║      ██╔════╝██╔════╝██╔══██╗██║   ██║██╔════╝██╔══██╗
        ███████╗██║██║  ███╗██╔██╗ ██║█████╗███████╗█████╗  ██████╔╝██║   ██║█████╗  ██████╔╝
        ╚════██║██║██║   ██║██║╚██╗██║╚════╝╚════██║██╔══╝  ██╔══██╗╚██╗ ██╔╝██╔══╝  ██╔══██╗
        ███████║██║╚██████╔╝██║ ╚████║      ███████║███████╗██║  ██║ ╚████╔╝ ███████╗██║  ██║
        ╚══════╝╚═╝ ╚═════╝ ╚═╝  ╚═══╝      ╚══════╝╚══════╝╚═╝  ╚═╝  ╚═══╝  ╚══════╝╚═╝  ╚═╝ started...

[2022-01-20 21:38:12.255] [Server] Listening on {
  hostConfig: {
    protected: false,
    username: 'username',
    password: 'password',
    authenticated: true
  },
  announced_ip: '192.168.8.100',
  server: 'https://localhost:3010',
  api_docs: 'https://localhost:3010/api/v1/docs',
  mediasoup_version: '3.9.5'
}
D:\Scenario\mirotalksfu-main\node_modules\mediasoup\node\lib\Worker.js:136
                    this.emit('@failure', new Error(`[pid:${this.#pid}, code:${code}, signal:${signal}]`));
                                          ^

Error: [pid:4472, code:3221225477, signal:null]
    at ChildProcess.<anonymous> (D:\Scenario\mirotalksfu-main\node_modules\mediasoup\node\lib\Worker.js:136:43)
    at ChildProcess.emit (node:events:520:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)

Node.js v17.4.0

**Comment by ibc** [comment]
Sorry, we cannot consider this kind of reported errors in which the whole issue template is ignored.
