### ISSUE TITLE
usrsctp incorrect hash for downloaded file

### ISSUE THREAD

**Issue by j1elo** [versatica/mediasoup#762]
### Your environment

- Operating system: Ubuntu 20.04
- Node version: 16.13.2
- npm version: 8.1.2
- gcc/clang version: 9.3.0 (with ccache 3.7.7)
- mediasoup version: 3.9.6
- mediasoup-client version: n/a

### Issue description

Related topic in the forum: https://mediasoup.discourse.group/t/error-usrsctp-hash-is-incorrect-build-fails/3896/10

I feel it might be too early to raise a warning, this is probably just a silly issue on the source repo, but in the worst case, there is a small chance this might be a "supply chain attack".

Today I'm unable to run `npm install` in my project, because mediasoup building fails when a hash mismatch occurs on the download zip of *usrsctp*.

This is the relevant part of the output:

> ERR! Downloading usrsctp source from https://github.com/sctplab/usrsctp/archive/9d6b99b10a70f7a63d21cd80d03c353da9ac19d3.zip
> ERR! Download size: 949227
> ERR! Downloading: ..........
> ERR! A fallback URL could be specified using source_fallback_url key in the wrap file
> ERR! 
> ERR! meson.build:176:0: ERROR: Incorrect hash for source:
> ERR!  d9b7b3350ea0be2a3d1437e404d4852df741c4984b734729c5edc337ff4b7611 expected
> ERR!  e86fe0b8aabef0eae207a94a5525da303e90477c37fce272c84e2d87d7ac169b actual.

I checked, and yeah, the zip in that URL does have the hash reported as "actual":

> $ wget -qO- https://github.com/sctplab/usrsctp/archive/9d6b99b10a70f7a63d21cd80d03c353da9ac19d3.zip | sha256sum
> e86fe0b8aabef0eae207a94a5525da303e90477c37fce272c84e2d87d7ac169b  -

**Comment by ibc** [comment]
@nazar-pc can you please say which is the proper way to proceed with this kind of errors?

**Comment by sheshadri** [comment]
Update package.json to the latest version of mediasoup(3.9.6 ), and then run "npm install"

**Comment by snnz** [comment]
$wget -qO- https://github.com/sctplab/usrsctp/archive/9d6b99b10a70f7a63d21cd80d03c353da9ac19d3.zip | sha256sum
d9b7b3350ea0be2a3d1437e404d4852df741c4984b734729c5edc337ff4b7611  -

I would have looked at the file with the incorrect hash: what it was?

**Comment by j1elo** [comment]
As [mentioned](https://mediasoup.discourse.group/t/error-usrsctp-hash-is-incorrect-build-fails/3896/9) in the mediasoup discussion forum, as of writing this message, the URL hash seems to have mysteriously reverted back to the old, expected hash:

> $ wget -qO- https://github.com/sctplab/usrsctp/archive/9d6b99b10a70f7a63d21cd80d03c353da9ac19d3.zip | sha256sum
> d9b7b3350ea0be2a3d1437e404d4852df741c4984b734729c5edc337ff4b7611  -

This leaves me with a sour taste because now I'm not sure if it has just been a somewhat spurious issue in GitHub infrastructure, or if there are malicious actors on the affected repo, that have noticed their mistake and now have taken action to cover their tracks.

**Comment by nazar-pc** [comment]
There must have been some kind of bug on GitHub (I have seen them in the past), this is one of the reasons there is sha256 hash sum checks after download. So nothing to fix in the end, right?

**Comment by j1elo** [comment]
Yeah, nothing actionable from the side of mediasoup. In fact, the checksum verification of Meson arguably *did a good job* detecting an incorrect file download.

I'll see if there is any way to ask the maintainers of usrsctp if they know anything. It sounds a bit strange that, if it was an issue on GitHub, it didn't show since the very first download that is done.

**Comment by ibc** [comment]
What about reporting this issue in usrsctp GH project and reference this issue? Maybe they can make a new release or something to fix it.

**Comment by j1elo** [comment]
I got in contact with what seems the main developer in that repo, to let them know about the situation and ask if they know anything of what has happened. Will keep this issue updated.

**Comment by j1elo** [comment]
Update: in principle it seems that it was indeed an issue from GitHub: https://twitter.com/shs96c/status/1488480089700503558

> It looks like github have repackaged zips downloaded from their site, breaking anyone who's using bazelbuild packages (or, indeed, anything that checks the checksum of packages it downloads)
> The unzipped contents are still the same, but the zips themselves differ.

> Engineer on the team responsible at GitHub here.  I just noticed this, and we rolled back the feature flag that we believe was causing the change, and will look into making the change without breaking the checksums.

But there is something to learn from it: they consider Release zips as part of their "public API" that they try not to break. But any other zips (in particular, per-commit zips that mediasoup uses) are *not* considered stable and they don't make promises of not breaking them: https://twitter.com/tgummerer/status/1488493481874055173

> In general we don't guarantee that the checksums of zip downloads will stay the same, they do for downloads of releases though.

This issue can be closed, as there is nothing to fix in mediasoup (might be worth discussing about the thing about zip checksums though)

**Comment by nazar-pc** [comment]
I wish usrsctp had meaningful releases more often :disappointed:

**Comment by ibc** [comment]
Thank a lot for figuring out the issue.

**Comment by ShoryuKyzan** [comment]
seeing the exact same issue, different hashes
```
  meson.build:199:0: ERROR: Incorrect hash for source:
   dcf71b9cba8dc0ca9940c4b316a0c796be8fab42b070bb6b7cab62b48f0e66c4 expected
   ee834b6d3de30437ac627f547dcfe791f63e61694ff68b34f75bd7b11f668343 actual.
```
This is mediasoup 0.5.3 build
error: failed to run custom build command for `mediasoup-sys v0.5.3`

Looks to be the same sort of cause? The zip has the 2nd SHA but it expects something different.

```
wget -qO- https://github.com/abseil/abseil-cpp/archive/20211102.0.tar.gz | sha256sum
ee834b6d3de30437ac627f547dcfe791f63e61694ff68b34f75bd7b11f668343 *-
```
Contains exact same source as
https://github.com/abseil/abseil-cpp/releases/tag/20211102.0
https://github.com/abseil/abseil-cpp/tree/215105818dfde3174fe799600bb0f3cae233d0bf

Different hashes than what https://github.com/versatica/mediasoup/blob/0b770e7e226b77f8b5eb184b50583a8b73507a8b/worker/subprojects/abseil-cpp.wrap expects.

**Comment by j1elo** [comment]
I was reading this in HackerNews the other day: [Git archive checksums may change](https://news.ycombinator.com/item?id=34586917) ([source](https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/)), and was thinking: "*I swear that this has been a topic somewhere where I participated*" but couldn't recall where or when. So well, here it is! 😄

There seems to be a bit of contentious discussion inside GitHub about whether the automatically-generated source ZIP archives are considered Public API or not. It's been less than 1 year and this broke already twice. I think that maybe direct linking to the generated ZIP archives -- using GitHub as cheap hosting, basically -- is in general not a good technique for package managers.

This will come up again, I'm sure.
