### ISSUE TITLE
Mediasoup not transmitting video and audio on mobile hotspot

### ISSUE THREAD

**Issue by ksarpotdar** [versatica/mediasoup#763]
Hi,

I was trying the mediasoup demo app at https://v3demo.mediasoup.org demo link, **on internet** transmitted **through mobile hotspot on desktop chrome** Version 97.0.4692.99 (Official Build) (64-bit). I opened one window in normal window and another in the incognito mode. However **it doesn't play video or audio** on the mediasoup. I had tried this demo link on normal wifi earlier and it worked perfectly, there wasn't a problem. What might be the issue?

**How to produce?**
1. Use Mobile Hotspot for connecting the laptop to the internet using the wifi transmitted through the hotspot
2. Open https://v3demo.mediasoup.org link on the chrome in normal window and start the meeting
3. Copy the meeting url and open the Incognito tab and start the meeting there as well.
4. the audio and video both does not transmit. 
5. I observed that the tracks and stream is transferred and the video and audio elements created but the video & audio doesn't play

Your response and resolution would be really helpful.

PS.
I have my normal webRTC Mesh application. that application is able to capture both the camera feeds from these two tabs and able to transmit using rtcPeerConnection and play both videos and audios.

**Comment by ibc** [comment]
Please ask in the mediasoup public forum as the issue template (that you just removed) states. This is not a bug in mediasoup.

**Comment by ksarpotdar** [comment]
Thanks for response. I am so sorry to remove the template. I wasn't aware. I thought its for the hosted solution and if any issue there. I shall check in public forum.
