### ISSUE TITLE
Thread based in v4

### ISSUE THREAD

**Issue by piranna** [versatica/mediasoup#771]
## Feature Request

Rust wrapper is based on threads instead of being IPC based, and has showed to have decreased calls delay 50x. I propose to have the same thread based architecture on Node.js for next v4 version.

In addition to that, targeting Node.js N-API instead of directly using v8 APIs would make it independent of the Node.js version being used, simplifying the publish of prebuilds.

**Comment by nazar-pc** [comment]
Part of the reason in Rust is memory sharing, not sure how tricky it would be in Node.js. Feel free to prototype it of course, but I'm not sure that is a bottleneck in most typical apps.

**Comment by satoren** [comment]
I, on the other hand, would like to see an option to run the Rust version on a Process basis. This is useful when robustness is more important than execution speed.

**Comment by piranna** [comment]
Regarding that topic, another alternative would be to compile Mediasoup to WebAssembly, so no need to also maintain proceses based No se.js implementation :-)

**Comment by ibc** [comment]
Definitely we don't want to make mediasoup-worker depend on Node or V8 C bindings. We want to keep the worker as a separate process since turning it into a thread would make the Node thread/process block unless the Node app uses Workers (separate Node threads) and we don't want to mandate such a usage. And I see zero reason to moving to WebAssembly.

I'll close this feature request since this is unlike to happen.

**Comment by piranna** [comment]
> turning it into a thread would make the Node thread/process block unless the Node app uses Workers (separate Node threads) and we don't want to mandate such a usage

I don't think this is needed at all, it's still possible to use v8 to start new threads, being them transparent to Javascript side. That's how works for example the access to filesystem in Node.js core.

**Comment by ibc** [comment]
Still I don't see any real benefit but just lot of work and just because it can be done. Otherwise migrate everything to WebAssembly, otherwise to any other language, and so on.

**Comment by piranna** [comment]
> just because it can be done

Agree, they are improvements regarding performance, but probably this is the main reason.
