### ISSUE TITLE
MS_LOG_TRACE isn't defined when mediasoup is built with buildtype parameter set to debug

### ISSUE THREAD

**Issue by dsdolzhenko** [versatica/mediasoup#791]
### Your environment
- mediasoup version: >= 3.9.0

### Issue description

It seems that the macro disappeared after migration to Meson build system along with `DEBUG` and `MS_LOG_FILE_LINE`.

**Comment by dsdolzhenko** [comment]
It can be easily fixed by adding the following snippet into `meson.build`:

```
if get_option('buildtype') == 'debug'
  cpp_args += [
    '-DDEBUG',
    '-DMS_LOG_TRACE',
    '-DMS_LOG_FILE_LINE'
  ]
endif
```

However, after enabling it I've realised that it may be not a good idea to log trace messages along with debug ones and it probably would be better to add a more severe log level and log only debug messages when log level set to LOG_DEBUG. What do you think?

**Comment by nazar-pc** [comment]
Hm, I somehow missed those, but they can be added with `MESON_ARGS` environment variable like this:
```
MESON_ARGS="-DDEBUG -DMS_LOG_TRACE -DMS_LOG_FILE_LINE" npm i
```

I think tracing has quite a lot of overhead, not sure it is worth enabling it in debug mode. But it is a fair criticism that it was enabled before and now it is not.

**Comment by dsdolzhenko** [comment]
> I think tracing has quite a lot of overhead, not sure it is worth enabling it in debug mode

Totally agree, that's why I'm proposing adding a dedicated log level for that

**Comment by nazar-pc** [comment]
Well, true, but even if it is not printed, there is a piece of logic running to support it, defines allow that code to not be compiled at all.

**Comment by jmillan** [comment]
> MESON_ARGS="-DDEBUG -DMS_LOG_TRACE -DMS_LOG_FILE_LINE" npm i

I would appreciate a comment about this somewhere, maybe Makefile. The fact that MESON_ARGS can be used to provide defines like these ones.

**Comment by jmillan** [comment]
And I agree that 'debug'  mode should not enable tracing. One can normally compile in debug mode to have the symbols for debugging solely.

**Comment by jmillan** [comment]
> I would appreciate a comment about this somewhere, maybe Makefile. The fact that MESON_ARGS can be used to provide defines like these ones.

Could you please add some comments in Makefile about the use of this ENV variable @nazar-pc ?

I'll close this issue since trace and debugging do not necessarily come together.
