### ISSUE TITLE
Rust version crash when using WorkerManager with multithreaded executor

### ISSUE THREAD

**Issue by satoren** [versatica/mediasoup#795]
## Bug Report

Crashes when using multithreaded executor to WorkerManager.
The following test reproduces the problem.
https://github.com/versatica/mediasoup/commit/da151f0086f8f68aa0a85692dcc9ee3d98a4c8f7#diff-9951565789cc682dc2da50fdf27b29e65d368f9549cc0e53b47cd8c9af84423fR318
This is copied from `test/integration/consumer.rs` and changed to the multithreaded executor.
Perhaps a data racecondition has occurred and can be quickly detect with TSAN or Valgrind.

### Your environment

- Operating system: macOS
- Node version: 
- npm version:
- gcc/clang version: Apple clang version 13.1.6 (clang-1316.0.21.2)
- mediasoup version: ce3f5f98b6c7dbbb676fed881fb471006e94913f
- mediasoup-client version: N/A

### Issue description

<details>

```
Caused by:
  process didn't exit successfully: `/Users/user/projects/mediasoup/target/debug/deps/integration-d637e415eca0dfbb` (signal: 11, SIGSEGV: invalid memory reference)
```

</details>

**Comment by nazar-pc** [comment]
Interesting, I'll take a look when I have time if you don't figure it out sooner.
