### ISSUE TITLE
rust mediasoup 

### ISSUE THREAD

**Issue by jason-shen** [versatica/mediasoup#797]
## Feature Request
would be good if rust mediasoup can return a threadId, so we can check the usage of the actual thread then decide if or not put routers on that worker, i know in rust 1 thread don't use the whole core as discussed in the forum, but in situation when we want a mega huge room, this can be useful, i am happy to do a pr if we happy with this

**Comment by nazar-pc** [comment]
You can already capture thread ID and even adjust things like pinning threads to CPU cores using thread initializer function: https://docs.rs/mediasoup/latest/mediasoup/worker/struct.WorkerSettings.html#structfield.thread_initializer
