### ISSUE TITLE
Rust version:  Error during WebSocket handshake

### ISSUE THREAD

**Issue by makorne** [versatica/mediasoup#807]
### Your environment

Your environment

    Operating system: Linux fedora 5.16.15-201.fc35.x86_64 

    https://github.com/versatica/mediasoup/issues/1 SMP PREEMPT Thu Mar 17 05:45:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

    gcc/clang version:
    Using built-in specs.
    COLLECT_GCC=gcc
    COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/11/lto-wrapper
    OFFLOAD_TARGET_NAMES=nvptx-none
    OFFLOAD_TARGET_DEFAULT=1
    Target: x86_64-redhat-linux
    Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-11.2.1-20220127/obj-x86_64-redhat-linux/isl-install --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux --with-build-config=bootstrap-lto --enable-link-serialization=1
    Thread model: posix
    Supported LTO compression algorithms: zlib zstd
    gcc version 11.2.1 20220127 (Red Hat 11.2.1-9) (GCC)

    mediasoup version: 0.9.2

### Issue description
Looks like something with WebSocket handshake is missing in rust mediasoup version.

I tried flutter client https://github.com/Blancduman/mediasoup_client_flutter_example.

And started websocket with  'wss://v3demo.mediasoup.org:4443' without problems. 
But running with 'ws://localhost:3000/ws" echo or videoroom cant even start websocket.

Error:
`html_dart2js.dart:31775 WebSocket connection to 'ws://localhost:3000/ws?roomId=8927097d-7da5-4c15-9ea4-810f2bafb8b8&peerId=ODTBdRY`H' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received

**Comment by nazar-pc** [comment]
Rust examples have special example clients. They are not the same and are not compatible with other frontends (for mediasoup demo for instance), also we don't support alternative frontends to them. They are provided for 1 purpose: examples.

I don't think there is Rust bug here, as such please post your question as discussion on the [forum](https://mediasoup.discourse.group/) instead.
