### ISSUE TITLE
Can you optimize postinstall flow in npm script?

### ISSUE THREAD

**Issue by moonrailgun** [versatica/mediasoup#813]
## Feature Request

Its looks no check when run postinstall in trigger, in some reason, build binary file for worker is very hard. And when i run `npm install`. postinstall will auto trigger and try to build it.

https://github.com/versatica/mediasoup/blob/092ebee3b39605ef541b1f540697113ff8c401ba/npm-scripts.js#L119-L133

Can you add some logic to check is binary file build once? For example just check `mediasoup-worker` existed?

**Comment by ibc** [comment]
Please open a thread in the forum.
