### ISSUE TITLE
(slightly) improved DTLS timeout handling

### ISSUE THREAD

**Issue by fippo** [versatica/mediasoup#814]
while looking at libwebrtc's DTLS stuff relating to timeouts last week (@lgrahl made me!) I spotted some minor things that could be improved in mediasoup (and Janus so tagging @lminiero):

https://github.com/versatica/mediasoup/blob/c559b95848a17a5ab070b040f5733132596ece1e/worker/src/RTC/DtlsTransport.cpp#L1002

- there is no reason to do that. 0 means "now".
I assume that currently this will just run into the next timeout current and still works.

https://github.com/versatica/mediasoup/blob/v3/worker/src/RTC/DtlsTransport.cpp#L1422
- if that returns an error, the connection shall fail. Typically that only happens after DTLS runs into the 12-retries timeout which takes several minutes.

**Comment by ibc** [comment]
> https://github.com/versatica/mediasoup/blob/v3/worker/src/RTC/DtlsTransport.cpp#L1002
> 
> * there is no reason to do that. 0 means "now".
>   I assume that currently this will just run into the next timeout current and still works.

According to the docs:

```
/* DTLSv1_get_timeout queries the next DTLS handshake timeout. If there is a
--
  | * timeout in progress, it sets \|*out\| to the time remaining and returns one.
  | * Otherwise, it returns zero.
  | *
  | * When the timeout expires, call \|DTLSv1_handle_timeout\| to handle the
  | * retransmit behavior.
  | *
  | * NOTE: This function must be queried again whenever the handshake state
  | * machine changes, including when \|DTLSv1_handle_timeout\| is called. */
  | OPENSSL_EXPORT int DTLSv1_get_timeout(const SSL *ssl, struct timeval *out);
```

**Comment by ibc** [comment]
PR done https://github.com/versatica/mediasoup/pull/815
