### ISSUE TITLE
In RtpPacket.hpp, why ‘constexpr uint8_t MidMaxLength’ value is 8？

### ISSUE THREAD

**Issue by g-i-a-m** [versatica/mediasoup#816]
This setting will cause the MID extension in the RTP extension header of any packet forwarded by mediasoup to append 7 bytes of padding

**Comment by ibc** [comment]
And what's the problem? We cannot assume that all added header extensions are multiple of 4 bytes so we don't know how the total sum of all extensions will be.

If you want to further discuss this, please open a topic in the public forum. This is not a bug. Thanks.
