### ISSUE TITLE
SimulcastConsumer fails to switch spatial layers

### ISSUE THREAD

**Issue by dsdolzhenko** [versatica/mediasoup#824]
### Your environment

- Operating system: macOS 12.3.1, Debian/Linux 10.11 amd64
- gcc version: (Debian 8.3.0-6) 8.3.0
- clang version: 13.0.0 x86_64-apple-darwin21.4.0
- mediasoup version: 3.9.13
- mediasoup client version: 3.6.50

### Issue description

As a result of a race condition in `SendRtpPacket` method, `SimulcastConsumer` may get into a loop repeatedly failing to switch current spatial layer. Here is an extract from a log demonstrating the issue. 

I've modified some log messages a bit so it would be easier to spot it. 
 - `sync key frame received` messages besides the obvious, contain `sl` - processing packet's spatial layer, `csl` - current spatial layer, `tsl` - target spatial layer, and `rsl` - reference spatial layer. 
 - `update tsOffset` messages indicate the moment when `SimulcastConsumer` resets its `tsOffset` used to overwrite re-transmitting packets' timestamps

```
19:38:08.435Z INFO: RTC::SimulcastConsumer::UpdateTargetLayers() | target layers changed [spatial:1, temporal:0, consumerId:cb7d0a76-3207-43d9-a995-9fa5ede66500]
19:38:08.435Z INFO: RTC::RtpStreamRecv::RequestKeyFrame() | sending PLI [ssrc:4212764866]

19:38:08.451Z INFO: RTC::SimulcastConsumer::SendRtpPacket() | sync key frame received [id:cb7d0a76-3207-43d9-a995-9fa5ede66500, producerId:03e28eee-ae15-49ff-bd2f-117238055045, ssrc:258980700, seq:6644, ts:2394201754, sl: 1, csl: 0, tsl: 1, rsl: 1]
19:38:08.451Z WARN: RTC::SimulcastConsumer::SendRtpPacket() | cannot switch stream due to too high RTP timestamp extra offset needed (8910), requesting keyframe [id:cb7d0a76-3207-43d9-a995-9fa5ede66500, producerId:03e28eee-ae15-49ff-bd2f-117238055045]
19:38:08.452Z INFO: RTC::RtpStreamRecv::RequestKeyFrame() | sending PLI [ssrc:4212764866]

19:38:09.484Z INFO: RTC::SimulcastConsumer::SendRtpPacket() | sync key frame received [id:cb7d0a76-3207-43d9-a995-9fa5ede66500, producerId:03e28eee-ae15-49ff-bd2f-117238055045, ssrc:258980699, seq:19018, ts:3640044774, sl: 0, csl: 0, tsl: 1, rsl: 1]
19:38:09.484Z INFO: RTC::SimulcastConsumer::SendRtpPacket() | update tsOffset 1245744110 -> 0
19:38:09.484Z INFO: RTC::SimulcastConsumer::SendRtpPacket() | sending sync packet [ssrc:715563397, seq:2722, ts:3640044774] from original [ssrc:258980699, seq:19018, ts:3640044774]

19:38:09.487Z INFO: RTC::SimulcastConsumer::SendRtpPacket() | sync key frame received [id:cb7d0a76-3207-43d9-a995-9fa5ede66500, producerId:03e28eee-ae15-49ff-bd2f-117238055045, ssrc:258980700, seq:6713, ts:2394294724, sl: 1, csl: 0, tsl: 1, rsl: 1]
19:38:09.487Z WARN: RTC::SimulcastConsumer::SendRtpPacket() | cannot switch stream due to too high RTP timestamp extra offset needed (1245753020), requesting keyframe [id:cb7d0a76-3207-43d9-a995-9fa5ede66500, producerId:03e28eee-ae15-49ff-bd2f-117238055045]
19:38:10.486Z INFO: RTC::RtpStreamRecv::RequestKeyFrame() | sending PLI [ssrc:4212764866]

19:38:10.514Z INFO: RTC::SimulcastConsumer::SendRtpPacket() | sync key frame received [id:cb7d0a76-3207-43d9-a995-9fa5ede66500, producerId:03e28eee-ae15-49ff-bd2f-117238055045, ssrc:258980699, seq:19044, ts:3640137744, sl: 0, csl: 0, tsl: 1, rsl: 1]
19:38:10.514Z INFO: RTC::SimulcastConsumer::SendRtpPacket() | update tsOffset 0 -> 0
19:38:10.514Z INFO: RTC::SimulcastConsumer::SendRtpPacket() | sending sync packet [ssrc:715563397, seq:2723, ts:3640137744] from original [ssrc:258980699, seq:19044, ts:3640137744]

19:38:10.516Z INFO: RTC::SimulcastConsumer::SendRtpPacket() | sync key frame received [id:cb7d0a76-3207-43d9-a995-9fa5ede66500, producerId:03e28eee-ae15-49ff-bd2f-117238055045, ssrc:258980700, seq:6782, ts:2394387694, sl: 1, csl: 0, tsl: 1, rsl: 1]
19:38:10.516Z WARN: RTC::SimulcastConsumer::SendRtpPacket() | cannot switch stream due to too high RTP timestamp extra offset needed (1245753020), requesting keyframe [id:cb7d0a76-3207-43d9-a995-9fa5ede66500, producerId:03e28eee-ae15-49ff-bd2f-117238055045]
19:38:10.517Z INFO: RTC::RtpStreamRecv::RequestKeyFrame() | sending PLI [ssrc:4212764866]
```

The last block of log messages containing `cannot switch stream due to too high RTP timestamp extra offset needed (1245753020)` gets repeated over and over again even though target layer stays the same.

In this particular case the following happens:
- The consumer is requested to change its target spatial layer
- The consumer initiates layer switch and requests a key-frame for target layer in order to sync RTP timestamps.
- Upon receiving the key-frame the consumer calculates `tsExtraOffset` which turns out to be too high to switch layers.
- The consumer requests a new key-frame for the target layer to try recalculate `tsExtraOffset` one more time.
- Next, the interesting happens. Instead of a key-frame for the target layer, the consumer receives a key-frame for the current layer and since `syncRequired` flag is on it resets `tsOffset` to `0`.
- Re-transmitting the packet forward the consumer indirectly changes `RtpStreamRecv`'s `maxPacketTs` which is used to calculate `tsExtraOffset`. As a result `maxPacketTs` jumps forward on a delta equals value `tsOffset` previously had.
- Next, the consumer finally receives the requested key-frame and tries to switch layers again.
- However, it fails due to too high RTP timestamp extra offset needed to sync the streams.
- It requests a new key-frame for the target layer one more time.
- Then, it receives a key-frame for the current layer before a key-frame for the target-layer and the cycle begins over.

As a result, the video stream on the consumer side is either completely frozen or displaying key-frames only. The former happens because of the wrongly calculated `tsOffset`, the latter because every time the consumer receives a key-frame for the target layer  it switches `syncRequired` flag and while it is on, the consumer drops all packets except those carrying key-frames.

`SimulcastConsumer` has a flag `keyFrameForTsOffsetRequested` which is supposed to prevent repeated requests of a key-frame for a target layer when an adequate `tsExtraOffset` cannot be computed. However, every time we receive a key-frame, even though it is from a different layer, `keyFrameForTsOffsetRequested` flag gets reset.

While investigating the issue I found out that `libwebrtc` [deliberately](https://source.chromium.org/chromium/_/webrtc/src.git/+/e62a08a87a6f21672b2ae8ba25632007f417a3f1) sends key frames for **all layers** no matter for what layer a key-frame is requested.However, even if we ignore it, there is no guarantee that a key-frame for current layer won't be received before a key-frame for target layer.

*Here I might made a number of assumptions about the details of implementation that may be wrong, please correct me if it is so.*

**Comment by ibc** [comment]
Fixed in https://github.com/versatica/mediasoup/pull/825
