### ISSUE TITLE
Memory fragmentation in mediasoup

### ISSUE THREAD

**Issue by chenwdong** [versatica/mediasoup#828]
There is no memory leak detected with Valgrind, but the memory has been slowly rising and cannot be reduced. Is it related to memory fragmentation? Storageitem has been frequently applied for. Is this the problem here? Are there any good ideas or suggestions to solve this problem?

**Comment by ibc** [comment]
Please read this: https://github.com/versatica/mediasoup/issues/769

This is gonna be fixed once we merge an in-progress PR that will change the buffer implementation.
