### ISSUE TITLE
Mediasoup installation error on Windows 10

### ISSUE THREAD

**Issue by sayamk3004** [versatica/mediasoup#829]
![IMG20220607081545](https://user-images.githubusercontent.com/69592671/172285935-8aa5d90b-266e-4b01-9aa9-c68e70b9effb.jpg)
![IMG20220607081627](https://user-images.githubusercontent.com/69592671/172285949-02a6f1f2-8f10-4cec-af32-c4e758c36551.jpg)
![IMG20220607081639](https://user-images.githubusercontent.com/69592671/172285975-886e8aef-3e3c-49bd-93c9-cd9db27b8fc8.jpg)
![IMG20220607081647](https://user-images.githubusercontent.com/69592671/172286000-c9c0882f-225d-4e30-afea-fa81fae19277.jpg)
This is what's happening when I try to hit npm install on server folder.
Ps Below is the list of things I did
1)Install basic packages from mingw
2) install latest python version make sure to path in env variables
3) pip3 install --user meson
4)pip install meson
5)set env variabe path to c:/windows/microsoft.net/framework64/v.1234/
6) set env variable path to c:/mingw/msys/1.0/bin
7) npm cache clean -- force
8) delete node modules from server folder
9) npm install

**Comment by nazar-pc** [comment]
Please search for similar topics on the forum and create a tread there with logs as text instead of screenshots

**Comment by sayamk3004** [comment]
Thank you for your response. I could finally install the mediasoup on my
windows 10.

*Thanks for giving us such an amazing system. I would be greatly favoured
if I could know:*

* How do I also assign viewers on the demo version of the website? Like I
want it to be like multi host live streaming. Where there producers can be
one to few and viewers, who just sees it, can be somewhere around
500-1000+.*

*Please help me with this, I'm right on the place to implement this
mediasoup technology onto next big thing in the industry *

**Comment by nazar-pc** [comment]
Question - on the forum
