### ISSUE TITLE
SetMaxOutgoingBitrate does not work if set before first consumer created

### ISSUE THREAD

**Issue by penguinol** [versatica/mediasoup#831]
https://github.com/versatica/mediasoup/blob/f147f77efe29d2ef1fadec91b277025b47d0ee99/worker/src/RTC/Transport.cpp#L633-L646
According to current code, the max outgoing bitrate will be set only when tccClient is created.
And set max incoming bitrate has not this limitation
https://github.com/versatica/mediasoup/blob/f147f77efe29d2ef1fadec91b277025b47d0ee99/worker/src/RTC/Transport.cpp#L593-L617
I think it's because we want to validate the max bitrate in tccClient->SetMaxOutgoingBitrate.

**Comment by ibc** [comment]
@penguinol see PR https://github.com/versatica/mediasoup/pull/833
