### ISSUE TITLE
Support more SRTP cipher suites

### ISSUE THREAD

**Issue by nazar-pc** [versatica/mediasoup#835]
## Feature Request

We currently support these:
* SRTP_AES128_CM_HMAC_SHA1_80
* SRTP_AES128_CM_HMAC_SHA1_32

We should also support more modern and more secure options:
* SRTP_AEAD_AES_128_GCM
* SRTP_AEAD_AES_256_GCM

Someone was already asking about this on the forum, I think it is time to make it happen.

**Comment by ibc** [comment]
In `DtlsTransport.cpp`:

```c++
	thread_local std::vector<DtlsTransport::Fingerprint> DtlsTransport::localFingerprints;
	std::vector<DtlsTransport::SrtpCryptoSuiteMapEntry> DtlsTransport::srtpCryptoSuites =
	{
		{ RTC::SrtpSession::CryptoSuite::AEAD_AES_256_GCM, "SRTP_AEAD_AES_256_GCM" },
		{ RTC::SrtpSession::CryptoSuite::AEAD_AES_128_GCM, "SRTP_AEAD_AES_128_GCM" },
		{ RTC::SrtpSession::CryptoSuite::AES_CM_128_HMAC_SHA1_80, "SRTP_AES128_CM_SHA1_80" },
		{ RTC::SrtpSession::CryptoSuite::AES_CM_128_HMAC_SHA1_32, "SRTP_AES128_CM_SHA1_32" }
	};
```

😀

**Comment by nazar-pc** [comment]
However, `SrtpCryptoSuite` in both TypeScript and Rust only shows the first two, also plain transport for some reason only supports the first two and pipe transport is limited to just `SRTP_AES128_CM_HMAC_SHA1_80` while more modern and faster options exist.

**Comment by ibc** [comment]
Really?? Then that's a bug or a missing thing.

**Comment by ibc** [comment]
Here: https://github.com/versatica/mediasoup/pull/837
