### ISSUE TITLE
Can't install mediasoup in docker

### ISSUE THREAD

**Issue by un-hongly** [versatica/mediasoup#858]
Hi,
Please help me with this. I'm struggling to install mediasoup when building a docker image. build-essential, python3-pip are installed and it was able to install mediasoup before but not now.

```
FROM node:16.0.0
ARG NPM_TOKEN
ARG NODE_ENV
RUN apt update
RUN apt install -y build-essential python3-pip
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package.json .
RUN npm install
ADD . .
EXPOSE 3000
CMD ["node", "index.js"]
```

This is the error log file from my pipeline:
[pipelineLog-{4b482e12-c995-403d-8d4e-297634f478ab}.txt](https://github.com/versatica/mediasoup/files/9040757/pipelineLog-.4b482e12-c995-403d-8d4e-297634f478ab.txt)

**Comment by ibc** [comment]
Questions in the forum.
