### ISSUE TITLE
Worker core dump in v3.10.2

### ISSUE THREAD

**Issue by mizoRC** [versatica/mediasoup#864]
### Your environment

- Operating system: Ubuntu 20.04 / macOS Monterey
- Node version: 14.15.4 / 16.15.1
- npm version:  6.14.10 / 6.14.17
- gcc/clang version: gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) / Apple clang version 13.1.6 (clang-1316.0.21.2)
- mediasoup version: 3.10.2
- mediasoup-client version: 3.6.53

### Issue description

Open a conference with one user, everything it's ok. Then add a second user and get mediasoup worker died:

![Captura de Pantalla 2022-07-05 a las 11 24 25](https://user-images.githubusercontent.com/17248343/177297536-646835b9-95a2-4668-af17-d4e7199c704f.png)

I have tried to get core dump report from the path that you put in the doc (/Users/USER/Library/Logs/DiagnosticReports), but there are only Siri crashes there apparently. (Retired folder is empty)

![image](https://user-images.githubusercontent.com/17248343/177298264-a8ddd3d2-71b0-4bc6-9e49-d57b65f155e7.png)

Thank u!

**Comment by nazar-pc** [comment]
Likely duplicate of #861

**Comment by mizoRC** [comment]
Honestly I don't think so, in our case whenever we create a conference, adding a second participant gives the worker died error. Unlike that other issue that says it happens arbitrarily, in our case it always replicates.

**Comment by ibc** [comment]
There is very little we can do if a core dump is not provided. Zero info provided.

**Comment by mizoRC** [comment]
Like I say in the bug report, I have tried to get core dump report as is described on mediasoup documentation (https://mediasoup.org/support/#crashes-in-mediasoup-get-a-core-dump) but there is no log file. How can i get core dump report in other way?

**Comment by ibc** [comment]
Problem is that now you have reported a crash with zero info and we are now discussing here how to get a core dump. Steps in that link you reference may vary from one OS to another, no idea, but here we need the info about the crash so we know what the issue is.

**Comment by mizoRC** [comment]
Fixed on 3.10.3

**Comment by ibc** [comment]
ok, so it was the SimpleConsumer fix. Thanks for confirming.
