### ISSUE TITLE
Recv video delay when sender's outbound packets lost

### ISSUE THREAD

**Issue by bianxg** [versatica/mediasoup#868]
### Your environment

- Operating system: Ubuntu
- Node version:
- npm version:
- gcc/clang version:
- mediasoup version: V3
- mediasoup-client version: 

### Issue description
1 webapp A, B and C are in the conference room. Using clumsy to drop outbound packets with 12% lost rate on webapp A's host.
2 Both webapp B and C see A's video have same 2 or 3 seconds delay sometimes. (sometimes recv video delay is low)

Question:
1 Where the delayed packets are buffered, mediasoup or webapp B and C?
2 How to reduce the recv video delay by modify mediasoup's code or config?

Thanks.

**Comment by bianxg** [comment]
Any clues of video delay when outbound packets lost?

**Comment by bianxg** [comment]
Any clues of video delay when outbound packets lost?

**Comment by nazar-pc** [comment]
Use forum for questions
