### ISSUE TITLE
Crash at assertion 'StorageItemBuffer contains more than 65535 entries'

### ISSUE THREAD

**Issue by satoren** [versatica/mediasoup#882]
## Bug Report
It occurred once in three days on ten servers.
```
(ABORT) RTC::RtpStreamSend::Insert() | failed assertion `this->buffer.size() <= MaxSeq': StorageItemBuffer contains more than 65535 entries
```

### Your environment

- Operating system: Ubuntu 20.04.2
- Node version:
- npm version:
- gcc/clang version:
- mediasoup version:Rust version mediasoup: 0.10.0 mediasoup-sys: 0.4.2
- mediasoup-client version: 3.6.50

### Issue description
==== updated ====
At the time of the crash, there were  6 producers and 17 consumers.
It may have continued to produce for a long time because the number of producers did not increase or decrease during the low user time period. (I do not know for sure, as I do not have produce time metrics.)

**Comment by nazar-pc** [comment]
Likely related to #840

**Comment by jmillan** [comment]
Absolutely, yes

**Comment by jmillan** [comment]
> I'll add more details later.

Yes please, any way we can reproduce it would be very helpful.

**Comment by jmillan** [comment]
I'll use the fuzzer in order to try to reproduce the issue.

**Comment by jmillan** [comment]
Update: crash reproduced with the fuzzer. Will be updating here.

**Comment by jmillan** [comment]
Issue detected, will actively work on this tomorrow morning.

**Comment by jmillan** [comment]
New version with the fix has been released.

**Comment by nazar-pc** [comment]
New mediasoup-sys version was published as well
