### ISSUE TITLE
Error: uv_udp_bind() failed [transport:udp, ip:'35.190.192.36', port:50000]: address not available [method:worker.createWebRtcServer]

### ISSUE THREAD

**Issue by ollyde** [versatica/mediasoup#888]
Deploying a MediaSoup server via Docker on Google Cloud Compute engine the ```uv_udp_bind``` always fails.

The firewall is set to open all ports and IP address ranges.

Tried both Debian and Ubuntu container optimized boot images.

Running with command 
`docker run -it -e "GCP_PROJECT=bap-prod-352014" -e "GOOGLE_CLOUD_PROJECT=bap-prod-352014" -e "MEDIA_SERVER=true" --net host -t eu.gcr.io/prod-352014/api`

Running locally seems to be fine.

Any ideas?

**Comment by ibc** [comment]
Please don't open an issue in GitHub due to usage issues. Ask in the public forum.

**Comment by ollyde** [comment]
@ibc ok thanks, I've posted on discourse. Awaiting moderator..

**Comment by ollyde** [comment]
For reference in-case anyone else is stuck

https://mediasoup.discourse.group/t/error-uv-udp-bind-failed-transport-udp-ip-35-190-192-36-port-50000-address-not-available-method-worker-createwebrtcserver/4475/3
