### ISSUE TITLE
Mediasoup demo - WebSocket connection failed

### ISSUE THREAD

**Issue by webRTCv1** [versatica/mediasoup#890]
## Bug Report

[Mediasoup demo](https://v3demo.mediasoup.org/) - `WebSocket connection failed`

### Issue description

I'm trying [mediasoup demo](https://v3demo.mediasoup.org/), but when i join with any browser, has `WebSocket connection failed`

![mediasoup-demo](https://user-images.githubusercontent.com/104159437/185440286-f5dd6749-87ca-41bc-ac2c-e7de16580a32.png)

Not sure if this is a right place to report it?

Anyway Thank you so much for this fantastic media server!

Regards

**Comment by ibc** [comment]
Use the public forum as stated in the issue template.

**Comment by j2l** [comment]
FYI about newbies like me: I followed the website to the demo, then finding this github project and reading this very same issue I have, and NOT finding any forum on the website or in the issue. :sob:
