### ISSUE TITLE
Provide more context for disambiguation to consumer "layerschange" event

### ISSUE THREAD

**Issue by ggarber** [versatica/mediasoup#897]
## Feature Request

When the application receives the `consumer.on('layerschange')` event with no layers (spatialLayer=-1, temporalLayer=-1) there are at least two possible reasons for that:

1/ The receiver doesn't have enough bandwidth to receive that video and it has been disabled.   Usually in these cases you want to show something in the UI like "Video disabled for network reasons".

2/ The sender is not sending any video layers (his computer is frozen, his camera broke....).   Usually in these cases you want to show something different like the last video frame frozen/blurred or a message like "Partcipants video not working".

As far as I know it is not possible to differentiate both cases with the `layerschange` event.   The suggestion is to extend the event with an additional field `availableSpatialLayers` (or maybe a list of all the layers if we want to make it more flexible) so that the application can disambiguate between 1/ and 2/.

I can work on a patch if this makes sense but I want to make sure it is a reasonable approach.

**Comment by ibc** [comment]
You can check consumer.score which includes producer score, which is 0 in those cases.

**Comment by ggarber** [comment]
Looking at this code, can't score be also 0 if packets lost == packets received?

```
		auto deliveredRatio = static_cast<float>(received - lost) / static_cast<float>(received);
		auto score          = static_cast<uint8_t>(std::round(std::pow(deliveredRatio, 4) * 10));
```

If thats correct, How do you differentiate bad network (50% packet loss) from no video received?

In addition to that the score is not very explicit (the algorithm is black magic afaict) and requires  implementing logic in the application to handle and combine both events ('score' and 'layerschange').

So maybe you could reconsider this.

Anyway using the 'score' is better than nothing for sure, so I will use that as a workaround for now.  Thank you! 😘

**Comment by ibc** [comment]
When consumer layers switch to -1 -1 the producer score is guaranteed to be 0 (in case the lack of layers is due to producer uplink issues). Isn't that enough?
