### ISSUE TITLE
how let mediasoup to support full ice with sdp？

### ISSUE THREAD

**Issue by xujingzhou** [versatica/mediasoup#925]
For special reasons, I need mediasoup to support full-ice with sdp. How should I solve this problem?

**Comment by nazar-pc** [comment]
Last warning, if you ignore rules you'll be banned

**Comment by xujingzhou** [comment]
I'm really sorry that this accidentally sent twice confused you!  Could you please send me the address discussed for this related problem? Thanks

**Comment by ibc** [comment]
As told before please search in the forum and keep posting in the forum rather than in GitHub.
