### ISSUE TITLE
Failed to parse notification error with webrtc datachannel

### ISSUE THREAD

**Issue by valliscooper** [versatica/mediasoup#930]
When using a webrtc datachannel I noticed with 0.11.1 rust crate each datachannel message causes an error in the log:
ERROR    mediasoup::router::data_consumer    - Failed to parse notification: invalid type: string "0", expected u32 at line 1 column 107

It looks to me like the Notification enum BufferedAmountLow member buffered_amount which is an i32 can no longer be deserialized from json containing a string instead of a number. 

It looks like this error wasn't there with the 0.10.0 rust crate

**Comment by nazar-pc** [comment]
This is not good. I'll try to look into this closer to the end of the week, feel free to send a PR if you fix it sooner.

**Comment by valliscooper** [comment]
[See also similar observation](https://github.com/serde-rs/json/issues/317#issuecomment-300251188)

Cheers.

**Comment by valliscooper** [comment]
Excellent. Thanks.
