### ISSUE TITLE
Worker crash due to std::out_of_range exception

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#932]
## Bug Report

mediasoup worker crashed in the demo site (v3demo.mediasoup.org) running latest 3.10.11.

### Your environment

- Operating system: Linux Debian
- Node version: v16.13.1
- gcc/clang version: gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
- mediasoup version: 3.10.11

### Issue description

No idea where this happened:

```
2022-10-26T07:22:05.449Z mediasoup:ERROR:Worker (stderr) terminate called after throwing an instance of '
2022-10-26T07:22:05.449Z mediasoup:ERROR:Worker (stderr) std::out_of_range
2022-10-26T07:22:05.449Z mediasoup:ERROR:Worker (stderr) '
2022-10-26T07:22:05.450Z mediasoup:ERROR:Worker (stderr)   what():  
2022-10-26T07:22:05.450Z mediasoup:ERROR:Worker (stderr) vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 2)
2022-10-26T07:22:05.452Z mediasoup:ERROR:Worker worker process died unexpectedly [pid:18091, code:null, signal:SIGABRT]
```

**Comment by ibc** [comment]
`std::out_of_range` exception can happen when attempting to read `someVector.at(idx)` if `idx >= someVector.size()`. Maybe also in other cases.

**Comment by jmillan** [comment]
NOTE: Such argument passed to `at()` (18446744073709551615) is `FFFFFFFFFFFFFFFF`, which is 8 bytes set to one.

There are just few places where we do 'at()' on a vector. I'm looking at it, but I don't see any possible place this could happen.

**Comment by ibc** [comment]
OMG I'm also looking for all `.at()` usages...

**Comment by jmillan** [comment]
Indeed only `size_t` has 8 bytes and IMHO the only place where this can happen is [here](https://github.com/versatica/mediasoup/blob/v3/worker/src/RTC/RTCP/FeedbackRtpTransport.cpp#L404) where we are providing a `size_t` as argument to `vector.at()`

**Comment by ibc** [comment]
**NOTE:** `std::out_of_range` can also be produced by:

- `std::map<Key,T,Compare,Allocator>::at(idx)`
- `std::deque::at(idx)`
- `std::bitset<N>::flip(N)`
- `std::bitset<N>::test(N)`
- `std::basic_string<CharT,Traits,Allocator>::at(idx)`

**Comment by ibc** [comment]
> Indeed only `size_t` has 8 bytes and IMHO the only place where this can happen is [here](https://github.com/versatica/mediasoup/blob/v3/worker/src/RTC/RTCP/FeedbackRtpTransport.cpp#L404) where we are providing a `size_t` as argument to `vector.at()`

Will try to reproduce it by forcing a wrong  `deltaIdx` value.

**Comment by jmillan** [comment]
No @ibc , I think the issue is definitely here:

https://github.com/versatica/mediasoup/blob/v3/worker/src/RTC/SimulcastConsumer.cpp#L630

We don't need to execute the loop if `this->producerRtpStreams.size() == 0`

```c++
 size_t size = 0 - 1;
 std::cout << "size: " << size;
```
size: 18446744073709551615`

**Comment by jmillan** [comment]
Writing a PR.

**Comment by ibc** [comment]
`SimpleConsumer::IsActive()` and `SvcConsumer::IsActive()` return `false` if the `RtpStream` in the `Producer` doesn't exist:
![CleanShot-2022-10-26-at-17 04 07@2x](https://user-images.githubusercontent.com/16191/198063453-cf1af579-9bc9-4834-834b-bef84fc55eb0.png)
![CleanShot-2022-10-26-at-17 03 25@2x](https://user-images.githubusercontent.com/16191/198063480-f47b50a2-b61f-49aa-8bf4-30c56c060263.png)

However in `SimulcastConsumer` we don't verify whether there is at least one stream in the `Producer`:
<img width="838" alt="CleanShot-2022-10-26-at-17 04 29@2x" src="https://user-images.githubusercontent.com/16191/198063646-6e1c9814-ced8-4705-902c-2855dbbc2cd4.png">

...and hence `SimulcastConsumer::IsActive()` may return `true` when there are 0 streams in the `Producer`. We must make `IsActive()` return `false` if there are no streams in the `Producer` for consistency. And if we do that, the issue will be fixed since:
![CleanShot-2022-10-26-at-17 07 41@2x](https://user-images.githubusercontent.com/16191/198063987-0e215f79-878e-4ef7-8be3-d0c2f1427983.png)

**Comment by CosmosisT** [comment]
I'll say I haven't crashed once, I don't use simulcast or SVC!

**Comment by ibc** [comment]
Working on branch https://github.com/versatica/mediasoup/tree/fix-issue-932 in which I've fixed `SimulcastConsumer::IsActive()` as explained above.

However, as Jose told me, this is not the reason of this crash since the error is clear:

`vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 2)`

and this is not the case.

**Comment by ibc** [comment]
![CleanShot-2022-10-26-at-17 35 20@2x](https://user-images.githubusercontent.com/16191/198070772-ee05d8de-d05a-4b7d-97f4-3924b9ca26f2.png)

@jmillan do I miss something here? We are casting to `size_t` (which is unsigned number) and then checking whether it's >= 0, which is always true by definition... However this should produce TONS of crashes already if wrong...

**Comment by jmillan** [comment]
Yes, `sIdx` will be always initialized 0 or positive, but in each iteration we are decreasing it and only want to run the loop body while > 0.

**Comment by jmillan** [comment]
So we check the desired bitrate on streams from the highest spatial layer to the lowest.

**Comment by ibc** [comment]
so... it's wrong right?

**Comment by ibc** [comment]
> Yes, `sIdx` will be always initialized 0 or positive, but in each iteration we are decreasing it and only want to run the loop body while > 0.

No, it will always be >0 since if 0 we would reach this line (`IsActive()` returned false above so we exit).

**Comment by ibc** [comment]
Last item fixed here: https://github.com/versatica/mediasoup/commit/956def7f443ae48e3a446315af0e1524e66b4da2

**Comment by ibc** [comment]
More info:

> SIZE_MAX (C99): maximum value of object of size_t type (macro constant)

```c++
#include <limits.h>

MS_ERROR("------- SIZE_MAX: %zu", SIZE_MAX);
```

Output:
`------- SIZE_MAX: 18446744073709551615`

And the above crash said:

`vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 2)`

So the fix in https://github.com/versatica/mediasoup/pull/933/ will indeed fix the regression in this commit https://github.com/versatica/mediasoup/commit/f4b3558aaffbccde9135c24aefacfc13face6f2c one month ago.
