### ISSUE TITLE
new delete not match

### ISSUE THREAD

**Issue by o-u-p** [versatica/mediasoup#959]
## Bug Report
asan option:-fsanitize=address, -fsanitize=undefined

### Your environment

- Operating system:
linux gcc-8.2

### Issue description

(field_trial.cc:140): Setting field trial string:WebRTC-Bwe-AlrLimitedBackoff/Enabled/                                                                                                                              
=================================================================
==30913==ERROR: AddressSanitizer: new-delete-type-mismatch on 0x60e000003a00 in thread T0:
  object passed to delete has wrong type:
  size of the allocated type:   152 bytes;
  size of the deallocated type: 96 bytes.
    #0 0x7f29156fe625 in operator delete(void*, unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10a625)
    #1 0x5586ace9cb1c in onClose ../../../src/handles/Timer.cpp:20
    #2 0x5586adec8885 in uv__finish_close ../../../subprojects/libuv-v1.43.0/src/unix/core.c:307
    #3 0x5586adec88cb in uv__run_closing_handles ../../../subprojects/libuv-v1.43.0/src/unix/core.c:321
    #4 0x5586adec8adb in uv_run ../../../subprojects/libuv-v1.43.0/src/unix/core.c:399
    #5 0x5586acddeb6e in DepLibUV::RunLoop() ../../../src/DepLibUV.cpp:100
    #6 0x5586ace3a107 in Worker::Worker(Channel::ChannelSocket*, PayloadChannel::PayloadChannelSocket*) ../../../src/Worker.cpp:42
    #7 0x5586acdc2280 in mediasoup_worker_run ../../../src/lib.cpp:176
    #8 0x5586adb98363 in main ../../../src/main.cpp:25
    #9 0x7f2914794bba in __libc_start_main ../csu/libc-start.c:308
    #10 0x5586acdc1749 in _start (/root/project/mediasoup/mediasoup-worker+0x4500749)

0x60e000003a00 is located 0 bytes inside of 152-byte region [0x60e000003a00,0x60e000003a98)
allocated by thread T0 here:
    #0 0x7f29156fd19f in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10919f)
    #1 0x5586ace9cb85 in operator() ../../../src/handles/Timer.cpp:30
    #2 0x5586acea2e5e in _M_invoke /usr/include/c++/8/bits/std_function.h:297
    #3 0x5586acddf176 in std::function<void ()>::operator()() const /usr/include/c++/8/bits/std_function.h:687
    #4 0x5586acdde6af in FlushTasks ../../../src/DepLibUV.cpp:39
    #5 0x5586adec80d0 in uv__async_io ../../../subprojects/libuv-v1.43.0/src/unix/async.c:163
    #6 0x5586adedc7fb in uv__io_poll ../../../subprojects/libuv-v1.43.0/src/unix/epoll.c:374
    #7 0x5586adec8ab7 in uv_run ../../../subprojects/libuv-v1.43.0/src/unix/core.c:389
    #8 0x5586acddeb6e in DepLibUV::RunLoop() ../../../src/DepLibUV.cpp:100
    #9 0x5586ace3a107 in Worker::Worker(Channel::ChannelSocket*, PayloadChannel::PayloadChannelSocket*) ../../../src/Worker.cpp:42
    #10 0x5586acdc2280 in mediasoup_worker_run ../../../src/lib.cpp:176
    #11 0x5586adb98363 in main ../../../src/main.cpp:25
    #12 0x7f2914794bba in __libc_start_main ../csu/libc-start.c:308

**Comment by ibc** [comment]
We are replacing libwebrtc version in a separate branch. Anyway it's hard to check if there is any possible bug with this short description. Let's close it.

**Comment by o-u-p** [comment]
> We are replacing libwebrtc version in a separate branch. Anyway it's hard to check if there is any possible bug with this short description. Let's close it.

![image](https://user-images.githubusercontent.com/22117027/203690213-26177629-b2ac-41f2-bbc8-659ccf4f1289.png)

**Comment by ibc** [comment]
What is exactly wrong there?

**Comment by ibc** [comment]
@o-u-p yo have attached an image of a modified version of mediasoup that I don't know where it comes from. You wrote absolutely anything in this issue but just copy&pasted things into it. It's completely impossible to understand this. No action can be taken here.

**Comment by o-u-p** [comment]
> What is exactly wrong there?

The main code remains. I think the current version may have this problem too, you can try build mediasoup with asan option and run.

**Comment by ibc** [comment]
@o-u-p I'm afraid you have not detailed any issue but just posted some output and an screenshot of your modified version of mediasoup. No idea what you are reporting, sorry.
