### ISSUE TITLE
Document Rust cargo commands in Building.md

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#961]
`doc/Building.md` documents all `npm` and `make` commands, however it lacks documentation of available Rust `cargo` commands.

While developing I'm having bad experiences running `cargo test`. It takes **long time** every time building `mediasoup-sys`. Running it as follows helps: ` KEEP_BUILD_ARTIFACTS=1 cargo test`. However this is not documented.

Could we have the list of useful `cargo` commands documented in `Building.md`? I mean: build, lint, format, test, etc commands.

**Comment by nazar-pc** [comment]
There are no special cargo commands to learn, `cargo build`, `cargo test` is what most developers use anyway, it is like describing that `npm install` exists, which working with Node you hopefully already know.

`KEEP_BUILD_ARTIFACTS=1` is the only special parameter really supported, we can document it, sure.  Without `KEEP_BUILD_ARTIFACTS=1` you compile C++ from scratch every time, which is indeed very time consuming.

**Comment by ibc** [comment]
> There are no special cargo commands to learn, `cargo build`, `cargo test` is what most developers use anyway, it is like describing that `npm install` exists, which working with Node you hopefully already know.

Other than `npm install` we document tons of custom NPM scripts: https://github.com/versatica/mediasoup/blob/v3/doc/Building.md#npm-scripts

`npm run lint` (for instance) is not an "standard" npm script at all.



> `KEEP_BUILD_ARTIFACTS=1` is the only special parameter really supported, we can document it, sure. Without `KEEP_BUILD_ARTIFACTS=1` you compile C++ from scratch every time, which is indeed very time consuming.

Yes, that's exactly the reason I ask these things to be documented, because I didn't know it and it's hell to code Rust in mediasoup without knowing it.

**Comment by nazar-pc** [comment]
> we document tons of custom NPM scripts

With Rust it is a bit easier; `cargo fmt` is standard formatting tool, `cargo clippy` is a standard linter, I believe both are installed by default. There isn't really anything special used except that single environment variable.

**Comment by ibc** [comment]
For instance, why does "cargo test" rebuild C++ code from scratch? It doesn't happen in "npm test". If a contributor works in Rust code he/she will face this problem and it's not documented anywhere.

**Comment by nazar-pc** [comment]
`cargo test` will always make sure to compile all the sources if code changes, it always works that way, whether you have C++ in your project or not. `npm test` doesn't have a notion of compilation, so, obviously, it'll not do anything.
Again, I'll create a PR documenting environment variable, but there isn't anything else to document IMO.

**Comment by ibc** [comment]
> cargo test will always make sure to compile all the sources if code changes

But why does it somehow invoke "make clean" before calling "make"?

**Comment by nazar-pc** [comment]
It does that after, not before: https://github.com/versatica/mediasoup/blob/c738b5e3797811937afdc30f6c746a5613ab9dbb/worker/build.rs#L131-L142

Most users are not mediasoup developers. They install package from crates.io and from there on it is immutable and will not be recompiled. As such there is no need to store anything other than static library, so by default it does cleanup automatically.

For mediasoup hacking that is indeed undesirable and inconvenient because you'll be recompiling a lot.
