### ISSUE TITLE
Media soup crashed in Windows Environment

### ISSUE THREAD

**Issue by ahmedbhesaniya97** [versatica/mediasoup#965]
@ibc 
I just open your Media soup Demo(https://v3demo.mediasoup.org/?roomId=ciufcgsp) from windows machine and it just restart the system while doing screen share or enable webcam, also i tested with i3 and i5 intel processor both processor has same results with Media soup demo.

**Machine Configuration :** 
OS : Windows 10
Processor : i3 and i5 intel
Browser : Chrome and Microsoft Edge

![image_2](https://user-images.githubusercontent.com/65531261/205630813-d48a703b-b720-4a57-b191-be103f6cfe05.png)

![image_1](https://user-images.githubusercontent.com/65531261/205630807-4b1abc16-1522-4baa-8fa6-971d5e07bf24.png)

**Comment by nazar-pc** [comment]
There must be a bug in your OS, browser or hardware, there is no way for page to crash or restart your computer otherwise. There is nothing to fix in mediasoup here.

**Comment by ahmedbhesaniya97** [comment]
@nazar-pc @ibc 
I have 2-3 windows machine, the same scenario is happening

**Comment by ahmedbhesaniya97** [comment]
If i take the meeting from Gmeet, Teams and zoom its working perfectly

**Comment by ahmedbhesaniya97** [comment]
Device configuration

![Screenshot from 2022-12-05 17-38-43](https://user-images.githubusercontent.com/65531261/205636929-8c5a7348-bada-4cea-b975-38dcbd796a58.png)

**Comment by nazar-pc** [comment]
As already said, there is nothing broken in mediasoup, something on your computer is. Start with reporting bugs to Chrome and Windows.
