### ISSUE TITLE
3.11.4 - Cannot find module mediasoup/node/lib/index.js

### ISSUE THREAD

**Issue by Mark90** [versatica/mediasoup#971]
Hi,

We're using Mediasoup's NodeJS client, and there seems to be a regression in tag 3.11.4. Starting our node application fails with: 

```
Error: Cannot find module '/service/node_modules/mediasoup/node/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:321:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:534:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/service/server.js:17:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/service/node_modules/mediasoup/package.json',
  requestPath: 'mediasoup'
```

With 3.11.3 this doesn't happen.

Comparing the 2 tags, `node/lib/index.js` indeed seems to have been removed but it's still referenced by `package.json` https://github.com/versatica/mediasoup/compare/3.11.3..3.11.4

Is this indeed a regression, or rather something we should fix in our NodeJS app?

Kind regards,
Mark

**Comment by ibc** [comment]
Please paste the content of your `service/node_modules/mediasoup/node` folder.

How are you installing mediasoup? From NPM or from Git? This has been tested in depth.

**Comment by Mark90** [comment]
Thanks your quick reply!

We were installing 3.11.4 through Git, changing to 3.11.4 from NPM indeed works. 

I.e. this version pin caused the error: `"mediasoup": "github:versatica/mediasoup#3.11.4"`
With this pin everything works fine: `"mediasoup": "^3.11.4"`

Sorry for the false alarm, and thanks again :)

**Comment by ibc** [comment]
It should work even if you use git. I tested it. Can you please try it and print what I asked before?

**Comment by Mark90** [comment]
When using git the directory is missing altogether;

```
ls: cannot access '/service/node_modules/mediasoup/node': No such file or directory
```

**Comment by nazar-pc** [comment]
It is in Git, but it should also be built automatically during installation

**Comment by Mark90** [comment]
With this minimal reproducible example I get the same result (no node/ folder):

`package.json`
```
{
  "name": "mypackage",
  "version": "1.0.0",
  "description": "testing something",
  "main": "index.js",
  "author": "me",
  "license": "ISC",
  "dependencies": {
    "mediasoup": "github:versatica/mediasoup#3.11.4"
  }
}
```

`Dockerfile`
```
FROM node:14.18.3-bullseye-slim

# Install DEB dependencies and others.
RUN \
	set -x \
	&& apt-get update \
	&& apt-get install -y net-tools build-essential valgrind python3-pip git

WORKDIR /service

COPY package.json .
RUN npm install
```


When I build this with `docker build -t temp .` and list the directory contents with `docker run --rm temp ls -la /service/node_modules/mediasoup` I get:

```
$ docker build -t temp .
[+] Building 277.6s (10/10) FINISHED
 => [internal] load build definition from Dockerfile
 => => transferring dockerfile: 283B
 => [internal] load .dockerignore
 => => transferring context: 2B
 => [internal] load metadata for docker.io/library/node:14.18.3-bullseye-slim
 => [1/5] FROM docker.io/library/node:14.18.3-bullseye-slim@sha256:a9f0e5666de84b193ca5e5d79388bc57c7e3a8130e1ed7bb170c28ef6152fdbe
 => [internal] load build context
 => => transferring context: 265B
 => CACHED [2/5] RUN  set -x  && apt-get update  && apt-get install -y net-tools build-essential valgrind python3-pip git
 => CACHED [3/5] WORKDIR /service
 => [4/5] COPY package.json .
 => [5/5] RUN npm install
 => exporting to image
 => => exporting layers
 => => writing image sha256:46b0952f4836d795f3f7d38d6a2ddc80e01902b98c300bda7491a193fa322c7f
 => => naming to docker.io/library/temp

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
$ docker run --rm temp ls -la /service/node_modules/mediasoup
total 80
drwxr-xr-x  3 root root  4096 Dec  9 15:07 .
drwxr-xr-x  9 root root  4096 Dec  9 15:07 ..
-rw-r--r--  1 root root 39859 Oct 26  1985 CHANGELOG.md
-rw-r--r--  1 root root   766 Oct 26  1985 LICENSE
-rw-r--r--  1 root root  4445 Oct 26  1985 README.md
-rw-r--r--  1 root root  5946 Oct 26  1985 npm-scripts.js
-rw-r--r--  1 root root  4129 Dec  9 15:05 package.json
drwxr-xr-x 10 root root  4096 Dec  9 15:05 worker
$
```

MacOS 12.6
Docker version 20.10.17, build 100c701

**Comment by ibc** [comment]
Which npm version are you using in Docker? Can you reproduce the issue with your simple repro project using a modern version of node/npm outside Docker?

**Comment by ibc** [comment]
It works perfectly fine for me:

* In `/tmp/kk`:
   ```bash
   $ ls
   index.js package.json
   ```

* `package.json`:
   ```json
   {
      "name": "kk",
      "version": "1.0.0",
      "description": "kk",
      "main": "index.js",
      "author": "",
      "license": "ISC",
      "dependencies": {
        "mediasoup": "github:versatica/mediasoup#3.11.4"
      }
    }
    ```
* `index.js`:
   ```js
    process.env.DEBUG="*mediasoup*";

    const mediasoup = require('mediasoup');

    run();

    async function run()
    {
    	const worker = await mediasoup.createWorker();

    	const dump = await worker.dump();

    	console.log('Worker created, dump:');
    	console.log(dump);
    }
   ```
* `node index.js`:
   ```bash
   $ /tmp/kk node index.js

  Worker created, dump:

  {
    channelMessageHandlers: {
      channelRequestHandlers: [],
      payloadChannelNotificationHandlers: [],
      payloadChannelRequestHandlers: []
    },
    pid: 1504,
    routerIds: [],
    webRtcServerIds: []
  }
  ```
* Versions:
  ```bash
  $ node -v
  v16.15.0

  $ npm -v
  8.19.2
  ```

**Comment by Mark90** [comment]
Indeed, when I change my earlier Dockerfile example from `node:14.18.3` (npm `6.14.15`) to `node:18.12.1` (npm `8.19.2`) I do get the `node/lib/` directory. So the problem seems to be with the older npm version.

**Comment by ibc** [comment]
As per npm docs `prepare` script is supported since npm@4.0.0 :-|

https://docs.npmjs.com/cli/v9/using-npm/scripts#life-cycle-scripts

**Comment by Mark90** [comment]
I did one final test: installing with npm 6 and npm 8 at the same time, in separate folders.

* NPM 6 mentions it will execute the prepare script, then runs postinstall which ends up running `make` - not sure if this is normal. This takes a long time and finally fails on missing x86-64 symbols (probably because I'm on arm64).
* NPM 8 oddly does not mention the prepare script, but does mention the postinstall, and finishes successfully (with the `node/lib/` directory present) - in about half the time that NPM 6 takes. I'm not sure if NPM 8 also ran `make`.

Partial output below. Probably not useful for this old node/npm version, but yeah :) 

Node 14 / npm 6
```
Ξ js/mediasoup-node14 → npm install versatica/mediasoup#3.11.4 --verbose
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/Users/mark/.nvm/versions/node/v14.19.0/bin/node',
npm verb cli   '/Users/mark/.nvm/versions/node/v14.19.0/bin/npm',
npm verb cli   'install',
npm verb cli   'versatica/mediasoup#3.11.4',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@6.14.16
npm info using node@v14.19.0
npm verb npm-session afe9a3dd8e02ffbf
npm verb prepareGitDep github:versatica/mediasoup#3.11.4: installing devDeps and running prepare script.
npm ERR! prepareGitDep 1>
npm ERR! prepareGitDep > mediasoup@3.11.4 postinstall /Users/mark/.npm/_cacache/tmp/git-clone-13b07498
npm ERR! prepareGitDep > node npm-scripts.js postinstall
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm-scripts.js [INFO] running task "postinstall"
npm ERR! prepareGitDep npm-scripts.js [INFO] buildWorker()
npm ERR! prepareGitDep npm-scripts.js [INFO] executeCmd(): make -C worker
...
npm ERR! prepareGitDep       RTC::DtlsTransport::GenerateCertificateAndPrivateKey() in src_RTC_DtlsTransport.cpp.o
npm ERR! prepareGitDep ld: symbol(s) not found for architecture x86_64
npm ERR! prepareGitDep clang: error: linker command failed with exit code 1 (use -v to see invocation)
npm ERR! prepareGitDep ninja: build stopped: subcommand failed.
...
```

Node 16 / npm 8
```
Ξ js/mediasoup-node16 → npm install versatica/mediasoup#3.11.4 --verbose
npm verb cli [
npm verb cli   '/Users/mark/.nvm/versions/node/v16.14.0/bin/node',
npm verb cli   '/Users/mark/.nvm/versions/node/v16.14.0/bin/npm',
npm verb cli   'install',
npm verb cli   'versatica/mediasoup#3.11.4',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@8.3.1
npm info using node@v16.14.0
npm timing npm:load:whichnode Completed in 0ms
...
npm timing build:link Completed in 317ms
npm info run mediasoup@3.11.4 postinstall node_modules/mediasoup node npm-scripts.js postinstall
npm info run mediasoup@3.11.4 postinstall { code: 0, signal: null }
npm timing build:run:postinstall:node_modules/mediasoup Completed in 71505ms
npm timing build:run:postinstall Completed in 71506ms
...
```

**Comment by nazar-pc** [comment]
Controversial, but maybe we can just bump Node.js requirement for mediasoup? It might still work for those who install from npm, but we'll not guarantee it working when installed from GitHub directly.

**Comment by ibc** [comment]
@Mark90 of course `make` is needed during installation. Worker C++ sources are compiled on install.

@nazar-pc I don't really know which min Node version can be required. Perhaps 16? Current LTS version is 18 and experimental one is 19. AFAIU from above comments, version 16 works fine when it comes to install mediasoup from Git, right?

**Comment by nazar-pc** [comment]
16 seems reasonable, it has been out [for a while](https://github.com/nodejs/release#release-schedule) and lately upgrades to newer releases are very easy and often boil down to updating base version in Dockerfile.

**Comment by ibc** [comment]
Ok. Will reopen this issue until that change is done.

**Comment by ibc** [comment]
Here https://github.com/versatica/mediasoup/pull/973
