### ISSUE TITLE
mediasoup-demo doesn't work at all

### ISSUE THREAD

**Issue by defcronyke** [versatica/mediasoup#976]
npm fails to install eslint and rxjs -> workaround by using yarn instead

npm start fails with hundreds of errors

is there a purpose of using Gulp? I thought that hasn't been used by projects in several years and tends to cause problems in 2022

I'm trying the docker method now and if that works that's okay I guess, but mediasoup-demo as documented, isn't working at all.

**Comment by nazar-pc** [comment]
With questions like this please reach out to the forum instead
