### ISSUE TITLE
WHIP and WHEP support?

### ISSUE THREAD

**Issue by mpisat** [versatica/mediasoup#979]
## Feature Request
Considering Cloudflare started WHIP/WHEP in their cloud Stream service, it would be nice if mediasoup added support for WHIP and WHEP. Ability to push videos via WHIP using CLI tools (gstreamer, and maybe ffmpeg in the future?) would be very interesting.

**Comment by nazar-pc** [comment]
mediasoup supports anything WebRTC, but it is a low-level library, as such for WHIP/WHEP you need to write an app on top, maybe someone already did.

So there is really nothing to do about it here. If you write a simple Rust example - feel free to contribute, there are a few other examples already.
