### ISSUE TITLE
Frequent joining and quitting meetings will cause the memory of chrome browser to continue to grow

### ISSUE THREAD

**Issue by bingofree2015** [versatica/mediasoup#980]
I used two machines to open the chrome browser and join the same conference room. One machine (Machine A) observed the changes in memory, and the other machine (Machine B) frequently joined and exited the conference through automated testing tools, with a frequency of 1 second. This lasted about 5 hours

The browser memory of machine A continues to grow from 113.347K to 497.890K. If it lasts for about 24 hours, the browser memory may grow to more than 1G, causing the browser to crash.

Code snippet:

Step 1:

const consumer = await this._ recvTransport.consume(

{

id,

producerId,

kind,

rtpParameters,

appData : { ...appData, peerId } // Trick.

});

Step 2:

consumer.close();

Step 3:

const consumer = await this._ recvTransport.consume(

{

id,

producerId,

kind,

rtpParameters,

appData : { ...appData, peerId } // Trick.

});

Step 4:

consumer.close();

....

**Comment by nazar-pc** [comment]
I see no reason why this would be a bug in mediasoup, especially backend. Please create a thread on the forum instead to discuss this.

**Comment by bingofree2015** [comment]
Sorry, this problem is found by using the mediasoop client SDK. It should have nothing to do with the backend. Thank you!
