### ISSUE TITLE
Regression in 3.10.6

### ISSUE THREAD

**Issue by piranna** [versatica/mediasoup#982]
Yes, I know 3.10.6 is 6 months old (by the way, published on my birthday :-)) but I have been updating some old code that was using 3.9.2 and found it, and regression is still present in latest 3.11.4.

### Your environment

- Operating system: Ubuntu Mate 22.10 64 bits
- Node version: v18.13.0
- npm version: 8.19.3
- gcc version: 12.2.0
- mediasoup version: 3.10.6
- mediasoup-client version: not aplicable

### Issue description

My battery test is of 100% coverage, and after updating dependencies from Mediasoup 3.9.2 to 3.11.4, I found they started to fail. I've tried multiple versions, and since about 3.10.0 (I don't remember the exact number) they started to be unstable, like if there were race conditions that made random exceptions to be thrown, but tests were passing since I was checking for exceptions being thrown instead of for the actual error (my fault, I have now in my todo list to both improve the tests and to take a look the source of the race conditions, since most of them are coming from out of limits Workers management, so probably I'm not doing a proper cleanup, although that didn't happen in the past with 3.9.2, but I was also using a less powerful laptop too with less CPUs).

While testing the multiple versions, I found that at version 3.10.6 they started to fail always the same two tests, both of them related to pip'ing routers with `pipeToRouter()` helper function. The most simple one is:

```js
const codec = {
  channels: 2,
  clockRate: 48000,
  mimeType: "audio/opus",
};

const routerOptions = {
  mediaCodecs: [
    {
      ...codec,
      kind: "audio",
    },
  ],
};

const router = new MafaldaRouter(createWorker, { routerOptions });

const promise = router
  .createDirectTransport()
  .then(function (transport) {
    return transport.produce(options);
  })
  .then(function (producer) {
    const router2 = new MafaldaRouter(createWorker, { routerOptions });

    return router
      .pipeToMafaldaRouter({
        producerId: producer.id,
        mafaldaRouter: router2,
      })
      .finally(router2.close.bind(router2));
  });

return expect(promise).resolves.toMatchObject({
  pipeConsumer: expect.any(Consumer),
  pipeProducer: expect.any(Producer),
});
```

This test from my project [Mafalda](https://mafalda.io) is creating an instance of MafaldaRouter (an abstract wrapper on top of Mediasoup Routers that manages their creation and destruction over multiple Mediasoup Workers as if they were a single one), creating a Mediasoup DirectTransport (can be of any other type), a Producer on it, and later pip'ing that Producer to another instance of MafaldaRouter with `pipeToMafaldaRouter()`, that's mostly a wrapper of Mediasoup `Router.pipeToRouter()` but also creating the internal Mediasoup Router object, and later destroying everything. As I've said, this test has been working flawlessly until upgrading Mediasoup to version 3.10.6 or newer ones, where it knows rejects with the next error:

```js
Error: Channel request handler with ID 375d3f8c-ff9e-4f4e-94a7-c34a10961263 already exists [method:transport.produce]
          at Channel.processMessage (/home/piranna/github/Mafalda/Mafalda/node_modules/mediasoup/node/lib/Channel.js:194:37)
          at Socket.<anonymous> (/home/piranna/github/Mafalda/Mafalda/node_modules/mediasoup/node/lib/Channel.js:69:34)
          at Socket.emit (node:events:513:28)
          at addChunk (node:internal/streams/readable:324:12)
          at readableAddChunk (node:internal/streams/readable:297:9)
          at Socket.Readable.push (node:internal/streams/readable:234:10)
          at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

It looks like someway it thinks the Producer is already in the target Router, as I was internally using the same Mediasoup Router (I'm going to check it, but have already tests to prevent that case...), but it seems more like some kind of checks or caching on the C++ side. On my own code I've put traces, and the error is happening exactly when internally calling to `Router.pipeToRouter()` method.

At version 3.10.6 [there's a lot of changes](https://github.com/versatica/mediasoup/compare/3.10.5...3.10.6), and i will need to do `git bisect` to try to find when the problem started, but by eye revision, I think it could be related to https://github.com/versatica/mediasoup/commit/555e433d7cd821df53c11e624c5b47db263a3f38, or more probably to https://github.com/versatica/mediasoup/commit/39ccbc5d42c63e8cbb334a22bee5e9ed78ba0a5d, that totally makes sense to me, but it's the kind of changes that I would put behind a major version (in fact, if that's the culprit, I will need to go back to the design state and start over my project from scratch... :-/).

**Comment by ibc** [comment]
See the note in pipeToRouter() method:

https://mediasoup.org/documentation/v3/mediasoup/api/#router-pipeToRouter

**Comment by ibc** [comment]
> See the note in pipeToRouter() method:
> 
> https://mediasoup.org/documentation/v3/mediasoup/api/#router-pipeToRouter

Exactly since 3.6.10 due to new optimized handlerId (see CHANGELOG file).

**Comment by piranna** [comment]
> See the note in pipeToRouter() method:
> 
> [mediasoup.org/documentation/v3/mediasoup/api/#router-pipeToRouter](https://mediasoup.org/documentation/v3/mediasoup/api/#router-pipeToRouter)

I didn't know about the performance optimizations, don't know how it can affect, but definitely I can agree it doesn't makes any sense to pipe a Producer to its same Worker... just only maybe I would still allow it, but manages the de-duplication internally, like if both source and target Routers are in the same Worker, share the Producer object between them and increase a references counter, for example. But yes, both by managing it internally, or forbiding to do it at all, totally makes sense to me to don't pipe to itself.


> Exactly since 3.6.10 due to new optimized handlerId (see CHANGELOG file).

I read the changelog, but didn't found anything that could lead me to think about this issue. Anyway, just only by forbidding it I would have set it as a major version, not as a patch, since it's a breaking behaviour.

**Comment by ibc** [comment]
As per semver rules, a breaking change would have required a MAYOR bump from 3 to 4 and that would be too much. I don't like this behavior change being honest and I spent lot of time already trying to figure out a way to keep allowing pipeToRouter between 2 routers in same worker, but I couldn't get it done. The problem is that, since 3.10.6, every entity (such a Producer, etc) must have a different id within the same worker, and pipeToRouter creates a new Producer with same id than the original Producer in purpose.

This is in my TODO for v4 where many other (breaking) changes will happen.

BTW I think we communicated this behavior change in Announcements in the forum, not sure, but anyway I agree it's not nice.

**Comment by piranna** [comment]
> As per semver rules, a breaking change would have required a MAYOR bump from 3 to 4 and that would be too much.

Agree, maybe have it in another `next` branch where other mayor changes get added until "there's enough" would also works.


> The problem is that, since 3.10.6, every entity (such a Producer, etc) must have a different id within the same worker, and pipeToRouter creates a new Producer with same id than the original Producer in purpose.

So, each object inside the Worker has an unique ID, and there would be a conflict, isn't it? Definitely that's a problem, but as I've said, if it's in fact the same object, we can just have a counter of how much Routers "own" that producer, or also a Producer internal list with that actual Router objects. I don't know the consecuences of that thouhg, but that could be a solution to don't have two Producers inside a Worker with the same ID... If you need help with that, just let me know and we can have a call.


> BTW I think we communicated this behavior change in Announcements in the forum, not sure, but anyway I agree it's not nice.

No issues, I'm not so much active in the forums as I should be, so if you announced it, probably I missed it anyway. At least it helped me to re-think a lot of things on my project, that's not so bad either :-)

**Comment by ibc** [comment]
> So, each object inside the Worker has an unique ID, and there would be a conflict, isn't it? Definitely that's a problem, but as I've said, if it's in fact the same object, we can just have a counter of how much Routers "own" that producer, or also a Producer internal list with that actual Router objects.

No idea how a counter may help here. The problem is that pipeToRouter creates a new Producer with same id as the original one (by design, it cannot be changed). If a producer with same id already existed in this Worker then `transport.produce({ id: original_producer.id })` (which is internally called by pipeToRouter method) throws due to "entity with same id already exists in this worker).

**Comment by piranna** [comment]
> pipeToRouter creates a new Producer with same id as the original one

I know, it's being done because both objects "produce" the same data, so a counter can help here: since we are pip'ing inside the same Worker, don't do the pipe at all, and instead creating a new Producer with the same ID, share the old one between both Routers, and increase a counter about how much Routers are currently using that Producer. It's said, instead of having two Producers with the same ID inside the Worker, have a single Producer shared by two Routers.

**Comment by nazar-pc** [comment]
We literally have a hashmap in worker now where ID of producer is the key. You can't just add a counter there.

**Comment by piranna** [comment]
> We literally have a hashmap in worker now where ID of producer is the key. You can't just add a counter there.

I don't mean adding the counter there, but inside the Producer object. Or the same, if you don't want a counter, a list of what Routers own that Producer, and count the length of list: if it's empty, nobody owns the Producer anymore, and can be safely deleted.

**Comment by nazar-pc** [comment]
That is how it was done before, it was slower and a bit more complex. We have simplified it and got this side-effect as the result. It is unfortunate, but was considered as acceptable due to use case making little sense in practice.

**Comment by ibc** [comment]
> don't do the pipe at all, and instead creating a new Producer with the same ID, share the old one between both Routers, and increase a counter about how much Routers are currently using that Producer. It's said, instead of having two Producers with the same ID inside the Worker, have a single Producer shared by two Routers.

Nope. We must be able to close/pause/whatever the original Producer and the piped Producer independently. Definitely we cannot add that much new logic just to enable a case that anyway doesn't make sense (piping a router into another router in same worker). As said before, we'll come back to this topic in v4 and see if there is any change to re-enable this not much valuable behavior in v4.

**Comment by piranna** [comment]
I know it doesn't make sense, it's just to make it more dev friendly in an optimal way better than saying them ["just avoid holding it in that way"](https://www.engadget.com/2010-06-24-apple-responds-over-iphone-4-reception-issues-youre-holding-th.html).

**Comment by ibc** [comment]
We may just disallow piping within same Worker (as we do know after that optimization in 3.10.6) and that would be perfectly fine. That use case has probably zero benefit.

**Comment by piranna** [comment]
> We may just disallow piping within same Worker (as we do know after that optimization in 3.10.6) and that would be perfectly fine. That use case has probably zero benefit.

That would be drastic... but also explicit, too: Producers are unique at Worker level. I don't disagree on that idea.

**Comment by ibc** [comment]
It's already like that.
