### ISSUE TITLE
expose Producer::close() in rust crates

### ISSUE THREAD

**Issue by aconchillo** [versatica/mediasoup#983]
## Feature Request

Currently, it seems it is not possible to `close()` a `Producer`. I believe the only way a `Producer` is closed is when its transport is closed. However, in some cases one might want to keep the transport open and simply close the producer (and notify its consumers via `on_producer_closed` callback) and open new producers through the same transport. Actually, there is a `Producer::close()` function but it's not exposed publicly. It would be nice to expose that in `Consumer` as well, but in the `Consumer` case `close()` does not exist.

This is possible in the JavaScript library https://mediasoup.org/documentation/v3/mediasoup/api/#producer-close.

Please, let me know if my assumption is incorrect and if there's another way to achieve the same if so. Thanks!

**Comment by aconchillo** [comment]
By the way, if this makes sense I would be happy to send a PR for it.

**Comment by ibc** [comment]
I'm pretty sure that, if there is no producer::close(), method then there is a Rudy way to finish/deallocate or whatever a Producer in Rust with same effect. I'll wait for @nazar-pc to comment about it.

**Comment by aconchillo** [comment]
> I'm pretty sure that, if there is no producer::close(), method then there is a Rudy way to finish/deallocate or whatever a Producer in Rust with same effect. I'll wait for @nazar-pc to comment about it.

Yes, I was expecting the same but when I removed my last reference to the `Producer` nothing happened (i.e. `on_producer_closed` was not called on the `Consumer`), so may be the transport is still holding a reference to it. I didn't actually take a look at that, but I'll check.

**Comment by nazar-pc** [comment]
Rust version follows RAII and ownership model, so in order to close producer, consumer or anything else you just need to drop it. No separate method exists for that.

If it doesn't happen, they you must be leaking producer somewhere (by creating circular reference for instance). We have [tests for closing event](https://github.com/versatica/mediasoup/blob/73446e0bd6ef0753bbf2751039914023cc6d0ea7/rust/tests/integration/producer.rs#L912-L920) and library is designed to never create circular references on its own.

**Comment by aconchillo** [comment]
I'll double-check again, but I was pretty sure I was cleaning the last reference of my producer. In the test you pointed out, if I understand correctly, the transport is dropped that's why producer is closed. In my app, the transport keeps running and I only drop the producer, but the close event doesn't happen (my guess, without checking, is that the transport keeps a reference). I'll verify again and report back. Thanks for the fast response!

**Comment by nazar-pc** [comment]
> In the test you pointed out, if I understand correctly, the transport is dropped that's why producer is closed.

No, we drop audio producer and it is closed on worker right away. Transport is closed much later.

> my guess, without checking, is that the transport keeps a reference

It doesn't. Make sure to not move clones of instances into event callbacks or use weak references to break circular references, there is https://docs.rs/mediasoup/latest/mediasoup/producer/struct.WeakProducer.html for instance.

**Comment by aconchillo** [comment]
> > In the test you pointed out, if I understand correctly, the transport is dropped that's why producer is closed.
> 
> No, we drop audio producer and it is closed on worker right away. Transport is closed much later.
> 

:+1: 

> > my guess, without checking, is that the transport keeps a reference
> 
> It doesn't. Make sure to not move clones of instances into event callbacks or use weak references to break circular references, there is https://docs.rs/mediasoup/latest/mediasoup/producer/struct.WeakProducer.html for instance.

I'll for sure check, I'll see if I have some time later today. :raised_hands:

**Comment by aconchillo** [comment]
I think I found the issue. I was registering the callback on a cloned `Producer` (and `Consumer`) which is different than the ones I was storing in a `HashMap`. When I removed the `HashMap` references the callback from the cloned one was not being called (even `drop()` and `close()` was being called).

```
2023-01-16T04:18:09.984319Z DEBUG mediasoup::router::producer: drop()    
2023-01-16T04:18:09.984355Z DEBUG mediasoup::router::producer: close()    
2023-01-16T04:18:09.984561Z DEBUG mediasoup::worker::channel: request() [method:transport.closeProducer, id:28]: ProducerCloseRequest { producer_id: ProducerId(05a17219-e5b0-468c-bbf4-b66779f8a5e4) }    
2023-01-16T04:18:09.984975Z DEBUG mediasoup::router::consumer: close()    
2023-01-16T04:18:09.985282Z DEBUG mediasoup::worker::channel: request succeeded [method:transport.closeProducer, id:28]    
```

Looking at the `Producer` code it seems the handlers are registered inside `Inner` so even if you clone the `Producer` those callbacks should still be valid, but it seems that's not the case. If you can clarify why this would happen it would be great! 

I will close this now. Thanks again for the quick replies and help!

**Comment by nazar-pc** [comment]
Handlers are associated with producer entity, not on a particular clone of it. Cloning is actually very cheap, it is just one atomic increment/decrement. As long as at least one clone of that producer exists handlers will be alive.

There is no way to create producer other than through provided API (so you can't have two distinct instances backed by the same producer on worker with unique set of handlers) and no other way to destroy rather than dropping last instance (so you can't call methods on already destroyed producer).

I hope it makes sense. If you have questions, feel free to create a thread on the forum, GitHub is for bugs.

**Comment by aconchillo** [comment]
> Handlers are associated with producer entity, not on a particular clone of it. Cloning is actually very cheap, it is just one atomic increment/decrement. As long as at least one clone of that producer exists handlers will be alive.
> 

Yes, I see it's just an `Arc`.

> There is no way to create producer other than through provided API (so you can't have two distinct instances backed by the same producer on worker with unique set of handlers) and no other way to destroy rather than dropping last instance (so you can't call methods on already destroyed producer).
> 

:+1: 

> I hope it makes sense. If you have questions, feel free to create a thread on the forum, GitHub is for bugs.

Will do, thanks! Just as a last comment (since we discussed everything here), I tried to reproduce this on the integration tests, and things work as I would expect, so certainly something on my end. Thanks again! Just pasting what I tried and works:

```
+        let mut _handler: Option<HandlerId> = None;
+
+        let (mut tx, rx) = async_oneshot::oneshot::<()>();
         {
-            let (mut tx, rx) = async_oneshot::oneshot::<()>();
-            let _handler = audio_producer.on_close(move || {
+            let audio_producer_cloned = audio_producer.clone();
+            _handler = Some(audio_producer_cloned.on_close(move || {
                 let _ = tx.send(());
-            });
-            drop(audio_producer);
-
-            rx.await.expect("Failed to receive close event");
+            }));
         }
+        drop(audio_producer);
+        rx.await.expect("Failed to receive close event");
```

**Comment by aconchillo** [comment]
> 
> I tried to reproduce this on the integration tests, and things work as I would expect, so certainly something on my end. 

For whoever finds the same issue. Remember to keep a reference to each `HandlerId` returned by `on_xxxx` callback registration. When a `HandlerId` is dropped, the corresponding callback won't be called. That was my root cause issue.
