### ISSUE TITLE
Upgrade Catch2 to version 3

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#987]
We must upgrade [Catch2](https://github.com/catchorg/Catch2) from 2.13.7 to latest 3.3.0 (o newer). I did it in libmediasoupclient project in this ongoing PR https://github.com/versatica/libmediasoupclient/pull/151. However, in there I didn't use the proper new approach 2 (which is building Catch2 as a proper static library). Instead I used approach 1. See:

https://github.com/catchorg/Catch2/blob/devel/docs/migrate-v2-to-v3.md#how-to-migrate-projects-from-v2-to-v3

Now, when it comes to do this in mediasoup I'm really lost:

- In `worker/subprojects/` there is a **custom?** `catch2.wrap` as follows:
  ```
  [wrap-file]
  directory = Catch2-2.13.7
  source_url = https://github.com/catchorg/Catch2/archive/v2.13.7.zip
  source_filename = Catch2-2.13.7.zip
  source_hash = 3f3ccd90ad3a8fbb1beeb15e6db440ccdcbebe378dfd125d07a1f9a587a927e9
  patch_filename = catch2_2.13.7-1_patch.zip
  patch_url = https://wrapdb.mesonbuild.com/v2/catch2_2.13.7-1/get_patch
  patch_hash = 2f7369645d747e5bd866317ac1dd4c3d04dc97d3aad4fc6b864bdf75d3b57158
  
  [provide]
  catch2 = catch2_dep
  ```
- Why can't we just use the `catch2.wrap` (version 2.x.x) available in official Meson wrap registry inhttps://mesonbuild.com/Wrapdb-projects.html?
- The official Meson wrap registry provides with a modern version of Catch2 3.2.1, which looks as follows:
  ```
  [wrap-file]
  directory = Catch2-3.2.0
  source_url = https://github.com/catchorg/Catch2/archive/v3.2.0.tar.gz
  source_filename = Catch2-3.2.0.tar.gz
  source_hash = feee04647e28ac3cbeff46cb42abc8ee2d8d5f646d36e3fb3ba274b8c69a58ea
  wrapdb_version = 3.2.0-1
  
  [provide]
  catch2 = catch2_dep
  catch2-with-main = catch2_with_main_dep
  ```
- It doesn't require any patch. Can we use it as it is?
- First steps for using Catch2 3.x.x as a static library is _"Change your CMakeLists.txt to link against Catch2WithMain target if you use Catch2's default main. (If you do not, keep linking against the Catch2 target.)"_. No idea how to do that.

**Comment by ibc** [comment]
@nazar-pc do you mind if I assign this task to you?

**Comment by nazar-pc** [comment]
We were using the version that was available at the time. Looks like upstream Catch2 added Meson support, which is great and that is why patch (which typically just adds meson.build file on top) is no longer necessary. In some cases https://mesonbuild.com/Wrapdb-projects.html just points to upstream packages as a discovery mechanism.

Feel free to use it, there is nothing wrong with that or I can take a look as well.

**Comment by nazar-pc** [comment]
https://github.com/catchorg/Catch2/releases/tag/v3.1.1 added Meson support

**Comment by ibc** [comment]
So we don't need any custom `catch2.wrap` anymore in `subprojects` folder I guess. Good.

Any thought about last bullet above?

> First steps for using Catch2 3.x.x as a static library is "Change your CMakeLists.txt to link against Catch2WithMain target if you use Catch2's default main. (If you do not, keep linking against the Catch2 target.)". No idea how to do that.

https://github.com/catchorg/Catch2/blob/devel/docs/migrate-v2-to-v3.md#how-to-migrate-projects-from-v2-to-v3

**Comment by nazar-pc** [comment]
`catch2.wrap` is still needed, it just looks a bit simpler now (without patch).

I see there are two things wrap now provides, you may need to replace `catch2_dep` with `catch2_with_main_dep`, but that should be about it.

**Comment by ibc** [comment]
> I see there are two things wrap now provides, you may need to replace catch2_dep with catch2_with_main_dep, but that should be about it.

Yup but I don't see where to replace it plus now Catch must be statically built rather than being header based as before.

**Comment by nazar-pc** [comment]
It is all in our `meson.build`: https://github.com/versatica/mediasoup/blob/f60845ba6c4be7fda3a779c0eb5cab1b4fc50ca7/worker/meson.build#L281

**Comment by ibc** [comment]
Oh, so do you mean that by changing that to "with_main" then Catch2 will be automatically linked when building the worker test target?

**Comment by nazar-pc** [comment]
If that is what upgrade guide says - sure. Try to compile it as is, if doesn't work then change that line. Otherwise I can take a look at it too.
